# Related Papers:
- https://aclanthology.org/2024.acl-short.2.pdf
- https://aclanthology.org/2024.emnlp-main.171.pdf
- https://arxiv.org/pdf/2408.09174v1
- https://aclanthology.org/2025.findings-emnlp.638.pdf
- https://aclanthology.org/2025.emnlp-main.363.pdf

In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
from dotenv.main import load_dotenv

load_dotenv()
REPO_PATH = os.getenv('REPO_PATH')

sys.path.append(REPO_PATH)

In [2]:
import json

def load_json(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)

def save_json(file_name, file):
    with open(os.path.join(REPO_PATH, "data_files", f"{file_name}.json"), "w", encoding="utf-8") as out_file:
        json.dump(file, out_file, indent=4)

def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]

def save_jsonl(file_name, records):
    path = os.path.join(REPO_PATH, "data_files", f"{file_name}.jsonl")
    with open(path, "w", encoding="utf-8") as out_file:
        for record in records:
            out_file.write(json.dumps(record, ensure_ascii=False) + "\n")

# Data Creation:

## Harvest Wikipedia pages with tables:

In [91]:
from knowledge_maze.create_dataset.create_questions.wikipedia_mining import WikiHarvester
# Initialize Wikipedia harvester
harvester = WikiHarvester()
# Run Phase 1 - Harvesting titles based on keywords
harvester.run_complete_harvest()
# Run Phase 2 - Filtering pages for tables
await harvester.filter_pages_async()

Harvesting Pages By Keywords:   0%|          | 0/233 [00:00<?, ?keyword/s]

TOTAL UNIQUE TITLES COLLECTED: 167913

Filtering Pages with Tables:   0%|          | 0/167913 [00:00<?, ?page/s]

TOTAL PAGES WITH TABLES COLLECTED: 62306

In [93]:
save_json("table_titles", harvester.valid_titles)

In [174]:
table_titles = load_json("C:/Users/Daniel/Desktop/KnowledgeMaze/data_files/table_titles.json")

## Parse and filter Wikipedia tables:

In [271]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
validated_tables_file_name = await extractor.run_with_progress(table_titles)
validated_tables = load_jsonl(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
cleaned_data = processor.process()

Pre-processing: cluster similar pages and discard similarities ---> 6426 pages discarded.

Extracting Tables:   0%|          | 0/55880 [00:00<?, ?Page/s]

Starting Extraction: 55880 titles | Async Limit: 20 | CPU Workers: 19
TOTAL PAGES WITH VALID TABLES: 32076 OUT OF 55880 (57.4%)

Filtering & Cleaning:   0%|          | 0/94101 [00:00<?, ?it/s]

════════════════════════════════════════════
📊 TABLE PROCESSING SUMMARY (Limit: 12)
════════════════════════════════════════════
Total tables scanned:      94101
Dropped (Bad Headers):     8435
Dropped (Cell too long):   2841
Dropped (Repeat Rows):     1783
Short tables found:        39837
Unique source pages:       16940
Final sampled (1/page):    16940
════════════════════════════════════════════

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                  ↓ EXAMPLE TABLES ↓
------------------------------------------------------------------------------------------------------------------------------------------------------

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Canada women's national soccer team > Individual records > Most appearances
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

    Rank              Player        Career  Caps  Goals
0      1  Christine Sinclair     2000–2023   331    190
1      2      Sophie Schmidt     2005–2023   226     20
2      3      Diana Matheson     2003–2021   206     19
3      4       Desiree Scott     2010–2025   188      0
4      5     Rhian Wilkinson     2003–2017   181      7
5      6   Kadeisha Buchanan  2013–present   154      6
6      7     Ashley Lawrence  2013–present   151      8
7      7      Jessie Fleming  2013–present   151     20
8      9     Brittany Baxter     2002–2014   132      5
9      9         Andrea Neil     1991–2007   132     24
10     9        Adriana Leon  2013-present   132     44

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Manchester City F.C. 3–2 Queens Park Rangers F.C. > Match > Statistics
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

           Statistic Manchester City Queens Park Rangers
0       Goals scored               3                   2
1         Possession           81.3%               18.7%
2    Shots on target              15                   3
3   Shots off target              10                   0
4      Blocked shots              19                   0
5       Corner kicks              19                   0
6              Fouls               4                   7
7            Tackles              15                  22
8           Offsides               1                   1
9       Yellow cards               2                   1
10         Red cards               1                   1

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Swinburne University of Technology > Notable people > Academics and staff
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Member,Executive team,Period
0,Pascale Quester,Vice-Chancellor,2020–present
1,Chris Pilgrim,Pro Vice-Chancellor (Academic),
2,Tara Magdalinski,Pro Vice-Chancellor (Education and Quality),
3,Sarah Maddison,Pro Vice-Chancellor (Academic Innovation and C...,
4,Bronwyn Fox,Deputy Vice-Chancellor (Research and Enterprise),
5,Beth Webster,Pro Vice-Chancellor (Research Policy and Impact),
6,Qing-Lon Han,Pro Vice-Chancellor (Research Quality),
7,Alan Kin-Tak Lau,Pro Vice-Chancellor (International Research De...,
8,Blair Kuys,Dean of the School of Design and Architecture,
9,Matthew Bailes,Director of the Data Science Research Institut...,
10,Karl Glazebrook,Laureate Fellow of the Centre for Astrophysics...,
11,Alan Duffy,Director of the Space Technology and Industry ...,

## Create Potential Entity Groups:

In [296]:
list_of_cleaned_data = [a for a in cleaned_data if a['table_name'].lower().startswith('list of')]
len(list_of_cleaned_data)

5690

In [297]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(random.sample(list_of_cleaned_data, 1000))
await group_constructor.get_groups()

🚀 Grouping 1000 tables using Entity-Focus logic...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1000 [00:00<?, ?it/s]

════════════════════════════════════════════════════════════════════════════════
                               📊 GROUPING REPORT
════════════════════════════════════════════════════════════════════════════════
  ✅ Valid Groups:   933
  ❌ Invalid Tables: 67
════════════════════════════════════════════════════════════════════════════════

✨ SAMPLE VALID NAMES:
  → Towns on the Isle of Wight
  → Senior Staff Officers of the Indian Air Force
  → Railway stations in India starting with O

────────────────────────────────────────────────────────────────────────────────
                     🕵️ REJECTION DEBUGGER (Random Sample)
────────────────────────────────────────────────────────────────────────────────

[TABLE]: List of founders of religious traditions > Bibliography
[REASON]: The table contains categories of religious traditions rather than unique instances of entities. It does not meet the criteria for a coherent group of entities.
[DATA]:   {'Abrahamic': 'African', 'Baháʼí Christianity Islam Judaism Rastafari': 'Berber Egyptian Kongo Kushite'}

[TABLE]: List of Canadian Football League records (team) > Streaks
[REASON]: The table contains numerical records categorized by regions (West, East, North, South) rather than unique instances of entities. It does not meet the criteria for a coherent group of entities.
[DATA]:   {'West': 33, 'East': 0, 'North': 1, 'South': 0}

[TABLE]: List of NCHC All-Tournament Teams > All-Tournament Teams > All-Tournament Team players by school
[REASON]: The table contains generic categories (schools) and counts of winners, which does not represent unique instances of a class. It is a summary of counts rather than a coherent group of entities.
[DATA]:   {'School': 'St. Cloud State', 'Winners': 17}

════════════════════════════════════════════════════════════════════════════════

In [310]:
stst = []
for sample in random.sample(group_constructor.valid_tables, 100):
    try:
        stst.append(list(sample['Table data'][0].keys()).index(sample['Entity column']))
        print(sample['Group name'])
        print(sample['Entity column'])
        for row in sample['Table data'][:3]:
            print(row)
        print("=" * 100)
        # display(pd.DataFrame(sample['Table data']))
    except:
        pass
        stst.append('Failed')
# print(Counter(stst))

Grammy Awards received by Carly Simon
Award
{'Year': 1974, 'Work': 'No Secrets', 'Award': 'Best Engineered Recording', 'Recipient': 'Robin Geoffrey Cable and Bill Schnee', 'Result': 'Nominated'}
{'Year': 1976, 'Work': 'Playing Possum', 'Award': 'Best Album Package', 'Recipient': 'Gene Christensen A', 'Result': 'Nominated'}
{'Year': 1978, 'Work': '" Nobody Does It Better "', 'Award': 'Song of the Year', 'Recipient': 'Marvin Hamlisch and Carole Bayer Sager', 'Result': 'Nominated'}
====================================================================================================
Massacres in the Ottoman Empire before 1914
Name
{'Name': 'Massacres during the Greek War of Independence', 'Date': '1821–1829', 'Location': 'Ottoman Empire', 'Deaths': 'Unknown', 'Responsible Party': 'Ottoman government and Greek rebels', 'Victims': 'Greeks , Turks, Albanians and Jews', 'Notes': 'Massacres were committed by both sides during the conflict.'}
{'Name': 'Massacres of Badr Khan', 'Date': '1843-1846', 'Location': 'Hakkari', 'Deaths': '4,000-7,000', 'Responsible Party': 'Kurdish Emirs of Bhutan, Badr Khan and Nurullah', 'Victims': 'Assyrians', 'Notes': 'Many who were not killed were sold into slavery. 1826 Janissaries massacred by government (link to Auspicious Incident).'}
{'Name': 'Asheetha Revolt', 'Date': 1843, 'Location': 'Hakkari', 'Deaths': 10000, 'Responsible Party': 'Tyari Assyrians', 'Victims': 'Kurds', 'Notes': 'Assyrians of Lower Tyari revolted against the oppressive rule of the Kurdish Mir of Berwari,  and killed 10,000 Kurds of Bedir Khan.'}
====================================================================================================
Settlements in Palau by population
Settlement
{'Settlement': 'Koror', 'State': 'Koror', 'Population (2020)': 9524}
{'Settlement': 'Meyuns', 'State': 'Koror', 'Population (2020)': 1631}
{'Settlement': 'Ngetkib', 'State': 'Airai', 'Population (2020)': 630}
====================================================================================================
Argentine cheeses
Name
{'Name': 'Cremoso cheese', 'Description': "A fresh cheese elaborated with cow's milk , with or without the addition of cream. It has its origin in Argentina , and derives from Italian cheeses with similar characteristics as Crescenza ."}
{'Name': 'Criollo', 'Description': ''}
{'Name': 'Goya', 'Description': ''}
====================================================================================================
Closed diplomatic missions in Cameroon
Mission
{'Host city': 'Yaoundé', 'Sending country': 'Greece', 'Mission': 'Embassy', 'Year closed': 2009}
{'Host city': 'Yaoundé', 'Sending country': 'Netherlands', 'Mission': 'Embassy', 'Year closed': 2011}
{'Host city': 'Yaoundé', 'Sending country': 'North Korea', 'Mission': 'Embassy', 'Year closed': 1995}
====================================================================================================
Football clubs in North Macedonia
Club
{'Club': 'Arsimi', 'City / Town': 'Čegrane'}
{'Club': 'Bashkimi', 'City / Town': 'Kumanovo'}
{'Club': 'Brera Strumica', 'City / Town': 'Strumica'}
====================================================================================================
Largest airlines in North America by available seat miles (ASMs)
Airline
{'Rank': 1, 'Airline': 'United Airlines', 'Country': 'United States', '2024': 311, '2023': 291, '2022': 248, '2021': 179, '2020': 123, '2019': 285}
{'Rank': 2, 'Airline': 'American Airlines', 'Country': 'United States', '2024': 293, '2023': 278, '2022': 260, '2021': 215, '2020': 143, '2019': 285}
{'Rank': 3, 'Airline': 'Delta Air Lines', 'Country': 'United States', '2024': 288, '2023': 272, '2022': 233, '2021': 194, '2020': 134, '2019': 275}
====================================================================================================
Later CD-i games
Title
{'Title': 'The New Grolier Electronic Encyclopedia', 'Developer': 'Digimail', 'Publisher': 'World Of Games', 'Release date': 2024, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'Required'}
{'Title': "Origami: Doll's House", 'Developer': 'Eaglevision Interactive productions b.v.', 'Publisher': 'World Of Games', 'Release date': 2024, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'No'}
{'Title': 'Klik', 'Developer': 'Editions Renyi Inc and Sidac s.p.a', 'Publisher': 'World Of Games', 'Release date': 2023, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'No'}
====================================================================================================
Largest companies in the Philippines (2024)
Name
{'Rank': 1, 'Forbes 2000 rank': 806, 'Name': 'SM Investments', 'Headquarters': 'Pasay', 'Revenue (billions US$)': 10.3, 'Profit (billions US$)': 1.4, 'Assets (billions US$)': 28.4, 'Value (billions US$)': 18.6, 'Industry': 'Conglomerate'}
{'Rank': 2, 'Forbes 2000 rank': 880, 'Name': 'Banco de Oro', 'Headquarters': 'Mandaluyong', 'Revenue (billions US$)': 6.1, 'Profit (billions US$)': 1.3, 'Assets (billions US$)': 81.4, 'Value (billions US$)': 12.7, 'Industry': 'Banking'}
{'Rank': 3, 'Forbes 2000 rank': 1137, 'Name': 'Top Frontier Investment Holdings', 'Headquarters': 'Mandaluyong', 'Revenue (billions US$)': 26.0, 'Profit (billions US$)': 0.0, 'Assets (billions US$)': 47.1, 'Value (billions US$)': 0.6, 'Industry': 'Conglomerate'}
====================================================================================================
Members of the Legion of Super-Heroes who joined after the 'Five Year Gap'
Character
{'Character': 'Kono', 'Real name': "Brita An'nan", 'Home world': 'Sklar', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #2 (December 1989); joined in Legion of Super-Heroes vol. 4, #12 (October 1990).', 'Powers': 'Mass-shifting powers allow her to turn herself and others immaterial or super-dense.'}
{'Character': 'Neon', 'Real name': 'Celeste McCauley (a.k.a. Celeste Rockfish)', 'Home world': 'Earth', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #6 (April 1990).', 'Powers': 'Imbued with ancient Green Lantern energy.'}
{'Character': 'Reflex', 'Real name': "Devlin O'Ryan", 'Home world': 'Xanthu', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #6 (April 1990); joined in Legion of Super-Heroes vol. 4, #40 (February 1993).', 'Powers': 'Can reflect physical and energy attacks back to their source.'}
====================================================================================================
Lakes of Latvia by depth
Name
{'Name': 'Drīdzis', 'Depth': '66.2 m (217 ft)'}
{'Name': 'Garais ezers', 'Depth': '56.0 m (183.7 ft)'}
{'Name': 'Lielais Gusena ezers', 'Depth': '56.0 m (183.7 ft)'}
====================================================================================================
Toonami block programs
Title
{'Title': 'FLCL', 'Premiere date': 'August 5, 2003', 'Finale date(s)': 'October 15, 2023'}
{'Title': 'Space Dandy', 'Premiere date': 'January 4, 2014', 'Finale date(s)': 'September 28, 2014'}
{'Title': 'Samurai Jack', 'Premiere date': 'March 11, 2017', 'Finale date(s)': 'May 20, 2017'}
====================================================================================================
Dubbed Malayalam films of 2001
Title
{'Title': 'City Hospital', 'Director': 'Moorthi', 'Screenplay': '', 'Cast': ''}
{'Title': 'Sukhamo Sukham', 'Director': 'KR Joshi', 'Screenplay': '', 'Cast': ''}
{'Title': 'Dheena', 'Director': 'AR Murukadas', 'Screenplay': 'AR Murukadas', 'Cast': 'Ajith Kumar, Suresh Gopi, Laila'}
====================================================================================================
Akademi Yuva Puraskar winners for Odia
Author
{'Year': 2011, 'Author': 'Gayatribala Panda', 'Book': 'Gaan', 'Category': 'Poetry'}
{'Year': 2012, 'Author': 'Srushthishree Naik', 'Book': 'Bhirna Upabana', 'Category': 'Short Stories'}
{'Year': 2013, 'Author': 'Kshetrabasi Naik', 'Book': 'Dadan', 'Category': 'Short Stories'}
====================================================================================================
Banned films in South Africa
Title
{'Date': 1910, 'Title': 'The Johnson-Jeffries Fight', 'Notes': 'Banned because the footage depicted the black boxer Jack Johnson defeating the white boxer James J. Jeffries , which had already inspired race riots in the American South.'}
{'Date': 1964, 'Title': 'Zulu', 'Notes': 'Banned under the apartheid regime from screening to black South Africans, because it depicts a Zulu uprising in the 19th century. Whites were allowed to see it in their own segregated cinemas.'}
{'Date': '1971–1984', 'Title': 'A Clockwork Orange', 'Notes': 'Banned under the apartheid regime for 13 years, then released with one cut and only made available to people over the age of 21.'}
====================================================================================================
Colleges and universities in the University of Missouri System
School
{'School': 'University of Missouri', 'Location(s)': 'Columbia', 'Control': 'Public', 'Type': 'Doctoral/very high activity research university', 'Enrollment (fall 2023)': 31543, 'Founded': 1839}
{'School': 'University of Missouri–Kansas City', 'Location(s)': 'Kansas City', 'Control': 'Public', 'Type': 'Doctoral/high activity research university', 'Enrollment (fall 2023)': 14732, 'Founded': 1933}
{'School': 'Missouri University of Science and Technology', 'Location(s)': 'Rolla', 'Control': 'Public', 'Type': 'Doctoral/high activity research university', 'Enrollment (fall 2023)': 7154, 'Founded': 1870}
====================================================================================================
Top ten grossing Philippine films of 2012
Film
{'Rank': 1.0, 'Film': 'Sisterakas', 'Production outfit': 'Star Cinema , Viva Films', 'Domestic gross 1': '₱ 393,439,711'}
{'Rank': 2.0, 'Film': 'The Mistress', 'Production outfit': 'Star Cinema', 'Domestic gross 1': '₱ 262,790,300'}
{'Rank': 3.0, 'Film': "This Guy's in Love with U Mare!", 'Production outfit': 'Star Cinema , Viva Films', 'Domestic gross 1': '₱ 249,105,182'}
====================================================================================================
Ten largest lakes in Jyväskylä
name
{'rank': 1, 'name': 'Päijänne', 'area (km 2 )': 1082.89}
{'rank': 2, 'name': 'Leppävesi', 'area (km 2 )': 63.593}
{'rank': 3, 'name': 'Muuratjärvi', 'area (km 2 )': 31.54}
====================================================================================================
Screen Actors Guild Awards received by Glenn Close
Nominated work
{'Year': 1995, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'Serving in Silence: The Margarethe Cammermeyer Story', 'Result': 'Nominated'}
{'Year': 1997, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'In the Gloaming', 'Result': 'Nominated'}
{'Year': 2004, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'The Lion in Winter', 'Result': 'Won'}
====================================================================================================
Battles with most Romanian military fatalities
Battle or siege
{'Battle or siege': 'Siege of Odessa', 'Conflict': 'World War II', 'Date': 'August 8 to October 16, 1941', 'Estimated number killed': '17,729 killed', 'Opposing force': 'Soviet Union'}
{'Battle or siege': 'Battle of Mărășești', 'Conflict': 'World War I', 'Date': 'August 6 to September 3, 1917', 'Estimated number killed': '5,125 killed', 'Opposing force': 'Germany Austria-Hungary'}
{'Battle or siege': 'Battle of Mirăslău', 'Conflict': 'Long Turkish War', 'Date': 'September 18, 1600', 'Estimated number killed': 'Over 5,000 killed', 'Opposing force': 'Holy Roman Empire'}
====================================================================================================
Dungeons & Dragons video games in other settings
Title
{'Title': 'Dungeons & Dragons Computer Fantasy Game', 'Setting': 'Generic', 'Genre': 'Action', 'Platform(s)': 'Handheld LCD', 'Developer': 'Mattel', 'Release': 1981, 'Engine': ''}
{'Title': 'Advanced Dungeons & Dragons: Cloudy Mountain', 'Setting': 'Generic', 'Genre': 'Action-adventure', 'Platform(s)': 'Intellivision', 'Developer': 'Mattel', 'Release': 1982, 'Engine': ''}
{'Title': 'Advanced Dungeons & Dragons: Treasure of Tarmin', 'Setting': 'Generic', 'Genre': 'Action-adventure', 'Platform(s)': 'Intellivision', 'Developer': 'Tom Loughry', 'Release': 1982, 'Engine': ''}
====================================================================================================
Highest-grossing films in Japan in 2007
Title
{'Rank': 1, 'Title': "Pirates of the Caribbean: At World's End", 'Gross': '¥10.90 billion ( $92.57 million )'}
{'Rank': 2, 'Title': 'Harry Potter and the Order of the Phoenix', 'Gross': '¥9.40 billion ( $79.83 million )'}
{'Rank': 3, 'Title': 'Hero', 'Gross': '¥8.15 billion ( $69.21 million )'}
====================================================================================================
Former Omaha landmarks
Name
{'Name': 'Clarinda & Page Apartments', 'Location': '1027 Farnam Street, 305-11 Turner Boulevard', 'Built': 1909, 'Destroyed': 2014, 'Notes': 'Demolished by the Mutual of Omaha , now an empty lot.'}
{'Name': 'Monmouth Park School', 'Location': '4508 North 33rd Street', 'Built': 1903, 'Destroyed': 1995, 'Notes': 'Declared a health and safety hazard and razed.'}
{'Name': 'Guy C. Barton House', 'Location': '3522 Farnam St', 'Built': 1899, 'Destroyed': 1982, 'Notes': 'Destroyed in a fire'}
====================================================================================================
Ambassadors of Tajikistan to China
ambassador
{'diplomatic agreement/designated/ Diplomatic accreditation': 'January 4, 1992', 'ambassador': '', 'Russian language': '', 'Observations': 'China and Tajikistan established diplomatic relations in 1992. The Republic of Tajikistan opened its diplomatic mission in Beijing in March 1992', 'Prime Minister of Tajikistan': 'Akbar Mirzoyev', "Premier of the People's Republic of China": 'Li Peng', 'Term end': ''}
{'diplomatic agreement/designated/ Diplomatic accreditation': 'June 20, 1997', 'ambassador': 'Jamshed Karimov', 'Russian language': 'ru:Каримов, Джамшед Хилолович', 'Observations': '', 'Prime Minister of Tajikistan': 'Yahyo Azimov', "Premier of the People's Republic of China": 'Li Peng', 'Term end': ''}
{'diplomatic agreement/designated/ Diplomatic accreditation': 2002, 'ambassador': 'Bahodur Abdulloev', 'Russian language': '', 'Observations': '(*1948 in Bokhtar District ) A major general of state security.', 'Prime Minister of Tajikistan': 'Oqil Oqilov', "Premier of the People's Republic of China": 'Zhu Rongji', 'Term end': 'December 28, 2005'}
====================================================================================================
Exoplanets discovered by star type
Planet
{'Star type': 'First pulsar planet discovered', 'Planet': 'PSR B1257+12 B PSR B1257+12 C', 'Star': 'PSR B1257+12', 'Year': 1992, 'Notes': ''}
{'Star type': 'First known planet orbiting a white dwarf', 'Planet': 'PSR B1620-26 b', 'Star': 'PSR B1620-26', 'Year': 1993, 'Notes': 'Orbits a pulsar and a white dwarf. Discovery confirmed in 2003. GD 66 b was announced in 2007, but has not been confirmed.'}
{'Star type': 'First known extrasolar planet orbiting a main sequence star (Sun-like)', 'Planet': '51 Pegasi b', 'Star': '51 Pegasi', 'Year': 1995, 'Notes': 'First hot Jupiter .'}
====================================================================================================
Kings of Greece from the House of Schleswig-Holstein-Sonderburg-Glücksburg
Name Reign
{'Name Reign': 'George I ( Γεώργιος Αʹ ) 30 March 1863 – 18 March 1913', 'Duration of reign': '49 years, 353 days', 'Birth Date, location, parents': '24 December 1845 Copenhagen , Denmark Son of Christian IX of Denmark and Louise of Hesse-Kassel', 'Marriage(s) Issue': 'Olga Constantinovna of Russia 27 October 1867 8 children', 'Death': '18 March 1913 Thessaloniki , Ottoman Empire  Aged 67', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Third cousin once removed through Christian Karl Reinhard of Leiningen-Dagsburg-Falkenburg and then elected King of the Greeks.'}
{'Name Reign': 'Constantine I ( Κωνσταντῖνος Αʹ ) 18 March 1913 – 11 June 1917', 'Duration of reign': '4 years, 85 days', 'Birth Date, location, parents': '2 August 1868 Athens , Kingdom of Greece Son of George I of Greece and Olga Constantinovna of Russia', 'Marriage(s) Issue': 'Sophia of Prussia 27 October 1889 6 children', 'Death': '11 January 1923 Palermo , Kingdom of Italy Aged 54', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Son of George I'}
{'Name Reign': 'Alexander ( Ἀλέξανδρος ) 11 June 1917 – 25 October 1920', 'Duration of reign': '3 years, 136 days', 'Birth Date, location, parents': '1 August 1893 Athens , Kingdom of Greece Son of Constantine I of Greece and Sophia of Prussia', 'Marriage(s) Issue': 'Aspasia Manos 17 November 1919 1 child', 'Death': '25 October 1920 Athens , Kingdom of Greece Aged 27', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Son of Constantine I'}
====================================================================================================
Faculty members of the College of Arts and Science at New York University
Saul Bellow
{'Saul Bellow': 'Harold Bloom', 'Writer': 'Literary critic', 'Professor': 'Berg Professor of English', '1976 Nobel Prize in Literature': '1985 MacArthur Fellow'}
{'Saul Bellow': 'Faye D. Ginsburg', 'Writer': 'Scholar', 'Professor': 'Professor of Anthropology', '1976 Nobel Prize in Literature': '1994 MacArthur Fellow'}
{'Saul Bellow': 'Galway Kinnell', 'Writer': 'Poet', 'Professor': 'Professor', '1976 Nobel Prize in Literature': '1982 Pulitzer Prize for Poetry'}
====================================================================================================
Marathi films released in 1942
Film
{'Year': 1942, 'Film': 'Pahili Mangalagaur', 'Director': 'R.S. Junnarkar', 'Cast': 'Vishnupant Jog, Lata Mangeshkar , Shahu Modak ,Snehprabha Pradhan', 'Production': 'Prabhat Films', 'Notes': 'This film is primarily remembered for being the acting debut of legend Lata Mangeshkar'}
{'Year': 1942, 'Film': 'Kiti Hasaal', 'Director': 'Vasant Joglekar', 'Cast': '', 'Production': '', 'Notes': ''}
{'Year': 1942, 'Film': 'Pahila Palna', 'Director': 'Vishram Bedekar', 'Cast': 'Shanta Hublikar , Indu Natu, Baburao Pendharkar', 'Production': '', 'Notes': ''}
====================================================================================================
Obscura band touring members
Name
{'Name': 'Ernst "Azmo" Wurdak', 'Years active': 2004, 'Instruments': 'bass', 'Details': "Following the departure of Martin Ketzer, Wurdak filled in for the band's show at Walpurgis Metal Days IV."}
{'Name': 'Matthias "Seraph" Landes', 'Years active': 2007, 'Instruments': 'drums', 'Details': 'Landes filled in for Jonas Baumgartl, who was unavailable, for a European tour in September 2007.'}
{'Name': 'Jacob Schmidt', 'Years active': '2009 2011', 'Instruments': 'bass', 'Details': 'Schmidt filled in for regular bassist Jeroen Paul Thesseling at shows in October 2009 and early 2011.'}
====================================================================================================
Highest-grossing American films of 1987
Title
{'Rank': 1, 'Title': 'Three Men and a Baby', 'Distributor': 'Buena Vista', 'Domestic gross': '$167,780,960'}
{'Rank': 2, 'Title': 'Fatal Attraction', 'Distributor': 'Paramount', 'Domestic gross': '$156,645,693'}
{'Rank': 3, 'Title': 'Beverly Hills Cop II', 'Distributor': 'Paramount', 'Domestic gross': '$153,665,036'}
====================================================================================================
Members of the Folketing (1990–1994)

In [663]:
for sample in random.sample(group_constructor.valid_tables, 25):
    print(f"Group name: {sample['Group name']}")
    print(f"Wikipedia page: {sample['Wikipedia link']}")
    print(f"Entity column: {sample['Entity column']}")
    display(pd.DataFrame(sample['Table data']))
    print()
    print()

Group name: Artists with multiple nominations and awards at the Brit Awards 2006
Wikipedia page: https://en.wikipedia.org/wiki/Brit_Awards_2006#Multiple_nominations_and_awards
Entity column: Artist

  Awards         Artist
0      3  Kaiser Chiefs
1  2 (3)       Coldplay
2  2 (3)      Green Day
3  2 (3)    James Blunt

Group name: Awards and nominations received by Sam Smith at the iHeartRadio Music Awards
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Sam_Smith#iHeartRadio_Music_Awards
Entity column: Nominee / work

,Year,Nominee / work,Award,Result
0,2015,Sam Smith,Artist of the Year,Nominated
1,2015,Sam Smith,Best New Artist,Won
2,2015,"""Stay with Me""",Song of the Year,Nominated
3,2015,"""Stay with Me""",Best Lyrics,Nominated
4,2016,Sam Smith,Male Artist of the Year,Nominated
5,2016,In the Lonely Hour,Album of the Year,Nominated
6,2016,"""Writing's on the Wall""",Best Song from a Movie,Nominated
7,2016,""" Hotline Bling """,Best Cover Song,Nominated
8,2020,"""Dancing With A Stranger"" (with Normani)",Best Collaboration,Nominated
9,2020,"""Dancing With A Stranger"" (with Normani)",Best Music Video,Nominated
10,2021,"""Fix You""",Best Cover Song,Nominated

Group name: 1965 Tennessee Volunteers football schedule
Wikipedia page: https://en.wikipedia.org/wiki/1965_Tennessee_Volunteers_football_team#Schedule
Entity column: Opponent

,Date,Opponent,Rank,Site,TV,Result,Attendance,Source
0,September 18,Army *,,"Neyland Stadium Knoxville, TN",,W 21–0,48500,
1,September 25,Auburn,,"Neyland Stadium Knoxville, TN ( rivalry )",,T 13–13,43614,
2,October 9,South Carolina,,"Neyland Stadium Knoxville, TN (rivalry )",,W 24–3,38519,
3,October 16,at Alabama,,"Legion Field Birmingham, AL ( Third Saturday i...",,T 7–7,65680,
4,October 23,Houston *,,"Neyland Stadium Knoxville, TN",,W 17–8,34504,
5,November 6,No. 7 Georgia Tech *,,Neyland Stadium ( rivalry ),,W 21–7,52174,
6,November 13,vs. Ole Miss,No. 8,"Memphis Memorial Stadium Memphis, TN ( rivalry )",NBC,L 13–14,40181,
7,November 20,at Kentucky,,"McLean Stadium Lexington, KY ( rivalry )",,W 19–3,38000,
8,November 27,Vanderbilt,No. 9,"Neyland Stadium Knoxville, TN ( rivalry )",,W 21–3,36248,
9,December 4,No. 5 UCLA *,No. 7,"Memphis Memorial Stadium Memphis, TN",,W 37–34,44495,
10,December 18,vs. Tulsa,No. 7,"Rice Stadium Houston, TX ( Bluebonnet Bowl )",NBC,W 27–6,40000,

Group name: Villains from the Young Bond series by Charlie Higson
Wikipedia page: https://en.wikipedia.org/wiki/List_of_James_Bond_villains#Novel_villains_by_author
Entity column: Villain

,Novel,Villain,Objective,Outcome,Fate
0,SilverFin,Lord Randolph Hellebore,Achieve world domination with an army of human...,Bond and George Hellebore wreck his laboratory...,Eaten alive by eels alongside his mutated brot...
1,Blood Fever,Count Ugo Carnifex,Steal paintings and sculptures from around the...,His associate Zoltan floods his palace for his...,Dies in the chaos of the flooding fortress whe...
2,Double or Die,"Irina Sedova ""Babushka""",Create an innovative decoding machine for the ...,Bond destroys the machine.,"Spared by Bond. Returns in By Royal Command , ..."
3,Hurricane Gold,Mrs. Glass,Sell important American documents to the Japan...,Succeeds.,Imprisoned on Huracán's island.
4,Hurricane Gold,El Huracán,Punish all guests on his island who break his ...,Bond beats his obstacle course and escapes.,Spared by Bond.
5,By Royal Command,Dr. Perseus Friend,Assist the Nazi cause by making a plan to murd...,"Bond saves the king, destroys Friend's operati...",Shot in the face by Colonel Sedova.
6,By Royal Command,"Irina Sedova ""Babushka""",Find and kill Friend after King George is dead.,"Bond saves the king, destroys Friend's operati...","Shot by Bond, but survives because of her bull..."
7,""" A Hard Man to Kill "" (short story)",Emil Lefebrve,Help General Caiboche escape.,Succeeds.,
8,""" A Hard Man to Kill "" (short story)",Caiboche,Escape from custody.,Succeeds.,Survives.

Group name: Adelaide Strikers Captains
Wikipedia page: https://en.wikipedia.org/wiki/List_of_Adelaide_Strikers_players#Captains
Entity column: Name

              Name             Span  Mat  Won  Lost  Tied  NR  Win %
0  Michael Klinger          2011/12    7    2     5     0   0  28.57
1      Johan Botha  2012/13–2014/15   23   12     9     0   2  57.14
2   Phillip Hughes          2013/14    2    0     2     0   0   0.00
3       Brad Hodge  2015/16–2016/17   17   10     7     0   0  58.82
4      Travis Head  2017/18–2022/23   28   17    11     0   0  60.71
5     Colin Ingram  2017/18–2018/19   14    5     9     0   0  35.71
6       Alex Carey  2019/20–2020/21   16    7     8     0   1  46.66
7     Peter Siddle  2020/21–2022/23   27   12    15     0   0  44.44
8       Matt Short         2022/23-   20   12     8     0   0  60.00
9        Alex Ross          2024/25    3    2     1     0   0  66.67

Group name: Hosts of the European Men's and Women's Team Badminton Championships
Wikipedia page: https://en.wikipedia.org/wiki/European_Men's_and_Women's_Team_Badminton_Championships#Hosts
Entity column: Host city

    Year                Host city
0   2006    Thessalonica , Greece
1   2008     Almere , Netherlands
2   2010          Warsaw , Poland
3   2012  Amsterdam , Netherlands
4   2014      Basel , Switzerland
5   2016           Kazan , Russia
6   2018            Kazan, Russia
7   2020          Liévin , France
8   2022          Lahti , Finland
9   2024            Łódź , Poland
10  2026        Istanbul , Turkey

Group name: Major employers in Ohio
Wikipedia page: https://en.wikipedia.org/wiki/Economy_of_Ohio#Major_employers
Entity column: Employer

,Rank,Employer,Number of Ohio employees,Headquarters location,Sector
0,1,Cleveland Clinic Foundation,56986,Cleveland,Health
1,2,Kroger,44077,Cincinnati,Retail: Food Stores
2,3,Ohio State University and Medical Center,35656,Columbus,Education and Health
3,4,Wright Patterson Air Force Base,28000,Dayton,Government: Air Force base
4,5,University Hospitals Health System,30891,Cleveland,Health
5,6,Mercy Health Partners,30510,Cincinnati,Health
6,7,OhioHealth,30488,Columbus,Health
7,8,ProMedica,18712,Toledo,Health
8,9,Cincinnati Children's Hospital Medical Center,17204,Cincinnati,Health
9,10,Kettering Health,14413,Dayton,Health

Group name: Senators appointed during the 31st Parliament of Canada
Wikipedia page: https://en.wikipedia.org/wiki/List_of_senators_in_the_31st_Parliament_of_Canada#List_of_senators
Entity column: Name

,Name,Party,Province (Division),Date appointed,Appointed by,Left office,Reason
0,Robert de Cotret,Progressive Conservative,Ontario,"June 5, 1979",Clark,"January 14, 1980",Resignation
1,Richard Donahoe,Progressive Conservative,Nova Scotia,"September 13, 1979",Clark,"September 27, 1984",Retirement
2,Lowell Murray,Progressive Conservative,Ontario,"September 13, 1979",Clark,"September 26, 2011",Retirement
3,James Balfour,Progressive Conservative,Saskatchewan,"September 13, 1979",Clark,"December 12, 1999",Death
4,Arthur Tremblay,Progressive Conservative,Quebec,"September 27, 1979",Clark,"June 18, 1992",Retirement
5,Guy Charbonneau,Progressive Conservative,Quebec,"September 27, 1979",Clark,"June 21, 1997",Retirement
6,Martha Bielish,Progressive Conservative,Alberta,"September 27, 1979",Clark,"September 26, 1990",Resignation
7,Nathan Nurgitz,Progressive Conservative,Manitoba,"October 3, 1979",Clark,"February 9, 1993",Resignation
8,Heath MacQuarrie,Progressive Conservative,Prince Edward Island,"October 3, 1979",Clark,"September 18, 1994",Retirement
9,C. William Doody,Progressive Conservative,Newfoundland and Labrador,"October 3, 1979",Clark,"December 27, 2005",Death
10,Cyril Sherwood,Progressive Conservative,New Brunswick,"October 3, 1979",Clark,"July 1, 1990",Retirement

Group name: Honorary degrees received by A. P. J. Abdul Kalam
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_honours_received_by_A._P._J._Abdul_Kalam#Scholastic
Entity column: Degree

,Year,Degree,University,Country
0,2007,Doctor of Science and Technology,Carnegie Mellon University,United States
1,2007,Doctor of Science,University of Wolverhampton,United Kingdom
2,2008,Doctor of Science,Aligarh Muslim University,India
3,2008,Doctor of Science,Universiti Sains Malaysia,Malaysia
4,2008,Doctor of Engineering,Nanyang Technological University,Singapore
5,2009,Honorary Doctorate,Oakland University,United States
6,2010,Doctor of Engineering,University of Waterloo,Canada
7,2012,Doctor of Law,Simon Fraser University,Canada
8,2014,Doctor of Science,University of Edinburgh,United Kingdom

Group name: Teams in the 1987–88 Football League Second Division
Wikipedia page: https://en.wikipedia.org/wiki/1987–88_Birmingham_City_F.C._season#Football_League_Second_Division
Entity column: Team

    Pos                  Team  Pld   W   D   L  GF  GA    GD  Pts
0  17th       AFC Bournemouth   44  13  10  21  56  68  − 12   49
1  18th       Shrewsbury Town   44  11  16  17  42  54  − 12   49
2  19th       Birmingham City   44  11  15  18  41  66  − 25   48
3  20th  West Bromwich Albion   44  12  11  21  50  69  − 19   47
4  21st      Sheffield United   44  13   7  24  45  74  − 29   46

Group name: Teams in the 1997–98 Norwich City F.C. season
Wikipedia page: https://en.wikipedia.org/wiki/1997–98_Norwich_City_F.C._season#Final_league_table
Entity column: Team v t e

   Pos         Team v t e  Pld   W   D   L  GF  GA    GD  Pts
0   13      Bradford City   46  14  15  17  46  59  − 13   57
1   14    Tranmere Rovers   46  14  14  18  54  57   − 3   56
2   15       Norwich City   46  14  13  19  52  69  − 17   55
3   16  Huddersfield Town   46  14  11  21  50  72  − 22   53
4   17               Bury   46  11  19  16  42  58  − 16   52

Group name: UEFA Team of the Year Managers
Wikipedia page: https://en.wikipedia.org/wiki/UEFA_Team_of_the_Year#Most_appearances
Entity column: Manager

           Manager  Appearances
0    José Mourinho            4
1    Alex Ferguson            2
2  Gérard Houllier            1
3      Şenol Güneş            1
4   Frank Rijkaard            1
5    Pep Guardiola            1

Group name: Germany women's national youth football teams head coaches
Wikipedia page: https://en.wikipedia.org/wiki/Germany_women's_national_youth_football_teams#Head_coaches
Entity column: Team

          Team        Head coach
0     Under-23            Vacant
1  Under-19/20     Kathrin Peter
2     Under-17  Friederike Kromp
3     Under-16    Sabine Loderer
4     Under-15  Bettina Wiegmann

Group name: MTV Video Music Awards received by Garbage
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Garbage#List_of_awards
Entity column: Recipient/Work

,Year,Category,Recipient/Work,Result,Winner
0,1996,Breakthrough Video,""" Queer """,Nominated,"The Smashing Pumpkins "" Tonight, Tonight """
1,1996,Best New Artist in a Video,""" Stupid Girl """,Nominated,"Alanis Morissette "" Ironic """
2,1998,Best Group Video,""" Push It """,Nominated,"Backstreet Boys "" Everybody (Backstreet's Back) """
3,1998,Best Alternative Video,""" Push It """,Nominated,"Green Day "" Good Riddance (Time of Your Life) """
4,1998,Breakthrough Video,""" Push It """,Nominated,"The Prodigy "" Smack My Bitch Up """
5,1998,Best Direction,""" Push It """,Nominated,"Madonna "" Ray of Light """
6,1998,Best Editing,""" Push It """,Nominated,"Madonna "" Ray of Light """
7,1998,Best Art Direction,""" Push It """,Nominated,"Björk "" Bachelorette """
8,1998,Best Cinematography,""" Push It """,Nominated,"Fiona Apple "" Criminal """
9,1998,Best Special Effects,""" Push It """,Nominated,"Madonna "" Frozen """
10,1999,Best Special Effects,""" Special """,Won,"Garbage ""Special"""

Group name: Release history of the album 'We Walked in Song'
Wikipedia page: https://en.wikipedia.org/wiki/We_Walked_in_Song#Release_history
Entity column: Region

,Region,Date,Label,Format,Catalog
0,Japan,"March 8, 2007",P-Vine,CD,PCD-23875
1,North America,"March 13, 2007",Badman Recording Co.,CD,BRCD-939
2,Korea,"March 13, 2007",Pastel Music,CD,PMCD-303
3,Taiwan,"March 19, 2007",Avant Garden,"CD, Vinyl",AG1068
4,North America,"March 20, 2007",Badman Recording Co.,Vinyl,BRLP-939
5,Europe,"August 18, 2007",Fargo,CD/Deluxe Edition,FA0096

Group name: Current members of the Anaheim City Council
Wikipedia page: https://en.wikipedia.org/wiki/Anaheim_City_Council#Current_members
Entity column: Councilmember

,District,Councilmember,Party (officially nonpartisan),Entered office,Next election
0,Mayor,Ashleigh Aitken,Democratic,2022,2026
1,1,Ryan Balius,Independent,2024,2028
2,2,Carlos A. Leon,Democratic,2022,2026
3,3,Natalie Rubalcava,Democratic,2022,2026
4,4,Norma Campos Kurtz,Democratic,2023,2028
5,5,Kristen M. Maahs,Democratic,2024,2028
6,6,Natalie Meeks,Republican,2022,2026

Group name: 2019 Ngoma Awards Theatre Winners
Wikipedia page: https://en.wikipedia.org/wiki/Ngoma_Awards#2019_winners
Entity column: Winner

,Award,Winner,Also Nominated
0,Most Outstanding Stage Theatre Actress,Maureen Banda as Mwansa in The Throne,Barbara Mumpanga as Zoe in The Baby ; Karen Nd...
1,Most Outstanding Stage Theatre Production,Banjo – Green Buffaloes,The Baby – Nkhwazi; The Chosen One – Napsa
2,Most Outstanding Comedian,Abel Chungu Musuka,Cheelo Mwanachingwala; Emmanuel Munsaka
3,Most Outstanding Community Theatre Production,Kakhonyonyo – Jere Ensemble Arts Acre,Children of the Dead – Mwazanji Dance Theatre;...
4,Most Outstanding Stage Theatre Director,Bizwell Mudenda for Banjo – Green Buffaloes,Hamalala Hamalala for The Chosen One – Napsa; ...
5,Most Outstanding Male Community Theatre Artist,Jacob Wachata – Chamwaza Performing Arts (Solw...,Daniel Ngoma – Tusole Theatre (Livingstone); S...
6,Most Outstanding Female Community Theatre Artist,Onolina Zulu – Twiza Mobile Theatre (Chipata),Grace Mudenda – Mwazanji Community Dance Theat...

Group name: Academy Awards received by Tony Kushner
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tony_Kushner#Major_associations
Entity column: Nominated work

   Year                  Category Nominated work     Result
0  2005   Best Adapted Screenplay         Munich  Nominated
1  2012   Best Adapted Screenplay        Lincoln  Nominated
2  2022              Best Picture  The Fabelmans  Nominated
3  2022  Best Original Screenplay  The Fabelmans  Nominated

Group name: Men's teams in the 1927 International Cross Country Championships
Wikipedia page: https://en.wikipedia.org/wiki/1927_International_Cross_Country_Championships#Team_Results
Entity column: Team

   Rank   Country                                               Team  Points
0     1    France  Seghir Beddari Henri Gallet Henri Lahitte Roge...      49
1     2   England  Lewis Payne Walter Beavers Ernie Harper Austin...      61
2     3  Scotland  Frank Stevenson Robert Miller Dunky Wright Joh...     112
3     4     Wales  Ernie Thomas E.R. Leyshon Danny Phillips Ted H...     120
4     5   Ireland  Pat Coyle Tommy Keating George Magan Patrick G...     145

Group name: Champions of the Low Countries Cup
Wikipedia page: https://en.wikipedia.org/wiki/Low_Countries_Cup#Champions
Entity column: Winner

   Year               Winner           Runner-up            3rd place
0  2006       Amstel Tijgers    Tilburg Trappers    Heerenveen Flyers
1  2005   Amsterdam Bulldogs   Heerenveen Flyers  Smoke Eaters Geleen
2  2004    Heerenveen Flyers  Amsterdam Bulldogs     Tilburg Trappers
3  1999  Smoke Eaters Geleen       HYC Herentals                 none
4  1998  Smoke Eaters Geleen           Den Bosch           IHC Leuven
5  1997        HYC Herentals           Den Bosch       Griffoens Geel
6  1996      Phantoms Deurne       HYC Herentals        HYS The Hague

Group name: MTV Movie & TV Awards received by John Travolta
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_John_Travolta#Other_associations
Entity column: Nominated work

,Year,Nominated work,Category,Result
0,1995,Pulp Fiction,Best Male Performance,Nominated
1,1995,Pulp Fiction,Best On-Screen Duo (shared with Samuel L. Jack...,Nominated
2,1995,Pulp Fiction,Best Dance Sequence (shared with Uma Thurman ),Won
3,1996,Broken Arrow,Best Villain,Nominated
4,1996,Broken Arrow,Best Fight (shared with Christian Slater ),Nominated
5,1997,Phenomenon,Best Male Performance,Nominated
6,1997,Phenomenon,Best Kiss (shared with Kyra Sedgwick ),Nominated
7,1998,Face/Off,Best Male Performance,Nominated
8,1998,Face/Off,Best Villain (shared with Nicolas Cage ),Nominated
9,1998,Face/Off,Best On-Screen Duo (shared with Nicolas Cage ),Won

Group name: Diplomatic missions of Syria in Africa
Wikipedia page: https://en.wikipedia.org/wiki/List_of_diplomatic_missions_of_Syria#Current_missions
Entity column: Host country

,Host country,Host city,Mission,Concurrent accreditation
0,Algeria,Algiers,Embassy,
1,Egypt,Cairo,Embassy,International Organizations : Arab League
2,Libya,Tripoli,Embassy,
3,Mauritania,Nouakchott,Embassy,
4,Nigeria,Abuja,Embassy,
5,Senegal,Dakar,Embassy,
6,South Africa,Pretoria,Embassy,Countries : Mauritius
7,Sudan,Khartoum,Embassy,Countries : Kenya
8,Tanzania,Dar es Salaam,Embassy,International Organizations : United Nations U...
9,Tunisia,Tunis,Embassy,

Group name: Racial and ethnic composition of Bay County, Florida
Wikipedia page: https://en.wikipedia.org/wiki/Bay_County,_Florida#Demographics
Entity column: Race / Ethnicity ( NH = Non-Hispanic )

,Race / Ethnicity ( NH = Non-Hispanic ),Pop 2000,Pop 2010,Pop 2020,% 2000,% 2010,% 2020
0,White (NH),122708,133790,128348,82.79%,79.24%,73.25%
1,Black or African American (NH),15526,17844,17549,10.48%,10.57%,10.02%
2,Native American or Alaska Native (NH),1096,1033,795,0.74%,0.61%,0.45%
3,Asian (NH),2534,3298,4068,1.71%,1.95%,2.32%
4,Native Hawaiian or Pacific Islander alone (NH),111,140,194,0.07%,0.08%,0.11%
5,Other race alone (NH),164,223,720,0.11%,0.13%,0.41%
6,Mixed race or Multiracial (NH),2487,4417,9696,1.68%,2.62%,5.53%
7,Hispanic or Latino,3591,8107,13846,2.42%,4.80%,7.90%

Group name: Guns N' Roses touring members
Wikipedia page: https://en.wikipedia.org/wiki/List_of_Guns_N'_Roses_members#Members
Entity column: Name

,Name,Years active,Instruments,Details
0,Fred Coury,1987–1988,drums,Coury substituted for Steven Adler between lat...
1,"Kid ""Haggis"" Chaos (Stephen Harris)",1988,bass,Harris replaced Duff McKagan for a show on May...
2,Don Henley,1989,drums backing vocals,Henley replaced Steven Adler for the 1989 Amer...
3,Teddy Andreadis,1991–1993,keyboards percussion harmonica backing vocals,Additional members of the Use Your Illusion To...
4,Roberta Freeman,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
5,Tracey Amos,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
6,Diane Jones,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
7,Cece Worrall,1991–1993,saxophones,Additional members of the Use Your Illusion To...
8,Lisa Maxwell,1991–1993,saxophones,Additional members of the Use Your Illusion To...
9,Anne King,1991–1993,trumpet,Additional members of the Use Your Illusion To...

Group name: Racial and ethnic composition of Rapids City, Illinois
Wikipedia page: https://en.wikipedia.org/wiki/Rapids_City,_Illinois#Demographics
Entity column: Race / Ethnicity ( NH = Non-Hispanic )

,Race / Ethnicity ( NH = Non-Hispanic ),Pop 2000,Pop 2010,Pop 2020,% 2000,% 2010,% 2020
0,White alone (NH),924,922,889,96.96%,96.14%,92.22%
1,Black or African American alone (NH),0,2,8,0.00%,0.21%,0.83%
2,Native American or Alaska Native alone (NH),0,1,1,0.00%,0.10%,0.10%
3,Asian alone (NH),1,3,1,0.10%,0.31%,0.10%
4,Native Hawaiian or Pacific Islander alone (NH),1,0,0,0.10%,0.00%,0.00%
5,Other race alone (NH),1,0,1,0.10%,0.00%,0.10%
6,Mixed race or Multiracial (NH),6,10,27,0.63%,1.04%,2.80%
7,Hispanic or Latino (any race),20,21,37,2.10%,2.19%,3.84%

## Create FanOut-style Questions out of the Entity Groups:

### Rule-Based Strategy Candidate Selection:

In [311]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(group_constructor.valid_tables)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/933 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/933 [00:00<?, ?it/s]

✅ Strategy Selection Complete.

═══════════════════════════════════════════════════════
📊 STRATEGY SELECTION SUMMARY
-------------------------------------------------------
✅ Groups Passed:     897
❌ Groups Discarded:  36
📈 Success Rate:      96.1%
-------------------------------------------------------
Strategy Distribution (Top 4 per table):
  - UNIQUE_DIVERSITY          : 657
  - COUNT_TOTAL               : 473
  - EXTREME_TEMPORAL          : 472
  - FILTER_COUNT_TEMPORAL     : 354
  - FREQUENCY_MODE            : 266
  - CATEGORICAL_FILTER_LOOKUP : 235
  - EXTREME_NUMERICAL         : 91
  - AGGREGATION               : 84
  - TOP_K_RANKING             : 83
  - COMPARATIVE_DIFFERENCE    : 57
  - FILTER_COUNT_NUMERICAL    : 34
-------------------------------------------------------
POSSIBLE STRATEGIES  | GROUP COUNT  | PERCENTAGE
-------------------------------------------------------
#1                   | 79           |       8.8%
#2                   | 182          |      20.3%
#3                   | 181          |      20.2%
#4                   | 455          |      50.7%
═══════════════════════════════════════════════════════

In [316]:
selector.debug_strategy_samples("FREQUENCY_MODE")

Found 266 total tables with this strategy. Showing 5 random samples.

🔗 Source: https://en.wikipedia.org/wiki/List_of_motor_vehicle_awards#People

,Award,Sponsor
0,Automotive Executive of the Year Award,DNV GL - Business Assurance
1,Automotive Hall of Fame,MotorCities National Heritage Area
2,Car Designer of the Century,Global Automotive Elections Foundation
3,Car Engineer of the Century,Global Automotive Elections Foundation
4,Car Entrepreneur of the Century,Global Automotive Elections Foundation
5,Louis Schwitzer Award,Society of Automotive Engineers
6,Time Magazine Quality Dealer Award,"Time , Ally Financial"

🔗 Source: https://en.wikipedia.org/wiki/List_of_new_members_of_the_109th_United_States_Congress#Senate

              Senator                                   Prior background
0     Ken Salazar (D)                       Attorney General of Colorado
1    Mel Martinez (R)  U.S. Secretary of Housing and Urban Developmen...
2  Johnny Isakson (R)  U.S. House of Representatives  Georgia Senate ...
3    Barack Obama (D)                                    Illinois Senate
4    David Vitter (R)  U.S. House of Representatives  Louisiana House...
5    Richard Burr (R)                      U.S. House of Representatives
6      Tom Coburn (R)                      U.S. House of Representatives
7      Jim DeMint (R)                      U.S. House of Representatives
8      John Thune (R)                      U.S. House of Representatives

🔗 Source: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Benedict_Cumberbatch#Major_awards

         Nominated work                                         Category
0  August: Osage County             Outstanding Cast in a Motion Picture
1      12 Years a Slave             Outstanding Cast in a Motion Picture
2    The Imitation Game             Outstanding Cast in a Motion Picture
3    The Imitation Game         Outstanding Male Actor in a Leading Role
4              Sherlock  Outstanding Male Actor in a Miniseries or Movie
5              Sherlock  Outstanding Male Actor in a Miniseries or Movie
6  The Power of the Dog         Outstanding Male Actor in a Leading Role

🔗 Source: https://en.wikipedia.org/wiki/List_of_power_stations_in_Idaho#Renewable_power_stations

                           Name           Primary fuel
0   Bannock County Landfill Gas           Landfill gas
1  Cargill Dry Creek Biofactory                 Biogas
2      Clearwater Paper Biomass        Wood/wood waste
3   Fighting Creek Landfill Gas           Landfill gas
4          Hidden Hollow Energy           Landfill gas
5             Milner Butte LFGE           Landfill gas
6                 Plummer Cogen        Wood/wood waste
7              Rock Creek Dairy                 Biogas
8             Simplot Don Plant  Industrial waste heat
9               Tamarack Energy        Wood/wood waste

🔗 Source: https://en.wikipedia.org/wiki/List_of_Dungeons_&_Dragons_video_games#List_of_games

                                             Title      Setting
0         Dungeons & Dragons Computer Fantasy Game      Generic
1     Advanced Dungeons & Dragons: Cloudy Mountain      Generic
2  Advanced Dungeons & Dragons: Treasure of Tarmin      Generic
3               Spelljammer: Pirates of Realmspace  Spelljammer
4                                       Stronghold      Generic
5                      Al-Qadim: The Genie's Curse     Al-Qadim
6                                           Slayer      Generic
7                                        DeathKeep      Generic
8                Birthright: The Gorgon's Alliance   Birthright
9                       Dungeons & Dragons Tactics      Generic

### Model-Based Question Generation:

In [312]:
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(random.sample(selector.updated_data, 100),
                              strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 100 tables...
--- Round 1: Processing 100 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/100 [00:00<?, ?it/s]

--- Round 2: Processing 1 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1 [00:00<?, ?it/s]

═════════════════════════════════════════════════════════════════
                  📊 QUESTION GENERATION SUMMARY
═════════════════════════════════════════════════════════════════
Initial Tables:      100
Successfully Gen:    100
Exhausted Strats:    0
Success Rate:        100.0%
-----------------------------------------------------------------
STRATEGY                     | SUCCESS  | TRIED    | RATE
-----------------------------------------------------------------
COUNT_TOTAL                  | 16       | 16       | 100%
UNIQUE_DIVERSITY             | 15       | 15       | 100%
EXTREME_TEMPORAL             | 14       | 14       | 100%
FILTER_COUNT_TEMPORAL        | 13       | 13       | 100%
FREQUENCY_MODE               | 13       | 14       |  93%
CATEGORICAL_FILTER_LOOKUP    | 13       | 13       | 100%
AGGREGATION                  | 4        | 4        | 100%
EXTREME_NUMERICAL            | 3        | 3        | 100%
TOP_K_RANKING                | 3        | 3        | 100%
COMPARATIVE_DIFFERENCE       | 3        | 3        | 100%
FILTER_COUNT_NUMERICAL       | 3        | 3        | 100%
-----------------------------------------------------------------
Total                        | 100      | 101      |  99%
═════════════════════════════════════════════════════════════════

🔍 SAMPLES OF FAILED DATA VIEWS:
-----------------------------------------------------------------

[1] Table: Automotive award recipients
    Original Data: https://en.wikipedia.org/wiki/List_of_motor_vehicle_awards#People
    Strategy Attempted: FREQUENCY_MODE
    Rejection Reason:   There is no single most frequent award as all awards are unique in the dataset.
    Table Data:

,Award,Sponsor
0,Automotive Executive of the Year Award,DNV GL - Business Assurance
1,Automotive Hall of Fame,MotorCities National Heritage Area
2,Car Designer of the Century,Global Automotive Elections Foundation
3,Car Engineer of the Century,Global Automotive Elections Foundation
4,Car Entrepreneur of the Century,Global Automotive Elections Foundation
5,Louis Schwitzer Award,Society of Automotive Engineers
6,Time Magazine Quality Dealer Award,"Time , Ally Financial"

-----------------------------------------------------------------

## Question Validation:

### Model-Based Question Validator (Gemini 2.5 Flash):

In [313]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(generator.valid_results, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/91 [00:00<?, ?it/s]

### Manual Validation:

In [318]:
tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 14 samples already tagged in 'tagger_progress.json'.

Output()

# Tests:

## Harvest Wikipedia pages with tables:

1. **The Discovery Phase (The Wide Net)**
   - Input: 22 Subject Groups (e.g., Infrastructure, Sports).
   - Action: We hit the Wikipedia API with two distinct patterns:
     - Prefix Mining: Grabbing every page starting with "Entity in/of..."
     - Search Mining: Finding every page with "List of [Entity]" in the title.
     - Goal: Maximum recall. We want to find everything that might be a list.
2. **The Validation Phase (The Filter)**
   - Action: We open every page found in Phase 1 (asynchronously for speed).
   - Logic: We look for the "DNA" of a table: the {| or wikitable tags.
   - Outcome: We discard the "stub" articles or prose-only pages that don't actually contain structured data.
3. **The Clustering Phase (The De-duplicator)**
   - Problem: Wikipedia often has "List of 2023 Films" and "List of films of 2023." These are duplicates.
   - Action: Using TF-IDF to cluster similar page titles.
   - If two titles are >80% similar, we draw a line (edge) between them.
   - Pick a representative from each cluster to continue.

In [97]:
from knowledge_maze.create_dataset.create_questions.wikipedia_mining import WikiMiner

miner = WikiMiner()
await miner.extract()

Mining Pages:   0%|          | 0/311 [00:00<?, ?entity/s]

Filtering Pages with Tables:   0%|          | 0/87615 [00:00<?, ?page/s]

Computing Similarities for 43421 Titles:   0%|          | 0/43421 [00:00<?, ?titles/s]

Picking Representatives from 38899 Clusters:   0%|          | 0/38899 [00:00<?, ?cluster/s]

## Parse and filter valid Wikipedia tables:

1. **Geometric Fix** - Rebuilds the "hidden grid" of the table. It maps merged cells (rowspans) to their correct spots so the data doesn't shift.
2. **Context Grab** - Captures the Section Path (e.g., Earthquakes > 1954) and the Intro Sentence above the table to explain what the data means.
3. **Trash Filter** - Deletes "Legend" tables, empty tables, and tiny snippets. If it's less than 4 rows or 50% empty, it’s gone.
4. **Variety Control** - "Detects ""Clones"" (like 12 identical monthly tables). It keeps a maximum of 4 different tables per page to ensure the dataset isn't boring.

In [130]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
validated_tables_file_name = await extractor.run_with_progress(miner.valid_titles)

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
cleaned_data = processor.process()

Extracting Tables:   0%|          | 0/38899 [00:00<?, ?Page/s]

Starting Extraction: 38899 titles | Async Limit: 20 | CPU Workers: 7

Filtering & Cleaning:   0%|          | 0/65565 [00:00<?, ?it/s]

In [119]:
processor.display_sample()

,Rank,Region,Numbers (in thousands),Percentage of world total numbers,As percentage of total adult population
0,-,World,62489,100.0,1.1
1,1,Northern America,26778,41.9,9.5
2,2,Europe,16696,26.7,2.8
3,3,Asia-Pacific,10755,17.2,0.8
4,4,China,6190,9.9,0.6
5,5,Latin America,915,1.5,0.2
6,6,India,796,1.3,0.1
7,7,Africa,352,0.6,0.1

## Create Potential Entity Groups:

In [192]:
raw_dat = load_jsonl(os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
len(raw_dat)

65565

In [196]:
raw_dat[0]['table_name']['header_chain']

'List of legislatures by country > List of legislatures > Supranational legislatures'

In [221]:
from collections import defaultdict

def long_tables_no_short_page(raw_dat):
    pages = defaultdict(list)

    for s in raw_dat:
        page = s['table_name']['header_chain'].split(" > ")[0]
        pages[page].append(s)

    return [
        {'title': t['table_name']['header_chain'], 'cols': list(t['rows'][0].keys())}
        for tables in pages.values()
        if all(len(t['rows']) > 12 for t in tables)
        for t in tables
    ]
long_tables = long_tables_no_short_page(raw_dat)
len(long_tables)

14765

In [229]:
SUPERLATIVE_WORDS = ["tallest", "highest", "largest", "biggest", "longest", "shortest", "fastest", "slowest", "oldest", "youngest", "lowest", "richest", "poorest", "deadliest", "busiest", 
                     "costliest", "hottest", "brightest", "strongest", "cleanest", "closest", "narrowest", "earliest", "latest", "greatest", "fewest", "best", "top", "most", "grossing"]
processed = set()
is_ranked = False


for table in long_tables:

    header_chain = table.get('title', {}).lower()
    first_col_name = table.get('cols', [])[0]

    # Match your logic: "Rank" in first col OR superlatives in header
    is_ranked = 'rank' in first_col_name.lower() or any(x in header_chain for x in SUPERLATIVE_WORDS)

    if is_ranked:
        processed.add(header_chain.split(" > ")[0])
        is_ranked = False
print(len(processed))
for p in processed:
    print(f"--> {p}")

912
--> list of cities in brandenburg by population
--> list of cities in kanagawa prefecture by population
--> list of asian countries by gdp
--> list of argentine provinces by human development index
--> list of largest shopping centres in the nordic countries
--> list of tallest buildings in anchorage
--> list of most-visited art museums
--> list of tallest buildings in cape town
--> list of most-isolated mountains of switzerland
--> list of cities in hyōgo prefecture by population
--> list of stadiums in ireland by capacity
--> list of tallest dams
--> list of tallest buildings in st. petersburg, florida
--> list of counties of kenya by gross county product
--> list of hindi films of 1968
--> list of best-selling nintendo switch video games
--> list of tallest buildings in chihuahua city
--> list of tallest buildings in the waterloo regional municipality
--> list of top country albums number ones of 1993
--> districts of west bengal
--> list of the oldest newspapers
--> list of medieval universities
--> list of the largest evangelical churches
--> list of serie a players
--> list of swiss universities by enrollment
--> list of cities in iwate prefecture by population
--> list of the busiest airports in colombia
--> list of earliest coeducational colleges and universities in the united states
--> list of best-selling albums in new zealand
--> list of schools of international relations in the united states
--> list of cities in uzbekistan
--> list of tallest buildings in alabama
--> list of united states senators in the 68th congress
--> list of presidents of the assembly of the republic (portugal)
--> list of youngest members of the united states congress
--> list of highest-earning fortnite players
--> list of longest-running american broadcast network television series
--> list of cities and towns in greenland
--> list of the most populous municipalities in the nordic countries
--> list of top 10 singles in 2019 (ireland)
--> list of highest-grossing film directors
--> list of cities in akita prefecture by population
--> list of tallest buildings and structures in greece
--> list of countries by population in 1500
--> list of most-attended concert tours
--> list of longest-serving higher education presidents in the united states
--> list of youngest euroleague players since the 2000–01 season
--> list of discoteca básica 500 greatest brazilian music records
--> list of albums which have spent the most weeks on the uk albums chart
--> list of cities in chad
--> list of cities in north dakota
--> list of protests and demonstrations in the united states by size
--> list of best-selling singles of the 1970s in the united kingdom
--> list of largest companies in israel
--> languages of pakistan
--> list of governors of new york by time in office
--> list of best-selling albums in japan
--> list of hindi films of 1975
--> list of serie a players with 100 or more goals
--> list of tallest buildings in myanmar
--> list of films based on comics
--> list of north american cities by population
--> list of the busiest airports in the philippines
--> list of colleges and universities in the united states by endowment
--> list of top 10 singles for 2006 in australia
--> list of uk top-ten albums in 2022
--> list of highest bridges
--> list of titles and honours of arthur wellesley, 1st duke of wellington
--> list of prime ministers of portugal by time in office
--> list of top country albums number ones of 2014
--> list of italian regions by highest point
--> list of cities in niger
--> list of animated television series by episode count
--> list of asean countries by hdi
--> list of 1971 box office number-one films in the united states
--> list of longest-serving members of the union council of ministers
--> list of nfl teams with fewest points scored
--> list of fc porto managers
--> list of songs in singstar games (playstation 2)
--> list of countries in asia-pacific by gdp (nominal)
--> list of most expensive books and manuscripts
--> list of countries by access to clean water
--> list of all england men's singles champions
--> list of top 10 singles in 2025 (ireland)
--> list of the busiest airports in europe (2010–2015)
--> list of tallest buildings in vermont
--> list of cities in the united states with the most skyscrapers
--> list of largest fish
--> list of tallest buildings in north hudson
--> list of dutch top 40 number-one singles of 2021
--> list of companies of south africa
--> list of individual gold medalists in swimming at the olympics and world aquatics championships (women)
--> list of soul train episodes
--> list of 1980s albums considered the best
--> list of longest-running american first-run syndicated television series
--> mountains of the central dingle peninsula
--> list of top country albums number ones of 2021
--> list of the busiest airports in germany
--> list of british army awards in the napoleonic wars
--> list of philippine provinces and regions by human development index
--> list of oldest schools in wiltshire
--> list of countries by fragile states index
--> list of countries by seafood consumption
--> list of top 10 singles in 2017 (france)
--> list of companies of russia
--> list of english-language books considered the best
--> list of tallest buildings by country
--> list of largest galaxies
--> list of tallest buildings in chile
--> list of cities in asean by population
--> list of multiple winter olympic medalists
--> list of the busiest airports in oceania
--> list of railway stations in county durham
--> list of cities in chiba prefecture by population
--> list of battles with most russian military fatalities
--> list of north american cities by number of major sports championships
--> list of tallest buildings and structures in southampton
--> list of latin american cities by gdp (ppp)
--> list of dutch top 40 number-one singles of 2016
--> list of highest mountains of switzerland
--> list of top country albums number ones of 2019
--> list of mexican states by human development index
--> list of newspapers by circulation
--> list of tallest buildings in gurgaon
--> list of awards and nominations received by christopher de leon
--> list of most expensive sculptures
--> list of european records in athletics
--> list of players who have appeared in multiple uefa european championships
--> list of most massive stars
--> list of french films of 2023
--> list of cities in himachal pradesh by population
--> list of the busiest airports in thailand
--> list of top 10 singles in 2019 (france)
--> list of cities in tanzania
--> list of highest mountains of austria
--> list of rivers of argentina
--> list of tallest buildings in ankara
--> list of tallest buildings in regina
--> list of united states men's international soccer players
--> list of dutch top 40 number-one singles of 2011
--> list of tallest buildings in bologna
--> list of u.s. states by the number of millionaire households
--> list of number-one billboard top latin albums from the 1990s
--> list of top 10 singles in 2018 (france)
--> list of tallest buildings in north america
--> list of multiple paralympic gold medalists
--> list of cities and towns in egypt
--> list of cities in saxony-anhalt by population
--> list of mountains of valais
--> list of european islands by area
--> list of the busiest airports in vietnam
--> list of association football stadiums by capacity
--> list of the busiest airports in japan
--> list of largest banks in asean
--> list of football clubs in england by competitive honours won
--> list of tallest buildings in pretoria
--> list of the most isolated major summits of the united states
--> list of mountains in kosovo
--> list of u.s. states and territories by exports and imports
--> list of argentine provinces and territories by life expectancy
--> list of mountain peaks of the united states
--> list of la liga winning managers
--> list of largest power stations in the united states
--> list of soccer players with 200 or more a-league men appearances
--> list of banks in bulgaria
--> list of number-one billboard top latin albums of 2007
--> list of all-time nfl win–loss records
--> list of top 100 singles of 2011 (france)
--> states of india by kashmiri speakers
--> list of top 25 albums for 2018 in australia
--> list of cities in germany by population
--> list of presidents of the congress of deputies
--> list of billboard hot 100 top-ten singles in 2025
--> list of number-one singles on tio i topp
--> list of longest-serving united states mayors
--> list of hindi films of 1967
--> list of top 10 singles in 2016 (france)
--> list of highest-certified music artists in the united states
--> list of the oldest buildings in mississippi
--> list of number-one singles from the 2000s (new zealand)
--> list of presidents of socialist vietnam
--> list of countries whose capital is not their largest city
--> list of tallest bridges
--> list of the major 3000-meter summits of the rocky mountains
--> list of buildings in pasadena, california
--> list of members of the 2022–2027 african national congress national executive committee
--> list of unrelegated association football clubs
--> list of cities in maharashtra by population
--> list of presidents of portugal
--> list of highest-grossing concert series at a single venue
--> reservoirs of azerbaijan
--> list of top country albums number ones of 1999
--> list of top 10 singles for 2008 in australia
--> list of tallest buildings in kolkata
--> list of the largest counties in the united states by area
--> list of cities in shizuoka prefecture by population
--> list of top country albums number ones of 2000
--> list of indonesian films of 2022
--> list of u.s. states and territories by infant mortality rates
--> list of tallest buildings in naples
--> list of top 10 singles for 2017 in australia
--> list of number-one singles of 1968 (canada)
--> list of top country albums number ones of 2013
--> list of tallest buildings in monterrey
--> list of north american stadiums by capacity
--> list of countries by pear production
--> list of largest banks in the philippines
--> list of tallest buildings in guiyang
--> list of most-attended concerts
--> list of cities in toyama prefecture by population
--> list of first-level administrative divisions by grdp
--> list of top 25 albums for 2013 in australia
--> list of french films of 2025
--> list of canterbury-bankstown bulldogs records
--> list of multiple sea games medalists
--> list of tallest buildings in karachi
--> list of tallest buildings in dalian
--> list of the oldest buildings in kentucky
--> list of mass shootings in the united states by death toll
--> list of number-one singles from the 1980s (new zealand)
--> list of islands of japan
--> list of tallest buildings in columbia, south carolina
--> list of tallest buildings in taichung
--> list of all-time nba win–loss records
--> list of largest internet companies
--> list of dutch top 40 number-one singles of 2006
--> list of atlantic hurricane records
--> list of largest retail companies
--> list of top 100 singles of 2014 (france)
--> list of billboard hot 100 top-ten singles in 1969
--> list of oldest buildings and structures in toronto
--> list of tallest buildings in camden
--> list of top 10 singles in 2011 (france)
--> list of largest dairy companies
--> list of top 10 singles in 2021 (ireland)
--> list of tallest buildings in toledo, ohio
--> list of presidents of france by tenure
--> list of tallest buildings and structures in the paris region
--> list of railway stations in cumbria
--> list of the simpsons guest stars (seasons 21–present)
--> list of islands in oceania by area
--> regions of tanzania
--> list of grand prix motorcycle racing winners
--> list of the oldest buildings in oregon
--> list of cities in baden-württemberg by population
--> list of largest companies in ireland
--> list of most watched united states television broadcasts of 1993
--> list of hindi films of 1990
--> list of cities in iran by province
--> list of little league world series championship games
--> list of best-selling singles of the 1990s in the united kingdom
--> list of the highest islands of north america
--> list of teams with the most victories in ncaa division i women's college basketball
--> list of the busiest airports in the european union
--> list of football clubs in scotland by major honours won
--> list of tallest buildings in california
--> list of hindi films of 1998
--> list of best-selling nintendo video games
--> list of highest mountains on earth
--> list of magazines by circulation
--> rankings of universities in brazil
--> list of singapore open women's singles champions
--> list of countries by rail usage
--> list of busiest airports in india
--> list of stop motion films
--> list of highest-grossing japanese films
--> list of best-selling light novels
--> list of billboard hot 100 top-ten singles in 1966
--> list of french films of 2024
--> list of cities in jordan
--> list of cities in russia by average winter temperature
--> list of artists with the most uk albums chart number ones
--> list of states and union territories of india by fertility rate
--> list of presidents of south korea by time in office
--> list of european cities by population within city limits
--> list of largest cities and towns in turkey
--> list of banks in the americas
--> list of companies by research and development spending
--> list of iranian football league winning managers
--> awards in the willem c. vis international commercial arbitration moot
--> list of mountains in iceland
--> list of battles with most united states military fatalities
--> list of cities in bavaria by population
--> list of inter milan managers
--> list of dutch top 40 number-one singles of 2020
--> list of olympic medalists in basketball
--> list of top country albums number ones of 1997
--> list of top 10 singles in 2020 (france)
--> list of regions of kazakhstan by gdp
--> list of submissions to the 41st academy awards for best foreign language film
--> list of lowest-income counties in the united states
--> list of highest-grossing mexican films
--> list of fa cup finals
--> list of longest state highways in the united states
--> list of cities in lower saxony by population
--> list of billboard hot 100 top-ten singles in 1962
--> list of dutch top 40 number-one singles of 2009
--> list of the youngest state legislators in the united states
--> list of tallest buildings in manchester, new hampshire
--> list of islands of finland
--> list of hindi films of 1992
--> list of the busiest airports in spain
--> list of top 10 singles in 2017 (ireland)
--> list of cities in yamaguchi prefecture by population
--> list of the oldest lacrosse teams
--> list of highest mountains of yosemite national park
--> list of the highest major summits of the united states
--> list of gp2 series race winners
--> list of cities in south america
--> list of tallest buildings and structures in brussels
--> list of best-selling nintendo ds video games
--> list of top gear home video releases
--> list of number 1 albums from the 1980s (new zealand)
--> list of top country albums number ones of 2003
--> list of tallest buildings in ramat gan
--> list of nigerian states by human development index
--> list of the oldest buildings in indiana
--> list of georgian football first tier players with 100 and more goals
--> list of longest rivers of canada
--> list of football managers with the most games
--> list of largest hospital campuses
--> list of prime ministers of belgium by time in office
--> list of cities in niigata prefecture by population
--> list of cities in togo
--> list of best-selling game boy advance video games
--> list of european ice hockey arenas
--> list of the busiest airports in indonesia
--> list of cycling tracks and velodromes
--> list of best-selling super nintendo entertainment system video games
--> list of largest container shipping companies
--> list of countries by milk production
--> list of french billionaires by net worth
--> list of stoke city f.c. records and statistics
--> list of the best cooking secrets episodes (2020)
--> list of tallest buildings in moscow
--> list of best-selling albums of the 2010s in the united kingdom
--> list of algerian cup finals
--> list of top country albums number ones of 2017
--> list of liga primera records
--> list of anime series listed among the best
--> list of tallest buildings in tallinn
--> list of oldest major league baseball players
--> list of longest tunnels
--> list of best-selling wii u video games
--> list of best-selling singles of the 2000s (decade) in the united kingdom
--> list of soccer players with 50 or more a-league men goals
--> list of best-selling singles of the 2010s in the united kingdom
--> list of telecommunications companies
--> list of newspapers in turkey
--> list of largest insurance companies
--> list of colleges and universities in pittsburgh
--> list of tallest buildings in windsor, ontario
--> list of uk singles chart number ones of the 1970s
--> list of tallest buildings in hangzhou
--> list of ceremonial counties in england by gva
--> list of best-selling gamecube video games
--> list of taça de portugal winning managers
--> list of tallest buildings in buffalo
--> list of best-selling xbox one video games
--> list of tallest lake islands
--> list of best-selling albums in the united states of the nielsen soundscan era
--> list of highest-grossing films in the soviet union
--> list of top 10 singles for 2002 in australia
--> list of longest animated films
--> list of highest paved roads in switzerland
--> list of supertall skyscrapers
--> list of billboard hot 100 top-ten singles in 1967
--> list of the busiest airports in the united states
--> list of dragon award nominees
--> list of brazilian states by highest point
--> list of most-played college football series in ncaa division i
--> list of oldest radio stations
--> list of cities and towns in telangana
--> list of cities in ōita prefecture by population
--> list of united states senators in the 69th congress
--> list of highest railway stations in switzerland
--> districts of peru
--> list of oldest buildings in alabama
--> list of riders with stage wins at all three cycling grand tours
--> list of cities in kagawa prefecture by population
--> list of top 10 singles for 1988 in australia
--> list of cities in missouri
--> list of juventus fc managers
--> list of most-downloaded songs in the united kingdom
--> list of cities by homicide rate
--> list of longest rivers of china
--> list of mountains of the canton of st. gallen
--> list of rivers of italy
--> list of tallest buildings in davao city
--> list of tallest buildings in colorado springs
--> list of record home attendances of australian soccer clubs
--> list of billboard hot 100 top-ten singles in 1995
--> list of tallest buildings in the czech republic
--> list of cities in tottori prefecture by population
--> list of cpbl most progressive awards
--> list of airports in romania
--> list of hindi films of 1991
--> list of record home attendances of english football clubs
--> list of cities in kōchi prefecture by population
--> list of singapore open men's singles champions
--> list of the busiest airports in portugal
--> list of united states senators in the 79th congress
--> list of fis nordic world ski championships 2011 medal winners
--> list of english non–league football stadiums
--> list of computer magazines
--> list of tallest buildings in greater sudbury
--> list of cities in okinawa prefecture by population
--> list of largest producing countries of agricultural commodities
--> list of cities in vidarbha
--> list of top 10 singles for 2016 in australia
--> list of tallest buildings and structures in leicester
--> list of multiple summer olympic medalists
--> list of tallest buildings in peru
--> list of number-one billboard top latin songs from the 1980s

In [3]:
import random

In [42]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
cleaned_data = processor.process()

Filtering & Cleaning:   0%|          | 0/65565 [00:00<?, ?it/s]

In [129]:
cnt = 0
ccc = 0
for s in cleaned_data:
    if "records" in s['table_name']['header_chain'].split(' > ')[0].lower():
        cnt += 1
        # print(f"--> {s['table_name']['header_chain']}")
        cols = list(s['rows'][0].keys())
        if any(["record" in a.lower() for a in cols]):
            ccc += 1
            # print(f"--> {s['table_name']['header_chain']}")
        else:
            print(f"--> {s['table_name']['header_chain']}")

print(cnt)
print(ccc)

--> List of Atletico Marte records and statistics > Achievements > Recopa de UNCAF/1991 Copa Centroamericano
--> List of Atletico Marte records and statistics > Players > Appearances
--> List of Atletico Marte records and statistics > Goalscorers > All-time top goalscorers (Clausura/Apertura) > Historical goals
--> List of Manly Warringah Sea Eagles records > Club Records > Win% vs Former Clubs
--> List of Manly Warringah Sea Eagles records > Club Records > Biggest Wins vs Former Clubs
--> List of Manly Warringah Sea Eagles records > Club Records > Biggest Losses vs Former Clubs
--> List of Manly Warringah Sea Eagles records > Club Records > Other Attendances
--> List of Melbourne Storm records > Individual Records > Points Scoring Records > Top 10 Most Points In a Game
--> List of Melbourne Storm records > Club Records > Losing Games > Top 10 Biggest Losses
--> List of Melbourne Storm records > Club Records > Winning Games > Top 10 Biggest Wins
--> List of Melbourne Storm records > Discipline > Players sent off
--> List of Penn State Nittany Lions wrestling records and statistics > Olympics and post-graduate careers
--> List of Penn State Nittany Lions wrestling records and statistics > National championships > Head coach history
--> List of C.D. FAS records and statistics > Players > Appearances
--> List of C.D. FAS records and statistics > Goalscorers > All-time top goalscorers > Historical goals
--> List of Atlanta Braves team records > Table key
--> List of Punjab Kings records > Individual Records (Bowling) > Best strike rates in an inning
--> List of Punjab Kings records > Individual Records (Batting) > Most Fours
--> List of Sunrisers Hyderabad records > Individual Records (bowling) > Most runs conceded in a match
--> List of Sunrisers Hyderabad records > Individual Records (Batting) > Most fours in an innings
--> List of Sunrisers Hyderabad records > Individual Records (Batting) > Most runs
--> List of Sunrisers Hyderabad records > Individual Records (Batting) > Highest individual score
--> List of AC Milan records and statistics > Player records > Trophies
--> List of AC Milan records and statistics > Managerial records > Trophies
--> List of AC Milan records and statistics > Player records > Appearances > Most appearances
--> List of Surrey List A cricket records > Team records > Margins of victory
--> List of Surrey List A cricket records > Team records > Scores
--> List of Surrey List A cricket records > Individual records > Batting > Career
--> List of Surrey List A cricket records > Individual records > Batting > Season
--> List of Lechia Gdańsk records and statistics > Random statistics > Amber Cup statistics > Top goalscorer
--> List of New Zealand Knights FC records and statistics > Player record > Appearances > Most appearances
--> List of Formula E driver records > Points > Most points in a season
--> List of Formula E driver records > Fastest laps > Most fastest laps in a season
--> List of Formula E driver records > Fastest laps > Highest percentage of fastest laps in a season
--> List of Formula E driver records > Podium finishes > Most races without a podium
--> List of men's association football attendance records > Domestic leagues
--> List of Sydney Roosters records > Attendance Records > Highest Home Attendances
--> List of Sydney Roosters records > Attendance Records > Highest Finals Attendances
--> List of Sydney Roosters records > Attendance Records > Highest Away Attendances
--> List of Sydney Roosters records > Individual records > Most Goals in a Match
--> List of Major League Baseball stolen base records > Team records > Fewest stolen bases by a team in one season (less than 20)
--> List of Major League Baseball stolen base records > Team records > Most stolen bases by a team in one season (450 or more)
--> List of Major League Baseball stolen base records > Team records > Most stolen bases by a team in one season, 1901–present (300 or more)
--> List of Inter Milan records and statistics > Player statistics > Most appearances
--> List of Inter Milan records and statistics > Player statistics > Top goalscorers
--> List of Inter Milan records and statistics > Player statistics > Transfers > Highest transfer fees paid
--> List of Inter Milan records and statistics > Player statistics > Transfers > Highest transfer fees received
--> List of Major League Baseball home run records > Career records > Most seasons with 40 home runs
--> List of Major League Baseball home run records > Career records > Most career grand slams
--> List of Major League Baseball home run records > Career records > Most consecutive seasons with 40 home runs
--> List of Major League Baseball home run records > Career records > Players who have hit at least one home run in 40 stadiums
--> List of Ranji Trophy records > Team records > Highest partnerships per wicket
--> List of Ranji Trophy records > Bowling records > Best bowling figures in an innings
--> List of Ranji Trophy records > Batting records > Most career runs
--> List of Ranji Trophy records > Team records > Lowest innings totals
--> List of Major League Baseball runs batted in records > Four or more seasons with 130 runs batted in
--> List of Major League Baseball runs batted in records > 950 runs batted in by a team in one season
--> List of Major League Baseball runs batted in records > League leader in runs batted in, five or more seasons > League leader in runs batted in, three or more consecutive seasons
--> List of Major League Baseball runs batted in records > Five or more consecutive seasons with 120 runs batted in
--> List of Bengaluru FC records and statistics > All time performance record
--> List of Manchester United W.F.C. records and statistics > Player records > Transfers > Highest transfer fees paid
--> List of AS Roma records and statistics > Top all-time goalscorers
--> List of AS Roma records and statistics > Capocannonierewinners
--> List of Afghanistan Test cricket records > Individual records > Batting records > Most runs against each team
--> List of Afghanistan Test cricket records > Individual records > Batting records > Most runs in each batting position
--> List of Afghanistan Test cricket records > Individual records > Batting records > Most ducks in career
--> List of Afghanistan Test cricket records > Team records > Team scoring records > Fewest runs conceded in an innings
--> List of Atlanta United FC records and statistics > International results > By country
--> Records of prime ministers of the United Kingdom > Number of living former PMs > In the House of Commons
--> Records of prime ministers of the United Kingdom > Number of living former PMs > Most
--> List of Yongin City FC records and statistics > Korean FA Cup records
--> List of Wolverhampton Wanderers F.C. records and statistics > Players > Goalscorers
--> List of Wolverhampton Wanderers F.C. records and statistics > Players > Appearances
--> List of New Zealand Warriors records > Club records > Biggest losses
--> List of New Zealand Warriors records > Club records > Biggest wins
--> List of New Zealand Warriors records > Club records > Kept to nil
--> List of New Zealand Warriors records > Club records > Kept opposition to nil
--> List of Dakar Rally records > T4 Modified Production SSV > Combined competitor and make podiums by nationality
--> List of Dakar Rally records > Quad > Most stage wins in a single Dakar
--> List of Dakar Rally records > T3 Lightweight Prototype > Stage wins in a single Dakar
--> List of Dakar Rally records > Truck > Most wins
--> List of spaceflight records > First independent suborbital and orbital human spaceflight by country
--> List of Parma Calcio 1913 records and statistics > Players > Goalscorers > Top league scorers
--> List of Parma Calcio 1913 records and statistics > Players > Transfers > Highest transfer fees paid
--> List of Parma Calcio 1913 records and statistics > Players > Appearances > Most league appearances
--> List of Yokohama F. Marinos records and statistics > Major International Competitions
--> List of Kerala Blasters FC records and statistics > Competitive record
--> List of Kerala Blasters FC records and statistics > Player records > Top goalscorers
--> List of Kerala Blasters FC records and statistics > Player records > Assists
--> List of Kerala Blasters FC records and statistics > Player records > Clean sheets
--> List of Scotland Twenty20 International cricket records > Partnership records > Highest partnerships
--> List of Scotland Twenty20 International cricket records > Partnership records > Record wicket partnerships
--> List of Scotland Twenty20 International cricket records > Team records > Team scoring records > Largest margin of victory (by balls remaining)
--> List of Scotland Twenty20 International cricket records > Individual records > Individual records (batting) > Most career runs
--> List of Surrey first-class cricket records > Team records > Scores
--> List of Surrey first-class cricket records > Team records > Margins of victory
--> List of Surrey first-class cricket records > Individual records > Batting > Career
--> List of Surrey first-class cricket records > Individual records > Batting > Season
--> List of Parramatta Eels records > Club Records > Biggest Wins vs Former Clubs
--> List of Parramatta Eels records > Club Records > Biggest Losses vs Former Clubs
--> List of Parramatta Eels records > Club Records > Eels Biggest Losses
--> List of Parramatta Eels records > Honours > Runners-up
--> List of Asian Games records in speed skating > Men
--> List of Asian Games records in speed skating > Women
--> List of Eminem records and achievements > Worldwide > Lists
--> List of Derbyshire List A cricket records > Partnership Records
--> List of Derbyshire List A cricket records > Batting Records
--> List of Derbyshire List A cricket records > Team Records
--> List of World Aquatics Championships men's water polo tournament records and statistics > Confederation statistics > Best performances by tournament
--> List of World Aquatics Championships men's water polo tournament records and statistics > Team statistics > Champions
--> List of Minnesota Twins team records > Single-season records > Pitching
--> List of Minnesota Twins team records > All-Time leaders > Batting > Strikeouts
--> List of Minnesota Twins team records > All-Time leaders > Batting > On-base percentage
--> List of Minnesota Twins team records > All-Time leaders > Pitching > Shutouts
--> List of New South Wales cricket records > First-class records > Batting records > Highest individual scores
--> List of New South Wales cricket records > First-class records > Bowling records > Most career wickets
--> List of India Twenty20 International cricket records > Batting records > Most runs in each batting position
--> List of India Twenty20 International cricket records > Batting records > Highest individual score in each batting position
--> List of India Twenty20 International cricket records > Batting records > Highest average in each batting position
--> List of India Twenty20 International cricket records > Batting records > Most career runs
--> List of FK Genclerbirliyi Sumqayit records and statistics > Player > Most appearances
--> List of Rajasthan first-class cricket records > Batting records > Highest individual scores
--> List of NRL Women's records > Team records > Result records > Most points scored in a game
--> List of NRL Women's records > Individual playing records > Most tries scored > In each season
--> List of NRL Women's records > Team records > Grand Final Appearances
--> List of NRL Women's records > Team records > Minor Premierships > Wooden Spoons
--> List of Sri Lanka Twenty20 International cricket records > Bowling records > Most career wickets > Best strike rates in an inning
--> List of Sri Lanka Twenty20 International cricket records > Batting records > Most career runs
--> List of Sri Lanka Twenty20 International cricket records > Bowling records > Most career wickets > Best economy rates in an inning
--> List of Sri Lanka Twenty20 International cricket records > Bowling records > Most career wickets
--> List of first-class cricket records > Team records > Team scoring records > Highest totals in the fourth innings
--> List of first-class cricket records > Individual records > Individual records (batting) > Highest individual score
--> List of first-class cricket records > Individual records > Individual records (wicket-keepers) > Most stumpings in a career
--> List of first-class cricket records > Individual records > Individual records (batting) > Most triple-centuries
--> List of Nepal Twenty20 International cricket records > Partnership records > Highest overall partnership runs by a pair
--> List of Nepal Twenty20 International cricket records > Individual records (Batting) > Highest strike rate in an innings
--> List of Nepal Twenty20 International cricket records > Individual records (Batting) > Most runs in a calendar year
--> List of Nepal Twenty20 International cricket records > Individual records (Batting) > Most runs in each batting position
--> List of Nepal One Day International records > Individual records (other) > Most matches played as captain
--> List of Nepal One Day International records > Individual records (wicketkeeping) > Most dismissals in an innings
--> List of Nepal One Day International records > Individual records (batting) > Highest career average
--> List of Nepal One Day International records > Individual records (batting) > Most runs in each batting position
--> List of women's Twenty20 International records > Batting records > Most career runs
--> List of women's Twenty20 International records > Bowling records > Best strike rate in an innings
--> List of women's Twenty20 International records > Partnership records > Highest partnerships (any wicket)
--> List of women's Twenty20 International records > Batting records > Highest average in each batting position
--> List of Fulham F.C. records and statistics > Fulham in Europe > Group stage: final table
--> List of Fulham F.C. records and statistics > Penalty shoot-outs
--> List of Fulham F.C. records and statistics > Transfers > Highest transfer fees received
--> List of Texas Rangers team records > Rare feats > Hitting for the cycle
--> List of Texas Rangers team records > Rare feats > Triple plays
--> List of England national rugby union team records > Individual career records > Most matches as captain
--> List of extreme weather records in Pakistan > Record-breaking torrential rainfall of August and September 2011 in Sindh > Heavy rainfall recorded during the wet spells of August and September 2011 in Sindh
--> List of extreme weather records in Pakistan > Wind
--> List of extreme weather records in Pakistan > Record-breaking heavy rainfall of September 2012 in Sindh > Heavy rainfall recorded during the wet spell of September 2012 in Sindh
--> List of extreme weather records in Pakistan > Record breaking heat wave of April 2017 > Recorded temperatures
--> List of Brisbane Lions individual awards and records > AFL awards and records > Club awards > Hall of Fame
--> List of Brisbane Lions individual awards and records > AFL awards and records > Club records > Most club goals
--> List of Brisbane Lions individual awards and records > AFL Women's awards and records > Club records > Most club games
--> List of Brisbane Lions individual awards and records > AFL awards and records > Club awards > Kings of the Pride
--> List of Zimbabwe One Day International cricket records > Individual records > Batting records > Most runs in each batting position > Top 10
--> List of Zimbabwe One Day International cricket records > Partnership records > Highest partnerships by wicket
--> List of Zimbabwe One Day International cricket records > Partnership records > Highest partnerships by runs
--> List of Zimbabwe One Day International cricket records > Individual records > Batting records > Highest individual score
--> List of National Lacrosse League records > Attendance records > Game records > Lowest attendance
--> List of National Lacrosse League records > Franchise records > All time records > Championships won
--> List of Nottingham Forest F.C. records and statistics > All-time XI
--> List of Tasmania first-class cricket records > Batting records > Partnership records
--> List of Tasmania first-class cricket records > Batting records > Highest individual scores
--> List of Tasmania first-class cricket records > Tasmania cricket team first-class records > Lowest team totals > Top 6
--> List of Tasmania first-class cricket records > Bowling records > Most career wickets
--> List of Newcastle Breakers FC records and statistics > Player records > Goalscorers > Top goalscorers
--> List of Newcastle Breakers FC records and statistics > Player records > Appearances > Most appearances
--> List of Newcastle Knights records > Club Records > Biggest Wins
--> List of Newcastle Knights records > Club Records > Biggest Losses
--> List of Newcastle Knights records > Individual Records > Match > Most Goals in a Match
--> List of Newcastle Knights records > Club Records > Highest Scores
--> List of South Africa Test cricket records > Team records > Team wins, losses, draws and ties
--> List of South Africa Test cricket records > Batting records > Most runs against each team
--> List of South Africa Test cricket records > Batting records > Most runs in each batting position
--> List of South Africa Test cricket records > Batting records > Highest scores at each batting position
--> List of women's association football attendance records > International matches > International friendlies
--> List of Cardiff City F.C. records and statistics > Player scoring records > Progressive season scoring record
--> List of Major League Baseball wins records > Top 10 career wins by league
--> List of Major League Baseball wins records > Nine or more seasons with 20 wins > Seven or more consecutive seasons with 20 wins
--> List of Major League Baseball wins records > League leader in wins, 5 or more seasons > League leader in wins, 3 or more consecutive seasons
--> List of Major League Baseball wins records > 100 wins in two leagues
--> List of Real Madrid CF records and statistics > Players > Goalscorers > Most goals
--> List of Real Madrid CF records and statistics > Managers > Most wins
--> List of Real Madrid CF records and statistics > Players > Goalscorers > Fastest goals
--> List of Real Madrid CF records and statistics > Players > Transfers > Highest transfer fees paid
--> List of Eintracht Frankfurt records and statistics > Player records > Goalscorers > All-time goalscorers
--> List of Eintracht Frankfurt records and statistics > Club records > Transfers > Bought
--> List of Eintracht Frankfurt records and statistics > Club records > Transfers > Sold
--> List of FC Vaslui records and statistics > Player records > Historical goals > All-time
--> List of FC Vaslui records and statistics > Player records > Historical goals > In Liga I
--> List of atmospheric pressure records in Europe > Western Europe > Germany > Germany monthly maximum figures for atmospheric pressure
--> List of atmospheric pressure records in Europe > Western Europe > France
--> List of atmospheric pressure records in Europe > Western Europe > Belgium
--> List of atmospheric pressure records in Europe > Northern Europe > Denmark > Denmark list of barometric pressure over 1050 hPa
--> List of Columbus Blue Jackets records > Single season records > Goalies
--> List of Tasmania List A cricket records > Batting records > List A partnership records
--> List of Tasmania List A cricket records > Batting records > Highest individual scores
--> List of Tasmania List A cricket records > Team totals > Greatest win margins (by runs)
--> List of Tasmania List A cricket records > Bowling records > Most career wickets

In [170]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(random.sample(cleaned_data, 100))
await group_constructor.get_groups()

🚀 Processing 100 tables...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/100 [00:00<?, ?it/s]

In [47]:
group_constructor.display_debug_samples(num_success=100)

In [156]:
from collections import Counter
ent_cols = [s['Entity column'].strip().lower() for s in group_constructor.valid_tables]
Counter(word for s in ent_cols for word in s.split())

Counter({'name': 92,
         'title': 45,
         'player': 19,
         'work': 14,
         'common': 10,
         'nominated': 9,
         'school': 9,
         'gold': 8,
         'team': 7,
         'film': 7,
         'club': 6,
         'award': 6,
         'nominee': 5,
         'institution': 5,
         'airline': 5,
         'station': 5,
         'airport': 4,
         'building': 4,
         'district': 4,
         'of': 4,
         'english': 4,
         'title)': 4,
         '/': 4,
         'ambassador': 4,
         'city': 4,
         'senator': 3,
         'company': 3,
         'ship': 3,
         'party': 3,
         'character': 3,
         'country': 3,
         'series': 3,
         'artist': 3,
         'conflict': 2,
         'wicket': 2,
         'national': 2,
         'region': 2,
         'in': 2,
         'malay': 2,
         'university': 2,
         'attorney': 2,
         'denomination': 2,
         'honor': 2,
         'athlete': 2,
         'chefs\\competitors': 2,
         'unit': 2,
         'or': 2,
         'faculty': 2,
         'main': 2,
         '(alternative': 2,
         'visiting': 1,
         'actors': 1,
         'railroad': 1,
         'german': 1,
         'episode': 1,
         'officeholder': 1,
         'member': 1,
         'institute': 1,
         'electoral': 1,
         'masashi': 1,
         'ozawa': 1,
         'lake': 1,
         'conflict(time)': 1,
         'peak': 1,
         'from': 1,
         'deputy': 1,
         '(original': 1,
         'location': 1,
         '(chinese': 1,
         'fencing': 1,
         'municipality': 1,
         'translation': 1,
         'clerk': 1,
         'river': 1,
         'museum': 1,
         'incumbent': 1,
         'manager': 1,
         'ambassadors': 1,
         'statue': 1,
         'file': 1,
         'system': 1,
         'clan': 1,
         'nomenclature': 1,
         'designation': 1,
         'county': 1,
         'stadium': 1,
         'native': 1,
         'language': 1,
         'country/territory': 1,
         'app': 1,
         '2014': 1,
         'pairing': 1,
         'species': 1,
         'judge': 1,
         'prosecuting': 1,
         'representative': 1,
         'bridge': 1,
         'churches': 1,
         'organisation': 1,
         'mayor': 1,
         'laureate': 1,
         'actor/actress': 1,
         'release': 1,
         'nickname': 1,
         'city/town': 1,
         'frequency/internet': 1,
         'mother': 1,
         'tongue': 1,
         'volume': 1,
         '(as': 1,
         'assigned': 1,
         'by': 1,
         'haer)': 1,
         'games': 1,
         'opposition': 1,
         'epithet': 1,
         'rr': 1,
         'romaja': 1,
         'software': 1,
         'bullion': 1,
         'coin': 1,
         'hydroelectric': 1,
         'number': 1,
         'hardcovers': 1,
         'subspecies': 1})

In [152]:
aaaaaa = 0
bbbbbb = 0
cccccc = 0
for s in group_constructor.valid_tables:
    if 'name' in s['Entity column'].strip().lower():
        aaaaaa += 1
    elif s['Entity column'].strip().lower() in s['Group name'].strip().lower():
        bbbbbb += 1
        # print(f"{s['Group name']} --> {s['Entity column']}")
    else:
        cccccc += 1
        print(f"{s['Group name']} --> {s['Entity column']}")

print(aaaaaa)
print(bbbbbb)
print(cccccc)

NFL Network Exclusive Game Series results for the 2024 season --> Visiting team
Banks listed on the Athens Stock Exchange --> Company
Companies founded by Stanford University alumni before 1960 --> Company
Wars involving Mongolia and the Mengjiang --> Conflict
Awards and nominations received by Yuna at Anugerah Juara Lagu --> Nominated work
Governors of Kongo Central (1962–1972) --> Officeholder
Awards and nominations received by The Crown at the Hollywood Critics Association Television Awards --> Nominee
Top 10 highest-grossing Japanese films of 2006 --> Title
Online professional wrestling magazines and newsletters --> Title
Episodes of Natural World Series 35 --> Title
Awards and nominations received by Sonali Kulkarni at Zee Chitra Gaurav Puraskar --> Nominated work
Defunct colleges and universities in Delaware --> Institution
Members of the European Parliament for Slovakia (2004–2009) --> National party
Participants of the 1974 Karl Gotch Cup in New Japan Pro-Wrestling --> Masashi Ozawa
Certifications of Songs in the Key of Springfield --> Region
Interim Suicide Squad members (2008–2011) --> Character
Private universities in West Bengal --> University
Universities and colleges in Iceland --> Institution
Motorways in Slovenia --> From
Members of the Ecolo Party in the French Community Parliament (2024–2029) --> Deputy
Belgian films of 2003 --> English title (original title)
Top 5 earthquakes by death toll in 1955 --> Location
Young Adult Fiction Awards --> Award Title
TVB series aired in 2006 --> English title (Chinese title)
Top 11 Amanda Award winners for Best Sound Design --> Film
Awards and nominations received by Alabama at the National Association Of Record Merchandisers Gift Of Music Awards --> Nominee / work
U.S. municipalities in multiple counties in New York --> Municipality
Currently circulating pound sterling coins --> Denomination
Awards and nominations received by Queen Latifah at the BET Awards --> Nominee / work
Ranks for Imperial family members --> English translation
Olympic medalists in men's beach volleyball --> Gold
Awards and nominations received by Joan Allen --> Honor
Israeli films released in 1979 --> Title
Grand Slam girls' singles champions with multiple titles in a season (Channel Slam) --> Player
Active Duty United States Rear Admirals in Joint Positions --> Incumbent
Top 10 highest-grossing Japanese films of 2021 --> Title
Asian Games medalists in men's double sculls --> Gold
Awards and nominations received by Richard Linklater at the Writers Guild Awards --> Nominated work
Films set in West Virginia from 1940 to 1969 --> Title
2005 World Games medal winners in Parachuting --> Gold
Israeli films released in 1985 --> Title
Members of the Althing (Icelandic Parliament) from 2017 to 2021 --> National party
Paralympic medalists in wheelchair curling --> Athlete
Public universities in the Dallas–Fort Worth metroplex --> Institution
Awards and nominations received by Philip Seymour Hoffman at the Academy Awards --> Nominated work
Introductory episodes of NCIS: New Orleans --> Title
Ambassadors appointed by Lula da Silva to Asian countries --> Country
Wars involving the Oyo Empire (1682–1833) --> Conflict
Season 4 competitors of Please Take Care of My Refrigerator --> Chefs\Competitors
Top 5 Kannada films of 1983 by gross revenue --> Title
Complete season sets of Prisoner home video releases in Region 4 --> Title
Pan American Games rhythmic gymnastics group all-around medalists --> Gold
Sacred botanical totems in Meitei culture --> Clan
Philippine laws and their abbreviations --> Nomenclature designation
Universities in Belgium founded after 1945 --> University
Counties of Croatia --> County
Quartermaster units of the United States Army --> Company
Languages spoken in Bulgaria according to the 2001 Census --> Native Language
Top 10 highest-grossing films of 1989 in the United States --> Title
Top 6 highest scores by a losing side in National Rugby League --> Team
Countries with Burger King franchises in Africa --> Country/territory
Hindi films of 1922 (P-R) --> Title
Awards and nominations received by LeAnn Rimes at the Grammy Awards --> Nominee / work
Top 10 highest transfer fees received by Austin FC --> Player
Awards and nominations received by Sudeepa at the Times Film Awards --> Nominated work
Awards and nominations received by Sonali Kulkarni at the Maharashtra State Film Awards --> Nominated work
Top 11 women with the most Grand Slam singles titles of all time --> Player
Top 4 episodes of Top Gear GTi --> Series
Business schools in Quebec, Canada --> School or Faculty
Top 10 American films of 2022 by box office gross --> Title
Business schools in Nova Scotia, Canada --> School or Faculty
Top 10 South African One Day International cricket bowlers by career wickets --> Player
Novels in Werewolf: The Apocalypse series --> Title
Former International Cricket Council members --> Country
Jon Anderson concert tours in 2009 --> City
Episodes of Baddies ATL Season 1 --> Title
2020s Portuguese Colonial War films --> Main title (Alternative title)
Dumplings in Chinese cuisine --> English
Top 10 Hindi films of 2012 by box office collection --> Title
Daily newspapers in Slovakia --> Title
District Attorneys in Hawaii --> Prosecuting Attorney
Weekly newspapers in Slovakia --> Title
Awards and nominations received by Iron Maiden --> Nominee / work
Ambassadors of Finland in Asia (Kuala Lumpur) --> Representative
Top 10 Chinese films of 2021 by box office gross --> Title
Grammy Awards received by Casting Crowns --> Nominated work
Top 10 most populous cities in Florida by decade (1850) --> City
Episodes of Family Guy Season 24 (2025–26) --> Title
Top 8 episodes of Top Gear Take 2 --> Series
Pre-season winners of the Brisbane Rugby League --> Club
Top 10 Hindi films of 2002 by gross revenue --> Title
U.S. municipalities in Kentucky --> City
Top 4 Marathi films of 2026 by box office collection --> Title
Co-operative banks in Germany --> Organisation
Olympic medalists in women's fencing (sabre, team) --> Gold
Top 10 FC Barcelona goalscorers in international competitions --> Player
Grammy Hall of Fame entries by Billie Holiday --> Title
Highways in Castilla-La Mancha --> Denomination
American short films of 1923 --> Title
Actors with two or more Academy Award nominations who have won in non-acting categories --> Actor/Actress
Hindi films of 1925 (T-Z) --> Title
Top 5 cities and towns in Artsakh communities controlled by Artsakh until the 2023 Azerbaijani offensive in Nagorno-Karabakh --> City/town
Top 10 Hong Kong films of 1996 by box office gross --> Title
Indian cities on rivers in Gujarat --> City
Episodes of Three Sheets Season 2 --> Title
Season 3 competitors of Please Take Care of My Refrigerator --> Chefs\Competitors
Top 5 Minnesota Twins pitching shutout leaders --> Player
Disney television series produced by ABC News Studios --> Title
Olympic medalists in alpine skiing medal sweep events --> Gold
Television shows produced by Valleycrest Productions --> Title
Asian Games women golf medalists in individual events --> Gold
British short films of 1938 --> Title
Top 9 Fortnite Championship Series winners by region --> Player
Chinese-language radio stations in Shanghai --> Frequency/Internet
Top 10 highest-grossing Cambodian films of 1970 --> Title
Languages spoken in Scotland --> Mother tongue
Medabots DVD Region 1 home video releases --> Volume
Top 5 wicket-keepers with most career dismissals in Australia One Day Internationals --> Player
Men's WTBA World Tenpin Bowling Championships Medalists (8er teams) --> Games
Israeli films released in 1964 --> Title
Season 9 Dinner: Impossible episodes --> Title
Top 10 Hong Kong films of 2005 by box office gross --> Title
Historical films set in Mainland Southeast Asia --> Title
Top 10 biggest losses of Parramatta Eels against former clubs --> Opposition
Provinces of Joseon --> RR Romaja
Awards and nominations received by Amy Adams at the Academy Awards --> Nominated work
Awards and nominations received by Zhou Xun at the Hundred Flowers Awards --> Nominated work
Soviet–Afghan War films from the 2010s --> Main title (Alternative title)
Top 4 Telugu films of 2006 by box office performance --> Title
National Film Awards received by Mithun Chakraborty --> Work
Fear Street novels --> Title
Hydroelectric power stations in Cameroon --> Hydroelectric station
Members of the Freedom Fighters roster --> Character
Roads in Portugal from the 1985 National Road Plan --> Number
Men's Team Sprint Medalists at FIS Nordic World Ski Championships in Nordic Combined --> Gold
Top 7 colleges and universities in Georgia by Rhodes Scholars --> Institution
Episodes of Taskmaster Series 4 (2017) --> Title
Collected editions of New Teen Titans comics --> Hardcovers
93
99
138

In [171]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidator

group_val = GroupValidator(random.sample(group_constructor.valid_tables, 50))
await group_val.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/50 [00:00<?, ?it/s]

In [172]:
from collections import Counter

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev['ACCEPT'] / sum(rev.values()):.1f}%")
rev

90.0%

Counter({'ACCEPT': 45,
         'FATEFULNESS': 2,
         'CORRECT_ENTITY': 1,
         'SPECIFICALITY': 1,
         'CLOSED_SET': 1})

In [173]:
for sample in group_val.output_data:
    members = [s[sample['Entity column']] for s in sample['Table data']]
    if sample['verdict'] != "ACCEPT":
        print(sample['Group name'])
        print(sample['Entity column'])
        print(f"{sample['verdict']} --> {sample['reason']}")
        print(sample['Wiki url'])
        print(members)
        print("-"*100)

Men's ice hockey players with multiple All-WCHA First Team appearances
Player
FATEFULNESS --> The entity list contains 'many player tied with', which is a table artifact and not a valid player name, making the group invalid.
https://en.wikipedia.org/wiki/List_of_men%27s_All-WCHA_Hockey_Teams#Multiple_appearances
['Marc Michaelis', 'Garry Bauman', 'Jason Blake', 'Jack Connolly', 'Tony Esposito', 'Greg Johnson', 'Keith Magnuson', 'John Mayasich', 'Bill Reichart', 'Brian Swanson', 'Ken Yackel', 'many player tied with']
----------------------------------------------------------------------------------------------------
21st-century vice presidents of the United States and their personal coats of arms
Name of vice president and blazon
CORRECT_ENTITY --> The Entity Column contains highly concatenated strings including the vice president's name, rank, term years, and the phrase 'No arms known', rather than just the primary entity names.
https://en.wikipedia.org/wiki/List_of_personal_coats_of_arms_of_vice_presidents_of_the_United_States#21st_century
['Dick Cheney , 46th vice president, 2001–2009 No arms known', 'Joe Biden , 47th vice president, 2009–2017 No arms known', 'Mike Pence , 48th vice president, 2017–2021 No arms known', 'Kamala Harris , 49th vice president, 2021–2025 No arms known', 'JD Vance , 50th vice president, 2025–present No arms known']
----------------------------------------------------------------------------------------------------
Miscellaneous power stations in Scotland (Wave, Peat, Waste, Tidal, and Landfill gas)
Name
SPECIFICALITY --> The group name 'Miscellaneous' indicates a catch-all category for leftovers (Wave, Peat, Waste, Tidal, and Landfill gas) rather than a single, cohesive, and well-defined concept.
https://en.wikipedia.org/wiki/List_of_power_stations_in_Scotland#Others
['Billia Croo', 'Braehour', 'Baldovie', 'Fall of Warness', 'Greengairs', 'Islay LIMPET', 'MeyGen', 'Shetland Tidal Array, Bluemull Sound', "Steven's Croft", 'Westfield']
----------------------------------------------------------------------------------------------------
Food and drink competitions and awards
Award
CLOSED_SET --> The group 'Food and drink competitions and awards' is an extremely broad category, and a list of only 6 members represents an incomplete, random subset rather than a comprehensive or well-defined closed set.
https://en.wikipedia.org/wiki/List_of_food_and_drink_awards#Competitions
['International Pasty Festival', 'The Food Network Awards', 'New York International Olive Oil Competition', "World Brewer's Cup", 'World Pasty Championships', 'World Porridge Making Championship']
----------------------------------------------------------------------------------------------------
Top 10 Hull City A.F.C. players with the most league goals
Chris Chilton
FATEFULNESS --> The Entity Column name 'Chris Chilton' is a data row (the top scorer) mistakenly used as a header, indicating a flawed table extraction.
https://en.wikipedia.org/wiki/List_of_Hull_City_A.F.C._records_and_statistics#Most_league_goals
['Ken Wagstaff', 'Paddy Mills', 'John Smith', 'Keith Edwards', 'Sammy Stevens', 'Bill Bradbury', 'Ken Houghton', 'Doug Clarke', 'Arthur Temple', 'Dean Windass']
----------------------------------------------------------------------------------------------------

In [164]:
accepted_samples = [sample for sample in group_val.output_data if sample['verdict']=='ACCEPT']

In [166]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidator

group_val = GroupValidator(accepted_samples)
await group_val.validate()

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev['ACCEPT'] / sum(rev.values()):.1f}%")
rev

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/89 [00:00<?, ?it/s]

92.1%

Counter({'ACCEPT': 82, 'CORRECT_ENTITY': 5, 'CLOSED_SET': 2})

In [169]:
for sample in group_val.output_data:
    members = [s[sample['Entity column']] for s in sample['Table data']]
    if sample['verdict'] == "CLOSED_SET":
        print(sample['Group name'])
        print(sample['Entity column'])
        print(f"{sample['verdict']} --> {sample['reason']}")
        print(sample['Wiki url'])
        print(members)
        print("-"*100)

Top 12 extinct Oceanian snails and slugs of the Holocene
Common name
CLOSED_SET --> The group name 'Top 12 extinct Oceanian snails and slugs' implies an arbitrary subset of a larger list, as there is no standard or objective ranking for extinct snails to form a 'Top 12'.
https://en.wikipedia.org/wiki/List_of_Oceanian_species_extinct_in_the_Holocene#FamilyPartulidae
['Toothed partula', "Captain Cook's bean snail", 'Rose-tipped partula snail', 'Miracle tree snail', 'Moorean smooth tree snail', 'Raiatean ground partula snail', 'Tahitian nodular partula', 'Pink partula', 'Sutural partula', 'Mount Tohiea tree snail', 'Mourning partula', 'Variable tree snail']
----------------------------------------------------------------------------------------------------
Fencing clubs in Australia
Fencing Club
CLOSED_SET --> The group name implies all fencing clubs in Australia, but the members only include university fencing clubs, making it an incomplete subset.
https://en.wikipedia.org/wiki/List_of_university_fencing_clubs#Australia
['ADELAIDE UNIVERSITY FENCING CLUB', 'Australian National University Fencing Club', 'La Trobe University Fencing Club', 'Melbourne University Fencing Club', 'Monash University Fencing Club', 'Sydney University Fencing Club', 'UTS Fencing Club', 'UWA Fencing Club']
----------------------------------------------------------------------------------------------------

In [199]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidatorTest

group_val = GroupValidatorTest(random.sample(group_constructor.valid_tables, 4))
await group_val.validate()

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev[True] / sum(rev.values()):.1f}%")
rev

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/4 [00:00<?, ?it/s]

ChatCompletion(id='gen-1773190353-q2hzZ6AWwTuuDHm1Vo26', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='True', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None, reasoning='**Evaluating Group Cohesion**\n\nI\'m currently focused on the coherence of the group "Wind power stations in Iran." Initial assessments suggest a common theme, but I need to ascertain if the group is specific enough to be meaningful. I\'m investigating if the shared location and function constitute a naturally occurring group, or if further refinement is necessary. The group size seems manageable for now.\n\n\n**Defining Group Membership**\n\nI\'ve confirmed each entity\'s presence within the specified geographic and functional criteria. The group\'s coherence is demonstrable, with all members adhering to the definition of "wind power stations in Iran." The entity column\'s members are valid, and the group definition provides a clear rationale for their inclusion. Further, I see the group isn\'t an arbitrary subset, it reflects a real-world category. The size is manageable and suitable. I\'m ready to answer.\n\n\n', reasoning_details=[{'type': 'reasoning.text', 'text': '**Evaluating Group Cohesion**\n\nI\'m currently focused on the coherence of the group "Wind power stations in Iran." Initial assessments suggest a common theme, but I need to ascertain if the group is specific enough to be meaningful. I\'m investigating if the shared location and function constitute a naturally occurring group, or if further refinement is necessary. The group size seems manageable for now.\n\n\n**Defining Group Membership**\n\nI\'ve confirmed each entity\'s presence within the specified geographic and functional criteria. The group\'s coherence is demonstrable, with all members adhering to the definition of "wind power stations in Iran." The entity column\'s members are valid, and the group definition provides a clear rationale for their inclusion. Further, I see the group isn\'t an arbitrary subset, it reflects a real-world category. The size is manageable and suitable. I\'m ready to answer.\n\n\n', 'format': 'google-gemini-v1', 'index': 0}, {'type': 'reasoning.encrypted', 'data': 'CnIBjz1rXyW+K0EOLK5LF8wW9kyMwkF38RlJtWb9PxraQ/bur0VKmM2QAKMVAftTX8lYY6g6gJqG+W68AA4zTYlBPJFv6GQ6GRRHDOYhUPaaC1iOqJvcXtMwMMRCVbUAjE3ZAb3Y8Fj8cU91Dl/IvXiTd1kKYwGPPWtfRNBMoFZ2jlQxEY4uJv6FkNkSfT2viBaOGUNGRuUq9kpvEQUK/nYDCZS8gomny5YUb2w+/nIWTURHm2DDQDJFcYAPzW6IcfuehzHT3LbcefTXP5tt+O6fO8JtK59sVgqLAQGPPWtfEuRie8Lr65IBJYTT08m2ztanpq4JcknLiQtKoe1WUpvFvZPDxgLOjPwC3thuskYFUP/Hi+y0318731IUEetlYafGjlKzFmy2wSFcVsFkuEjKhcvFlIza+si/Q0mrjcG7IdV/zd5Lq7espFRxwk6KsmcXwAMTGy6PGSi7SqA398XScfNALdYKiwEBjz1rX3wp0MlXhxOkAsrV3aSVrM9eEUPfYiLFYYvNPYZjChl2L+V3OUfET1MbpmCexZV0A8KRscLQk/8N78Epmih5vsBFa8C2WVedn6lXS03agzvIAiBN8bc0k1CkCmyFsDSBOHyedN9bJeWf3Bt3/geZCdBEVh9pezQOdpqlzBQkkoEe30ib8Hv1CsQBAY89a18aFiwDzgnQtkCD/BzleaH4wXVsQUm5liduO9zdZlioihY4P7uSjJKK8hiGNB32VCD2YymsB7BzBSPiUvwSTJL7TwA207jjFgcHocNVzN9yUGVJwVPAJpRCDYs+Ve6FJM+o7z88clfCVw66bz/F9DNT7vBeioyjfOGDzKC2Sy6DpJ8wyV55zjsZcT4o3HgRnQzac2SQRr6mgrrAFYd0yqzwGpK1mxF7ZRaUAPdWWjeYdG8cjCMkVkPE+7mDf7HWPgq0AQGPPWtfxougKnAttG4cTKL1V9pWQIbU5wQQ/Ts+gHN8Y03sermrwuvY7KBOOQ87YqIwq2ouTZ9lSlzQUXyscIpHXJuvgXsFIevtnR2alTugq5ecyI0GQOApXLNarLr78c5/cTTEueaDzuONGNLdI0y8atUbdKrcXECFpFsEB6vUwwKTg1Y/f6K3cmu8NGEa2fpeHpY6169QOmldx1RgeRUoE/sEyZWqXLtB168xsrJBT8QWJwrBAgGPPWtfoUmtA1uspY+gzX0IQGPVRV7pJl29X/eM3fjcEu+Obl/R8uMqWI844Do1mdiluyDwccDwx4zPIddCgUHVzvJJVEOKdKCpevbwOEUaILp4pINx7Jpd5NJVXlNiGPaDtrG0m5H/xaCUnYUacGbIHR2F0Z5DITS3kV4TyavVCPi50hdm6jsgwFAMERpNrlewmyLJPF8bFGX4AFmL6CmUN5dxibmIwgp9p8Nq2k9upg0NZApdV5O4CJMT+ttUSXBb90UwH2HYM9/6IKfHxffFGpniYmzcZgszLw1YghGrt0ld8+pHGdLbM9Ppa9AsjHY6XpQ+RPHNOSnRmY4sxdoA1eBkQby6AEoVLrGGDYwiVaIH/rP0ClW+9eZ+bIMPbrGGmEIRXFADjzRV85eI6Grmm7GHWzjx6vCv0meSQwy2DgqbAgGPPWtfSGbrl3Q+0M0X9/6yJrimJxNfQw33oQdEGEgxtdPaXSd5UHnMoFWoaMX+k7xiKsmPI5bgAmqOM9pOFNADV/doLVhuOUnAzlpzW5qkSwDSTwZT4qW+caot9DAFhhqvEdIAIDBWqyOp7FQaSCWmLWKSS/8NmWHAYvu22w2nUs4xRPb1W4TRg/gdUZdAwDksRq9HoRiq1vdRs/A4lP5uxVkaE9/K4bbFSGOQcoHq2VPQYAYe38EePXrp6LGq/TIBH2Z3yDQ3o/A3EFR37+hUSqmc6VSDMQ74fEdpPVyWqIgxuMvtdSBUyejQOCyJFHdGjE5/1+MEEqfGCEjx4CzaIUfKlth0SEB2dJGpXVsBoHJKXwop3uFjx24KUwGPPWtfmS8X/EQvpc8ts5YGS5RLICaUusIL5yrXP6o6fphZD/VdLrUnauFH78FEpCkh2ILOu640qW5Tfk+/fmkv347Iu8GN4+R4vcRppEc+9grO', 'format': 'google-gemini-v1', 'index': 1}]), native_finish_reason='STOP')], created=1773190353, model='google/gemini-3.1-pro-preview-20260219', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=340, prompt_tokens=153, total_tokens=493, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=339, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.004386, is_byok=False, cost_details={'upstream_inference_cost': 0.004386, 'upstream_inference_prompt_cost': 0.000306, 'upstream_inference_completions_cost': 0.00408}), provider='Google')
Unexpected Error: 'ChatCompletionMessage' object has no attribute 'parsed'
ChatCompletion(id='gen-1773190353-UsULX3UXGLhbdde5zvkU', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='True', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None, reasoning='**Analyzing Group Cohesion**\n\nI\'m currently focused on the coherence of the group. Initial assessment indicates a specific, rather focused, group. Its members seem to be naturally connected by their shared role. Now, I\'m verifying the naturalness of the group, which could be dependent on the duration of their tenure and other factors.\n\n\n**Validating the Membership**\n\nI\'m now cross-referencing the example members against the official list. It appears there may have been a typo ("Xiaoshen" instead of "Xiaosheng"), but otherwise the list seems accurate. Now, I\'ll analyze the listed period of service.\n\n\n**Confirming the Attributes**\n\nThe "Ambassador" designation appears accurate, given the role\'s function as a de facto embassy. The group definition is precise and the listed members align with the official roster, once the single typo is corrected.\n\n\n', reasoning_details=[{'type': 'reasoning.text', 'text': '**Analyzing Group Cohesion**\n\nI\'m currently focused on the coherence of the group. Initial assessment indicates a specific, rather focused, group. Its members seem to be naturally connected by their shared role. Now, I\'m verifying the naturalness of the group, which could be dependent on the duration of their tenure and other factors.\n\n\n**Validating the Membership**\n\nI\'m now cross-referencing the example members against the official list. It appears there may have been a typo ("Xiaoshen" instead of "Xiaosheng"), but otherwise the list seems accurate. Now, I\'ll analyze the listed period of service.\n\n\n**Confirming the Attributes**\n\nThe "Ambassador" designation appears accurate, given the role\'s function as a de facto embassy. The group definition is precise and the listed members align with the official roster, once the single typo is corrected.\n\n\n', 'format': 'google-gemini-v1', 'index': 0}, {'type': 'reasoning.encrypted', 'data': 'CncBjz1rXwa+BQyDsHLtOoDPzzkUay5z4FAxYV87cc9tE8T/8dNQXvIs3uFd7bMeiaEHwPf0u+cUTsh2HyP/KCsvDpg1Fqu07xcukflCY1TFV//LgPtFBii5NNUVgY4+qxuvZx7VAL1S2PLNms+mFE9BcPzu0DJBAgptAY89a1/NnHOFgKbl9MaxuPhPM8TQH0H71XRJZ4haWbteftNh7Nzsm0ZyAU5e+1JjO/kph9Y9a/KXd6c+uzqVzMjdRZsiUzh0/HQQ5GbYfpt8Fc6rOrmJVNfd0wBG6mGPtuhZ2s877Sy44f/JTwq1AQGPPWtfEQag4Z6XARBDcpwlSIlSEvNQKMwQgDpShSSnm5oCDwIpDgvwTdvEp9OfEcZihzSXQRbf3tv2kwCOMCwIPHblsu/qGNY5yDaBAnqeizSillLs/mCuiZc1fvHaKJkifutpmpkKBo+VPkj3lg/rh5BJFqiIFSbNjKhB6HooxfkvFHYB2D7GCbi5zm5GISty+o+d6myMrpSrkFgIvFEzOgVe5cRwc1gjhqtFdpz67fP2TBMKewGPPWtf9cG9aAmWNaPaeq52Ph5sv/a+Avv5Fc6XEQ0fZLrtQrlN+VWzBIFheOirQH/UEs9Y4/2JzsUvvYAD1m6dqunoZp461grlJ3aW6zZ59nYze9euGJtHWU+Zaw711Rnfv8MV9Vblb7WgHpL+iowsBb681ojF3NkTeArkAQGPPWtfOCcnoSu/CIzswPbUW2E2G/Phd9yrON4GN26BWP3CWIPiLTfG2fZVJ6Qzj9R0mfaYesCykI1U3T+ATAABcbeFl2etcCb5mJ7SnJ0Bckujx1v8qtKTvLVVc7myoZIMM6vVwCzEsZJ9PWfG+z7qEOmCVXTLBZzs6hDMMe7SopOBV90Yf4Fr4OJbQ7bDo18V/gtun2y5h6TU+pMQQv+gcEJs71RUP4C0bcHcG1gI9ugTr6kOhLe8fI88yLhKqwnXbKlRjwlAIIOj3whs+JKAsZ06uu68YJ/JpcuJefTofz8HLQqFAgGPPWtfkcqs+MouFUMGNd170021kRp8/8vcmJm1tLxi+oILNV1eGbHJGyGIweR20ZbwHAVgykgwUjm93cUHanqZG/0COuRJZ4nh4SBg3fNwYVpwllA5nFDGaXTcCkpFgCEkJC5bsCYcBZgapPZv99fHsd18oK27+ubO7swSGTbqu+//fqd+DYT4HJuJfRc3ZFpfe0z2LaxLhS8Ma5FjrtKtsq657IUmQiqSUCJfiwiO17QM72ZCgduLT9LQaVrgOfxQGrTYqBzJLow4umDSRHCSWMq8wMGXybR7z/DiVLxWZFrznuFpAv4fyYsuGhvBKgXQweu/WT/OqVrbkf2W6v+p0lOX7ArBAQGPPWtfJFdJu6BuoaGSuxLteuzkXP5kMGRMpGyyXegggRroKxovmBlP2GajbD5iHwx+GrNOwLuTxi8z8Qxjp6MezMAuxGetb6drF4sySoiTPQz4zzQGwesq+E/HMQ07OvTkm4eQR9HjUQjbr62Ly7DYgVDmKmAr16pGbm58Y8AR+wiA+76m2hHq0c4eFT31kfrIelRdeD2BOqzTxqdBgfVW3+f5FqQn+MChH5d06vGM8aHa9PmR45rUk7oLEOrxXI0KkwEBjz1rX5Hoz5xSmeXXS/Fp8DcsavPNOtJ6qMX0YA0NhJ2/oZcS7ysm+T+kubZPREMHPtSbcTy/eku/+LfJDN1rZV/F0uBfrwy3NnHpRziH2p5YZwcIA6PEUtdqmYMOOPOTVLA1xDuWdOb7vpiu86ZTeYBAO2N0OTZlA+K99epKJx3aDCnhglJdB4z7n3QpNs5H6xcKvwEBjz1rX/SpnjYeHKVii0hjIrvnMd0iW0MjJuf6btVHTcL19O8uWDmifq9nPx4kz+D6DDeOvN4P3emjKaEu+xD/d4rfe3IuuKtED0Xwjc3cDque+V42gQ4l4VjLGZ+dj5gi0Jqsh4TQARJoGl7cqb6iSnq/815Jj1Ds10TPKuqQ2P27SizneAGY77r2+HrUw/wfkeSrkCVVYh2/vw8T8Xkp5RM2jhXSJ6XiYUz6NJ1TmeOrJ4b4lT4UWQjzBG/b4wqVAQGPPWtfXDJbe7PKrcBBK4qMmoPt7A+ImLdq15+oRu0rWJ+vH5+8S3VTmgVV5VggP4mGe/4ZxCf8ghbOOi2BFoWCVDIS3BtGIleIiFOGZj+13XgaJZvo8YB8gXt/PqeyAITktEVCQ14baNvQU19TPBsZaYHxQA3hjLnPjci8H/UHtqNEFgCair1Npt0ViiG/VxBq4rPOCs4BAY89a19RhSOHzUA7zDgpY/Z0USUl5z8x3Vp2naGbjB6obhXYeYAOkYgs3Ma03nAGrgGAfIlZUTVj8ZbJ/70nhOfteYp6cp1yRTfTn+zHiJ5ycuee+VeEp1soVs+PqMASYmXaheQHhq8cpJjNM334ePzAlOWCXmp7oKO3ThNMQRqlqAc7wo/Vyl7UBfnWZsGlvuMlsErUKM1ns14Y1AXQ651oKHzb3IEp07mEpQ/AwbR24adDGKe2ea4bYSDHWOCXrGMWWPs94JQP1NTDqlgKwQIBjz1rX4hef+c1HCsE6XZTOuWPkrOvvUowo1wACiR4WC8Y4Dx8em6MBIF0O3yP5PKMkw277/mEDvPtjcl1dlXV90kpVE+HmAU3ARyqeipoC1lemmrePQjs82nLSggKqPy5oDkdTgy9sKnFOBfQLuA3StcuoSI0MyMYzYyqyYTDby9Ab15LX67ilvlHMsmxdrsmqRfYSnlI85ximYo3YqRB22VTmhNxgPKLtdHw+jAeCtG5xQJ8Lf0Zh2QMgoVVIZnJb/Zft5tkcaZ+VjRKhrFbqQG0K2BILuZ3MEaSsFkhHhdPxiKyWARgV3cYCnejT3LI7YR/v6RfaU5/B/v4GpzVQAAMikTpA89f22y79oFbhLR3jSX0cu9Hm95ZpS0NeqKzp+Ead+MA19ODaCUGDhyNQeA1HjsyPzuB+FSqp3owNqoKmAIBjz1rXyTLZuiVjx3PfRxyu3OcTcNJn5XWZHoWh1td8bw+7muGfBkaZnx1z+ApDBNlj01LOixSLrwX9v0RtJxQFJDnHTe3ljfZVMCUNolNYblvhzfhOEgA1C4QreV8BCx7l5Loa0+AL4K9SGw6lgxcbgPUHw8LNY22slyzYxEOXvm9WVJ+emgLbfTZdu7dDiFiNsqABDeFiFAocj4v/iKXPmco4P9Vq5jX4E3e5E7BSZhpI0zyGoGqUuV+tImEQHNY6YSmLPIsRH4JEbEeGsTEz+UTKwjQjh6zwXXlEPxyYu0OsqvsSkjsrIaRD80qPjG+5uONhB9gutiVBAIOGVO74XiI6P1i2Ckqkx4NKMY53q4IoMNG4kQzCpECAY89a1+LRh37Dt5JK5+AEGRd8EUwY/GZkDMz1FVRt0KeRsjl32uEicPDukFuON+YHcLVZ/BAKIbjjOR2l6yO9ZHIpaRspjldgYeoSRJtvV281VFhGv2rqGOCcniuZENEdst0M900Gl6wjJPWUTw/RTSgz9NI11aaqBT9vOYm4TDLLMkENadQQgk+CKPzMPhnz70D4ft9nOV/PQOSKJ0tt3tDJF5fgXsPJmQZgPP/WX6/1FPiTmNOgd88c8zlViM4jUiH9j99WqQggupRAgCDxJ2bOZ5Swn3I73x9linnDeiGD+7s6lUbpna7xbEE/Mk5sqX4iPA7ef7pLymse6KmiQ9jzq8UB5EdhoNZ4X310mAF', 'format': 'google-gemini-v1', 'index': 1}]), native_finish_reason='STOP')], created=1773190353, model='google/gemini-3.1-pro-preview-20260219', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=714, prompt_tokens=145, total_tokens=859, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=713, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.008858, is_byok=False, cost_details={'upstream_inference_cost': 0.008858, 'upstream_inference_prompt_cost': 0.00029, 'upstream_inference_completions_cost': 0.008568}), provider='Google')
Unexpected Error: 'ChatCompletionMessage' object has no attribute 'parsed'

Counter({None: 4})

In [184]:
for s in [sample for sample in group_val.output_data if not sample['verdict']]:
    print(s['Group name'])
    print(s['Entity column'])
    print(s['Wiki url'])
    print("-"*100)

Members of Task Force ✱/Suicide Squad Dark
Character
https://en.wikipedia.org/wiki/List_of_Suicide_Squad_members#Task_Force_%E2%9C%B1/Suicide_Squad_Dark
----------------------------------------------------------------------------------------------------
Top 5 mainland Chinese albums by annual sales percentage on the Billboard China V Chart in 2016
Album
https://en.wikipedia.org/wiki/List_of_Billboard_China_V_Chart_top_10_albums_of_2016#Mainland_%28Domestic%29_albums
----------------------------------------------------------------------------------------------------
Taiwanese films released in 2001
Title
https://en.wikipedia.org/wiki/List_of_Taiwanese_films_of_the_2000s#2001
----------------------------------------------------------------------------------------------------

In [187]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidator

group_val = GroupValidator([sample for sample in group_val.output_data if sample['verdict']])
await group_val.validate()

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev['ACCEPT'] / sum(rev.values()):.1f}%")
rev

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/17 [00:00<?, ?it/s]

Input tokens: 642
Output tokens: 188
Input tokens: 577
Output tokens: 271
Input tokens: 578
Output tokens: 207
Input tokens: 519
Output tokens: 255
Input tokens: 629
Output tokens: 236
Input tokens: 622
Output tokens: 251
Input tokens: 533
Output tokens: 369
Input tokens: 624
Output tokens: 406
Input tokens: 616
Output tokens: 430
Input tokens: 606
Output tokens: 548
Input tokens: 630
Output tokens: 182
Input tokens: 596
Output tokens: 217
Input tokens: 607
Output tokens: 155
Input tokens: 571
Output tokens: 238
Input tokens: 544
Output tokens: 219
Input tokens: 580
Output tokens: 892
Input tokens: 581
Output tokens: 181
94.1%

Counter({'ACCEPT': 16, 'CLOSED_SET': 1})

In [26]:
def format_sample_for_chat(s):
    cols = list(s['Table data'][0].keys())
    entity_col = s['Entity column']
    entities = [r.get(entity_col, "") for r in s['Table data']]

    return f"""
Group name: {s['Group name']}
Entity column: {entity_col}
Columns: {cols}
Entity members: {entities}
Group size: {len(entities)}
Source: {s['Wiki url']}
Row example: {s['Table data'][0]}
--------------------
""".strip()

In [48]:
for i in random.sample(group_constructor.valid_tables, 100):
    print(format_sample_for_chat(i))

Group name: International schools in Kowloon City District, Hong Kong
Entity column: Name (Abbreviation)
Columns: ['Name (Abbreviation)', 'Curriculum', 'Affiliation', 'Established']
Entity members: ['American International School Hong Kong (AIS)', 'Australian International School Hong Kong (AISHK)', 'Beacon Hill School (BHS)', 'Christian Alliance P.C. Lau Memorial International School (CAPCL)', 'Jockey Club Sarah Roe School (JCSRS)', 'King George V School, Hong Kong (KGV)', 'Kingston International School (Kingston)', 'Kowloon Junior School (KJS)', 'Po Leung Kuk Ngan Po Ling College (NPL)', 'Stamford American School Hong Kong (SAIS)', 'Think International School (TIS)', 'Yew Chung International School (YCIS)']
Group size: 12
Source: https://en.wikipedia.org/wiki/List_of_international_schools_in_Hong_Kong#Kowloon_City_District
Row example: {'Name (Abbreviation)': 'American International School Hong Kong (AIS)', 'Curriculum': 'AP', 'Affiliation': 'Americans in Hong Kong', 'Established': 1986}
--------------------
Group name: NCAA Division I men's soccer coaches in the Horizon League
Entity column: Head coach
Columns: ['Program', 'Head coach', 'First season']
Entity members: ['Siniša Ubiparipović', 'Nate Kopunek', "John O'Reilly", 'Sid van Druenen', 'Kris Kelderman', 'Ryan Swan', 'Sean Teepen', 'Paul Doroh', 'Stephen Gorton', 'Jonathan Potter', 'Alex Van der Sluijss']
Group size: 11
Source: https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_men%27s_soccer_coaches#Horizon_League
Row example: {'Program': 'Cleveland State', 'Head coach': 'Siniša Ubiparipović', 'First season': 2019}
--------------------
Group name: Players with 100 or more appearances for FC Ararat-Armenia
Entity column: Name
Columns: ['Name', 'Years', 'League apps', 'League goals', 'Cup apps', 'Cup goals', 'Super Cup apps', 'Super Cup goals', 'Europe apps', 'Europe goals', 'Total apps', 'Total goals', 'International Career']
Entity members: ['Armen Ambartsumyan', 'Karen Muradyan', 'Alwyn Tera', 'Junior Bueno', 'Mailson Lima', 'Artyom Avanesyan', 'Alemão', 'Zhirayr Shaghoyan', 'Tenton Yenne', 'Jonathan Duarte']
Group size: 10
Source: https://en.wikipedia.org/wiki/List_of_FC_Ararat-Armenia_records_and_statistics#100_or_more_appearances
Row example: {'Name': 'Armen Ambartsumyan', 'Years': '2018–Present', 'League apps': 181, 'League goals': 17, 'Cup apps': 28, 'Cup goals': 0, 'Super Cup apps': 3, 'Super Cup goals': 0, 'Europe apps': 20, 'Europe goals': 0, 'Total apps': 232, 'Total goals': 17, 'International Career': 'Russia under-21'}
--------------------
Group name: Private vocational schools in Istanbul
Entity column: Name
Columns: ['Name', 'Year of Foundation', 'Founder Foundation']
Entity members: ['Istanbul Şişli Vocational School', 'Ataşehir Adıgüzel Vocational School', 'Istanbul Health and Social Sciences Vocational School', 'Dreams Academy (Düşler Akademisi)']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_universities_in_Istanbul#Private_vocational_schools
Row example: {'Name': 'Istanbul Şişli Vocational School', 'Year of Foundation': 2012, 'Founder Foundation': 'Istanbul Şişli Foundation'}
--------------------
Group name: Symphyotrichum species in the Section Concolores
Entity column: Scientific name and picture
Columns: ['Scientific name and picture', 'Author citation', 'Basionym', 'Year', 'Common name(s) and varieties', 'NS', 'Habitat', 'Distribution']
Entity members: ['S. concolor', 'S. lucayanum', 'S. plumosum', 'S. pratense', 'S. sericeum']
Group size: 5
Source: https://en.wikipedia.org/wiki/List_of_Symphyotrichum_species#SectionConcolores
Row example: {'Scientific name and picture': 'S. concolor', 'Author citation': '( L. ) G.L.Nesom', 'Basionym': 'Aster concolor', 'Year': 1753, 'Common name(s) and varieties': 'Eastern silver aster Two varieties  S. c. var. concolor S. c. var. devestitum', 'NS': 'G5', 'Habitat': 'Scrub, flatwoods, fields, roadsides 0–600 m (0–1,970 ft)', 'Distribution': ''}
--------------------
Group name: Bilingual Hindi and Persian films
Entity column: Hindi Title
Columns: ['Year', 'Hindi Title', 'Persian Title', 'Director(s)']
Entity members: ['Subah-O-Shaam', 'International Crook ( Kala Bazaar )', 'Salaam Mumbai', "Devil's Daughter"]
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_multilingual_Indian_films#Hindi_and_Persian
Row example: {'Year': 1971, 'Hindi Title': 'Subah-O-Shaam', 'Persian Title': 'Homaye Saadat', 'Director(s)': 'Tapi Chanakya'}
--------------------
Group name: Collected editions of Despicable Deadpool titles
Entity column: Title
Columns: ['Title', 'Material collected', 'Pages', 'Publication Date', 'ISBN']
Entity members: ['Volume 1: Deadpool Kills Cable', 'Volume 2: Bucket List', 'Volume 3: The Marvel Universe Kills Deadpool', 'Despicable Deadpool Hardcover']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_Deadpool_titles#Despicable_Deadpool_%282017%29_by_Gerry_Duggan
Row example: {'Title': 'Volume 1: Deadpool Kills Cable', 'Material collected': 'Despicable Deadpool #287–291', 'Pages': 136, 'Publication Date': 'March 2018', 'ISBN': 'ISBN 978-1302909949'}
--------------------
Group name: Avengers members who joined in the 1970s
Entity column: Character
Columns: ['Character', 'Name', 'Joined in', 'Avengers team']
Entity members: ['Black Widow', 'Mantis', 'Two-Gun Kid', 'Beast', 'Moondragon', 'Hellcat', 'Ms. Marvel / Warbird / Captain Marvel', 'Falcon / Captain America']
Group size: 8
Source: https://en.wikipedia.org/wiki/List_of_Avengers_members#1970s
Row example: {'Character': 'Black Widow', 'Name': 'Natasha Romanoff (born Natalia Alianovna Romanova)', 'Joined in': 'Avengers #111 (May 1973)', 'Avengers team': 'Avengers , Mighty Avengers ,  New Avengers'}
--------------------
Group name: Members of the Althing from 2009 to 2013
Entity column: National party
Columns: ['National party', '2009 election', '1 January 2010', '1 January 2011', '1 January 2012', '1 January 2013', '2013 election']
Entity members: ['Social Democratic Alliance', 'Independence Party', 'Left-Green Movement', 'Progressive Party', "Citizens' Movement", 'The Movement', 'Solidarity', 'Dawn', 'Bright Future', 'Pirate Party', 'Independent']
Group size: 11
Source: https://en.wikipedia.org/wiki/List_of_members_of_the_Althing%2C_2009%E2%80%932013#Election_results
Row example: {'National party': 'Social Democratic Alliance', '2009 election': '20 / 63', '1 January 2010': '20 / 63', '1 January 2011': '20 / 63', '1 January 2012': '20 / 63', '1 January 2013': '19 / 63', '2013 election': '19 / 63'}
--------------------
Group name: Awards and honours received by Wole Soyinka
Entity column: Honor
Columns: ['Year', 'Honor', 'Notes']
Entity members: ['RSL Fellow', 'Anisfield-Wolf Book Award', 'Nobel Prize in Literature', 'Eni Enrico Mattei Prize for the Humanities', 'Commander of the Order of the Federal Republic', 'Benson Medal', 'Golden Plate Award', 'Lifetime Achievement Award', 'International Humanist Award', '"Special Prize", Europe Theatre Prize']
Group size: 10
Source: https://en.wikipedia.org/wiki/List_of_awards_and_honours_received_by_Wole_Soyinka#Awards
Row example: {'Year': 1983, 'Honor': 'RSL Fellow', 'Notes': 'Elected by the Royal Society of Literature .'}
--------------------
Group name: Communication ships of the United States during World War II
Entity column: Communications ship
Columns: ['CS', 'Communications ship']
Entity members: ['Maintenance ship, a CS ship additionally equipped to perform radio repair', 'News ship, was used by civilian journalist', 'Quarters ship, a floating dormitory', 'Patrol Craft, Escort, Rescue']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_World_War_II_vessel_types_of_the_United_States#Communication_ships
Row example: {'CS': 'CSM', 'Communications ship': 'Maintenance ship, a CS ship additionally equipped to perform radio repair'}
--------------------
Group name: Films based on video games released for television
Entity column: Title
Columns: ['Title', 'Direction', 'Release date', 'Original game publisher']
Entity members: ['Fatal Fury: Legend of the Hungry Wolf', 'Fatal Fury 2: The New Battle', 'Art of Fighting', 'Samurai Shodown: The Motion Picture', 'Pokémon: Mewtwo Returns', 'Pokémon: The Legend of Thunder', 'House of the Dead 2 (live-action)', 'Pokémon: The Mastermind of Mirage Pokémon', 'Red Faction: Origins (live-action)', 'Higurashi no Naku Koro ni Kaku: Outbreak', 'Rabbids Invasion: Mission to Mars', 'The Mortuary Assistant']
Group size: 12
Source: https://en.wikipedia.org/wiki/List_of_films_based_on_video_games#Released
Row example: {'Title': 'Fatal Fury: Legend of the Hungry Wolf', 'Direction': 'Hiroshi Fukutomi', 'Release date': 'December 23, 1992', 'Original game publisher': 'SNK'}
--------------------
Group name: Four or more seasons with 130 runs batted in in Major League Baseball
Entity column: Player
Columns: ['Player', 'Years', 'Seasons and teams']
Entity members: ['Babe Ruth  *', 'Lou Gehrig  *', 'Jimmie Foxx  *', 'Hank Greenberg  *', 'Alex Rodriguez', 'Ryan Howard', 'Joe DiMaggio  *', 'Juan González', 'Ken Griffey Jr.  *', 'Sammy Sosa', 'Manny Ramirez']
Group size: 11
Source: https://en.wikipedia.org/wiki/List_of_Major_League_Baseball_runs_batted_in_records#Four_or_more_seasons_with_130_runs_batted_in
Row example: {'Player': 'Babe Ruth  *', 'Years': 10, 'Seasons and teams': '1920–21, 23, 26–32 New York (AL)'}
--------------------
Group name: Churches in the Diocese of Stockton, Deanery I
Entity column: Name
Columns: ['Name', 'Location', 'Description/Notes']
Entity members: ['Cathedral of the Annunciation', 'Church of the Presentation of the Blessed Virgin Mary', "St. Bernadette's", 'St. Luke', 'University of the Pacific Newman Center']
Group size: 5
Source: https://en.wikipedia.org/wiki/List_of_churches_in_the_Diocese_of_Stockton#Deanery_I
Row example: {'Name': 'Cathedral of the Annunciation', 'Location': '400 W Rose St, Stockton', 'Description/Notes': 'Modified Gothic church built 1942'}
--------------------
Group name: Churches in Riverside, California
Entity column: Name
Columns: ['Name', 'Location']
Entity members: ['Our Lady of Guadalupe Mission (Belltown)', 'Our Lady of Guadalupe Shrine', 'Our Lady of Perpetual Help', 'Queen of Angels', 'Sacred Heart', 'St. Andrew Kim', 'St. Andrew Newman Center', 'St. Anthony', 'St. Catherine of Alexandria', 'St. Francis de Sales', 'St. John the Evangelist', 'St. Thomas the Apostle']
Group size: 12
Source: https://en.wikipedia.org/wiki/List_of_churches_in_the_Diocese_of_San_Bernardino#City_of_Riverside
Row example: {'Name': 'Our Lady of Guadalupe Mission (Belltown)', 'Location': '2518 Hall Ave, Riverside'}
--------------------
Group name: Phase Six Marvel Cinematic Universe films
Entity column: Film
Columns: ['Film', 'U.S. release date', 'Director(s)', 'Screenwriter(s)', 'Producer(s)', 'Status']
Entity members: ['The Fantastic Four: First Steps', 'Spider-Man: Brand New Day', 'Avengers: Doomsday', 'Avengers: Secret Wars']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_Marvel_Cinematic_Universe_films#Phase_Six
Row example: {'Film': 'The Fantastic Four: First Steps', 'U.S. release date': 'July 25, 2025 ( 2025-07-25 )', 'Director(s)': 'Matt Shakman', 'Screenwriter(s)': 'Josh Friedman and Eric Pearson and Jeff Kaplan & Ian Springer', 'Producer(s)': 'Kevin Feige', 'Status': 'Released'}
--------------------
Group name: Defunct airlines of American Samoa
Entity column: Airline
Columns: ['Airline', 'IATA', 'ICAO', 'Callsign', 'Founded', 'Ceased operations', 'Notes']
Entity members: ['Inter Island Airways', 'Samoa Airlines', 'Samoan Air Lines', 'South Pacific Island Airways']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_airlines_of_American_Samoa#Defunct
Row example: {'Airline': 'Inter Island Airways', 'IATA': 'JY', 'ICAO': 'IWY', 'Callsign': 'INTER ISLAND', 'Founded': 1993, 'Ceased operations': 2014, 'Notes': ''}
--------------------
Group name: Replacement banknotes of Zimbabwe
Entity column: Currency
Columns: ['Currency', 'Replacement prefixes']
Entity members: ['First dollar (1980–1994)', 'First dollar (1994–2003)', 'First dollar (bearer cheques)', 'Second dollar', 'Third and fourth dollar', 'Bond notes', 'Fifth dollar', 'ZiG']
Group size: 8
Source: https://en.wikipedia.org/wiki/Banknotes_of_Zimbabwe#Replacement_banknotes
Row example: {'Currency': 'First dollar (1980–1994)', 'Replacement prefixes': 'AW ($2) BW ($5) CW ($10) DW ($20)'}
--------------------
Group name: Contestants from Episode 3 of Chase (2008 TV series)
Entity column: Name
Columns: ['Name', 'Gender', 'Age', 'From', 'Occupation', 'Prize money ( USD )', 'Status']
Entity members: ['Trisha', 'London', 'Adria', 'Lucas', 'Andrew', 'Tracy', 'Lynda', 'Darin', 'Evan', 'Ameenah']
Group size: 10
Source: https://en.wikipedia.org/wiki/List_of_Chase_%282008_TV_series%29_episodes#Contestants
Row example: {'Name': 'Trisha', 'Gender': 'Female', 'Age': 28, 'From': 'Santa Monica, CA', 'Occupation': 'Artist', 'Prize money ( USD )': '$26,000', 'Status': 'Winner'}
--------------------
Group name: Counties of Albania
Entity column: County
Columns: ['County', 'Seat', 'Municipalities', 'NUTS-2', 'Area', 'Population (2023)', 'Population density (per km 2 in 2023)', 'Emblem', 'Geographic coordinates']
Entity members: ['Berat', 'Dibër', 'Durrës', 'Elbasan', 'Fier', 'Gjirokastër', 'Korçë', 'Kukës', 'Lezhë', 'Shkodër', 'Tirana', 'Vlorë']
Group size: 12
Source: https://en.wikipedia.org/wiki/Counties_of_Albania#List
Row example: {'County': 'Berat', 'Seat': 'Berat', 'Municipalities': 'Berat, Kuçovë , Poliçan , Skrapar , Ura Vajgurore', 'NUTS-2': 'Southern Region', 'Area': '1,798 km 2 (694 sq mi)', 'Population (2023)': 140956, 'Population density (per km 2 in 2023)': 78.4, 'Emblem': '', 'Geographic coordinates': '40°44′N 19°59′E \ufeff / \ufeff 40.733°N 19.983°E \ufeff / 40.733; 19.983 \ufeff ( Berat County )'}
--------------------
Group name: Ambassadors of Sri Lanka to the Soviet Union
Entity column: Ambassadors
Columns: ['Ambassadors', 'Start of Term', 'End of Term', 'Head of State/Government']
Entity members: ['Gunapala Piyasena Malalasekera', 'Tikiri Banda Subasinghe', 'B. F. Perera', 'M. V. P. Peiris', 'J. C. T. Kotelawala', 'C. D. S. Siriwardene', 'C. E. S. Weeratunge', 'Walter Jayawardene', 'R. C. A. Johnpulle', 'Neville Kanakaratne', 'Rodney Vandergert']
Group size: 11
Source: https://en.wikipedia.org/wiki/List_of_ambassadors_of_Sri_Lanka_to_Russia#Ambassador_to_the_Soviet_Union
Row example: {'Ambassadors': 'Gunapala Piyasena Malalasekera', 'Start of Term': 1957, 'End of Term': 1961, 'Head of State/Government': 'S. W. R. D. Bandaranaike Wijeyananda Dahanayake Dudley Senanayake Sirimavo Bandaranaike'}
--------------------
Group name: Colleges and universities in the Roman Catholic Archdiocese of Baltimore
Entity column: School
Columns: ['School', 'Location', 'Religious order', 'Founded']
Entity members: ['Loyola University Maryland', "Mount St. Mary's Seminary", "Mount St. Mary's University", 'Notre Dame of Maryland University', "St. Mary's Seminary and University"]
Group size: 5
Source: https://en.wikipedia.org/wiki/List_of_schools_in_the_Roman_Catholic_Archdiocese_of_Baltimore#Colleges_and_universities
Row example: {'School': 'Loyola University Maryland', 'Location': 'Baltimore', 'Religious order': 'Society of Jesus', 'Founded': 1852}
--------------------
Group name: South Carolina state forests
Entity column: Name (by alphabetical order)
Columns: ['Name (by alphabetical order)', 'Location (of main entrance)']
Entity members: ['Harbison State Forest', 'Manchester State Forest', 'Poe Creek State Forest', 'Sand Hills State Forest', 'Wee Tee State Forest']
Group size: 5
Source: https://en.wikipedia.org/wiki/List_of_South_Carolina_state_forests#South_Carolinastate_forests
Row example: {'Name (by alphabetical order)': 'Harbison State Forest', 'Location (of main entrance)': 'Columbia'}
--------------------
Group name: Scheduled airlines of the Maldives
Entity column: Airline
Columns: ['Airline', 'IATA', 'ICAO', 'Callsign', 'Commenced operations', 'Notes']
Entity members: ['BeOnd', 'Villa Air (Flyme)', 'Maldivian', 'Manta Air', 'Trans Maldivian Airways']
Group size: 5
Source: https://en.wikipedia.org/wiki/List_of_airlines_of_the_Maldives#Scheduled_airlines
Row example: {'Airline': 'BeOnd', 'IATA': 'B4', 'ICAO': 'BYD', 'Callsign': 'BEOND', 'Commenced operations': 2023, 'Notes': 'International carrier'}
--------------------
Group name: Top 11 largest mosques in Indonesia
Entity column: Name
Columns: ['Name', 'Building capacity', 'Area', 'Location', 'Year']
Entity members: ['Istiqlal Mosque', 'Al Jabbar Grand Mosque', 'Al-Akbar Mosque', 'At-Tin Mosque', 'Jakarta Islamic Center', 'Dian Al-Mahri Mosque', 'Grand Mosque of West Sumatra', 'Raja Hamidah Great Mosque of Batam', 'Al-Azhom Grand Mosque', 'Great Mosque of Central Java', 'Grand Mosque of Sabilal Muhtadin']
Group size: 11
Source: https://en.wikipedia.org/wiki/List_of_mosques_in_Indonesia#Largest_mosques
Row example: {'Name': 'Istiqlal Mosque', 'Building capacity': 200000, 'Area': '10,000 m 2 (building)  93,200 m 2', 'Location': 'Central Jakarta 6°10′13″S 106°49′53″E \ufeff / \ufeff 6.1702°S 106.8314°E \ufeff / -6.1702; 106.8314 \ufeff ( Istiqlal Mosque, Jakarta )', 'Year': 1978}
--------------------
Group name: Documentary films about World War II from the 1980s
Entity column: Title
Columns: ['Year', 'Country', 'Title', 'Director']
Entity members: ['The Yellow Star - The Persecution of the Jews in Europe 1933-45', 'The Life and Times of Rosie the Riveter', 'Genocide', 'The Story of Chaim Rumkowski and the Jews of Lodz', 'Who Shall Live and Who Shall Die', 'Shoah', 'Unfinished Business', "The Emperor's Naked Army Marches On", 'Hôtel Terminus: The Life and Times of Klaus Barbie', 'De Nuremberg à Nuremberg', 'Fascist Legacy', 'The Architecture of Doom']
Group size: 12
Source: https://en.wikipedia.org/wiki/List_of_documentary_films_about_World_War_II#1980s
Row example: {'Year': 1980, 'Country': 'West Germany', 'Title': 'The Yellow Star - The Persecution of the Jews in Europe 1933-45', 'Director': 'Dieter Hildebrandt'}
--------------------
Group name: Discontinued special edition magazines published by MediaWorks
Entity column: Title
Columns: ['Title', 'Parent magazine', 'Type', 'Magazine run']
Entity members: ["Dengeki G's Paradise", 'Dengeki Online D', 'Dengeki PS2', 'Dengeki Teioh']
Group size: 4
Source: https://en.wikipedia.org/wiki/List_of_magazines_published_by_MediaWorks#Special_edition_versions
Row example: {'Title': "Dengeki G's Paradise", 'Parent magazine': "Dengeki G's Magazine", 'Type': 'Bishōjo game', 'Magazine run': '1997 (one issue)'}
--------------------
Group name: Administrative regions of Kosovo
Entity column: Administrative districts (regions)
Columns: ['Administrative districts (regions)', 'Area in km 2', 'Population in 2024 (rank)', 'Density per km 2', 'Municipalities', 'District number', 'Settlements']
Entity members: ['District of Ferizaj ( Rajoni i Ferizajit/Uroševački okrug )', 'District of Gjakova ( Rajoni i Gjakovës/Đakovički okrug )', 'District of Gjilan ( Rajoni i Gjilanit/Gnjilanski okrug )', 'District of Mitrovica ( Rajoni i Mitrovicës/Kosovskomitrovački okrug )', 'District of Peja ( Rajoni i Pejës/Pećki okrug )', 'District of Pristina ( Rajoni i Prishtinës/Prištinski okrug )', 'District of Prizren ( Rajoni i Prizrenit/Prizrenski okrug )']
Group size: 7
Source: https://en.wikipedia.org/wiki/Districts_of_Kosovo#Seven_administrative_regions_in_Kosovo%3A
Row example: {'Administrative districts (regions)': 'District of Ferizaj ( Rajoni i Ferizajit/Uroševački okrug )', 'Area in km 2': 1030, 'Population in 2024 (rank)': 180897, 'Density per km 2': 175.6, 'Municipalities': 'Ferizaj Hani i Elezit Kaçanik Shtime Štrpce', 'District number': 5, 'Settlements': 126}
--------------------
Group name: Original members of the Animals band
Entity column: Name
Columns: ['Name', 'Years active', 'Instruments', 'Release contributions']

In [ ]:
### ROLE
You are a strict Data Quality Auditor. Your task is to validate structured table groups extracted from Wikipedia.
You must determine whether each sample represents a clean, meaningful, and well-defined entity group suitable for a high-quality dataset.
Be conservative: reject doubtful samples rather than accepting them.

### INPUT DATA
- **Group Name:** The semantic description of the group extracted from the Wikipedia table or section.
- **Entity column:** The table column that represents the main entity type of the group.
- **Entity members:** The list of values from the entity column for all rows.
- **Group size:** Number of rows (entities) in the table.
- **Source:** The Wikipedia URL where the table was extracted.
- **Row example:** A full example row from the table.


### RULES FOR VALIDITY

1. **FATEFULNESS:**
   - The entity members must clearly match the concept described in the Group Name.
   - Reject if:
        - Entities do not logically belong to the group.
        - The group description is misleading or overly broad.
        - The entities represent multiple unrelated concepts.
    - Examples:
        - Group: European Rivers → Entities include cities. --> REJECT
        - Group: Famous Scientists → Entities include organizations. --> REJECT

2. **CLOSED_SET:**
   - Does this set represent a coherent and complete group?
   - Reject if:
        - The group appears to be a random subset of a larger list.
        - The group is ambiguous about why these specific rows were chosen.
        - *Exception:* If the Group Name specifies a filter (e.g., "Top 4 Scorers"), then a small set is valid. 
    - Examples:
        - Cities in France with only 6 random entries. --> REJECT
        - Top 10 Indian films of 2025 by box office collection. --> ACCEPT

3. **SPECIFICALITY:**
    - The group name must define a clear and narrow concept.
    - Reject if:
        - The group is too generic or vague.
        - The grouping rule is unclear.
    - Examples:
        - Famous movies --> REJECT
        - Important countries --> REJECT

4. **NATURALNESS:**
    - The group must represent a natural category people would reasonably group together.
    - Reject if:
        - The group looks artificially constructed.
        - The grouping rule feels arbitrary or meaningless.
    - Examples:
        - Cities whose names start with the letter Q and have more than 3 vowels --> REJECT
        - Countries with GDP between X and Y but excluding Z --> REJECT

5. **CORRECT_ENTITY:**
    - The Entity column must correctly represent the primary entity of the group.
    - Reject if:
        - The column contains metadata (rank, year, ID, etc.).
        - The column represents attributes rather than entities.
    - Examples:
        - Entity column: Rank --> REJECT
        - Entity column: Year --> REJECT

### OUTPUT FORMAT:
After analyzing all samples provide:
1. Dataset Quality Summary
    - Total samples: X
    - Valid samples: X
    - Invalid samples: X
    - Success rate: X%
2. If success rate < 95%:
    - List the main recurring problems, such as:
    - weak group definitions
    - incorrect entity columns
    - partial lists
    - unnatural groupings
    - Provide specific suggestions to improve dataset quality.

All samples are separated by a line, Evaluate each sample independently.

In [ ]:
f"""### ROLE
You are a strict Data Quality Auditor. Your task is to validate a structured table group extracted from Wikipedia. 
Determine if the sample represents a clean, meaningful, and well-defined entity group for a high-quality dataset.
Be conservative: reject doubtful samples rather than accepting them.

### SOURCE TRUST POLICY
Trust the provided Wikipedia Source and Group Name as the ground truth for the intent of the list. However, if the Entity Members or Column clearly contradict the source (e.g., the source is about "Rivers" but the entities are "Cities"), you must reject it.

### INPUT DATA
- **Group Name:** {GROUP_NAME}
- **Entity Column:** {ENTITY_COLUMN}
- **Entity Members:** {MEMBERS_LIST}
- **Group Size:** {SIZE}
- **Source URL:** {URL}
- **Row Example:** {EXAMPLE_ROW}

### RULES FOR VALIDITY

1. **FATEFULNESS:** Members must logically match the Group Name. Reject if the description is misleading, overly broad, or contains unrelated concepts.
2. **CLOSED_SET:** The group must be coherent and complete. Reject random subsets (e.g., "6 random cities in France"). 
   *Exception:* Specific filters (e.g., "Top 10", "Oldest 5", "Members in 2024") are valid.
3. **SPECIFICALITY:** The group must have a narrow, clear concept. Reject vague names like "Famous movies" or "Important countries."
4. **NATURALNESS:** The category must be one that humans would reasonably group together. Reject arbitrary rules (e.g., "Cities starting with Q that have 3 vowels").
5. **CORRECT_ENTITY:** The Entity Column must contain the primary entities, not metadata (Rank, Year, ID) or attributes.

### OUTPUT FORMAT
Provide only a single Python-style tuple containing the decision and the explanation. Do not include any other text, markdown formatting, or headers.

Format: ("DECISION", "EXPLANATION")
For Acceptances: ("ACCEPT", "Reason why the group is valid and coherent.")
For Rejections: ("RULE_NAME", "Specific explanation of the violation.")"""

# Test 3:

In [18]:
import re

def get_entity_col_deterministic(rows, page_title, section_header):
    """
    rows: The full list of dictionaries for the table.
    """
    if not rows or not isinstance(rows, list):
        return None
        
    # Correctly handle headers from the first row
    headers = list(rows[0].keys())
    page_ctx = (page_title + " " + section_header).lower()
    
    # 1. THE GRID FILTER (Pre-check)
    # Rejects tables that are just a matrix of years or stats
    grid_indicators = [r'^\d{4}$', r'^\d{4}–\d{4}$', r'^gold$', r'^silver$', r'^bronze$', r'^total$']
    num_grid_headers = sum(1 for h in headers if any(re.search(p, h.lower().strip()) for p in grid_indicators))
    
    if len(headers) > 0 and (num_grid_headers / len(headers)) > 0.6:
        return None

    # 2. THE KILL LIST
    kill_list = ['rank', 'gross', 'collection', 'revenue', 'year', 'date', 'pos', 'notes', 'ref', 'no.', 'total', 'index']
    
    # 3. PRIORITY WEIGHTS
    universal_priority = ['name', 'title', 'airline', 'team', 'character', 'honor', 'mayor', 'organization', 'mission']

    scores = {}
    for h in headers:
        h_low = h.lower().strip()
        score = 0
        
        # Rule A: Hard Block (Case-insensitive full word match)
        if any(k == h_low or f" {k}" in h_low or f"{k} " in h_low for k in kill_list):
            scores[h] = -100
            continue

        # Rule B: Lexical Anchor (Direct overlap with Page/Section context)
        # Matches "Airline" if "Airlines" is in the title
        ctx_words = re.findall(r'\w+', page_ctx)
        singular_h = h_low.rstrip('s')
        if singular_h in [w.rstrip('s') for w in ctx_words] and len(singular_h) > 2:
            score += 50

        # Rule C: Universal Match
        if h_low in universal_priority:
            score += 40

        # Rule D: Fuzzy Name Match (Catches 'Common name', 'Name in English')
        if 'name' in h_low:
            score += 30

        # Rule E: Data Content Validation (The "Peek" test)
        # We check the first 3 rows. If they are all numbers, it's not our entity.
        try:
            samples = [str(rows[i][h]) for i in range(min(len(rows), 3)) if rows[i].get(h)]
            if samples and all(s.replace('.', '', 1).isdigit() for s in samples):
                score -= 60 
        except:
            pass

        # Rule F: Position Bias (Wikipedia editors put the subject on the left)
        score += (len(headers) - headers.index(h)) * 1 

        scores[h] = score

    # Final Selection
    valid_scores = {k: v for k, v in scores.items() if v > 10}
    if not valid_scores:
        return None
        
    return max(valid_scores, key=valid_scores.get)

In [23]:
for s in [a for a in cleaned_data[:200] if a['table_name'].startswith("List of")]:
    # print(s['table_name'].split(' > ', 1)[0])
    print(s['table_name'].split('(', 1)[0])
    print(s['rows'][0].keys())
    page_title = s['table_name'].split(' > ', 1)[0]
    section_header = s['table_name'].split(' > ', 1)[-1].split('(', 1)[0]
    print(get_entity_col_deterministic(s['rows'], page_title, section_header))
    print(generate_deterministic_name(page_title, section_header))
    print("-" *100)

List of Social Distortion band members > Members > Current
dict_keys(['Name', 'Years active', 'Instruments', 'Release contributions'])
Name
> current Social Distortion band members
----------------------------------------------------------------------------------------------------
List of fictional birds > Charadriiformes
dict_keys(['Name', 'Species', 'Work', 'Notes'])
Name
Charadriiformes fictional birds
----------------------------------------------------------------------------------------------------
List of supermarket chains in Serbia > Speciality store chains > Cosmetics and healthcare
dict_keys(['Name', 'Stores', 'First store', 'Parent'])
Name
Speciality store > cosmetics and healthcare supermarket chains in Serbia
----------------------------------------------------------------------------------------------------
List of Supertramp band members > Members > Touring
dict_keys(['Name', 'Years active', 'Instruments', 'Release contributions'])
Name
> touring Supertramp band members
----------------------------------------------------------------------------------------------------
List of Tamil films of 2019 > Box office collection
dict_keys(['Rank', 'Title', 'Production company', 'Distributor', 'Worldwide gross'])
Title
Box office collection Tamil films of 2019
----------------------------------------------------------------------------------------------------
List of programs broadcast by Universal Kids > Former programming > Blocks
dict_keys(['Title', 'Premiere date', 'End date'])
Title
Former programming > blocks programs broadcast by Universal Kids
----------------------------------------------------------------------------------------------------
List of 2012 box office number-one films in Japan > Highest-grossing films
dict_keys(['Rank', 'Title', 'Gross'])
Title
Highest-grossing 2012 box office number-one films in Japan
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Lay Zhang > Listicles > ForbesChina Celebrity 100
dict_keys(['Year', 'Rank'])
None
Listicles > forbeschina celebrity 100 awards and nominations received by Lay Zhang
----------------------------------------------------------------------------------------------------
List of diplomatic missions of Yemen > Current missions > Multilateral organisations
dict_keys(['Organization', 'Host city', 'Host country', 'Mission', 'Concurrent accreditation'])
Mission
Current > multilateral organisations diplomatic missions of Yemen
----------------------------------------------------------------------------------------------------
List of Flotsam and Jetsam band members > Members > Current
dict_keys(['Name', 'Years active', 'Instruments', 'Release contributions'])
Name
> current Flotsam and Jetsam band members
----------------------------------------------------------------------------------------------------
List of universities in Brunei > Private institutions
dict_keys(['Name in English', 'Name in Malay', 'Abbreviation', 'Foundation'])
Name in English
Private institutions universities in Brunei
----------------------------------------------------------------------------------------------------
List of crew of the International Space Station > Statistics > By nationality
dict_keys(['Nationality', 'ISS Crew', 'On-board'])
Nationality
Statistics > by nationality crew of the International Space Station
----------------------------------------------------------------------------------------------------
List of lighthouses in Saint Helena > Lighthouses
dict_keys(['Name', 'Light characteristic', 'Focal height (metres)', 'NGA number', 'Admiralty number', 'Range (nautical miles)'])
Name
Lighthouses in saint helena
----------------------------------------------------------------------------------------------------
List of Cardiff City F.C. seasons > Key
dict_keys(['1st or W', 'Winners'])
None
Key Cardiff City F.C. seasons
----------------------------------------------------------------------------------------------------
List of largest companies in Taiwan > 2025Fortunelist
dict_keys(['Rank', 'Fortune 500 rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Profits (USD millions)', 'Employees', 'Headquarters'])
Name
2025fortunelist largest companies in Taiwan
----------------------------------------------------------------------------------------------------
List of mayors of Subiaco > City of Subiaco
dict_keys(['Mayor', 'Term', 'Notes'])
Mayor
City mayors of Subiaco
----------------------------------------------------------------------------------------------------
List of airlines of Mali > Defunct airlines
dict_keys(['Airline', 'IATA', 'ICAO', 'Callsign', 'Commenced operations', 'Ceased operations', 'Notes'])
Airline
Defunct airlines of Mali
----------------------------------------------------------------------------------------------------
List of Kannada films of 1992 > Top-grossing films
dict_keys(['Rank', 'Title', 'Collection'])
Title
Top-grossing Kannada films of 1992
----------------------------------------------------------------------------------------------------
List of Chinese films of 2014 > Box office
dict_keys(['Rank', 'Title', 'Gross (in USD)'])
Title
Box office Chinese films of 2014
----------------------------------------------------------------------------------------------------
List of ports in Djibouti > List of ports and harbours in Djibouti
dict_keys(['Port/Harbour name', 'Regions', 'City/Town name', 'Coordinates', 'UN/Locode', 'Max. draught (m)', 'Max. deadweight (t)', 'Remarks'])
Port/Harbour name
And harbours ports in Djibouti
----------------------------------------------------------------------------------------------------
List of diplomatic missions of Croatia > Current missions > Americas
dict_keys(['Host country', 'Host city', 'Mission', 'Concurrent accreditation'])
Mission
Current > americas diplomatic missions of Croatia
----------------------------------------------------------------------------------------------------
List of Japanese films of 2003 > Highest-grossing films
dict_keys(['Rank', 'Title', 'Gross'])
Title
Highest-grossing Japanese films of 2003
----------------------------------------------------------------------------------------------------
List of athletes from Montana > Basketball
dict_keys(['Name', 'Lifetime', 'Montana connection', 'Comments'])
Name
Basketball athletes from Montana
----------------------------------------------------------------------------------------------------
List of documentary films > Z
dict_keys(['Title', 'Year', 'Director(s)', 'Producer(s)'])
Title
Z documentary films
----------------------------------------------------------------------------------------------------
List of Falling in Reverse band members > Members > Current
dict_keys(['Name', 'Years active', 'Instruments', 'Release contributions'])
Name
> current Falling in Reverse band members
----------------------------------------------------------------------------------------------------
List of major Negro league baseball teams > Pennsylvania
dict_keys(['Team', '1st Yr', 'Last Yr', 'Affiliation(s)', 'Notes'])
Team
Pennsylvania major Negro league baseball teams
----------------------------------------------------------------------------------------------------
List of 2010 box office number-one films in Spain > Highest-grossing films
dict_keys(['Rank', 'Title', 'Distributor', 'Director(s)', 'Release', 'Country', 'Domestic Gross'])
Title
Highest-grossing 2010 box office number-one films in Spain
----------------------------------------------------------------------------------------------------
List of bridges in South Africa > Historical and architectural interest bridges
dict_keys(['Name', 'Distinction', 'Length', 'Type', 'Carries Crosses', 'Opened', 'Location', 'Province'])
Name
Historical and architectural interest bridges in South Africa
----------------------------------------------------------------------------------------------------
List of threatened, endangered and extinct species in the Mariana Islands > Migratory birds
dict_keys(['Common name', 'Scientific name', 'US Fish & Wildlife conservation status', 'IUCN Red List status', 'Notes'])
Common name
Migratory birds threatened, endangered and extinct species in the Mariana Islands
----------------------------------------------------------------------------------------------------
List of Olympic medalists in gymnastics
dict_keys(['Games', 'Gold', 'Silver', 'Bronze'])
None
Artistic > discontinued events > rope climbing Olympic medalists in gymnastics (men)
----------------------------------------------------------------------------------------------------
List of Freedom Fighters members > Second roster
dict_keys(['Character', 'Real name', 'First appearance', 'Notes'])
Character
Second roster Freedom Fighters members
----------------------------------------------------------------------------------------------------
List of airlines of the United Arab Emirates > Scheduled airlines
dict_keys(['Airline', 'IATA', 'ICAO', 'Callsign', 'Commenced operations', 'Hub airport(s)', 'Notes'])
Airline
Scheduled airlines of the United Arab Emirates
----------------------------------------------------------------------------------------------------
List of works by William Merritt Chase > Alphabetical listing > L-N
dict_keys(['Lady in a Pink Dress', 'c. 1892', 'Westmoreland Museum of American Art , Greensburg, Pennsylvania'])
None
Alphabetical listing > l-n works by William Merritt Chase
----------------------------------------------------------------------------------------------------
List of defunct airlines of Oceania > Norfolk Island
dict_keys(['Airline', 'IATA', 'ICAO', 'Callsign', 'Commenced operations', 'Ceased operations', 'Notes'])
Airline
Norfolk island defunct airlines of Oceania
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Tom Cruise > State honors
dict_keys(['Country', 'Year', 'Honor'])
Honor
State honors awards and nominations received by Tom Cruise
----------------------------------------------------------------------------------------------------
List of Cuban League baseball players
dict_keys(['Name', 'Debut', 'Last Game', 'Position', 'Teams'])
Name
J Cuban League baseball players (E–L)
----------------------------------------------------------------------------------------------------
List of diplomatic missions of Cyprus > Current missions > Americas
dict_keys(['Host country', 'Host city', 'Mission', 'Concurrent accreditation'])
Mission
Current > americas diplomatic missions of Cyprus
----------------------------------------------------------------------------------------------------
List of Sooty Show episodes > The Sooty Show
dict_keys(['Guests', 'Original airdate'])
None
The Sooty Show episodes
----------------------------------------------------------------------------------------------------
List of female members of the European Parliament for Malta > List
dict_keys(['Name', 'National party', 'EP group', 'Elected', 'Year left'])
Name
Female members of the european parliament for malta
----------------------------------------------------------------------------------------------------
List of companies of the Socialist Federal Republic of Yugoslavia > Automotive industry
dict_keys(['Name', 'Headquarters', 'Republic/province', 'Established in', 'Operations/products'])
Name
Automotive industry companies of the Socialist Federal Republic of Yugoslavia
----------------------------------------------------------------------------------------------------
List of American films of 2006 > Box office
dict_keys(['Rank', 'Title', 'Distributor', 'Domestic gross'])
Title
Box office American films of 2006
----------------------------------------------------------------------------------------------------
List of Dutch films of the 1990s > 1990
dict_keys(['Title', 'Director', 'Cast', 'Genre', 'Notes'])
Title
1990 Dutch films of the 1990s
----------------------------------------------------------------------------------------------------
List of power stations in New York > Retired plants
dict_keys(['Owner, operator, or billing organization', 'Plant name', 'Town or city', 'In-service date', 'Summer capability (MW)', 'Winter capability (MW)', 'Unit type', 'Primary fuel', 'Secondary fuel', '2017 net energy (GWh)', 'Notes'])
Plant name
Retired plants power stations in New York
----------------------------------------------------------------------------------------------------
List of books on history of number systems > Children's books on the history of numbers
dict_keys(['Author', 'Title', 'Year', 'Publisher / ISBN', 'Summary'])
Title
Children's the numbers books on history of number systems
----------------------------------------------------------------------------------------------------
List of earthquakes in 1916 > Notable events > July
dict_keys(['Strongest magnitude', '7.1 M w Fiji'])
None
Notable events > july earthquakes in 1916
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Ian McKellen > Honorary awards
dict_keys(['Year', 'Ceremony', 'Category'])
None
Honorary awards and nominations received by Ian McKellen
----------------------------------------------------------------------------------------------------
List of ambassadors of Sweden to Moldova > List of representatives
dict_keys(['Name', 'Period', 'Title', 'Notes'])
Name
Representatives ambassadors of Sweden to Moldova
----------------------------------------------------------------------------------------------------
List of lakes of Western Australia, L–P > O
dict_keys(['Name', 'Coordinates'])
Name
O lakes of Western Australia, L–P
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Alan Walker > Other accolades > DJ MagazineTop 100 DJs
dict_keys(['Year', 'Position', 'Notes'])
None
Other accolades > dj magazinetop 100 djs awards and nominations received by Alan Walker
----------------------------------------------------------------------------------------------------
List of ambassadors of Georgia to the United States > List of representatives
dict_keys(['Diplomatic agrément', 'Diplomatic accreditation', 'ambassador', 'Prime Minister of Georgia', 'President of the United States'])
ambassador
Representatives ambassadors of Georgia to the United States
----------------------------------------------------------------------------------------------------
List of awards and nominations received by the Jonas Brothers > iHeartRadio Music Awards
dict_keys(['Year', 'Nominee / work', 'Award', 'Result'])
Award
Iheartradio music awards and nominations received by the Jonas Brothers
----------------------------------------------------------------------------------------------------
List of Marathi films of 2017 > Box office collection
dict_keys(['Rank', 'Film', 'Worldwide gross'])
Film
Box office collection Marathi films of 2017
----------------------------------------------------------------------------------------------------
List of diplomatic missions of Slovakia > Current missions > Multilateral Organizations
dict_keys(['Organization', 'Host city', 'Host country', 'Mission', 'Concurrent accreditation'])
Organization
Current > multilateral organizations diplomatic missions of Slovakia
----------------------------------------------------------------------------------------------------
List of awards and nominations received by K. Balachander > Tamil Nadu State Film Awards
dict_keys(['Year', 'Film', 'Category', 'Outcome'])
Film
Tamil nadu state film awards and nominations received by K. Balachander
----------------------------------------------------------------------------------------------------
List of Commonwealth Sport country codes > Current CGAs > S
dict_keys(['Code', 'Nation (CGA)', 'Other codes used'])
Code
Current cgas > s Commonwealth Sport country codes
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Stanley Tucci > Critics awards
dict_keys(['Year', 'Category', 'Nominated work', 'Result'])
None
Critics awards and nominations received by Stanley Tucci
----------------------------------------------------------------------------------------------------
List of power metal bands > I
dict_keys(['Name', 'Origin', 'Years active', 'Brief summary', 'Note'])
Name
I power metal bands
----------------------------------------------------------------------------------------------------
List of exoplanets detected by microlensing > List > Candidate rogue planets
dict_keys(['Planet', 'Mass', 'Year of discovery'])
Planet
List > candidate rogue planets exoplanets detected by microlensing
----------------------------------------------------------------------------------------------------
List of Kannada films of 2002 > Highest grossing films
dict_keys(['Rank', 'Title', 'Collection'])
Title
Highest grossing Kannada films of 2002
----------------------------------------------------------------------------------------------------
List of T-Series films > 1980s
dict_keys(['Year', 'Film', 'Actors'])
Film
1980s T-Series films
----------------------------------------------------------------------------------------------------
List of mountains in Georgia
dict_keys(['Rank', 'Summit', 'County', 'Elevation', 'Prominence', 'Isolation', 'Location'])
None
Highest mountains in Georgia (U.S. state)
----------------------------------------------------------------------------------------------------
List of ambassadors of China to Ivory Coast > List of representatives
dict_keys(['Name (English)', 'Name (Chinese)', 'Tenure begins', 'Tenure ends', 'Note'])
Name (English)
Representatives ambassadors of China to Ivory Coast
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Howard Shore > Major Awards > Academy Awards
dict_keys(['Year', 'Category', 'Nominated work', 'Result'])
None
Major > academy awards and nominations received by Howard Shore
----------------------------------------------------------------------------------------------------
List of churches in Bjørgvin > Bergen domprosti
dict_keys(['Municipality', 'Parish ( sokn )', 'Church', 'Location', 'Year built'])
None
Bergen domprosti churches in Bjørgvin
----------------------------------------------------------------------------------------------------
List of diplomatic missions of Ivory Coast > Americas
dict_keys(['Host country', 'Host city', 'Mission', 'Concurrent accreditation'])
Mission
Americas diplomatic missions of Ivory Coast
----------------------------------------------------------------------------------------------------
List of awards and nominations received by Lou Grant > Awards and nominations > Emmy Awards > Creative Arts Emmy Awards
dict_keys(['Year', 'Category', 'Nominee(s)', 'Episodes(s)', 'Result'])
None
> emmy > creative arts emmy awards and nominations received by Lou Grant
----------------------------------------------------------------------------------------------------
List of Western Sydney Wanderers FC players > Captains
dict_keys(['Dates', 'Captain'])
Captain
Captains Western Sydney Wanderers FC players
----------------------------------------------------------------------------------------------------
List of Star Studio18 films > As Star Studio18
dict_keys(['Release date', 'Title', 'Language', 'Director', 'Notes'])
Title
As Star Studio18 films
----------------------------------------------------------------------------------------------------
List of ambassadors of Malaysia to Morocco > List of heads of mission > Ambassadors to Morocco
dict_keys(['Ambassador', 'Term start', 'Term end'])
Ambassador
Heads mission > ambassadors of Malaysia to Morocco

In [22]:
import re

def generate_deterministic_name(page_title, section_header):
    # 1. Clean the Page Title
    # Remove "List of", "List of the", etc.
    clean_title = re.sub(r'^list of (the )?', '', page_title, flags=re.IGNORECASE).strip()
    
    # 2. Clean the Section Header
    # Remove redundant info like "List of...", "(1990-2000)", or "Table"
    clean_section = re.sub(r'\(.*?\)', '', section_header).strip()
    clean_section = re.sub(r'^list of ', '', clean_section, flags=re.IGNORECASE).strip()
    
    # 3. Detect Redundancy
    # If the section header is "Current missions" and title is "Missions of Yemen"
    # we don't want "Current missions Missions of Yemen"
    words_in_title = set(clean_title.lower().split())
    words_in_section = clean_section.lower().split()
    
    # Filter out words from section that already exist in the title
    unique_section_words = [w for w in words_in_section if w not in words_in_title]
    unique_section = " ".join(unique_section_words).strip()

    # 4. Assembly
    if not unique_section or unique_section.lower() in ['list', 'table', 'current', 'general']:
        return clean_title.capitalize()
        
    return f"{unique_section.capitalize()} {clean_title}"

In [679]:
list_of_subset = [s for s in generator.valid_results if s['Wiki link'].split('/wiki/', 1)[-1].replace("_", " ").startswith("List of")]
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(list_of_subset, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/35 [00:00<?, ?it/s]

In [681]:
tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 10 samples already tagged in 'tagger_progress.json'.

Output()

In [543]:
from difflib import SequenceMatcher
import pandas as pd
from IPython.display import display, HTML

def audit_categorical_system(samples, fuzzy_threshold=0.9):
    categorical_strategies = ['UNIQUE_DIVERSITY', 'FREQUENCY_MODE', 'CATEGORICAL_FILTER_LOOKUP']
    
    # Filter targets
    target_samples = [s for s in samples if s.get('Selected strategy') in categorical_strategies]
    total_samples = len(target_samples)
    
    if total_samples == 0:
        print("🔍 No samples found for the specified categorical strategies.")
        return

    problematic_sample_indices = []
    column_stats = {}
    fail_details = []

    # --- PROCESSING ---
    for idx, sample in enumerate(target_samples):
        table = sample.get('Relevant table data', [])
        if not table or not isinstance(table, list): continue
        
        strat = sample.get('Selected strategy')
        all_cols = list(table[0].keys())
        if len(all_cols) <= 1: continue
        
        # Skip the first column (Entity Column)
        data_cols = all_cols[1:] 
        sample_has_issue = False
        
        for col in data_cols:
            if col not in column_stats:
                column_stats[col] = {'systemic_fails': 0, 'any_issue_count': 0}
            
            raw_values = [str(row.get(col, "")).strip() for row in table if row.get(col)]
            unique_vals = sorted(list(set(raw_values)), key=len)
            if len(unique_vals) < 2: continue
            
            issue_vals = set()
            for i in range(len(unique_vals)):
                for j in range(i + 1, len(unique_vals)):
                    v1, v2 = unique_vals[i].lower(), unique_vals[j].lower()
                    if v1 in v2 or SequenceMatcher(None, v1, v2).ratio() >= fuzzy_threshold:
                        issue_vals.update([unique_vals[i], unique_vals[j]])

            if issue_vals:
                column_stats[col]['any_issue_count'] += 1
                sample_has_issue = True
                
                # Check for Systemic Fail
                if len(issue_vals) == len(unique_vals):
                    column_stats[col]['systemic_fails'] += 1
                    fail_details.append({
                        'sample': sample,
                        'bad_col': col,
                        'bad_values': unique_vals
                    })

        if sample_has_issue:
            problematic_sample_indices.append(idx)

    # --- 1. THE BIG PICTURE SUMMARY ---
    clean_count = total_samples - len(problematic_sample_indices)
    
    display(HTML(f"""
    <div style="border: 2px solid #2c3e50; border-radius: 10px; padding: 20px; font-family: sans-serif; background-color: #f8f9fa;">
        <h2 style="margin-top: 0; color: #2c3e50;">📊 CATEGORICAL AUDIT: TOTAL PICTURE</h2>
        <div style="display: flex; gap: 40px;">
            <div style="text-align: center;">
                <h1 style="color: #27ae60; margin: 0;">{clean_count}</h1>
                <p style="color: #666;">CLEAN SAMPLES</p>
            </div>
            <div style="text-align: center;">
                <h1 style="color: #e74c3c; margin: 0;">{len(problematic_sample_indices)}</h1>
                <p style="color: #666;">PROBLEMATIC SAMPLES</p>
            </div>
            <div style="text-align: center; border-left: 1px solid #ccc; padding-left: 40px;">
                <h1 style="color: #2980b9; margin: 0;">{(clean_count/total_samples)*100:.1f}%</h1>
                <p style="color: #666;">SUCCESS RATE</p>
            </div>
        </div>
    </div>
    """))

    # --- 2. DRILL DOWN (SYSTEMIC FAILS) ---
    if fail_details:
        display(HTML("<h3 style='margin-top: 30px; color: #c0392b;'>🚨 SYSTEMIC FAILURES DETECTED</h3>"))
        
        for fail in fail_details:
            s = fail['sample']
            df_full = pd.DataFrame(s['Relevant table data'])
            
            # Highlight the problematic column in the display
            html_output = f"""
            <div style="margin-bottom: 40px; border-left: 5px solid #e74c3c; padding-left: 15px;">
                <p style="margin: 0;"><b>Strategy:</b> <span style="color: #2980b9;">{s['Selected strategy']}</span></p>
                <p style="margin: 5px 0;"><b>Question:</b> <span style="font-size: 1.1em; color: #2c3e50;">{s['Question']}</span></p>
                <p style="margin: 0; font-size: 0.9em; color: #c0392b;"><b>Issue:</b> Every value in column <b>'{fail['bad_col']}'</b> is a near-duplicate.</p>
                <div style="margin-top: 10px;">
                    {df_full.to_html(index=False)}
                </div>
            </div>
            <hr style="border: 0; border-top: 1px solid #eee;">
            """
            display(HTML(html_output))
    else:
        print("✅ No systemic failures found in the categorical attributes.")

# Usage
# audit_categorical_system(generator.valid_results)

In [596]:
audit_categorical_system(generator.valid_results)

In [570]:
cou = 0
tot = 0
sam = 0
for s in [a for a in generator.valid_results if a['Selected strategy'] == "TOP_K_RANKING"]:
    if "three" in s['Question'].lower():
       tot += 1
    sam += 1
print(f"Top 3: {tot/sam}")

Top 3: 1.0

In [557]:
cou = 0
tot = 0
sam = 0
for s in [a for a in generator.valid_results if a['Selected strategy'] == "AGGREGATION"]:
    if "total" in s['Question'].lower():
       tot += 1
    if "average" in s['Question'].lower():
       cou += 1
    sam += 1
print(f"Sum: {tot/sam}, Avg: {cou/sam}")

Sum: 0.9148936170212766, Avg: 0.0851063829787234

In [595]:
import pandas as pd
import re
from IPython.display import display, HTML

def audit_numeric_in_categorical(samples):
    categorical_strategies = ['UNIQUE_DIVERSITY', 'FREQUENCY_MODE', 'CATEGORICAL_FILTER_LOOKUP']
    target_samples = [s for s in samples if s.get('Selected strategy') in categorical_strategies]
    total_samples = len(target_samples)
    
    if total_samples == 0:
        print("🔍 No samples found for categorical strategies.")
        return

    problem_details = []
    problematic_sample_indices = set()

    # Regex to find: Integers, Decimals, and Ranges (e.g., 10-20, 10 to 20, 10/20)
    # This also handles currency symbols and commas
    num_pattern = re.compile(r'^[\$€£%]*\d+([.,]\d+)?([\s\-\/]+(to[\s\-]+)?\d+([.,]\d+)?[\$€£%]*)?$')

    for idx, sample in enumerate(target_samples):
        table = sample.get('Relevant table data', [])
        if not table or not isinstance(table, list): continue
        
        all_cols = list(table[0].keys())
        if len(all_cols) <= 1: continue
        
        data_cols = all_cols[1:]
        
        for col in data_cols:
            values = [str(row.get(col, "")).strip() for row in table if row.get(col)]
            if not values: continue
            
            # Find values that match numeric or range patterns
            numeric_values = [v for v in values if num_pattern.match(v.replace(',', ''))]

            # NEW THRESHOLD: 25% (1/4 of the column)
            if len(numeric_values) >= len(values) / 4:
                problematic_sample_indices.add(idx)
                problem_details.append({
                    'sample': sample,
                    'col': col,
                    'found_nums': list(set(numeric_values))
                })
                break 

    # --- 1. THE BIG PICTURE SUMMARY ---
    clean_count = total_samples - len(problematic_sample_indices)
    
    display(HTML(f"""
    <div style="border: 2px solid #8e44ad; border-radius: 10px; padding: 20px; font-family: sans-serif; background-color: #f4f0f7;">
        <h2 style="margin-top: 0; color: #8e44ad;">🔢 NUMERIC & RANGE AUDIT (Threshold: 25%)</h2>
        <div style="display: flex; gap: 40px;">
            <div style="text-align: center;">
                <h1 style="color: #27ae60; margin: 0;">{clean_count}</h1>
                <p style="color: #666;">CATEGORICAL PURITY</p>
            </div>
            <div style="text-align: center;">
                <h1 style="color: #e74c3c; margin: 0;">{len(problematic_sample_indices)}</h1>
                <p style="color: #666;">NUMERIC/RANGE LEAKS</p>
            </div>
            <div style="text-align: center; border-left: 1px solid #ccc; padding-left: 40px;">
                <h1 style="color: #8e44ad; margin: 0;">{(clean_count/total_samples)*100:.1f}%</h1>
                <p style="color: #666;">OVERALL QUALITY</p>
            </div>
        </div>
    </div>
    """))

    # --- 2. EXAMPLES (QUESTION + FULL TABLE) ---
    if problem_details:
        display(HTML("<h3 style='margin-top: 30px; color: #e67e22;'>⚠️ LEAKAGE EXAMPLES (Including Ranges)</h3>"))
        for p in problem_details:
            s = p['sample']
            df_full = pd.DataFrame(s['Relevant table data'])
            
            html_output = f"""
            <div style="margin-bottom: 40px; border-left: 5px solid #e67e22; padding-left: 15px;">
                <p style="margin: 0;"><b>Strategy:</b> {s['Selected strategy']}</p>
                <p style="margin: 5px 0;"><b>Question:</b> <span style="font-size: 1.1em; color: #2c3e50; font-weight: bold;">{s['Question']}</span></p>
                <p style="margin: 0; color: #d35400;"><b>Issue:</b> Column <b>'{p['col']}'</b> leaked numeric values or ranges: <code style="background: #fff; padding: 2px 5px;">{p['found_nums']}</code></p>
                <div style="margin-top: 10px;">
                    {df_full.to_html(index=False)}
                </div>
            </div>
            <hr style="border: 0; border-top: 1px solid #eee;">
            """
            display(HTML(html_output))
    else:
        print("✅ No numeric or range leakage detected in categorical columns!")

In [594]:
audit_numeric_in_categorical(generator.valid_results)

# Test for entities:

In [143]:
from collections import Counter
num_tot = len(cleaned_data)
num_lo = []
ent_h = []
temp_num = 0
for s in cleaned_data:
    wiki_title = s['table_name'].split(' > ')[0].split('List of ')[1].lower()
    for h in s['rows'][0].keys():
        if h.lower() in [a.lower() for a in TEST_KEYWORDS] or h.lower() in universal_priority or 'name' in h.lower():
            temp_num += 1
    if temp_num == 5:
        pass
        print(f"{wiki_title} --> {s['rows'][0].keys()}")
    num_lo.append(temp_num)
    if temp_num == 1:
        for h in s['rows'][0].keys():
            if h.lower() in [a.lower() for a in TEST_KEYWORDS]:
                # print(f"{wiki_title} --> {h}")
                ent_h.append(h)
    temp_num = 0
print(Counter(num_lo))
print(len(set(ent_h)))
# set(ent_h)

ncaa division i institutions --> dict_keys(['School', 'Common name', 'Nickname', 'City', 'State', 'Type', 'Subdivision', 'Former Div.', 'Conference', 'Reclassified', 'Full member'])
bridges in croatia --> dict_keys(['English name', 'Croatian name', 'Distinction', 'Length', 'Type', 'Carries Crosses', 'Opened', 'Location', 'County'])
cities, towns and villages in cyprus --> dict_keys(['Name ( en )', 'District', 'Population ( urban )(2021)', 'Area ( urban )', 'Name ( gr )', 'Name ( tr )', 'Other name(s)'])
Counter({1: 2878, 0: 1432, 2: 1108, 3: 223, 4: 46, 5: 3})
75

In [148]:
from knowledge_maze.create_dataset.create_questions.visualization import WikiTableCleaner

# ==========================================
# USAGE EXAMPLE
# ==========================================

# Run the processor
cleaner = WikiTableCleaner()
new_dataset = cleaner.process_batch(cleaned_data)

# # Print results
# import json

# print(json.dumps(new_dataset, indent=2, ensure_ascii=False))

================================================================================
                         WIKI TABLE PROCESSING SUMMARY
================================================================================
Total Tables Processed:   5690
Passed (Closed Sets):     5099
Rejected:                 591
Success Rate:             89.6%
--------------------------------------------------------------------------------
                                EXTRACTED GROUPS
--------------------------------------------------------------------------------
 1. Current Social Distortion band members                                           | Column: Name                 | Rows: 4
 2. Speciality store Cosmetics and healthcare supermarket chains in Serbia           | Column: Name                 | Rows: 11
 3. Touring Supertramp band members                                                  | Column: Name                 | Rows: 5
 4. Box office collection Tamil films of 2019                                        | Column: Title                | Rows: 10
 5. Former programming Blocks programs broadcast by Universal Kids                   | Column: Title                | Rows: 10
 6. Top 10 Highest-grossing 2012 box office number-one films in Japan                | Column: Title                | Rows: 10
 7. Current Multilateral organisations diplomatic missions of Yemen                  | Column: Mission              | Rows: 4
 8. Current Flotsam and Jetsam band members                                          | Column: Name                 | Rows: 5
 9. Private institutions universities in Brunei                                      | Column: Name in English      | Rows: 7
10. Statistics By nationality crew of the International Space Station                | Column: Nationality          | Rows: 11
11. Lighthouses in Saint Helena                                                      | Column: Name                 | Rows: 4
12. Top 6 2025Fortunelist largest companies in Taiwan                                | Column: Name                 | Rows: 6
13. City mayors of Subiaco                                                           | Column: Mayor                | Rows: 9
14. Defunct airlines of Mali                                                         | Column: Airline              | Rows: 11
15. Top 5 Top-grossing Kannada films of 1992                                         | Column: Title                | Rows: 5
16. Box office Chinese films of 2014                                                 | Column: Title                | Rows: 10
17. And harbours ports in Djibouti                                                   | Column: Port/Harbour name    | Rows: 4
18. Current Americas diplomatic missions of Croatia                                  | Column: Mission              | Rows: 9
19. Top 5 Highest-grossing Japanese films of 2003                                    | Column: Title                | Rows: 5
20. Basketball athletes from Montana                                                 | Column: Name                 | Rows: 11
================================================================================

In [149]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(new_dataset)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/5099 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/5099 [00:00<?, ?it/s]

✅ Strategy Selection Complete.

═══════════════════════════════════════════════════════
📊 STRATEGY SELECTION SUMMARY
-------------------------------------------------------
✅ Groups Passed:     5025
❌ Groups Discarded:  74
📈 Success Rate:      98.5%
-------------------------------------------------------
Strategy Distribution (Top 4 per table):
  - UNIQUE_DIVERSITY          : 3722
  - COUNT_TOTAL               : 2493
  - EXTREME_TEMPORAL          : 2362
  - FILTER_COUNT_TEMPORAL     : 1913
  - FREQUENCY_MODE            : 1328
  - CATEGORICAL_FILTER_LOOKUP : 988
  - EXTREME_NUMERICAL         : 553
  - TOP_K_RANKING             : 471
  - AGGREGATION               : 427
  - COMPARATIVE_DIFFERENCE    : 363
  - FILTER_COUNT_NUMERICAL    : 266
-------------------------------------------------------
POSSIBLE STRATEGIES  | GROUP COUNT  | PERCENTAGE
-------------------------------------------------------
#1                   | 639          |      12.7%
#2                   | 1168         |      23.2%
#3                   | 961          |      19.1%
#4                   | 2257         |      44.9%
═══════════════════════════════════════════════════════

In [150]:
import random
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(random.sample(selector.updated_data, 100),
                              strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 100 tables...
--- Round 1: Processing 100 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/100 [00:00<?, ?it/s]

--- Round 2: Processing 2 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/2 [00:00<?, ?it/s]

--- Round 3: Processing 1 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1 [00:00<?, ?it/s]

═════════════════════════════════════════════════════════════════
                  📊 QUESTION GENERATION SUMMARY
═════════════════════════════════════════════════════════════════
Initial Tables:      100
Successfully Gen:    98
Exhausted Strats:    2
Success Rate:        98.0%
-----------------------------------------------------------------
STRATEGY                     | SUCCESS  | TRIED    | RATE
-----------------------------------------------------------------
FILTER_COUNT_TEMPORAL        | 15       | 17       |  88%
UNIQUE_DIVERSITY             | 15       | 15       | 100%
EXTREME_TEMPORAL             | 14       | 15       |  93%
COUNT_TOTAL                  | 14       | 16       |  88%
FREQUENCY_MODE               | 13       | 13       | 100%
CATEGORICAL_FILTER_LOOKUP    | 12       | 12       | 100%
AGGREGATION                  | 3        | 3        | 100%
EXTREME_NUMERICAL            | 3        | 3        | 100%
TOP_K_RANKING                | 3        | 3        | 100%
COMPARATIVE_DIFFERENCE       | 3        | 3        | 100%
FILTER_COUNT_NUMERICAL       | 3        | 3        | 100%
-----------------------------------------------------------------
Total                        | 98       | 103      |  95%
═════════════════════════════════════════════════════════════════

🔍 SAMPLES OF FAILED DATA VIEWS:
-----------------------------------------------------------------

[1] Table: Collection films at the 2007 Sundance Film Festival
    Original Data: https://en.wikipedia.org/wiki/List_of_films_at_the_2007_Sundance_Film_Festival
    Strategy Attempted: EXTREME_TEMPORAL
    Rejection Reason:   The table contains non-specific entries for the 'Year' column and does not provide a clear earliest or latest date for the films listed.
    Table Data:

                  Title                                               Year
0          River's Edge                                               1986
1          River's Edge                            Written by Neal Jimenez
2          River's Edge  Starring Crispin Glover , Keanu Reeves , Ione ...
3  X: The Unheard Music                                               1986
4  X: The Unheard Music                            Written by W. T. Morgan
5  X: The Unheard Music  Starring Exene Cervenka , John Doe , Billy Zoo...

-----------------------------------------------------------------

[2] Table: Key Boston Bruins players
    Original Data: https://en.wikipedia.org/wiki/List_of_Boston_Bruins_players
    Strategy Attempted: COUNT_TOTAL
    Rejection Reason:   The data provided does not include any distinct entities (players) to count, only statistical categories are listed.
    Table Data:

       W
0     SO
1      L
2    GAA
3      T
4  OTL a
5    SV%

-----------------------------------------------------------------

[3] Table: Collection films at the 2007 Sundance Film Festival
    Original Data: https://en.wikipedia.org/wiki/List_of_films_at_the_2007_Sundance_Film_Festival
    Strategy Attempted: FILTER_COUNT_TEMPORAL
    Rejection Reason:   The 'Year' column contains non-temporal data and does not allow for a valid count of films within a specific year range.
    Table Data:

                  Title                                               Year
0          River's Edge                                               1986
1          River's Edge                            Written by Neal Jimenez
2          River's Edge  Starring Crispin Glover , Keanu Reeves , Ione ...
3  X: The Unheard Music                                               1986
4  X: The Unheard Music                            Written by W. T. Morgan
5  X: The Unheard Music  Starring Exene Cervenka , John Doe , Billy Zoo...

-----------------------------------------------------------------

In [151]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(generator.valid_results, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/85 [00:00<?, ?it/s]

In [152]:
from knowledge_maze.create_dataset.create_questions.question_validator import ManualTagger

tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 0 samples already tagged in 'tagger_progress.json'.

Output()

In [54]:
validated_tables[0]

{'table_name': 'White City: A Novel > Track listing (Side one)',
 'rows': [{'No.': 1.0, 'Title': '" Give Blood "', 'Length': '5:44'},
  {'No.': 2.0, 'Title': '"Brilliant Blues"', 'Length': '3:06'},
  {'No.': 3.0, 'Title': '" Face the Face "', 'Length': '5:51'},
  {'No.': 4.0, 'Title': '"Hiding Out"', 'Length': '3:00'},
  {'No.': 5.0, 'Title': '"Secondhand Love"', 'Length': '4:12'}],
 'density': 1.0}

In [62]:
validated_tables = load_jsonl(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
list_of_validated_tables = [a for a in validated_tables if a['table_name'].startswith("List of")]
save_jsonl("final_tables_list_of", list_of_validated_tables)
processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/final_tables_list_of.jsonl"))
cleaned_data = processor.process()

Filtering & Cleaning:   0%|          | 0/41609 [00:00<?, ?it/s]

════════════════════════════════════════════
📊 TABLE PROCESSING SUMMARY (Limit: 12)
════════════════════════════════════════════
Total tables scanned:      41609
Dropped (Bad Headers):     1659
Dropped (Cell too long):   1628
Dropped (Repeat Rows):     802
Short tables found:        17514
Unique source pages:       5690
Final sampled (1/page):    5690
════════════════════════════════════════════

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                  ↓ EXAMPLE TABLES ↓
------------------------------------------------------------------------------------------------------------------------------------------------------

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
List of members of the European Parliament for Luxembourg, 2014–2019 > List
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Name,National party,EP group
0,Georges Bach,Christian Social People's Party (CSV),EPP
1,Mady Delvaux-Stehres,Luxembourg Socialist Workers' Party (LSAP),S&D
2,Frank Engel,Christian Social People's Party (CSV),EPP
3,Charles Goerens,Democratic Party (DP),ALDE
4,Christophe Hansen (2018–2019),Christian Social People's Party (CSV),EPP
5,Tilly Metz (2018–2019),The Greens,Greens/EFA
6,Viviane Reding (2014–2018),Christian Social People's Party (CSV),EPP
7,Claude Turmes (2014–2018),The Greens,Greens/EFA

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
List of governors of Danish India > List > Governors of Dannemarksnagore (List of governors of Dannemarksnagore)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Tenure,Incumbent,Notes
0,1698–1699,Andreas Andræ,Concluded the Dano-Mughal Treaty together with...
1,1699–1702,Thomas Schmertz,Concluded the Dano-Mughal Treaty together with...
2,1702–1706,Johan Michelsen,
3,1706–1709,Jacob Panch,
4,1709–1711,Wolf Ravn,
5,1711–1714,Rasmus Attrup,Left the fort because of Mughal holstilities
6,1718,Gallus Bøgvad,

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
List of WNBL awards > Individual awards
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Award,Created,Description,Most recent winner(s)
0,Most Valuable Player ( Suzy Batkovic Medal ),1982,Awarded to the best performing player of the W...,Stephanie Talbot (2020)
1,Grand Final Most Valuable Player ( Rachael Spo...,1985,Awarded to the best performing player of the W...,Leilani Mitchell (2020)
2,Defensive Player of the Year ( Robyn Maher Med...,1990,Awarded to the best defensive player of the WN...,Stephanie Talbot (2020)
3,Youth Player of the Year (Betty Watson Medal),1988,Awarded to the best performing player 23 years...,Shyla Heal (2020)
4,Sixth Woman of the Year,2020,Awarded to the most incredible talent coming o...,Zitina Aokuso (2020)
5,Coach of the Year,1987,Awarded to the best coach of the WNBL season.,Shannon Seebohm (2020)
6,Leading Scorer Award,1981,Awarded to the player with the highest average...,Liz Cambage (2020)
7,Leading Rebounder Award,2020,Awarded to the player with the highest average...,Anneli Maley (2020)
8,Golden Hands Award,2020,Awarded to the player with the highest Golden ...,Leilani Mitchell (2020)

In [67]:
import re

class ClosedSetExtractor:
    def __init__(self):
        # Keywords that signal an "Open" or "Subjective" set (100% Precision Kill-switch)
        self.open_set_triggers = [
            r'\bnotable\b', r'\bfamous\b', r'\bselected\b', 
            r'\bmajor\b', r'\bexamples?\b', r'\bpartial\b'
        ]
        # High-confidence entity identifiers
        self.universal_priority = [
            'name', 'title', 'airline', 'team', 'character', 'honor', 
            'mayor', 'organization', 'mission', 'planet', 'film', 'company'
        ]
        # Statistical columns to reject
        self.kill_list = [
            'rank', 'gross', 'collection', 'revenue', 'year', 'date', 
            'pos', 'notes', 'ref', 'no.', 'total', 'index', 'rank'
        ]
        
        self.stats = {"total_processed": 0, "passed": 0, "rejected_open_set": 0, "rejected_no_entity": 0, "incomplete_set": 0}

    def _is_closed_set(self, page_title, hierarchy):
        """Determines if the context implies a complete, exhaustive list."""
        context = (page_title + " " + " ".join(hierarchy)).lower()
        for pattern in self.open_set_triggers:
            if re.search(pattern, context):
                return False
        return True

    def _extract_entity_col(self, rows, page_title, hierarchy):
        """Deterministic Scorer from our previous iteration."""
        if not rows: return None
        headers = list(rows[0].keys())
        page_ctx = (page_title + " " + " ".join(hierarchy)).lower()
        
        scores = {}
        for h in headers:
            h_low = h.lower().strip()
            # Rule 1: Kill list
            if any(k == h_low or f" {k}" in h_low or f"{k} " in h_low for k in self.kill_list):
                continue
            
            score = 0
            # Rule 2: Lexical Anchor (Title match)
            singular_h = h_low.rstrip('s')
            if singular_h in page_ctx and len(singular_h) > 2:
                score += 50
            # Rule 3: Universal Labels
            if h_low in self.universal_priority:
                score += 40
            # Rule 4: Data Check (Numbers check)
            try:
                samples = [str(rows[i][h]) for i in range(min(len(rows), 3)) if rows[i].get(h)]
                if samples and all(s.replace('.', '', 1).isdigit() for s in samples):
                    score -= 60
            except: pass
            
            # Rule 5: Position
            score += (len(headers) - headers.index(h))
            scores[h] = score

        return max(scores, key=scores.get) if scores and max(scores.values()) > 0 else None

    def _generate_group_name(self, page_title, hierarchy):
        """Fuses Hierarchy and Title while removing redundancy."""
        clean_title = re.sub(r'^list of (the )?', '', page_title, flags=re.IGNORECASE).strip()
        # Filter hierarchy to remove redundancy with the title
        title_words = set(clean_title.lower().split())
        filtered_hierarchy = []
        for h in hierarchy:
            h_clean = re.sub(r'\(.*?\)', '', h).strip()
            h_words = h_clean.split()
            unique_words = [w for w in h_words if w.lower() not in title_words]
            if unique_words:
                filtered_hierarchy.append(" ".join(unique_words))
        
        if not filtered_hierarchy:
            return clean_title.capitalize()
        return f"{' '.join(filtered_hierarchy).capitalize()} {clean_title}"

    def process(self, page_title, hierarchy, table_dict):
        """
        Input: 
            page_title (str)
            hierarchy (list of strings: [h2, h3...])
            table_dict (list of dicts)
        """
        self.stats["total_processed"] += 1
        
        # 1. Check if the set is defined as "Closed"
        if not self._is_closed_set(page_title, hierarchy):
            self.stats["rejected_open_set"] += 1
            return None

        # 2. Identify Entity Column
        entity_col = self._extract_entity_col(table_dict, page_title, hierarchy)
        if not entity_col:
            self.stats["rejected_no_entity"] += 1
            return None

        # 3. Generate the Set Name
        group_name = self._generate_group_name(page_title, hierarchy)

        for row in table_dict:
            val = str(row.get(entity_col, "")).strip().lower()
    
            if val and val not in ["", "none", "null", "n/a", "na", "-", "—", "unknown", "tba", "tbd"]:
                # The member is valid, proceed with extraction
                # print(val + " - OK")
                pass
            else:
                # Skip this row or mark the table as potentially incomplete
                # print(val + " - PROBLEM")
                self.stats["incomplete_set"] += 1
                return None
        
        self.stats["passed"] += 1
        return {
            "group_name": group_name,
            "entity_column": entity_col,
            "members": [t[entity_col] for t in table_dict],
            "status": "CLOSED_SET_VERIFIED",
            "table": table_dict
        }

    def get_summary(self):
        return (f"--- Processing Summary ---\n"
                f"Total Tables: {self.stats['total_processed']}\n"
                f"Passed (Closed Sets): {self.stats['passed']}\n"
                f"Rejected (Subjective/Open): {self.stats['rejected_open_set']}\n"
                f"Rejected (No clear Entity): {self.stats['rejected_no_entity']}\n"
                f"Rejected (Incomplete Set): {self.stats['incomplete_set']}\n"
                f"Precision Estimate: 100% (Deterministic)")

In [70]:
import pandas as pd
extractor = ClosedSetExtractor()

# Assuming 'all_tables' is your list of table objects
for s in cleaned_data[:100]:
    # 1. Prepare the inputs from your data structure
    current_rows = s['rows'] 
    
    # Splitting the title and hierarchy from your 'table_name' string
    # e.g., "List of defunct airlines of Oceania > Norfolk Island"
    parts = s['table_name'].split(' > ')
    page_title = parts[0]
    hierarchy = parts[1:] if len(parts) > 1 else []

    # 2. Run the extractor
    result = extractor.process(
        page_title=page_title,
        hierarchy=hierarchy,
        table_dict=current_rows
    )

    # 3. Handle the result
    if result:
        print(f"Set Verified: {result['group_name']}")
        print(f"Entity Col:   {result['entity_column']}")
        print(f"Entities:    {result['members']}")
        print("Table Data:")
        display(pd.DataFrame(result['table']))
        
        print("-" * 30)

# See the final tally
print(extractor.get_summary())

Set Verified: Current Social Distortion band members
Entity Col:   Name
Entities:    ['Mike Ness', 'Jonny "2 Bags" Wickersham', 'Brent Harding', 'David Hidalgo Jr.']
Table Data:

,Name,Years active,Instruments,Release contributions
0,Mike Ness,1978–present,lead vocals lead guitar,all Social Distortion releases
1,"Jonny ""2 Bags"" Wickersham",2000–present,rhythm guitar backing vocals,"all Social Distortion releases from Sex, Love ..."
2,Brent Harding,2005–present,bass backing vocals,"all Social Distortion releases from "" Far Behi..."
3,David Hidalgo Jr.,2010–present,drums percussion,""" Up Around the Bend "" (2013) Machine Gun Melo..."

------------------------------
Set Verified: Speciality store cosmetics and healthcare supermarket chains in Serbia
Entity Col:   Name
Entities:    ['BENU', 'Lilly', 'DM', 'Jasmin', 'The Body Shop', 'KIKO', 'Sephora', "L'Occitane en Provence", "Kiehl's", 'Yves Rocher', 'Lush']
Table Data:

                      Name  Stores  First store                Parent
0                     BENU     451         2010  Phoenix Pharmahandel
1                    Lilly     234         2006        Lilly drogerie
2                       DM     132         2004                    DM
3                   Jasmin      27         1956    Jasmin parfimerije
4            The Body Shop      11         2019           Natura & Co
5                     KIKO       9         2021           KIKO Milano
6                  Sephora       5         2010                  LVMH
7   L'Occitane en Provence       5         2012            L'occitane
8                  Kiehl's       4         2019               L'Oréal
9              Yves Rocher       1         2008           Yves Rocher
10                    Lush       1         2020                  Lush

------------------------------
Set Verified: Touring Supertramp band members
Entity Col:   Name
Entities:    ['Scott Page', 'Fred Mandel', 'Marty Walsh', 'Brad Cole', 'Steve Reid']
Table Data:

,Name,Years active,Instruments,Release contributions
0,Scott Page,1983–1986,saxophone woodwind guitar backing vocals,The Story So Far... (1983/1990) Brother Where ...
1,Fred Mandel,1983,keyboards guitar backing vocals,The Story So Far (1983/1990) Some Things Never...
2,Marty Walsh,1984–1988,guitar backing vocals,Brother Where You Bound (1985) Free as a Bird ...
3,Brad Cole,1985 1987–1988,saxophone keyboards,Live '88 (1988)
4,Steve Reid,1987–1988,percussion,Free as a Bird (1987) Live '88 (1988)

------------------------------
Set Verified: Box office collection Tamil films of 2019
Entity Col:   Title
Entities:    ['Bigil', 'Petta', 'Viswasam', 'Kanchana 3', 'Asuran', 'Nerkonda Paarvai', 'Kaithi', 'Kaappaan', 'Namma Veetu Pillai', 'NGK']
Table Data:

,Rank,Title,Production company,Distributor,Worldwide gross
0,1,Bigil,AGS Entertainment,AGS Entertainment,₹285-305 crore
1,2,Petta,Sun Pictures,Sun Pictures,₹219-250 crore
2,3,Viswasam,Sathya Jyothi Films,KJR Studios,₹185-200 crore
3,4,Kanchana 3,Sun Pictures & Raghavendra Productions,Sun Pictures,₹130 crore
4,5,Asuran,V Creations,V Creations,₹ 110 crore
5,6,Nerkonda Paarvai,Boney Kapoor & Zee Studios,S Pictures & Kandhasamy Arts,₹108 crore
6,7,Kaithi,Dream Warrior Pictures,Dream Warrior Pictures,₹105 crore
7,8,Kaappaan,Lyca Productions,Lyca Productions,₹100 crore
8,9,Namma Veetu Pillai,Sun Pictures,Sun Pictures,₹ 63 crore
9,10,NGK,Dream Warrior Pictures,Reliance Entertainment,₹ 62.35 crore

------------------------------
Set Verified: Former programming blocks programs broadcast by Universal Kids
Entity Col:   Title
Entities:    ['The Birthday Show', 'The Good Night Show', 'Sprout Diner', 'Sprout Sharing Show', "The Let's Go Show", 'Musical Mornings with Coo', 'The Sunny Side Up Show', 'Wiggly Waffle', 'The Super Sproutlet Show', 'Family Movie Night']
Table Data:

                       Title       Premiere date            End date
0          The Birthday Show  September 26, 2005        May 12, 2009
1        The Good Night Show  September 26, 2005      March 31, 2017
2               Sprout Diner  September 18, 2006  September 20, 2008
3        Sprout Sharing Show         May 5, 2008        May 11, 2014
4          The Let's Go Show       June 25, 2007  September 24, 2010
5  Musical Mornings with Coo  September 26, 2007     August 21, 2009
6     The Sunny Side Up Show  September 26, 2007     August 11, 2017
7              Wiggly Waffle     August 24, 2009      March 22, 2013
8   The Super Sproutlet Show   February 14, 2012       June 19, 2015
9         Family Movie Night  September 26, 2015   September 8, 2017

------------------------------
Set Verified: Highest-grossing 2012 box office number-one films in Japan
Entity Col:   Title
Entities:    ['Brave Hearts: Umizaru', 'Thermae Romae', 'Bayside Shakedown: The Final', 'Mission: Impossible – Ghost Protocol', 'Evangelion: 3.0 You Can (Not) Redo', 'Wolf Children', 'Resident Evil: Retribution', 'Doraemon: Nobita and the Island of Miracles—Animal Adventure', 'The Avengers', 'Pokémon the Movie: Kyurem vs. the Sword of Justice']
Table Data:

,Rank,Title,Gross
0,1,Brave Hearts: Umizaru,¥7.33 billion ( $91.87 million )
1,2,Thermae Romae,¥5.98 billion ( $74.95 million )
2,3,Bayside Shakedown: The Final,¥5.97 billion ( $74.82 million )
3,4,Mission: Impossible – Ghost Protocol,¥5.38 billion ( $67.43 million )
4,5,Evangelion: 3.0 You Can (Not) Redo,¥5.30 billion ( $66.42 million )
5,6,Wolf Children,¥4.22 billion ( $52.89 million )
6,7,Resident Evil: Retribution,¥3.81 billion ( $47.75 million )
7,8,Doraemon: Nobita and the Island of Miracles—An...,¥3.62 billion ( $45.37 million )
8,9,The Avengers,¥3.61 billion ( $45.24 million )
9,9,Pokémon the Movie: Kyurem vs. the Sword of Jus...,¥3.61 billion ( $45.24 million )

------------------------------
Set Verified: Current multilateral organisations diplomatic missions of Yemen
Entity Col:   Mission
Entities:    ['Permanent Mission', 'Permanent Mission', 'Permanent Mission', 'Delegation']
Table Data:

,Organization,Host city,Host country,Mission,Concurrent accreditation
0,Arab League,Cairo,Egypt,Permanent Mission,
1,United Nations,New York City,United States,Permanent Mission,
2,United Nations,Geneva,Switzerland,Permanent Mission,Countries : Switzerland
3,UNESCO,Paris,France,Delegation,

------------------------------
Set Verified: Current Flotsam and Jetsam band members
Entity Col:   Name
Entities:    ['Eric "A. K." Knutson', 'Michael Gilbert', 'Steve Conley', 'Ken Mary', 'Bill Bodily']
Table Data:

,Name,Years active,Instruments,Release contributions
0,"Eric ""A. K."" Knutson",1982–2001 2003–present,lead vocals,all Flotsam and Jetsam (F&J) releases
1,Michael Gilbert,1985–1997 1999–2000 2010–present,guitar backing vocals,all F&J releases from Iron Tears (1985) to Hig...
2,Steve Conley,2013–present,guitar backing vocals,all F&J releases from No Place for Disgrace 20...
3,Ken Mary,2017–present,drums,The End of Chaos (2019) Blood in the Water (20...
4,Bill Bodily,2020–present (plus touring in 2016 and 2019),bass backing vocals,Blood in the Water (2021) I Am the Weapon (2024)

------------------------------
Set Verified: Private institutions universities in Brunei
Entity Col:   Name in English
Entities:    ['Cosmopolitan College of Commerce and Technology', 'Kemuda Institute', 'Laksamana College of Business - Brunei campus of Kensington College of Business', 'International Graduate Studies College', 'Micronet International College', 'Bicpa-Ftms Accountancy Academy', 'HADtech College']
Table Data:

,Name in English,Name in Malay,Abbreviation,Foundation
0,Cosmopolitan College of Commerce and Technology,Kolej Perdangangan dan Teknologi Cosmopolitan,CCCT,2004
1,Kemuda Institute,Institut KEMUDA,KI,2004
2,Laksamana College of Business - Brunei campus ...,Kolej Perdagangan Laksamana,LCB / KCB,2003
3,International Graduate Studies College,Kolej Pengajian Siswazah Antarabangsa,IGS,2002
4,Micronet International College,Kolej Antarabangsa Micronet,MIC,1989
5,Bicpa-Ftms Accountancy Academy,Akademi Perakaunan Bicpa-Ftms,BICPA,1987
6,HADtech College,Kolej HADtech,HADC,2019

------------------------------
Set Verified: Statistics by nationality crew of the International Space Station
Entity Col:   Nationality
Entities:    ['United States', 'Russia', 'Japan', 'Italy', 'Canada', 'Denmark', 'Germany', 'France', 'Belgium', 'Netherlands', 'United Kingdom']
Table Data:

       Nationality  ISS Crew  On-board
0    United States        57         3
1           Russia        46         3
2            Japan         6         1
3            Italy         3         0
4           Canada         3         0
5          Denmark         1         0
6          Germany         2         0
7           France         2         0
8          Belgium         1         0
9      Netherlands         1         0
10  United Kingdom         1         0

------------------------------
Set Verified: Lighthouses in saint helena
Entity Col:   Name
Entities:    ['James Bay Range Front Lighthouse', 'James Bay Range Rear Lighthouse', 'Buttermilk Point Lighthouse', 'Chubbs Point Lighthouse']
Table Data:

,Name,Light characteristic,Focal height (metres),NGA number,Admiralty number,Range (nautical miles)
0,James Bay Range Front Lighthouse,Fl G 3s,143,113-26100,D4904,3
1,James Bay Range Rear Lighthouse,Iso G 8s,170,113-26104,D4904.1,3
2,Buttermilk Point Lighthouse,Fl(2) W 10s,37,113-26112,D4908,10
3,Chubbs Point Lighthouse,Fl(2) R 10s,25,113-26108,D4906,3

------------------------------
Set Verified: Key Cardiff City F.C. seasons
Entity Col:   1st or W
Entities:    ['2nd or RU', '↑', '↓', '*', '♦']
Table Data:

    1st or W                                  Winners
0  2nd or RU                               Runners-up
1          ↑                                 Promoted
2          ↓                                Relegated
3          *                   Promoted via play-offs
4          ♦  Top league scorer in Cardiff's division

------------------------------
Set Verified: 2025fortunelist largest companies in Taiwan
Entity Col:   Name
Entities:    ['Hon Hai Precision Industry', 'Taiwan Semiconductor Manufacturing', 'Quanta Computer', 'Pegatron', 'CPC Corporation', 'Wistron']
Table Data:

,Rank,Fortune 500 rank,Name,Industry,Revenue (USD millions),Profits (USD millions),Employees,Headquarters
0,1,28,Hon Hai Precision Industry,Electronics,213699,4757,633167,New Taipei City
1,2,126,Taiwan Semiconductor Manufacturing,Semiconductor,90167,36087,83825,Hsinchu
2,3,348,Quanta Computer,Electronics,43950,1860,65926,Taoyuan
3,4,461,Pegatron,Electronics,35058,526,98202,Taipei
4,5,494,CPC Corporation,Oil and Gas,32769,-1028,16637,Kaohsiung
5,6,496,Wistron,Electronics,32687,543,42091,Taipei

------------------------------
Set Verified: City mayors of Subiaco
Entity Col:   Mayor
Entities:    ['Joseph H. Abrahams', 'Evelyn Helena Parker', 'Alf Fernihough', 'Richard Diggins', 'Helen Passmore', 'Tony Costa', 'Heather Henderson', 'Penny Taylor', 'David McMullen']
Table Data:

,Mayor,Term,Notes
0,Joseph H. Abrahams,1952–1974,"Longest serving mayor of Subiaco, at 25 years"
1,Evelyn Helena Parker,1974–1977,First woman mayor in Western Australia; second...
2,Alf Fernihough,1977–1978,
3,Richard Diggins,1978–1989,
4,Helen Passmore,1989–1994,
5,Tony Costa,1994–2005,
6,Heather Henderson,2005–2017,Chose not to contest 2017 election
7,Penny Taylor,2017–2021,Chose not to contest 2021 election
8,David McMullen,2021–present,Re-elected unopposed at the 2025 election

------------------------------
Set Verified: Defunct airlines of Mali
Entity Col:   Airline
Entities:    ['Air Mali (1960–89)', 'Air Mali (1993)', 'Air Mali (2005)', 'Air Mali International', 'CAM - Compagnie Aérienne du Mali', 'Douniah Airlines', 'Mali Air Express', 'Mali Air Transport', 'SAM Intercontinental', 'STA Trans African Airlines', 'Transair Mali']
Table Data:

,Airline,IATA,ICAO,Callsign,Commenced operations,Ceased operations,Notes
0,Air Mali (1960–89),MY,AIM,-,1960,1985,
1,Air Mali (1993),L9,MLI,-,1993,2001,
2,Air Mali (2005),I5,CMM,CAMALI,2009,2012,
3,Air Mali International,XG,KLB,-,2002,2003,
4,CAM - Compagnie Aérienne du Mali,I5,CMM,-,2005,2009,Rebranded as Air Mali
5,Douniah Airlines,DH,DTS,-,2012,2014,
6,Mali Air Express,,VXP,-,2001,2020,
7,Mali Air Transport,,,-,2008,2009,
8,SAM Intercontinental,,MMT,,2008,2020,
9,STA Trans African Airlines,T8,SBA,-,2002,2005,
10,Transair Mali,,TSM,-,1991,1995,

------------------------------
Set Verified: Top-grossing Kannada films of 1992
Entity Col:   Title
Entities:    ['Jeevana Chaitra', 'Halli Meshtru', 'Aatma Bandhana', 'Belliyappa Bangarappa', 'Tharle Nan Maga']
Table Data:

   Rank                  Title                       Collection
0   1.0        Jeevana Chaitra  ₹9 crore (₹73.84 crore in 2025)
1   2.0          Halli Meshtru  ₹5 crore (₹41.02 crore in 2025)
2   3.0         Aatma Bandhana  ₹4 crore (₹32.87 crore in 2025)
3   4.0  Belliyappa Bangarappa  ₹3 crore (₹24.61 crore in 2025)
4   5.0        Tharle Nan Maga  ₹2 crore (₹16.44 crore in 2025)

------------------------------
Set Verified: Box office Chinese films of 2014
Entity Col:   Title
Entities:    ['Breakup Buddies', 'The Monkey King', 'The Taking of Tiger Mountain', 'Where Are We Going, Dad?', 'The Breakup Guru', 'The Continent', 'Fleet of Time', 'From Vegas to Macau', 'Tiny Times 3', 'Gone with the Bullets']
Table Data:

   Rank                         Title Gross (in USD)
0     1               Breakup Buddies   $190,120,000
1     2               The Monkey King   $167,880,000
2     3  The Taking of Tiger Mountain   $141,110,000
3     4      Where Are We Going, Dad?   $111,890,000
4     5              The Breakup Guru   $107,440,000
5     6                 The Continent   $101,080,000
6     7                 Fleet of Time    $94,190,000
7     8           From Vegas to Macau    $84,590,000
8     9                  Tiny Times 3    $83,370,000
9    10         Gone with the Bullets    $83,330,000

------------------------------
Set Verified: List of and harbours ports in Djibouti
Entity Col:   Port/Harbour name
Entities:    ['Port of Djibouti', 'Port of Tadjoura', 'Port of Doraleh', 'Port of Ghoubet']
Table Data:

,Port/Harbour name,Regions,City/Town name,Coordinates,UN/Locode,Max. draught (m),Max. deadweight (t),Remarks
0,Port of Djibouti,Djibouti City,Djibouti City,11°36′N 43°06′E ﻿ / ﻿ 11.600°N 43.100°E ﻿ / 11...,DJJIB,16.0,156198,Medium-sized port on the coast of the Gulf of...
1,Port of Tadjoura,Tadjourah Region,Tadjoura,11°46′N 43°06′E ﻿ / ﻿ 11.767°N 43.100°E ﻿ / 11...,DJTDJ,12.0,65000,The port is located on the northern coast of t...
2,Port of Doraleh,Djibouti City,Djibouti City,11°36′N 42°58′E ﻿ / ﻿ 11.600°N 42.967°E ﻿ / 11...,DJDCT,15.3,100000,The multipurpose port is located in the wester...
3,Port of Ghoubet,Arta Region,Ghoubet,,,15.0,100000,The port is located 45 km south of the Ghoubbe...

------------------------------
Set Verified: Current americas diplomatic missions of Croatia
Entity Col:   Mission
Entities:    ['Embassy', 'Embassy', 'Embassy', 'Consulate–General', 'Embassy', 'Embassy', 'Consulate–General', 'Consulate–General', 'Consulate–General']
Table Data:

,Host country,Host city,Mission,Concurrent accreditation
0,Argentina,Buenos Aires,Embassy,Countries : Paraguay Uruguay
1,Brazil,Brasília,Embassy,Countries : Colombia Trinidad and Tobago Venez...
2,Canada,Ottawa,Embassy,
3,Canada,Mississauga,Consulate–General,
4,Chile,Santiago de Chile,Embassy,Countries : Bolivia Ecuador Peru
5,United States,"Washington, D.C.",Embassy,Countries : Marshall Islands Mexico Micronesia...
6,United States,Chicago,Consulate–General,Countries : Marshall Islands Mexico Micronesia...
7,United States,Los Angeles,Consulate–General,Countries : Marshall Islands Mexico Micronesia...
8,United States,New York City,Consulate–General,Countries : Marshall Islands Mexico Micronesia...

------------------------------
Set Verified: Highest-grossing Japanese films of 2003
Entity Col:   Title
Entities:    ['Bayside Shakedown 2', 'Pokémon: Jirachi—Wish Maker', 'Detective Conan: Crossroad in the Ancient Capital', 'Yomigaeri', 'Zatōichi']
Table Data:

   Rank                                              Title           Gross
0     1                                Bayside Shakedown 2  ¥17.35 billion
1     2                        Pokémon: Jirachi—Wish Maker   ¥4.50 billion
2     3  Detective Conan: Crossroad in the Ancient Capital   ¥3.20 billion
3     4                                          Yomigaeri   ¥3.07 billion
4     5                                           Zatōichi   ¥2.85 billion

------------------------------
Set Verified: Basketball athletes from Montana
Entity Col:   Name
Entities:    ['Cass Bauer-Bilodeau', 'Jim Creighton', 'Denise Curry', 'Brad Holland', 'Phil Jackson', 'Ed Kalafat', 'Larry Krystkowiak', 'Mike Lewis', 'Adam Morrison', 'Robin Selvig', 'Keith Tower']
Table Data:

,Name,Lifetime,Montana connection,Comments
0,Cass Bauer-Bilodeau,1972–present,Born and raised in Hysham ; attended college i...,Women's National Basketball Association small ...
1,Jim Creighton,1950–present,Born in Billings,National Basketball Association small forward ...
2,Denise Curry,1959–present,Born in Fort Benton,Olympic gold medalist (1984); professional bas...
3,Brad Holland,1956–present,Born in Billings,National Basketball Association shooting guard...
4,Phil Jackson,1945–present,Born and lived for several years in Deer Lodge,National Basketball Association (NBA) power fo...
5,Ed Kalafat,1932–2019,Attended high school in Anaconda,National Basketball Association center (1955–1...
6,Larry Krystkowiak,1964–present,Born in Missoula ; raised in Shelby ; finished...,National Basketball Association power forward ...
7,Mike Lewis,1946–present,Born in Missoula,American Basketball Association center (1969–1...
8,Adam Morrison,1984–present,Born in Glendive,National Basketball Association small forward ...
9,Robin Selvig,1953–present,Born in Outlook,Coach of University of Montana women's team (1...
10,Keith Tower,1970–present,Born in Libby,National Basketball Association center (1994–1...

------------------------------
Set Verified: Z documentary films
Entity Col:   Title
Entities:    ['Z Channel: A Magnificent Obsession', 'Zappa', 'Zeitgeist †', 'Zero Days', 'Zielen Van Napels', 'Zodiac Killer Project', 'Zombie Girl: The Movie', 'Zoo']
Table Data:

,Title,Year,Director(s),Producer(s)
0,Z Channel: A Magnificent Obsession,2004,Xan Cassavetes,"Marshall Persinger, Rick Ross"
1,Zappa,2020,Alex Winter,"Jade Allen, Devorah DeVries, John Frizzell, Ah..."
2,Zeitgeist †,2007–2011,Peter Joseph,Peter Joseph
3,Zero Days,2016,Alex Gibney,
4,Zielen Van Napels,2005,Vincent Monnikendam,Sherman De Jesus and Cécile van Eijk
5,Zodiac Killer Project,2025,Charlie Shackleton,"Charlie Shackleton, Anthony Ing, Catherine Bray"
6,Zombie Girl: The Movie,2009,"Justin Johnson, Aaron Marshall, Erik Mauck","Justin Johnson, Aaron Marshall, Erik Mauck"
7,Zoo,2007,Robinson Devore,Peggy Case and Alexis Ferris

------------------------------
Set Verified: Current Falling in Reverse band members
Entity Col:   Name
Entities:    ['Ronnie Radke', 'Christian Thompson', 'Luke Holland', 'Marc Okubo', 'Daniel "DL" Laskiewicz']
Table Data:

,Name,Years active,Instruments,Release contributions
0,Ronnie Radke,2008–present,lead vocals keyboards rhythm guitar (2017–2018),all Falling in Reverse releases
1,Christian Thompson,2015–2018 2020–present,"lead guitar (2015–2018, 2024–present) rhythm g...",all releases since Coming Home (2017)
2,Luke Holland,2021–present,drums percussion,all releases since Popular Monster (2024)
3,Marc Okubo,2024–present,rhythm guitar backing vocals,"""All My Women"" (2025)"
4,"Daniel ""DL"" Laskiewicz",2025–present,bass backing vocals,"""All My Women"" (2025)"

------------------------------
Set Verified: Highest-grossing 2010 box office number-one films in Spain
Entity Col:   Title
Entities:    ['Toy Story 3', 'Alice in Wonderland', 'The Twilight Saga: Eclipse', 'Inception', 'Shrek Forever After', 'Harry Potter and the Deathly Hallows – Part 1', "The King's Speech", 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Clash of the Titans', 'Despicable Me']
Table Data:

,Rank,Title,Distributor,Director(s),Release,Country,Domestic Gross
0,1.0,Toy Story 3,Disney,Lee Unkrich,July 21,United States,"$33,154,762"
1,2.0,Alice in Wonderland,Disney,Tim Burton,April 16,United States,"$28,769,165"
2,3.0,The Twilight Saga: Eclipse,Aurum,David Slade,June 30,United States,"$25,050,394"
3,4.0,Inception,Warner Bros.,Christopher Nolan,August 6,United Kingdom United States,"$22,212,764"
4,5.0,Shrek Forever After,Paramount,Mike Mitchell,July 8,United States,"$21,928,719"
5,6.0,Harry Potter and the Deathly Hallows – Part 1,Warner Bros.,David Yates,November 19,United Kingdom United States,"$19,017,186"
6,7.0,The King's Speech,DeAPlaneta,Tom Hooper,December 24,United Kingdom,"$15,863,460"
7,8.0,The Chronicles of Narnia: The Voyage of the Da...,Fox,Michael Apted,December 3,United Kingdom United States,"$14,992,713"
8,9.0,Clash of the Titans,Warner Bros.,Louis Leterrier,March 31,United States United Kingdom,"$14,556,322"
9,10.0,Despicable Me,Universal,Pierre Coffin & Chris Renaud,October 8,United States,"$14,257,017"

------------------------------
Set Verified: Historical and architectural interest bridges in South Africa
Entity Col:   Name
Entities:    ['Kaaimans River Bridge', 'Van Stadens River Railway Bridge', 'Oudtshoorn Suspension Bridge', 'Kaaimans River Railway Bridge', 'Alfred Beit Railway Bridge', 'Tsitsikamma Suspension Bridge', 'Oribi Gorge Suspension Bridge', 'Victoria & Alfred Waterfront Swing Bridge (1997) dismantled in 2019', 'Victoria & Alfred Waterfront Swing Bridge (2019)']
Table Data:

,Name,Distinction,Length,Type,Carries Crosses,Opened,Location,Province
0,Kaaimans River Bridge,Protected Site,,Arch Concrete deck arch,Seven Passes Road Kaaimans River,1904,George – Wilderness 33°58′15.8″S 22°32′51.9″E ...,Western Cape
1,Van Stadens River Railway Bridge,Second highest railway bridge in Africa when i...,197 m (646 ft),Truss Steel,Avontuur Railway Van Stadens River,1905,Thomhill 33°53′21.6″S 25°12′28.2″E ﻿ / ﻿ 33.88...,Eastern Cape
2,Oudtshoorn Suspension Bridge,Protected Site,,Suspension,Footbridge Kerk Street Grobbelaars River,1913,Oudtshoorn 33°35′17.1″S 22°12′3.7″E ﻿ / ﻿ 33.5...,Western Cape
3,Kaaimans River Railway Bridge,Crosses by Outeniqua Choo Tjoe,,Beam Steel,George – Knysna railway Kaaimans River,,Wilderness 33°59′52.2″S 22°33′25.5″E ﻿ / ﻿ 33....,Western Cape
4,Alfred Beit Railway Bridge,South Africa–Zimbabwe border,"473 m (1,552 ft)",Truss Steel,Railway bridge Limpopo River,1929,Musina – Beitbridge 22°13′27.8″S 29°59′13.2″E ...,Limpopo Zimbabwe
5,Tsitsikamma Suspension Bridge,,,Suspension Steel,Footbridge Storms River,1969,Tsitsikamma National Park 34°1′10.3″S 23°54′12...,Western Cape
6,Oribi Gorge Suspension Bridge,,80 m (260 ft),Suspension Steel,Footbridge Oribi Gorge,,Lake Eland Game Reserve 30°43′16.1″S 30°11′10....,KwaZulu-Natal
7,Victoria & Alfred Waterfront Swing Bridge (199...,Swing cable-stayed bridge,34 m (112 ft),"Cable-stayed Single tower, steel",Footbridge Victoria & Alfred Waterfront,1997,Le Cap 33°54′22.7″S 18°25′19.0″E ﻿ / ﻿ 33.9063...,Western Cape
8,Victoria & Alfred Waterfront Swing Bridge (2019),Swing cable-stayed bridge,40 m (130 ft),"Cable-stayed Single tower, steel",Footbridge Victoria & Alfred Waterfront,2019,Le Cap 33°54′22.6″S 18°25′19.1″E ﻿ / ﻿ 33.9062...,Western Cape

------------------------------
Set Verified: Migratory birds threatened, endangered and extinct species in the Mariana Islands
Entity Col:   Common name
Entities:    ['Short-tailed albatross', 'Far eastern curlew', 'Siberian sandplover', 'White-necked petrel', 'Juan Fernandez petrel', "Stejneger's petrel", 'Common pochard', 'Sharp-tailed sandpiper', "Leach's storm-petrel", "Matsudaira's storm-petrel", 'Bar-tailed godwit', 'Grey-tailed tattler']
Table Data:

,Common name,Scientific name,US Fish & Wildlife conservation status,IUCN Red List status,Notes
0,Short-tailed albatross,Phoebastria albatrus,Endangered (USFWS),Vulnerable (IUCN),"Native to North Pacific Ocean, mostly breeding..."
1,Far eastern curlew,Numenius madagascariensis,,Endangered (IUCN),"Breeds in eastern Asian Russia and Mongolia, b..."
2,Siberian sandplover,Charadrius mongolus,,Endangered (IUCN),"Breeds in Australia, New Zealand and Russia, w..."
3,White-necked petrel,Pterodroma cervicalis,,Vulnerable (IUCN),"Breeds in New Zealand, Norfolk Island and Vanu..."
4,Juan Fernandez petrel,Pterodroma externa,,Vulnerable (IUCN),"Breeds in Chile; extant in French Polynesia, G..."
5,Stejneger's petrel,Pterodroma longirostris,,Vulnerable (IUCN),"Breeds in Chile; extant in French Polynesia, G..."
6,Common pochard,Aythya ferina,,Vulnerable (IUCN),"Widespread in Europe, Asia and northern Africa..."
7,Sharp-tailed sandpiper,Calidris acuminata,,Vulnerable (IUCN),Breeds in Russia; extant in Asia and western P...
8,Leach's storm-petrel,Hydrobates leucorhous,,Vulnerable (IUCN),"Native throughout the oceans, non-breeding in ..."
9,Matsudaira's storm-petrel,Hydrobates matsudairae,,Vulnerable (IUCN),Breeds in Japan; migrates from eastern African...
10,Bar-tailed godwit,Limosa lapponica,,Near threatened (IUCN),"Breeds in Russia and Alaska, extant in numerou..."
11,Grey-tailed tattler,Tringa brevipes,,Near threatened (IUCN),"Breeds in Mongolia; extant in Southeast Asia, ..."

------------------------------
Set Verified: Artistic discontinued events rope climbing Olympic medalists in gymnastics (men)
Entity Col:   Games
Entities:    ['1896 Athens details', '1900 Paris', '1904 St. Louis details', '1908–1920', '1924 Paris details', '1924 Paris details', '1928 Amsterdam', '1932 Los Angeles details']
Table Data:

,Games,Gold,Silver,Bronze
0,1896 Athens details,Nicolaos Andriakopoulos Greece,Thomas Xenakis Greece,Fritz Hofmann Germany
1,1900 Paris,not included in the Olympic program,not included in the Olympic program,not included in the Olympic program
2,1904 St. Louis details,George Eyser United States,Charles Krause United States,Emil Voigt United States
3,1908–1920,not included in the Olympic program,not included in the Olympic program,not included in the Olympic program
4,1924 Paris details,Bedřich Šupčík Czechoslovakia,Albert Séguin France,August Güttinger Switzerland
5,1924 Paris details,Bedřich Šupčík Czechoslovakia,Albert Séguin France,Ladislav Vácha Czechoslovakia
6,1928 Amsterdam,not included in the Olympic program,not included in the Olympic program,not included in the Olympic program
7,1932 Los Angeles details,Raymond Bass United States,William Galbraith United States,Thomas F. Connolly United States

------------------------------
Set Verified: Second roster Freedom Fighters members
Entity Col:   Character
Entities:    ['Black Condor', 'Damage', 'Human Bomb', 'Iron Munro', 'The Patriot / Uncle Sam', 'Phantom Lady', 'The Ray']
Table Data:

,Character,Real name,First appearance,Notes
0,Black Condor,Ryan Kendall,JSA: Our Worlds at War #1 (September 2001),Former member of Primal Force . Apparent death...
1,Damage,Grant Emerson,JSA: Our Worlds at War #1 (September 2001),Former member of: Titans Young Justice Later m...
2,Human Bomb,Roy Lincoln,JSA: Our Worlds at War #1 (September 2001),Apparent death in Infinite Crisis #1 (October ...
3,Iron Munro,Arn Munro,JSA: Our Worlds at War #1 (September 2001),Former member of: Young All-Stars All-Star Squ...
4,The Patriot / Uncle Sam,N/A,JSA: Our Worlds at War #1 (September 2001),
5,Phantom Lady,Dee Tyler,JSA: Our Worlds at War #1 (September 2001),Apparent death in Infinite Crisis #1 (October ...
6,The Ray,Ray Terrill,JSA: Our Worlds at War #1 (September 2001),Former member of: Justice League Task Force Ju...

------------------------------
Set Verified: Scheduled airlines of the United Arab Emirates
Entity Col:   Airline
Entities:    ['Air Arabia', 'Air Arabia Abu Dhabi', 'Emirates', 'Etihad Airways', 'Flydubai']
Table Data:

,Airline,IATA,ICAO,Callsign,Commenced operations,Hub airport(s),Notes
0,Air Arabia,G9,ABY,ARABIA,2003,"Sharjah International Airport , Ras Al Khaimah...",Largest low-cost airline in the Middle East .
1,Air Arabia Abu Dhabi,3L,ABY,NAWRAS,2020,Zayed International Airport,Low-cost carrier of Abu Dhabi and a subsidiary...
2,Emirates,EK,UAE,EMIRATES,1985,Dubai International Airport,Largest airline in the Middle East .
3,Etihad Airways,EY,ETD,ETIHAD,2003,Zayed International Airport,Second largest airline in the United Arab Emir...
4,Flydubai,FZ,FDB,SKY DUBAI,2008,Dubai International Airport,Low-cost carrier of Dubai .

------------------------------
Set Verified: Alphabetical listing l-n works by William Merritt Chase
Entity Col:   Lady in a Pink Dress
Entities:    ['Landscape', 'Landscape, Near Coney Island', 'Landscape: Shinnecock, Long Island', 'The Lone Fisherman', 'Lydia Field Emmet', 'Lydia Field Emmet', 'Marianne Heyward Taylor', 'A Modern Magdalen', 'The Moorish Warrior', 'Morning at Breakwater, Shinnecock']
Table Data:

,Lady in a Pink Dress,c. 1892,"Westmoreland Museum of American Art , Greensburg, Pennsylvania"
0,Landscape,c. 1885,"Wright Museum of Art at Beloit College , Wisco..."
1,"Landscape, Near Coney Island",c. 1886,"Hyde Collection Art Museum , Glens Falls, New ..."
2,"Landscape: Shinnecock, Long Island",,"Princeton University Art Museum , New Jersey"
3,The Lone Fisherman,1890s,"Hood Museum of Art , Dartmouth College , New H..."
4,Lydia Field Emmet,1892,"Brooklyn Museum , New York City"
5,Lydia Field Emmet,c. 1892,"Detroit Institute of Arts , Michigan"
6,Marianne Heyward Taylor,c. 1902-06,"Columbia Museum of Art , South Carolina"
7,A Modern Magdalen,c. 1888,"Museum of Fine Arts , Boston, Massachusetts"
8,The Moorish Warrior,c. 1878,"Brooklyn Museum , New York City"
9,"Morning at Breakwater, Shinnecock",c. 1897,"Terra Museum of American Art , Chicago, Illinois"

------------------------------
Set Verified: Norfolk island defunct airlines of Oceania
Entity Col:   Airline
Entities:    ['Norfolk Air', 'Norfolk Island Airlines', 'Norfolk Island Airlines', 'Norfolk Jet Express']
Table Data:

,Airline,IATA,ICAO,Callsign,Commenced operations,Ceased operations,Notes
0,Norfolk Air,N5,NFK,NORFIK AIR,2005,2011,
1,Norfolk Island Airlines,UG,NIA,,1973,1992,
2,Norfolk Island Airlines,,,,2017,2018,Used Nauru Airlines aircraft
3,Norfolk Jet Express,YE,,,1997,2004,

------------------------------
Set Verified: State honors awards and nominations received by Tom Cruise
Entity Col:   Honor
Entities:    ['Medal of Honorary Citizen of Marseille', 'Honorary Member of the Patrol of France by French Air and Space Force', 'Knight of the Order of Arts and Letters by the Government of France', 'Certificate of Irish Heritage from the Department of Foreign Affairs', 'Honorary Citizen of Busan', 'Star on Hollywood Walk of Fame ( Motion Picture category )', "US Navy 's 36th Honorary Naval Aviator", "US Navy 's Distinguished Public Service Award"]
Table Data:

         Country  Year                                              Honor
0         France  2005             Medal of Honorary Citizen of Marseille
1         France  2022  Honorary Member of the Patrol of France by Fre...
2         France  2024  Knight of the Order of Arts and Letters by the...
3        Ireland  2013  Certificate of Irish Heritage from the Departm...
4    South Korea  2013                          Honorary Citizen of Busan
5  United States  1986  Star on Hollywood Walk of Fame ( Motion Pictur...
6  United States  2020             US Navy 's 36th Honorary Naval Aviator
7  United States  2024      US Navy 's Distinguished Public Service Award

------------------------------
Set Verified: J Cuban League baseball players (E–L)
Entity Col:   Name
Entities:    ['Bienvenido Jiménez', 'Eugenio Jiménez', 'Eusebio Jiménez', 'L. Jiménez', 'Sabino Jiménez', 'Chappie Johnson', 'Home Run Johnson', 'Heavy Johnson', 'Judy Johnson', 'Francisco Jordán', 'José Junco']
Table Data:

,Name,Debut,Last Game,Position,Teams
0,Bienvenido Jiménez,1912,1923,Second baseman / Shortstop,Habana / San Francisco Park / Almendares
1,Eugenio Jiménez,1897,1902,Unknown,Feista / Habana / San Francisco
2,Eusebio Jiménez,1922,1922,Third baseman,Habana
3,L. Jiménez,1910,1913,Catcher / Pitcher,Club Fé / Almendares
4,Sabino Jiménez,1901,1903,Second baseman,San Francisco
5,Chappie Johnson,1906,1906,Catcher,Habana
6,Home Run Johnson,1906,1911,Second baseman,Club Fé / Habana
7,Heavy Johnson,1923,1923,Second baseman,Leopardos de Santa Clara
8,Judy Johnson,1927,1927,Third baseman,Cuba
9,Francisco Jordán,1889,1890,Unknown,Progreso
10,José Junco,1909,1918,Pitcher / Outfielder,Club Fé / Habana / Cuban Stars (West)

------------------------------
Set Verified: Current americas diplomatic missions of Cyprus
Entity Col:   Mission
Entities:    ['Embassy', 'Embassy', 'High Commission', 'Embassy', 'Embassy', 'Consulate-General']
Table Data:

,Host country,Host city,Mission,Concurrent accreditation
0,Argentina,Buenos Aires,Embassy,Countries : Chile Paraguay Peru
1,Brazil,Brasília,Embassy,Countries : Bolivia Guyana Uruguay
2,Canada,Ottawa,High Commission,International Organizations : International Ci...
3,Cuba,Havana,Embassy,
4,United States,"Washington, D.C.",Embassy,Countries : Bahamas Barbados International Org...
5,United States,New York City,Consulate-General,Countries : Antigua and Barbuda Saint Kitts an...

------------------------------
Set Verified: The 1972: series 7 Sooty Show episodes
Entity Col:   Guests
Entities:    ['"Episode 1 Jimmy Jewel "', '"Episode 2 Nigel Pegram "', '"Episode 3 Larry Parker "', '"Episode 4 Matthew Corbett "', '"Episode 5 Roger Floss "', '"Episode 6 Ivor Emmanuel "', '"Episode 7 George Chisholm "', '"Episode 8 Billy Glass "', '"Episode 9 Gerry Marsden "', '"Episode 10 Janet Brown "', '"Episode 11 Ali Bongo "']
Table Data:

                          Guests                 Original airdate
0       "Episode 1 Jimmy Jewel "    4 January 1972 ( 1972-01-04 )
1      "Episode 2 Nigel Pegram "   11 January 1972 ( 1972-01-11 )
2      "Episode 3 Larry Parker "   18 January 1972 ( 1972-01-18 )
3   "Episode 4 Matthew Corbett "   25 January 1972 ( 1972-01-25 )
4       "Episode 5 Roger Floss "   1 February 1972 ( 1972-02-01 )
5     "Episode 6 Ivor Emmanuel "   8 February 1972 ( 1972-02-08 )
6   "Episode 7 George Chisholm "  15 February 1972 ( 1972-02-15 )
7       "Episode 8 Billy Glass "  22 February 1972 ( 1972-02-22 )
8     "Episode 9 Gerry Marsden "  29 February 1972 ( 1972-02-29 )
9      "Episode 10 Janet Brown "      7 March 1972 ( 1972-03-07 )
10       "Episode 11 Ali Bongo "     14 March 1972 ( 1972-03-14 )

------------------------------
Set Verified: List female members of the European Parliament for Malta
Entity Col:   Name
Entities:    ['Roberta Metsola', 'Marlene Mizzi', 'Claudette Abela Baldacchino', 'Therese Comodini Cachia', 'Miriam Dalli', 'Josianne Cutajar']
Table Data:

                          Name     National party EP group  Elected  Year left
0              Roberta Metsola  Nationalist Party      EPP     2013  Incumbent
1                Marlene Mizzi       Labour Party      S&D     2013       2019
2  Claudette Abela Baldacchino       Labour Party      S&D     2013       2014
3      Therese Comodini Cachia  Nationalist Party      EPP     2014       2017
4                 Miriam Dalli       Labour Party      S&D     2014       2020
5             Josianne Cutajar       Labour Party      S&D     2019       2024

------------------------------
Set Verified: Automotive industry companies of the Socialist Federal Republic of Yugoslavia
Entity Col:   Name
Entities:    ['IDA-Opel', 'Zavodi Crvena Zastava', 'Ikarus', 'Neobus', 'Maribor Automobile and Engine Factory (TAM)', 'Cimos', 'Sežana Motorcycle Factory (TOMOS)', 'Sarajevo Car Factory (TAS)', 'Zagreb Bus Factory (TAZ)', 'Priboj Car Factory (FAP)', 'FAS 11 Oktomvri (FAS Sanos)']
Table Data:

,Name,Headquarters,Republic/province,Established in,Operations/products
0,IDA-Opel,Kikinda,SR Serbia ( SAP Vojvodina ),1977,cars; 49% owned by General Motors
1,Zavodi Crvena Zastava,Kragujevac,SR Serbia,1904,Fiat cars and trucks
2,Ikarus,Zemun,SR Serbia,1923,buses
3,Neobus,Novi Sad,SR Serbia ( SAP Vojvodina ),1952,buses
4,Maribor Automobile and Engine Factory (TAM),Maribor,SR Slovenia,1946,trucks
5,Cimos,Koper,SR Slovenia,1972,cars; half owned by Citroën
6,Sežana Motorcycle Factory (TOMOS),Koper,SR Slovenia,1954,motorcycles and cars
7,Sarajevo Car Factory (TAS),Sarajevo,SR Bosnia and Herzegovina,1969,VW cars
8,Zagreb Bus Factory (TAZ),Zagreb,SR Croatia,1930,buses
9,Priboj Car Factory (FAP),Priboj,SR Serbia,1953,trucks and buses
10,FAS 11 Oktomvri (FAS Sanos),Skopje,SR Macedonia,1946,buses

------------------------------
Set Verified: Box office American films of 2006
Entity Col:   Title
Entities:    ["Pirates of the Caribbean: Dead Man's Chest", 'Night at the Museum', 'Cars', 'X-Men: The Last Stand', 'The Da Vinci Code', 'Superman Returns', 'Happy Feet', 'Ice Age: The Meltdown', 'Casino Royale', 'The Pursuit of Happyness']
Table Data:

,Rank,Title,Distributor,Domestic gross
0,1,Pirates of the Caribbean: Dead Man's Chest,Disney,"$423,315,812"
1,2,Night at the Museum,20th Century Fox,"$250,863,268"
2,3,Cars,Disney,"$244,082,982"
3,4,X-Men: The Last Stand,20th Century Fox,"$234,362,462"
4,5,The Da Vinci Code,Sony,"$217,536,138"
5,6,Superman Returns,Warner Bros.,"$200,081,192"
6,7,Happy Feet,Warner Bros.,"$198,000,317"
7,8,Ice Age: The Meltdown,20th Century Fox,"$195,330,621"
8,9,Casino Royale,Sony,"$167,445,960"
9,10,The Pursuit of Happyness,Sony,"$163,566,459"

------------------------------
Set Verified: 1990 Dutch films of the 1990s
Entity Col:   Title
Entities:    ['Alissa in Concert', 'Crocodiles in Amsterdam', 'In Krakende Welstand', 'De Gulle Minnaar', 'Han de Wit', 'Mijn Blauwen Hemel', 'Kracht', 'Romeo', 'Een Vreemde Liefde', 'Het Phoenix Mysterie', 'Spelen of Sterven']
Table Data:

,Title,Director,Cast,Genre,Notes
0,Alissa in Concert,Erik van Zuylen,,Music Drama,
1,Crocodiles in Amsterdam,Annette Apon,"Yolana Entius, Anette Apon",Comedy,
2,In Krakende Welstand,Mijke de Jong,Ottolien Boeschoten,Drama,
3,De Gulle Minnaar,Mady Saks,"Peter Faber , Mariska van Kolck",Comedy Drama,
4,Han de Wit,Joost Ranzijn,"Koen De Bouw , Nelly Frijda",Drama,
5,Mijn Blauwen Hemel,Ronald Beer,"Ruud de Wolf, Bo Bojoh",Drama,a.k.a. My Blue Heaven
6,Kracht,Frouke Fokkema,"Theu Boermans, Anneke Blok",Drama,
7,Romeo,Rita Horst,"Monique van de Ven, Johan Leysen",Drama,Entered into the 17th Moscow International Fil...
8,Een Vreemde Liefde,Pim de la Para,,,
9,Het Phoenix Mysterie,,Liz Snoyink,Drama,
10,Spelen of Sterven,Frank Krom,Geert Hunaerts,Drama,

------------------------------
Set Verified: Retired plants power stations in New York
Entity Col:   Owner, operator, or billing organization
Entities:    ['AES Eastern Energy, LP', 'AES Hickling LLC', 'Binghamton BOP, LLC', 'Cayuga Operating Company, LLC', 'Helix Ravenswood, LLC', 'NRG Power Marketing LLC', 'NRG Power Marketing LLC', 'NRG Power Marketing LLC', 'Somerset Operating Company, LLC']
Table Data:

,"Owner, operator, or billing organization",Plant name,Town or city,In-service date,Summer capability (MW),Winter capability (MW),Unit type,Primary fuel,Secondary fuel,2017 net energy (GWh),Notes
0,"AES Eastern Energy, LP",Westover 8,Union 42°06′41″N 75°58′26″W ﻿ / ﻿ 42.11139°N 7...,1951-12-01,0.0,0.0,Steam turbine,Bituminous coal,,,Retired in 2011
1,AES Hickling LLC,Hickling Power Station,Corning 42°07′21″N 76°58′57″W ﻿ / ﻿ 42.12250°N...,?,70.0,70.0,Steam turbine,Bituminous coal,,,Retired in 2000
2,"Binghamton BOP, LLC",Binghamton BOP,Binghamton,,43.7,47.1,,,,,Retired in 2018
3,"Cayuga Operating Company, LLC","Cayuga 1, 2, IC1, and IC2",Lansing 42°36′09″N 76°38′01″W ﻿ / ﻿ 42.60250°N...,1967-08-01,239.5,309.2,Steam turbine and internal combustion,Bituminous coal,Fuel oil (No. 2),220.2,"Plant ceased production on 8.29.2019, and was ..."
4,"Helix Ravenswood, LLC","Ravenswood 04, 05, and 06",Queens,,41.0,49.3,,,,,Mothballed in 2016
5,NRG Power Marketing LLC,"Astoria GT 05, GT 07, GT 08, GT 10, GT 11, GT ...",Queens,,104.7,136.6,,,,,Some mothballed and others forced outages in 2016
6,NRG Power Marketing LLC,Dunkirk Generating Station,Dunkirk 42°29′28″N 79°20′46″W ﻿ / ﻿ 42.49111°N...,1950-12-01,505.0,505.0,Steam turbine,Bituminous coal,,,"The last unit retired on January 1, 2016."
7,NRG Power Marketing LLC,Huntley Generating Station,Tonawanda 42°58′15″N 78°55′56″W ﻿ / ﻿ 42.97083...,1958-12-01,816.0,816.0,Steam turbine,Bituminous coal,,,The last units retired in 2016.
8,"Somerset Operating Company, LLC",Somerset,Somerset 43°21′29″N 78°36′14″W ﻿ / ﻿ 43.35806°...,1984-08-01,685.9,691.5,Steam turbine,Bituminous coal,,347.3,"Burned last coal on March 13, 2020, decommissi..."

------------------------------
Set Verified: Children's the numbers books on history of number systems
Entity Col:   Title
Entities:    ["Anno's Mysterious Multiplying Jar", 'The Librarian Who Measured the Earth', 'The History of Counting', 'Blockhead: The Life of Fibonacci', 'Count Like an Egyptian', 'Place Value', 'Who Owns the Numbers?']
Table Data:

,Author,Title,Year,Publisher / ISBN,Summary
0,Mitsumasa Anno,Anno's Mysterious Multiplying Jar,1983,Philomel Books,Introduces factorials through a visual and nar...
1,Kathryn Lasky,The Librarian Who Measured the Earth,1994,"Little, Brown and Company","Biography of Eratosthenes , who calculated Ear..."
2,Denise Schmandt-Besserat,The History of Counting,1999,HarperCollins,Chronicles the evolution of counting systems a...
3,Joseph D’Agnese,Blockhead: The Life of Fibonacci,2010,Henry Holt & Co.,Story of Fibonacci and his influence on number...
4,David Reimer,Count Like an Egyptian,2014,Princeton University Press,Engaging introduction to ancient Egyptian math...
5,David A. Adler,Place Value,2016,Holiday House,Child-friendly explanation of place value and ...
6,Nandini Chakrabarti,Who Owns the Numbers?,2022,Blueberry Illustrations,Simplified introduction to the history of our ...

------------------------------
Set Verified: Honorary awards and nominations received by Ian McKellen
Entity Col:   Ceremony
Entities:    ['Pride International Film Festival', 'Olivier Awards', 'Olivier Awards', 'Evening Standard Awards', 'Empire Awards', 'Istanbul International Film Festival']
Table Data:

,Year,Ceremony,Category
0,2004,Pride International Film Festival,Lifetime Achievement & Distinction Award
1,2006,Olivier Awards,Society's Special Award
2,2006,Olivier Awards,Society's Special Award
3,2009,Evening Standard Awards,The Lebedev Special Award
4,2010,Empire Awards,Empire Icon Award
5,2017,Istanbul International Film Festival,Honorary Award

------------------------------
Set Verified: List representatives ambassadors of Sweden to Moldova
Entity Col:   Name
Entities:    ['Jan Lundvik', 'Jan Lundvik', 'Göran Jacobsson', 'Nils Gunnar Revelius', 'Svante Kilander', 'Mats Åberg', 'Ingrid Tersman', 'Signe Burgstaller', 'Anna Lyberg', 'Katarina Fried', 'Petra Lärke']
Table Data:

,Name,Period,Title,Notes
0,Jan Lundvik,1992–1994,Ambassador,Resident in Berlin .
1,Jan Lundvik,1994–1998,Ambassador,Resident in Budapest .
2,Göran Jacobsson,1998–2000,Ambassador,Resident in Kiev .
3,Nils Gunnar Revelius,2000–2001,Ambassador,Resident in Bucharest .
4,Svante Kilander,2001–2006,Ambassador,Resident in Bucharest.
5,Mats Åberg,2006–2010,Ambassador,Resident in Bucharest.
6,Ingrid Tersman,2010–2015,Ambassador,
7,Signe Burgstaller,2015–2018,Ambassador,
8,Anna Lyberg,1 September 2018 – 2021,Ambassador,
9,Katarina Fried,2021–2025,Ambassador,
10,Petra Lärke,2025–present,Ambassador,

------------------------------
Set Verified: O lakes of Western Australia, L–P
Entity Col:   Name
Entities:    ["Lake O'Connor", 'Oaljalup Lake', 'Old Station Billabong', 'One Tree Billabong', 'Lake Ottaway']
Table Data:

                    Name                                        Coordinates
0          Lake O'Connor  32°29′S 119°13′E ﻿ / ﻿ 32.483°S 119.217°E ﻿ / ...
1          Oaljalup Lake  34°18′S 116°25′E ﻿ / ﻿ 34.300°S 116.417°E ﻿ / ...
2  Old Station Billabong  15°40′S 128°41′E ﻿ / ﻿ 15.667°S 128.683°E ﻿ / ...
3     One Tree Billabong  18°28′S 125°27′E ﻿ / ﻿ 18.467°S 125.450°E ﻿ / ...
4           Lake Ottaway  33°12′S 119°4′E ﻿ / ﻿ 33.200°S 119.067°E ﻿ / -...

------------------------------
Set Verified: List representatives ambassadors of Georgia to the United States
Entity Col:   ambassador
Entities:    ['Peter Chkheidze', 'Tedo Japaridze', 'Levan Mikeladze', 'Vasil Sikharulidze', 'Batu Kutelia', 'Temur Iakobashvili', 'Archil Gegeshidze', 'Giorgi Tsikolia', 'Giorgi Khelashvili', 'Davit Bakradze', 'David Zalkaliani', 'Tamar Taliashvili']
Table Data:

,Diplomatic agrément,Diplomatic accreditation,ambassador,Prime Minister of Georgia,President of the United States
0,"June 14, 1993","September 3, 1993",Peter Chkheidze,Eduard Shevardnadze,Bill Clinton
1,"December 7, 1994","January 30, 1995",Tedo Japaridze,Otar Patsatsia,Bill Clinton
2,"June 28, 2002","July 30, 2002",Levan Mikeladze,Avtandil Jorbenadze,George W. Bush
3,"March 9, 2006","March 13, 2006",Vasil Sikharulidze,Zurab Noghaideli,George W. Bush
4,"March 19, 2009","May 20, 2009",Batu Kutelia,Nika Gilauri,Barack Obama
5,"February 15, 2011","February 23, 2011",Temur Iakobashvili,Nika Gilauri,Barack Obama
6,"April 12, 2013","April 15, 2013",Archil Gegeshidze,Irakli Garibashvili,Barack Obama
7,2015,,Giorgi Tsikolia,Giorgi Kvirikashvili,Barack Obama
8,2015,,Giorgi Khelashvili,Giorgi Kvirikashvili,Barack Obama
9,2016,,Davit Bakradze,Giorgi Kvirikashvili,Donald Trump
10,"April 4, 2022",,David Zalkaliani,Irakli Garibashvili,Joe Biden
11,"June 10, 2025",,Tamar Taliashvili,Irakli Kobakhidze,Donald Trump

------------------------------
Set Verified: Iheartradio music awards and nominations received by the Jonas Brothers
Entity Col:   Award
Entities:    ['Song of the Year', 'Best Music Video', 'Best Duo/Group of the Year', 'Best Duo/Group of the Year', 'Favorite Tour Style', 'Best Duo/Group of the Year', 'Favorite On Screen', 'Favorite Tour Tradition', 'Favorite Soundtrack']
Table Data:

,Year,Nominee / work,Award,Result
0,2020,""" Sucker """,Song of the Year,Nominated
1,2020,""" Sucker """,Best Music Video,Nominated
2,2020,Themselves,Best Duo/Group of the Year,Won
3,2021,Themselves,Best Duo/Group of the Year,Nominated
4,2024,Themselves,Favorite Tour Style,Nominated
5,2024,Themselves,Best Duo/Group of the Year,Nominated
6,2026,Themselves,Favorite On Screen,Nominated
7,2026,Jonas20: Greetings from Your Hometown Tour : S...,Favorite Tour Tradition,Nominated
8,2026,A Very Jonas Christmas Movie (Original Soundtr...,Favorite Soundtrack,Nominated

------------------------------
Set Verified: Box office collection Marathi films of 2017
Entity Col:   Film
Entities:    ['Sachin: A Billion Dreams', 'Ti Saddhya Kay Karte', 'FU: Friendship Unlimited', 'Boyz', 'Faster Fene', 'Muramba', 'Fugay']
Table Data:

   Rank                      Film                 Worldwide gross
0     1  Sachin: A Billion Dreams  ₹ 76.86 crore (US$9.1 million)
1     2      Ti Saddhya Kay Karte  ₹ 22.54 crore (US$2.7 million)
2     3  FU: Friendship Unlimited      ₹ 9 crore (US$1.1 million)
3     4                      Boyz       ₹ 8.40 crore (US$990,000)
4     5               Faster Fene          ₹ 8 crore (US$950,000)
5     6                   Muramba          ₹ 7 crore (US$830,000)
6     7                     Fugay          ₹ 4 crore (US$470,000)

------------------------------
Set Verified: Current multilateral organizations diplomatic missions of Slovakia
Entity Col:   Organization
Entities:    ['Council of Europe', 'European Union', 'NATO', 'OECD', 'UNESCO', 'United Nations', 'United Nations', 'United Nations']
Table Data:

,Organization,Host city,Host country,Mission,Concurrent accreditation
0,Council of Europe,Strasbourg,France,Permanent Mission,
1,European Union,Brussels,Belgium,Permanent Representation,
2,NATO,Brussels,Belgium,Permanent Delegation,
3,OECD,Paris,France,Permanent Mission,
4,UNESCO,Paris,France,Permanent Delegation,
5,United Nations,New York City,United States,Permanent Mission,
6,United Nations,Geneva,Switzerland,Permanent Mission,International Organizations : Conference on Di...
7,United Nations,Vienna,Austria,Permanent Mission,International Organizations : OSCE Internation...

------------------------------
Set Verified: Tamil nadu state film awards and nominations received by K. Balachander
Entity Col:   Film
Entities:    ['Ethir Neechal , Thamarai Nenjam', 'Thappu Thalangal', 'Varumayin Niram Sivappu', 'Agni Sakshi', 'Pudhu Pudhu Arthangal', 'Pudhu Pudhu Arthangal', 'Vaaname Ellai', 'Vaaname Ellai', 'Roja', 'Jathi Malli', 'Various films']
Table Data:

,Year,Film,Category,Outcome
0,1968,"Ethir Neechal , Thamarai Nenjam",Best Dialogue Writer,Won
1,1978,Thappu Thalangal,Best Dialogue Writer,Won
2,1980,Varumayin Niram Sivappu,Best Director,Won
3,1982,Agni Sakshi,Best Film (Second prize),Won
4,1989,Pudhu Pudhu Arthangal,Best Director,Won
5,1989,Pudhu Pudhu Arthangal,Best Film (Second prize),Won
6,1992,Vaaname Ellai,Story Writer,Won
7,1992,Vaaname Ellai,Special Prize (Best Film),Won
8,1992,Roja,Best Film (First prize),Won
9,1993,Jathi Malli,Best Film (First prize),Won
10,1990,Various films,Tamil Nadu State Film Honorary Award,Won

------------------------------
Set Verified: Current cgas s Commonwealth Sport country codes
Entity Col:   Code
Entities:    ['SAM', 'SCO', 'SEY', 'SHN', 'SGP', 'SKN', 'SLE', 'SOL', 'SRI', 'SVG', 'SWZ']
Table Data:

   Code                      Nation (CGA) Other codes used
0   SAM                             Samoa
1   SCO                          Scotland
2   SEY                        Seychelles
3   SHN                      Saint Helena       SHE (2006)
4   SGP                         Singapore  SIN (1965–2016)
5   SKN             Saint Kitts and Nevis       SCN (1978)
6   SLE                      Sierra Leone
7   SOL                   Solomon Islands
8   SRI                         Sri Lanka  CEY (1938–1970)
9   SVG  Saint Vincent and the Grenadines
10  SWZ         Swaziland (now Eswatini )

------------------------------
Set Verified: Critics awards and nominations received by Stanley Tucci
Entity Col:   Category
Entities:    ['Boston Society of Film Critics Best New Director', 'Boston Society of Film Critics Award for Best Screenplay', 'New York Film Critics Circle Award for Best New Director', 'Chicago Film Critics Association Award for Best Screenplay', 'Broadcast Film Critics Association Award for Best Supporting Actor', 'Chicago Film Critics Association Award for Best Supporting Actor', 'Dallas–Fort Worth Film Critics Association Award for Best Supporting Actor', 'Boston Society of Film Critics Award for Best Supporting Actor', 'Detroit Film Critics Society Award for Best Supporting Actor']
Table Data:

,Year,Category,Nominated work,Result
0,1996,Boston Society of Film Critics Best New Director,Big Night,Won
1,1996,Boston Society of Film Critics Award for Best ...,Big Night,Won
2,1996,New York Film Critics Circle Award for Best Ne...,Big Night,Won
3,1996,Chicago Film Critics Association Award for Bes...,Big Night,Nominated
4,2009,Broadcast Film Critics Association Award for B...,The Lovely Bones,Nominated
5,2009,Chicago Film Critics Association Award for Bes...,The Lovely Bones,Nominated
6,2009,Dallas–Fort Worth Film Critics Association Awa...,The Lovely Bones,3rd place
7,2009,Boston Society of Film Critics Award for Best ...,Julie & Julia,2nd place
8,2013,Detroit Film Critics Society Award for Best Su...,The Hunger Games: Catching Fire,Nominated

------------------------------
Set Verified: I power metal bands
Entity Col:   Name
Entities:    ['Iced Earth', 'Ilium', 'Imperial Age', 'Impulse', 'Into Eternity', 'Ion Vein', 'Iron Fire', 'Iron Maiden', 'Iron Mask', 'Iron Savior']
Table Data:

,Name,Origin,Years active,Brief summary,Note
0,Iced Earth,United States,1985–present,Successful band that has played many different...,
1,Ilium,Australia,1998–present,In 2012 they recorded a music video dedicated ...,: 209
2,Imperial Age,Russia,2012−present,Imperial Age have three singers (one male and ...,
3,Impulse,Bulgaria,"1979–1991, 1995–1998, 2012-present",One of the first Bulgarian heavy metal bands.,
4,Into Eternity,Canada,1997−present,Progressive/melodic death with a bit of power ...,
5,Ion Vein,United States,1995–present,Progressive/Power metal band from Chicago.,": 211,212"
6,Iron Fire,Denmark,1995–present,Early speed metal style incorporated with rece...,
7,Iron Maiden,England,1975–present,"Not considered Power Metal, but often listed a...",
8,Iron Mask,Belgium,2002–present,Contains ex- Yngwie Malmsteen members.,
9,Iron Savior,Germany,1996–present,Blends power metal with a high-concept science...,

------------------------------
Set Verified: List candidate rogue planets exoplanets detected by microlensing
Entity Col:   Planet
Entities:    ['MOA-2011-BLG-274L', 'OGLE-2016-BLG-1540L', 'OGLE-2012-BLG-1323L', 'OGLE-2017-BLG-0560L', 'OGLE-2019-BLG-0551L', 'KMT-2019-BLG-2073L', 'OGLE-2016-BLG-1928L', 'KMT-2017-BLG-2820L']
Table Data:

                Planet           Mass  Year of discovery
0    MOA-2011-BLG-274L  0.8 ± 0.3 M J               2014
1  OGLE-2016-BLG-1540L        ~35 M 🜨               2017
2  OGLE-2012-BLG-1323L       ~2.3 M 🜨               2018
3  OGLE-2017-BLG-0560L       ~1.9 M J               2018
4  OGLE-2019-BLG-0551L       ~7.7 M 🜨               2020
5   KMT-2019-BLG-2073L        ~59 M 🜨               2020
6  OGLE-2016-BLG-1928L       ~0.3 M 🜨               2020
7   KMT-2017-BLG-2820L       ~8.2 M 🜨               2020

------------------------------
Set Verified: Highest grossing Kannada films of 2002
Entity Col:   Title
Entities:    ['Hollywood', 'Appu', 'Simhadriya Simha', 'H2O', 'Thavarige Baa Thangi']
Table Data:

   Rank                 Title                         Collection
0   1.0             Hollywood  ₹38 crore (₹161.33 crore in 2025)
1   2.0                  Appu  ₹27 crore (₹114.62 crore in 2025)
2   3.0      Simhadriya Simha   ₹19 crore (₹80.66 crore in 2025)
3   4.0                   H2O   ₹10 crore (₹42.45 crore in 2025)
4   5.0  Thavarige Baa Thangi    ₹6 crore (₹25.47 crore in 2025)

------------------------------
Set Verified: 1980s T-Series films
Entity Col:   Film
Entities:    ['Lal Dupatta Malmal Ka', 'Phir Lehraya Lal Dupatta Malmal Ka', 'Abhi To Main Jawan Hoon', 'Gawaahi']
Table Data:

,Year,Film,Actors
0,1989,Lal Dupatta Malmal Ka,"Sahil Chaddha, Veverly"
1,1989,Phir Lehraya Lal Dupatta Malmal Ka,"Sahil Chaddha, Veverly"
2,1989,Abhi To Main Jawan Hoon,
3,1989,Gawaahi,"Zeenat Aman , Shekhar Kapur , Ranjeeta Kaur , ..."

------------------------------
Set Verified: Highest mountains in Georgia (U.S. state)
Entity Col:   Summit
Entities:    ['Brasstown Bald', 'Rabun Bald', "Dick's Knob", 'Hightower Bald', 'Wolfpen Ridge', 'Blood Mountain', 'Tray Mountain', 'Grassy Ridge', 'Slaughter Mountain', 'Double Spring Knob', 'Coosa Bald']
Table Data:

,Rank,Summit,County,Elevation,Prominence,Isolation,Location
0,1,Brasstown Bald,"Towns , Union","4,784 ft 1458 m","2,108 ft 643 m",15.93 mi 25.6 km,34°52′27″N 83°48′38″W ﻿ / ﻿ 34.874199°N 83.810...
1,2,Rabun Bald,Rabun,"4,696 ft 1431 m","1,016 ft 310 m",5.01 mi 8.06 km,34°57′56″N 83°18′00″W ﻿ / ﻿ 34.965556°N 83.300...
2,3,Dick's Knob,Rabun,"4,600 ft 1402 m",160 ft 49 m,0.91 mi 1.46 km,34°59′08″N 83°31′18″W ﻿ / ﻿ 34.985556°N 83.521...
3,4,Hightower Bald,Towns,"4,568 ft 1392 m",808 ft 246 m,2.38 mi 3.83 km,34°59′05″N 83°37′13″W ﻿ / ﻿ 34.984696°N 83.620...
4,5,Wolfpen Ridge,Towns / Union,"4,561 ft 1390 m",201 ft 61 m,0.72 mi 1.16 km,34°51′49″N 83°48′31″W ﻿ / ﻿ 34.863744°N 83.808...
5,6,Blood Mountain,Lumpkin / Union,"4,458 ft 1359 m","1,480 ft 451 m",11.24 mi 18.09 km,34°44′23″N 83°56′14″W ﻿ / ﻿ 34.73983°N 83.9371...
6,7,Tray Mountain,Towns / White,"4,430 ft 1350 m","1,481 ft 451 m",8.3 mi 13.36 km,34°48′04″N 83°41′02″W ﻿ / ﻿ 34.8012°N 83.68378...
7,8,Grassy Ridge,Rabun,"4,400 ft 1341 m",231 ft 70 m,1.04 mi 1.67 km,34°59′01″N 83°28′59″W ﻿ / ﻿ 34.983682°N 83.483...
8,9,Slaughter Mountain,Union,"4,338 ft 1322 m",458 ft 140 m,0.94 mi 1.51 km,34°44′53″N 83°57′01″W ﻿ / ﻿ 34.748055°N 83.950...
9,10,Double Spring Knob,Rabun / Towns,"4,280 ft 1305 m",920 ft 280 m,5.54 mi 8.92 km,34°52′42″N 83°39′24″W ﻿ / ﻿ 34.878472°N 83.656...
10,10,Coosa Bald,Union,"4,280 ft 1305 m",960 ft 293 m,2.25 mi 3.62 km,34°46′44″N 83°57′48″W ﻿ / ﻿ 34.778891°N 83.963...

------------------------------
Set Verified: List representatives ambassadors of China to Ivory Coast
Entity Col:   Name (English)
Entities:    ['Xing Geng', 'Zhu Chengcai', 'Cai Zaidu', 'Liu Lide', 'Zhao Baozhen', 'Ma Zhixue', 'Wei Wenhua', 'Zhang Guoqing', 'Tang Weibin', 'Wan Li']
Table Data:

,Name (English),Name (Chinese),Tenure begins,Tenure ends,Note
0,Xing Geng,邢耿,August 1983,February 1984,Chargé d'affaires
1,Zhu Chengcai,祝成才,February 1984,April 1988,
2,Cai Zaidu,蔡再杜,May 1988,August 1993,
3,Liu Lide,刘立德,September 1993,March 1999,
4,Zhao Baozhen,赵宝珍,April 1999,November 2003,
5,Ma Zhixue,马志学,November 2003,July 2007,
6,Wei Wenhua,魏文华,November 2007,January 20125,
7,Zhang Guoqing,张国庆,February 2012,26 June 2015,
8,Tang Weibin,唐卫斌,June 2015,April 2019,
9,Wan Li,万黎,May 2019,December 2022,

------------------------------
Set Verified: Bergen domprosti churches in Bjørgvin
Entity Col:   Church
Entities:    ['Bergen Cathedral', 'Church of the Cross', "St. Jacob's Church", "St. George's Hospital Church", "St. John's Church", "St. Maria's Church", 'New Church', 'Laksevåg Church', 'Loddefjord Church', 'Nygård Church', 'Olsvik Church', 'Sandvik Church']
Table Data:

,Municipality,Parish ( sokn ),Church,Location,Year built
0,Bergen,Bergen domkirke,Bergen Cathedral,Bergen,begun ca. 1250
1,Bergen,Bergen domkirke,Church of the Cross,Bergen,late 12th century
2,Bergen,Bergen domkirke,St. Jacob's Church,Nygård,1921
3,Bergen,Bergen domkirke,St. George's Hospital Church,Bergen,1702
4,Bergen,Bergen domkirke,St. John's Church,Sydnes,1894
5,Bergen,Bergen domkirke,St. Maria's Church,Bergenhus,after 1140
6,Bergen,Bergen domkirke,New Church,Nordnes,1763
7,Bergen,Laksevåg,Laksevåg Church,Laksevåg,1875
8,Bergen,Loddefjord,Loddefjord Church,Loddefjord,1926
9,Bergen,Nygård,Nygård Church,Gravdal,1972
10,Bergen,Olsvik,Olsvik Church,Olsvik,1990
11,Bergen,Sandviken,Sandvik Church,Sandviken,1881

------------------------------
Set Verified: Americas diplomatic missions of Ivory Coast
Entity Col:   Mission
Entities:    ['Embassy', 'Embassy', 'Embassy', 'Embassy', 'Consulate-General']
Table Data:

,Host country,Host city,Mission,Concurrent accreditation
0,Brazil,Brasília,Embassy,Countries : Argentina Bolivia Chile Colombia E...
1,Canada,Ottawa,Embassy,
2,Mexico,Mexico City,Embassy,Countries : Belize Costa Rica Cuba El Salvador...
3,United States,Washington D.C.,Embassy,Countries : Bahamas Trinidad and Tobago
4,United States,New York City,Consulate-General,Countries : Bahamas Trinidad and Tobago

------------------------------
Set Verified: Emmy creative arts emmy awards and nominations received by Lou Grant
Entity Col:   Category
Entities:    ['Outstanding Achievement in Film Sound Editing for a Series', 'Outstanding Film Editing for a Series', 'Outstanding Music Composition for a Series', 'Outstanding Music Composition for a Series (Dramatic Underscore)', 'Outstanding Achievement in Film Editing for a Series', 'Outstanding Achievement in Hairstyling', 'Outstanding Achievement in Music Composition for a Series (Dramatic Underscore)', 'Outstanding Cinematography for a Series', 'Outstanding Achievement in Music Composition for a Series (Dramatic Underscore)']
Table Data:

,Year,Category,Nominee(s),Episodes(s),Result
0,1978,Outstanding Achievement in Film Sound Editing ...,"Ron Clark, Tony Garber, and Dale Johnston","for ""Nazi""",Nominated
1,1979,Outstanding Film Editing for a Series,James Galloway,"for ""Hooker""",Nominated
2,1979,Outstanding Music Composition for a Series,Patrick Williams,"for ""Prisoner""",Nominated
3,1980,Outstanding Music Composition for a Series (Dr...,Patrick Williams,"for ""Hollywood""",Won
4,1981,Outstanding Achievement in Film Editing for a ...,James Galloway,"for ""Strike""",Nominated
5,1981,Outstanding Achievement in Hairstyling,Jean Austin,"for ""Stroke""",Nominated
6,1981,Outstanding Achievement in Music Composition f...,Patrick Williams,"for ""Stroke""",Nominated
7,1982,Outstanding Cinematography for a Series,Robert F. Liu,"for ""Ghosts""",Nominated
8,1982,Outstanding Achievement in Music Composition f...,Patrick Williams,"for ""Stroke""",Nominated

------------------------------
Set Verified: Captains Western Sydney Wanderers FC players
Entity Col:   Captain
Entities:    ['Michael Beauchamp ( AUS )', 'Nikolai Topor-Stanley ( AUS )', 'Dimas ( ESP )', 'Robert Cornthwaite ( AUS )', 'Brendan Hamill ( AUS )', 'Mitchell Duke ( AUS )', 'Dylan McGowan ( AUS )']
Table Data:

       Dates                        Captain
0  2012–2014      Michael Beauchamp ( AUS )
1  2014–2016  Nikolai Topor-Stanley ( AUS )
2  2016–2017                  Dimas ( ESP )
3  2017–2018     Robert Cornthwaite ( AUS )
4  2018–2019         Brendan Hamill ( AUS )
5  2019–2020          Mitchell Duke ( AUS )
6      2020–          Dylan McGowan ( AUS )

------------------------------
Set Verified: As Star Studio18 films
Entity Col:   Title
Entities:    ['Jolly LLB 3', 'Single Salma', 'Kis Kisko Pyaar Karoon 2', 'The Great Shamsuddin Family ‡']
Table Data:

,Release date,Title,Language,Director,Notes
0,19 September 2025,Jolly LLB 3,Hindi,Subhash Kapoor,co-production with Kangra Talkies; first film ...
1,31 October 2025,Single Salma,Hindi,Nachiket Samant,co-production with Elemen3 Entertainment
2,12 December 2025,Kis Kisko Pyaar Karoon 2,Hindi,Anukalp Goswami,co-production with Venus Worldwide Entertainme...
3,12 December 2025,The Great Shamsuddin Family ‡,Hindi,Anusha Rizvi,co-production with Third World Films Productio...

------------------------------
Set Verified: List heads mission ambassadors of Malaysia to Morocco
Entity Col:   Ambassador
Entities:    ['Bakri Ayub Ghazali', 'K. Nadarajah Nagalingam', 'Yusof Hashim', 'Idris Zainuddin', 'Siddiq Firdause Mohd Ali', 'Mohd Nor Atan', 'Othman Samin', 'Jamal Hassan', 'Astanah Banu Shri Abdul Aziz']
Table Data:

                     Ambassador         Term start           Term end
0            Bakri Ayub Ghazali     10 August 1989     5 October 1992
1       K. Nadarajah Nagalingam   19 February 1992  22 September 1993
2                  Yusof Hashim  26 September 1994       10 July 1996
3               Idris Zainuddin   12 December 1996       29 June 1999
4      Siddiq Firdause Mohd Ali      9 August 2000      2 August 2001
5                 Mohd Nor Atan    1 February 2002   30 November 2005
6                  Othman Samin               2007               2010
7                  Jamal Hassan        8 July 2011   2 September 2017
8  Astanah Banu Shri Abdul Aziz               2017          Incumbent

------------------------------
Set Verified: Historical and architectural interest bridges in Bhutan
Entity Col:   Name
Entities:    ['Tamchog Chakzam rebuilt in 2005', 'Punakha Bridge  rebuilt in 2008', 'Nemi Zam', 'Wangdue Zam destroyed in 1968', 'Dotanang Covered Bridge', 'Kuendeyling Baazam', 'Langjo Bridge', 'Changjiji Bridge', 'Punakha Suspension Bridge']
Table Data:

,Name,Dzongkha,Distinction,Length,Type,Carries Crosses,Opened,Location,District
0,Tamchog Chakzam rebuilt in 2005,,Built by Thang Tong Gyalpo,,"Suspension Chain bridge , masonry towers",Footbridge Paro Chhu,1433,Tamchog Lhakhang 27°19′46.7″N 89°30′16.7″E ﻿ /...,Paro District
1,Punakha Bridge rebuilt in 2008,Puna Mochhu Bazam,Span : 55 m (180 ft) Punakha Dzong,73 m (240 ft),"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Mo Chhu,1637,Punakha 27°34′59.8″N 89°51′42.4″E ﻿ / ﻿ 27.583...,Punakha District
2,Nemi Zam,,Rinpung Dzong,24 m (79 ft),"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Paro Chhu,18th century,Paro 27°25′29.1″N 89°25′18.7″E ﻿ / ﻿ 27.424750...,Paro District
3,Wangdue Zam destroyed in 1968,,Constructed without using single piece of iron...,,"Covered bridge Cantilever wooden beam, 3 mason...",Footbridge Sankosh River,18th century,Wangdue Phodrang 27°28′29.1″N 89°53′42.7″E ﻿ /...,Wangdue Phodrang District
4,Dotanang Covered Bridge,,,46 m (151 ft),"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Raidāk River (Wang Chhu),19th century,Dotanang 27°35′37.0″N 89°37′45.1″E ﻿ / ﻿ 27.59...,Thimphu District
5,Kuendeyling Baazam,,,,"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Raidāk River (Wang Chhu),,Thimphu 27°28′30.4″N 89°38′32.3″E ﻿ / ﻿ 27.475...,Thimphu District
6,Langjo Bridge,,Tashichho Dzong,,"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Raidāk River (Wang Chhu),,Thimphu 27°29′30.7″N 89°38′09.0″E ﻿ / ﻿ 27.491...,Thimphu District
7,Changjiji Bridge,,,29 m (95 ft),"Covered bridge Cantilever wooden beam, 2 mason...",Footbridge Raidāk River (Wang Chhu),2007,Thimphu 27°27′22.4″N 89°38′56.2″E ﻿ / ﻿ 27.456...,Thimphu District
8,Punakha Suspension Bridge,,,,Suspension Steel,Footbridge Pho Chhu,,Punakha 27°35′20.3″N 89°52′11.8″E ﻿ / ﻿ 27.588...,Punakha District

------------------------------
Set Verified: Royal television society awards and nominations received by Holby City
Entity Col:   Award ceremony
Entities:    ['Craft and Design Awards', 'Programme Awards', 'Programme Awards', 'Programme Awards', 'Programme Awards']
Table Data:

,Year,Award ceremony,Category,Nominee,Result
0,2000,Craft and Design Awards,Best Graphic Design – Titles,"Sean De Sparengo, Richard Gort",Nominated
1,2007,Programme Awards,Soap and Continuing Drama,Holby City,Nominated
2,2008,Programme Awards,Soap and Continuing Drama,Holby City,Nominated
3,2018,Programme Awards,Soap and Continuing Drama,Holby City,Nominated
4,2021,Programme Awards,Soap and Continuing Drama,Holby City,Nominated

------------------------------
Set Verified: National general newspapers in Indonesia
Entity Col:   Name
Entities:    ['Jawa Pos', 'Kompas', 'Koran Jakarta', 'Koran Tempo', 'Media Indonesia', 'Rakyat Merdeka']
Table Data:

,Name,Format,First published,Owner,Circulation readership,Notes
0,Jawa Pos,Broadsheet / Tabloid,1949,Jawa Pos Group,450000,
1,Kompas,Broadsheet,1965,Kompas Gramedia Group,880990,
2,Koran Jakarta,Broadsheet,2008,PT Berita Nusantara,,
3,Koran Tempo,Tabloid,2001,Tempo Inti Media,,Digital-only format
4,Media Indonesia,Broadsheet,1970,Media Group,250000,
5,Rakyat Merdeka,Broadsheet,1997,Jawa Pos Group,,Political news daily

------------------------------
Set Verified: Dubbed Malayalam films of 1978
Entity Col:   Movie
Entities:    ['Kaadu Njangalude Veedu', 'Anthony Punnyavaalan', 'Parassuraman', 'Shilayugathile Sundharikal', 'Aaru Manikkoor', 'Prathyaksha Deivam', 'Mishiha Charithram']
Table Data:

                        Movie      Direction
0      Kaadu Njangalude Veedu     R. S. Babu
1        Anthony Punnyavaalan
2                Parassuraman      C. S. Rao
3  Shilayugathile Sundharikal  G. R. Moorthy
4              Aaru Manikkoor  Devaraj Mohan
5          Prathyaksha Deivam      K. Sankar
6          Mishiha Charithram   A. Bhimsingh

------------------------------
Set Verified: Fourth republic senators of Doubs
Entity Col:   Name
Entities:    ['Georges Pernot', 'Georges Reverbori', 'Lucien Tharradin', 'Louis Maillot']
Table Data:

,In office,Name,Party
0,1946-1958,Georges Pernot,Republican Party of Liberty (PRL)
1,1946 - 1948,Georges Reverbori,French Section of the Workers' International (...
2,1948 - 1957,Lucien Tharradin,Rally of the French People (RPF)
3,1957 - 1958,Louis Maillot,Républicains indépendants (RI)

------------------------------
Set Verified: People's state presidents of the Landtag of Hesse
Entity Col:   Name
Entities:    ['Bernhard Adelung', 'Heinrich Delp', 'Ferdinand Werner', 'Philipp Jung']
Table Data:

               Name     Period  Party
0  Bernhard Adelung  1919–1928    SPD
1     Heinrich Delp  1928–1931    SPD
2  Ferdinand Werner  1931–1933  NSDAP
3      Philipp Jung       1933  NSDAP

------------------------------
Set Verified: Fossil-fuel natural gas and petroleum power stations in Montana
Entity Col:   Name
Entities:    ['Basin Creek Generation Plant', 'Culbertson Generation Station', 'Dave Gates Generating Station', 'Glendive Gas Turbine', 'Lewis & Clark 2', 'Miles City Gas Turbine', 'OREG 1 & 2', 'Phillips 66 Billings Refinery', 'Yellowstone Energy']
Table Data:

,Name,Location,Coordinates,Capacity ( MW ),Fuel type,Generation type,Year opened
0,Basin Creek Generation Plant,Silver Bow County,45°55′45″N 112°31′10″W ﻿ / ﻿ 45.9293°N 112.519...,54.0,Gas,Reciprocating engine (x9),2006
1,Culbertson Generation Station,Roosevelt County,48°12′36″N 104°23′30″W ﻿ / ﻿ 48.2100°N 104.391...,85.0,Gas,Simple cycle,2010
2,Dave Gates Generating Station,Deer Lodge County,46°06′17″N 112°52′36″W ﻿ / ﻿ 46.1047°N 112.876...,150.0,Gas,Simple cycle (x3),2011
3,Glendive Gas Turbine,Dawson County,47°03′14″N 104°44′24″W ﻿ / ﻿ 47.0539°N 104.740...,75.0,Gas,Simple cycle (x2),1979/2003
4,Lewis & Clark 2,Richland County,47°40′45″N 104°09′36″W ﻿ / ﻿ 47.6791°N 104.160...,19.0,Gas,Internal combustion (x2),2015
5,Miles City Gas Turbine,Custer County,46°24′40″N 105°47′43″W ﻿ / ﻿ 46.4112°N 105.795...,24.0,Gas,Simple cycle,1972
6,OREG 1 & 2,Roosevelt County,48°12′51″N 104°23′51″W ﻿ / ﻿ 48.2141°N 104.397...,40.0,Waste heat from gas compressor turbine,ORC generator (x8),2006/2009
7,Phillips 66 Billings Refinery,Yellowstone County,45°46′37″N 108°29′28″W ﻿ / ﻿ 45.7769°N 108.491...,1.5,Petroleum gases,Steam turbine,2007
8,Yellowstone Energy,Yellowstone County,45°48′42″N 108°25′40″W ﻿ / ﻿ 45.8117°N 108.427...,52.0,Petroleum,Steam turbine,1995

------------------------------
Set Verified: List supplementary fujian members of the first Legislative Yuan
Entity Col:   Elected member
Entities:    ['Wu Chin-tzan', 'Wu Chin-tzan', 'Wu Chin-tzan', 'Wu Chin-tzan', 'Wu Chin-tzan', 'Huang Wuu-ran']
Table Data:

   Election Elected member
0      1972   Wu Chin-tzan
1      1975   Wu Chin-tzan
2      1980   Wu Chin-tzan
3      1983   Wu Chin-tzan
4      1986   Wu Chin-tzan
5      1989  Huang Wuu-ran

------------------------------
Set Verified: Timeline numbered minor planets that are also comets exceptional asteroids
Entity Col:   Name
Entities:    ['2060 Chiron', '4015 Wilson–Harrington', '7968 Elst–Pizarro', '60558 Echeclus', '118401 LINEAR']
Table Data:

,Name,Cometary name,Comment
0,2060 Chiron,95P/Chiron,"First centaur discovered in 1977, later identi..."
1,4015 Wilson–Harrington,107P/Wilson–Harrington,"In 1992, it was realized that asteroid 1979 VA..."
2,7968 Elst–Pizarro,133P/Elst–Pizarro,"Discovered in 1996 as a comet, but orbitally m..."
3,60558 Echeclus,174P/Echeclus,"Centaur discovered in 2000, comet designation ..."
4,118401 LINEAR,176P/LINEAR (LINEAR 52),Main-belt comet – asteroid discovered to have ...

------------------------------
Set Verified: Media, llc peacock tv NBCUniversal television programs
Entity Col:   Title
Entities:    ['Lost Speedways', 'John Wayne Gacy: Devil in Disguise', "Epstein's Shadow: Ghislaine Maxwell", 'Dr Death: The Undoctored Story', 'Olympic Highlights with Kevin Hart and Snoop Dogg', 'Frogger', 'Top Chef Family Style', 'Hart to Heart', 'Backyard Blowout', 'Unidentified with Demi Lovato', 'The Siwa Dance Pop Revolution', 'Poker Face']
Table Data:

,Title,Original run,Network,Notes
0,Lost Speedways,2020,Peacock,co-production with Dirty Mo Media
1,John Wayne Gacy: Devil in Disguise,2021,Peacock,co-production with Witchcraft Motion Picture C...
2,Epstein's Shadow: Ghislaine Maxwell,2021,Peacock,"co-production with Blue Ant Media , Sky and Al..."
3,Dr Death: The Undoctored Story,2021,Peacock,co-production with Universal Content Productio...
4,Olympic Highlights with Kevin Hart and Snoop Dogg,2021,Peacock,co-production with LOL Studios and Snoopadelic...
5,Frogger,2021,Peacock,co-production with Eureka Productions and Kona...
6,Top Chef Family Style,2021,Peacock,co-production with Magical Elves Productions
7,Hart to Heart,2021–present,Peacock,co-production with LOL Studios
8,Backyard Blowout,2021,Peacock,co-production with Departure Films
9,Unidentified with Demi Lovato,2021,Peacock,co-production with Goodstory Productions and S...
10,The Siwa Dance Pop Revolution,2021,Peacock,"co-production with Evolution Media , Stinson M..."
11,Poker Face,2023–present,Peacock,"produced by Zucks., Animal Pictures , T-Street..."

------------------------------
Set Verified: Politics u.s. congress Pi Lambda Phi members
Entity Col:   Name
Entities:    ['Ben Cardin', 'Eliot Engel', 'Herbert Kohl', 'Arlen Specter', 'Sidney R. Yates']
Table Data:

,Name,Original chapter,Initiation year,Notability
0,Ben Cardin,PA Gamma Sigma,1961,"U.S. Senator (D), Maryland"
1,Eliot Engel,NY Alpha Mu,1967,"U.S. Representative (D), New York, 1989 to 2021."
2,Herbert Kohl,WI Omega,1953,"U.S. Senator (D), Wisconsin, from 1989 to 2013..."
3,Arlen Specter,PA Epsilon Zeta,1948,"U.S. Senator (D), Pennsylvania from 1980 to 20..."
4,Sidney R. Yates,IL Omicron,1927,"U.S. Representative (D), 9th District, Illinoi..."

------------------------------
Set Verified: Current multilateral organizations diplomatic missions of the Dominican Republic
Entity Col:   Organization
Entities:    ['Food and Agriculture Organization', 'International Civil Aviation Organization', 'Organization of American States', 'United Nations', 'United Nations', 'United Nations', 'UNESCO', 'World Trade Organization']
Table Data:

,Organization,Host city,Host country,Mission
0,Food and Agriculture Organization,Rome,Italy,Permanent Mission
1,International Civil Aviation Organization,Montreal,Canada,Permanent Mission
2,Organization of American States,"Washington, D.C.",United States,Permanent Mission
3,United Nations,New York City,United States,Permanent Mission
4,United Nations,Geneva,Switzerland,Permanent Mission
5,United Nations,Vienna,Austria,Permanent Mission
6,UNESCO,Paris,France,Permanent Delegation
7,World Trade Organization,Geneva,Switzerland,Permanent Mission

------------------------------
Set Verified: City voter elections mayors of Traverse City, Michigan
Entity Col:   Name
Entities:    ['Margaret B. Dodd', 'Linda Smyka', 'Michael Estes', 'Chris M. Bzdok', 'Michael Estes', 'Jim Carruthers', 'Richard Lewis', 'Amy Shamroe']
Table Data:

,Number,Name,Years,Notes
0,84,Margaret B. Dodd,2001–2003,
1,85,Linda Smyka,2003–2007,
2,86,Michael Estes,2007–2009,"One term, first time in office."
3,87,Chris M. Bzdok,2009–2011,
4,88,Michael Estes,2011–2015,"Two terms, second time in office."
5,89,Jim Carruthers,2015–2021,"Served three consecutive terms, and was Traver..."
6,90,Richard Lewis,2021–2023,Former city council member
7,91,Amy Shamroe,2023–,Mayor pro tem from 2017 to 2023; reelected in ...

------------------------------
Set Verified: Royal royal standards Thai flags
Entity Col:   Use
Entities:    ['Royal Standard of the King of Thailand', 'Standard of Queen Sirikit the Queen Mother', 'Standard of the Queen of Thailand', 'Standard for Senior members of the royal family (created for the Princess Mother )', 'Standard of the Crown Prince of Thailand .', 'Standard of Princess Maha Chakri Sirindhorn', 'Standard of Princess Chulabhorn Krom Phra Srisavangavadhana', 'Standard for the Royal Consort of the Crown Prince of Thailand.', 'Standard for other princes in the Chakri dynasty .', 'Standard for other princesses in the Chakri dynasty.', 'Standard for the Regent of Thailand .']
Table Data:

,Date,Use,Description
0,1911–,Royal Standard of the King of Thailand,A yellow plain square flag with a dancing red ...
1,2019 –,Standard of Queen Sirikit the Queen Mother,Similar to the Royal Standard in the ratio of ...
2,1911–,Standard of the Queen of Thailand,King's Standard in ratio 2:3 with swallow-tail...
3,1979–,Standard for Senior members of the royal famil...,Queen's Standard in ratio 2:3 with swallow-tai...
4,1911–,Standard of the Crown Prince of Thailand .,Thai king's standard with blue border.
5,2019 –,Standard of Princess Maha Chakri Sirindhorn,Dark blue rectangle with the ratio of 2:3 defa...
6,2019 –,Standard of Princess Chulabhorn Krom Phra Sris...,Dark blue rectangle defaced with yellow circle...
7,1911–,Standard for the Royal Consort of the Crown Pr...,Blue 2:3 rectangle defaced with King's Standar...
8,1911–,Standard for other princes in the Chakri dynas...,Blue square defaced with yellow circle. The c...
9,1911–,Standard for other princesses in the Chakri dy...,Standard for the male royalties in ratio 2:3 w...
10,1936–,Standard for the Regent of Thailand .,A white plain square flag with the Garuda and ...

------------------------------
Set Verified: 2013 Bodo-language films
Entity Col:   Film
Entities:    ['Hainamuli 4', 'Gwswm Jwmwi', 'Hwmbla', 'Maoria', 'Ang Nwngkhow Baonw Haya', 'Mr. Ranger Babu', 'Rojeni Radai', 'Nokhor Songsar', 'Simang Fara', 'Thwd Phagli Phagli', 'Thwinai Baidi Jiu']
Table Data:

,Film,Release date,Director,Artists,Producer,Production
0,Hainamuli 4,2013,Jagat Boro,"Jwngsrang Brahma, Dimasha Boro, Jagat Boro, Ri...",,Bangbula Film Production Presents
1,Gwswm Jwmwi,2013,Gajen Raj & Dipak Instri,"Nayan, Maidangsri",,
2,Hwmbla,2013,Phylaw Basumatary,"Mosko Brahma, Jonali Basumatary",,
3,Maoria,2013,Raja Narzary,"Kwrwm Mushahary, Kamla, Samson Basumatary, Dh...","Raja, Rupali, Sanjay",Rupali Films Production
4,Ang Nwngkhow Baonw Haya,2013,UC Brahma,"Fwilao, Rama, Dwimalu, Maya, Abinash",,JD Film Production
5,Mr. Ranger Babu,2013,Probin Goyary,Dilip Basumatary,,
6,Rojeni Radai,2013,,"Omprakash Kherkatary, Eyerish",,
7,Nokhor Songsar,2013,Rabi Narzary,"Rabi Narzary, Riju",Rabi Narzary,RN Films
8,Simang Fara,2013,Raju,"Jwngsrang Brahma, Dimasha Boro",Dahit & Indra,BHA
9,Thwd Phagli Phagli,2013,Chiraj Baglary,"Geolang Brahma, Jirina Brahma",,
10,Thwinai Baidi Jiu,2013,Mizing Narzary,"Mizing Narzary, Jumu Rani Brahma",,

------------------------------
Set Verified: Local and regional analogue and digital commercial northern ireland radio stations in the United Kingdom
Entity Col:   Name
Entities:    ['Cool FM', 'Downtown Country', 'Downtown Radio', 'Greatest Hits Radio Northern Ireland', 'Hits Radio Northern Ireland', 'Q Belfast 96.7 / 102.5', 'Q Mid Antrim 107', 'Q Mid Ulster 106', 'Q Newry and Mourne 100.5', 'Q North Coast 97.2', 'Q North West 102.9', 'Q Tyrone and Fermanagh 101.2']
Table Data:

,Name,Licence area,FM,DAB
0,Cool FM,Belfast,97.4,12D
1,Downtown Country,Northern Ireland,,12D
2,Downtown Radio,Northern Ireland,96.4 ( Limavady ) 96.6 ( Omagh and Enniskillen...,12D
3,Greatest Hits Radio Northern Ireland,Northern Ireland,,12D
4,Hits Radio Northern Ireland,Northern Ireland,,12D
5,Q Belfast 96.7 / 102.5,Belfast,96.7 ( Greater Belfast ) 102.5 ( Ards and Nort...,12D
6,Q Mid Antrim 107,Ballymena,107.0 107.6 ( Larne ),
7,Q Mid Ulster 106,Mid Ulster,106.0 106.3 107.2,
8,Q Newry and Mourne 100.5,Newry and Mourne,100.5 101.1 ( Kilkeel ),
9,Q North Coast 97.2,Coleraine,97.2 97.6 (Ballycastle),
10,Q North West 102.9,Derry,102.9,
11,Q Tyrone and Fermanagh 101.2,Omagh and Enniskillen,101.2 102.1 ( Enniskillen ),

------------------------------
Set Verified: Unmanned aerial vehicles intelligence unmanned aerial vehicles modern equipment of the German Army
Entity Col:   Model
Entities:    ['EMT Luna X-2000', 'EMT Luna NG/B', 'Rheinmetall KZO', 'EMT Aladin', 'Quantum Vector VTOL', 'AirRobot AR 100-B', 'AirRobot AR 100-H', 'AirRobot AR 200', 'Black Hornet Nano', 'DJI Phantom 4', 'DJI Matrice 200']
Table Data:

,Model,Image,Origin,Type,Role,Quantity,Notes
0,EMT Luna X-2000,,Germany,Fixed-wing unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",81,Currently being replaced by LUNA NG. (in 2013...
1,EMT Luna NG/B,,Germany,Fixed-wing unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",20,Replacing LUNA and KZO 1st batch of 20 alread...
2,Rheinmetall KZO,,Germany,Fixed-wing unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",43,Currently being replaced by LUNA NG.
3,EMT Aladin,,Germany,Fixed-wing unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",290,"As of 2013, 290 were in service, and 30 were l..."
4,Quantum Vector VTOL,,Germany,Tiltrotor unmanned aerial vehicle,Counter unmanned air system (intercepting UAV ...,14,14 expected to arrive in service in the Bundes...
5,AirRobot AR 100-B,,Germany,Mini multicopter unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",163,
6,AirRobot AR 100-H,—,Germany,Mini multicopter unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",145,"145 ordered, to arrive from 2023. Dubbed MIKA..."
7,AirRobot AR 200,,Germany,Mini multicopter unmanned aerial vehicle,"Intelligence, surveillance, and reconnaissance",—,
8,Black Hornet Nano,,Norway,Micro multicopter unmanned aerial vehicle,"Intelligence, surveillance, target acquisition...",30,Additional ordered in December 2024 (Black Hor...
9,DJI Phantom 4,,China,Commercial mini multicopter unmanned aerial ve...,"Intelligence, surveillance, target acquisition...",30,
10,DJI Matrice 200,,China,Commercial mini multicopter unmanned aerial ve...,"Intelligence, surveillance, target acquisition...",60,

------------------------------
Set Verified: Grammy awards accolades received by James Bond films
Entity Col:   Film
Entities:    ['Goldfinger', 'Casino Royale', 'Live and Let Die', 'The Spy Who Loved Me', 'Tomorrow Never Dies', 'Casino Royale', 'Skyfall', 'Skyfall', 'No Time to Die']
Table Data:

,Year,Category,Film,Soundtrack or song,Nominee(s),Result
0,1965,Best Original Score Written for a Motion Pictu...,Goldfinger,Goldfinger,John Barry,Nominated
1,1968,Best Original Score Written for a Motion Pictu...,Casino Royale,Casino Royale,Burt Bacharach,Nominated
2,1974,Best Album of Best Original Score Written for ...,Live and Let Die,Live and Let Die,"Paul McCartney , Linda McCartney , George Martin",Nominated
3,1978,Best Original Score Written for a Motion Pictu...,The Spy Who Loved Me,The Spy Who Loved Me,Marvin Hamlisch,Nominated
4,1999,Best Song Written for a Motion Picture or for ...,Tomorrow Never Dies,""" Tomorrow Never Dies """,Sheryl Crow & Mitchell Froom,Nominated
5,2008,"Best Song Written for a Motion Picture, Televi...",Casino Royale,""" You Know My Name """,David Arnold & Chris Cornell,Nominated
6,2014,Best Score Soundtrack for Visual Media,Skyfall,Skyfall,Thomas Newman,Won
7,2014,Best Song Written for Visual Media,Skyfall,""" Skyfall """,Adele Adkins & Paul Epworth,Won
8,2021,Best Song Written for Visual Media,No Time to Die,""" No Time to Die """,Billie Eilish O'Connell & Finneas O'Connell,Won

------------------------------
Set Verified: Grand princes of hungary house of árpád Hungarian monarchs
Entity Col:   Name Reign
Entities:    ['Árpád c. 895 ┃ c. 907', 'Zoltán c. 907 ┃ c. 947', 'Fajsz c. 947 ┃ c. 955', 'Taksony c. 955 ┃ c. 972', 'Géza c. 972 ┃ 997', 'Stephen 997 ┃ 1000']
Table Data:

,Name Reign,Portrait,Arms,Birth Parentage,Marriage(s) Issue,Death Burial,Notes
0,Árpád c. 895 ┃ c. 907,,,"c. 845 Son of Álmos, Grand Prince of the Hunga...",,c. 907 Aged c. 62,Hungarian conquest of the Carpathian Basin
1,Zoltán c. 907 ┃ c. 947,,,"c. 896 Son of Árpád, Grand Prince of the Hunga...","Menumorut 's daughter (?) Taksony, Grand Princ...",c. 947,
2,Fajsz c. 947 ┃ c. 955,,,Early 10th century Son of Jutocsa,,,"Grandson of Árpád, Grand Prince of the Hungarians"
3,Taksony c. 955 ┃ c. 972,,,"c. 931 Son of Zoltán, Grand Prince of the Hung...","""Cuman"" lady (A Khazar, Pecheneg or Volga Bulg...",c. 972 Aged c. 41,
4,Géza c. 972 ┃ 997,,,"c. 945 Son of Taksony, Grand Prince of the Hun...","Sarolt , daughter of Gyula of Transylvania Jud...",997 Aged c. 52,
5,Stephen 997 ┃ 1000,,,"c. 975 Esztergom Son of Géza, Grand Prince of ...",Blessed Gisela of Bavaria 996 Otto (Before 100...,15 August 1038 Esztergom or Székesfehérvár Age...,Became the first King of Hungary Asserted his ...

------------------------------
Set Verified: Box office American films of 1999
Entity Col:   Title
Entities:    ['Star Wars: Episode I – The Phantom Menace', 'The Sixth Sense', 'Toy Story 2', 'Austin Powers: The Spy Who Shagged Me', 'The Matrix', 'Tarzan', 'Big Daddy', 'The Mummy', 'Runaway Bride', 'The Blair Witch Project']
Table Data:

,Rank,Title,Distributor,Domestic gross
0,1,Star Wars: Episode I – The Phantom Menace,20th Century Fox,"$431,088,295"
1,2,The Sixth Sense,Disney,"$293,506,292"
2,3,Toy Story 2,Disney,"$245,852,179"
3,4,Austin Powers: The Spy Who Shagged Me,New Line Cinema,"$206,040,086"
4,5,The Matrix,Warner Bros. Pictures,"$171,479,930"
5,6,Tarzan,Disney,"$171,091,819"
6,7,Big Daddy,Sony Pictures,"$163,479,795"
7,8,The Mummy,Universal Pictures,"$157,138,535"
8,9,Runaway Bride,Paramount Pictures,"$152,257,509"
9,10,The Blair Witch Project,Artisan Entertainment,"$140,539,099"

------------------------------
Set Verified: Tv tonight awards and nominations received by Home and Away
Entity Col:   Category
Entities:    ['Best Drama (Australian)', 'Best Female', 'Favourite Female', 'Worst Show (Australian)', 'Worst Female', 'Best Australian Drama', 'Best Australian Drama']
Table Data:

   Year                 Category                    Nominee     Result
0  2007  Best Drama (Australian)              Home and Away  Nominated
1  2007              Best Female               Kate Ritchie        Won
2  2008         Favourite Female               Kate Ritchie  Nominated
3  2009  Worst Show (Australian)              Home and Away  Nominated
4  2009             Worst Female                Jodi Gordon  Nominated
5  2020    Best Australian Drama  Home and Away (season 32)  Nominated
6  2022    Best Australian Drama  Home and Away (season 34)  Nominated

------------------------------
Set Verified: Croatia shipwrecks of Europe
Entity Col:   Ship
Entities:    ['Audace', 'Baron Gautsch', 'Cesare Rossarol', 'Giuseppe Garibaldi', 'SMS Niobe', 'Peltastis', 'SMS Szent István', 'UB-129', 'SMS Viribus Unitis']
Table Data:

,Ship,Flag,Sunk date,Notes,Coordinates
0,Audace,Regia Marina,1 November 1944,An Urakaze -class destroyer that was sunk by H...,
1,Baron Gautsch,Austria-Hungary,12 August 1914,An Austrian steam liner sunk by an underwater ...,
2,Cesare Rossarol,Regia Marina,16 November 1918,An Italian Alessandro Poerio -class cruiser su...,
3,Giuseppe Garibaldi,Regia Marina,18 July 1915,A Giuseppe Garibaldi -class armored cruiser th...,
4,SMS Niobe,Kriegsmarine,22 December 1943,A Gazelle -class light cruiser that ran agroun...,44°22′N 14°42′E ﻿ / ﻿ 44.367°N 14.700°E ﻿ / 44...
5,Peltastis,Greece,8 January 1968,A Greek cargo ship sunk in bad weather at sea.,45°9′49″N 14°38′44″E ﻿ / ﻿ 45.16361°N 14.64556...
6,SMS Szent István,Austria-Hungary,10 June 1918,A Tegetthoff -class dreadnought battleship tha...,44°12′07″N 14°27′05″E ﻿ / ﻿ 44.20194°N 14.4513...
7,UB-129,Imperial German Navy,31 October 1918,A Type UB III U-boat that was scuttled at Rije...,45°19′N 14°26′E ﻿ / ﻿ 45.317°N 14.433°E ﻿ / 45...
8,SMS Viribus Unitis,Austria-Hungary,1 November 1918,A Tegetthoff -class dreadnought battleship tha...,44°52′9″N 13°49′9″E ﻿ / ﻿ 44.86917°N 13.81917°...

------------------------------
Set Verified: Box office collection Kannada films of 2012
Entity Col:   Title
Entities:    ['Krantiveera Sangolli Rayanna', 'Dandupalya', 'Addhuri', 'Katari Veera Surasundarangi', 'Drama', 'Anna Bond', 'Chingari', 'Govindaya Namaha', 'Rambo', 'Jaanu']
Table Data:

,Rank,Title,Production company,Worldwide gross
0,1,Krantiveera Sangolli Rayanna,Sri Sangolli Rayanna films,₹ 40 crore (US$4.7 million)
1,2,Dandupalya,Apple Blossom Creations,₹ 25 crore (US$3.0 million)
2,3,Addhuri,CMR Productions,₹ 25 crore (US$3.0 million)
3,4,Katari Veera Surasundarangi,Rockline Productions,₹ 16 crore (US$1.9 million)
4,5,Drama,Jayanna Combines,₹ 13 crore (US$1.5 million)
5,6,Anna Bond,Poornima Enterprises,₹ 12 crore (US$1.4 million)
6,7,Chingari,Mahashaila Cine Sankula,₹ 12 crore (US$1.4 million)
7,8,Govindaya Namaha,Suresh Arts,"₹ 8 crore (US$950,000)"
8,9,Rambo,Laddoo Cinema House,"₹ 5 crore (US$590,000)"
9,10,Jaanu,Jayanna Combines,"₹ 2 crore (US$240,000)"

------------------------------
Set Verified: Releases unknown premiere date Israeli films of 1975
Entity Col:   Premiere
Entities:    ['?', '?', '?', '?', '?']
Table Data:

,Premiere,Title,Director,Cast,Genre
0,?,"Hagiga B'Snuker ( Hebrew : חגיגה בסנוקר , lit....",Boaz Davidson,"Yehuda Barkan , Ze'ev Revach , Joseph Shiloach...","Comedy , Bourekas film"
1,?,"Hagiga Le'enayim ( Hebrew : חגיגה לעיניים , li...",Assi Dayan,,Drama
2,?,"Yom Hadin ( Hebrew : יום הדין , lit. ""Day of J...",George Obadiah,,Drama
3,?,Yi'ihiyeh Tov Salomonico ( Hebrew : יהיה טוב ס...,Alfred Steinhardt,Reuven Bar-Yotam,Drama
4,?,"Ha-Diber Ha-11 ( Hebrew : הדיבר ה-11 , lit. ""T...",Shlomo Suriano,"Michal Bat-Adam , Yossi Graber",Drama

------------------------------
Set Verified: Primary and secondary education public school districts schools in Indianapolis
Entity Col:   Name
Entities:    ['Beech Grove City Schools', 'Franklin Township Community School Corporation', 'Indianapolis Public Schools', 'Metropolitan School District of Decatur Township', 'Metropolitan School District of Lawrence Township', 'Metropolitan School District of Pike Township', 'Metropolitan School District of Warren Township', 'Metropolitan School District of Washington Township', 'Metropolitan School District of Wayne Township', 'Perry Township Schools', 'School Town of Speedway']
Table Data:

,Name,Municipalities served,No. of schools,Enrollment
0,Beech Grove City Schools,Beech Grove,5,2837
1,Franklin Township Community School Corporation,Indianapolis,11,11139
2,Indianapolis Public Schools,Indianapolis,57,22115
3,Metropolitan School District of Decatur Township,Indianapolis,9,6681
4,Metropolitan School District of Lawrence Township,Indianapolis · Lawrence,17,16247
5,Metropolitan School District of Pike Township,Indianapolis,13,10901
6,Metropolitan School District of Warren Township,Indianapolis,16,11801
7,Metropolitan School District of Washington Tow...,Indianapolis,14,10901
8,Metropolitan School District of Wayne Township,Indianapolis,19,16343
9,Perry Township Schools,Indianapolis · Southport,17,16603
10,School Town of Speedway,Speedway,6,1863

------------------------------
Set Verified: Wins by position Six Nations Championship Player of the Championship winners
Entity Col:   Position
Entities:    ['Full-back', 'Centre', 'Wing', 'Flanker', 'Scrum-half', 'Lock', 'Fly-half', 'Number eight', 'Hooker', 'Prop']
Table Data:

       Position  Wins                             Years
0     Full-back     5  2011 , 2013 , 2014 , 2016 , 2017
1        Centre     5  2004 , 2006 , 2007 , 2009 , 2024
2          Wing     4         2008 , 2010 , 2018 , 2025
3       Flanker     3                2005 , 2012 , 2021
4    Scrum-half     3                2020 , 2022 , 2023
5          Lock     2                       2015 , 2019
6      Fly-half     0                                 —
7  Number eight     0                                 —
8        Hooker     0                                 —
9          Prop     0                                 —

------------------------------
Set Verified: Nalappadan award Malayalam literary awards
Entity Col:   Recipient
Entities:    ['Mullanezhi', 'Puzhankara Balanarayanan', 'N. Mohanan', 'Vayala Vasudevan Pillai', 'M. Leelavathy', 'O. N. V. Kurup', 'Anand', 'E. Harikumar', 'M. P. Veerendra Kumar', 'K. B. Sreedevi', 'Yusufali Kechery']
Table Data:

    Year                 Recipient                          Work
0   1989                Mullanezhi              Naranath Prathan
1   1990  Puzhankara Balanarayanan                   Ardhanagnar
2   1991                N. Mohanan                 Sheshapathram
3   1992   Vayala Vasudevan Pillai    Oru Pakshikunjinte Maranam
4   1993             M. Leelavathy  Adipraroopangal Sahithyathil
5   1994            O. N. V. Kurup                      Ujjayini
6   1996                     Anand         Govardhande Yathrakal
7   1998              E. Harikumar   Sookshichu Vacha Mayilpeeli
8   1999     M. P. Veerendra Kumar   Prathibhayude Verukal Thedi
9   2000            K. B. Sreedevi                   Chanakkallu
10  2001          Yusufali Kechery             Mukhapadamillathe

------------------------------
Set Verified: By country arabian gulf countries highest-grossing Indian films in overseas markets
Entity Col:   Title
Entities:    ['Jawan', 'Pathaan', 'Baahubali 2: The Conclusion', 'L2: Empuraan', 'Bajrangi Bhaijaan', 'Dangal', 'Sultan', 'Lokah Chapter 1: Chandra', 'Dilwale', 'KGF: Chapter 2']
Table Data:

   Rank                        Title Gross ( USD ) Language(s)  Year
0     1                        Jawan   $17,700,000       Hindi  2023
1     2                      Pathaan   $14,200,000       Hindi  2023
2     3  Baahubali 2: The Conclusion   $10,310,000      Telugu  2017
3     4                 L2: Empuraan    $9,719,000   Malayalam  2025
4     5            Bajrangi Bhaijaan    $9,450,000       Hindi  2015
5     6                       Dangal    $8,800,000       Hindi  2016
6     7                       Sultan    $8,570,000       Hindi  2016
7     8     Lokah Chapter 1: Chandra    $8,510,000   Malayalam  2025
8     9                      Dilwale    $8,410,000       Hindi  2015
9    10               KGF: Chapter 2    $8,150,000     Kannada  2022

------------------------------
Set Verified: Boston music awards and nominations received by Ray LaMontagne
Entity Col:   Award
Entities:    ['Act of the Year', 'Male Vocalist of the Year', 'Best Male Singer-Songwriter', 'Album of the Year', 'Song of the Year', 'Act of the Year', 'Male Vocalist of the Year', 'Album of the Year']
Table Data:

   Year       Nominee / work                        Award     Result
0  2005       Ray LaMontagne              Act of the Year  Nominated
1  2005       Ray LaMontagne    Male Vocalist of the Year  Nominated
2  2005       Ray LaMontagne  Best Male Singer-Songwriter        Won
3  2005              Trouble            Album of the Year        Won
4  2005          " Trouble "             Song of the Year        Won
5  2008       Ray LaMontagne              Act of the Year  Nominated
6  2008       Ray LaMontagne    Male Vocalist of the Year  Nominated
7  2008  Gossip in the Grain            Album of the Year  Nominated

------------------------------
--- Processing Summary ---
Total Tables: 100
Passed (Closed Sets): 92
Rejected (Subjective/Open): 5
Rejected (No clear Entity): 2
Rejected (Incomplete Set): 1
Precision Estimate: 100% (Deterministic)

# Test for caption finding:

In [181]:
for s in cleaned_data:
    if "(" in s['table_name'].lower():
        print(f"{s['table_name']} --> {s['table_name'].split('(')[-1].split(')')[0]}")

List of fictional birds > Charadriiformes(gulls, terns, auks, and waders) --> gulls, terns, auks, and waders
List of Tamil films of 2019 > Box office collection (Highest worldwide gross of 2019) --> Highest worldwide gross of 2019
List of 2012 box office number-one films in Japan > Highest-grossing films (Highest-grossing films of 2012) --> Highest-grossing films of 2012
List of Cardiff City F.C. seasons > Key (Key to colours and symbols:) --> Key to colours and symbols:
List of Chinese films of 2014 > Box office (Highest-grossing domestic films of 2014 in China) --> Highest-grossing domestic films of 2014 in China
List of athletes from Montana > Basketball (Basketball players from Montana) --> Basketball players from Montana
List of documentary films > Z (Contents : Top 0–9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z See also References) --> Contents : Top 0–9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z See also References
List of 2010 box office number-one films in Spain > Highest-grossing films (Highest-grossing films of 2010) --> Highest-grossing films of 2010
List of Olympic medalists in gymnastics (men) > Artistic gymnastics > Discontinued events > Rope climbing (Rope climbing) --> Rope climbing
List of Freedom Fighters members > Second roster (This roster covers the iteration of the team introduced in 2001.) --> This roster covers the iteration of the team introduced in 2001.
List of defunct airlines of Oceania > Norfolk Island (Defunct airlines of the Norfolk Island include:) --> Defunct airlines of the Norfolk Island include:
List of awards and nominations received by Tom Cruise > State honors (Name of country, year given, and name of honor) --> Name of country, year given, and name of honor
List of Cuban League baseball players (E–L) > J --> E–L
List of Sooty Show episodes > The Sooty Show(**Harry Corbett Years**) > 1972: Series 7 --> **Harry Corbett Years**
List of American films of 2006 > Box office (Highest-grossing films of 2006) --> Highest-grossing films of 2006
List of power stations in New York > Retired plants (This is a list of retired plants.) --> This is a list of retired plants.
List of earthquakes in 1916 > Notable events > July (July) --> July
List of exoplanets detected by microlensing > List > Candidate rogue planets (A number of candidate rogue planets have been detected by microlensing.) --> A number of candidate rogue planets have been detected by microlensing.
List of mountains in Georgia (U.S. state) > Highest mountains (The 10 highest summits of Georgia with at least 100 feet of topographic prominence) --> The 10 highest summits of Georgia with at least 100 feet of topographic prominence
List of awards and nominations received by Lou Grant > Awards and nominations > Emmy Awards > Creative Arts Emmy Awards (Creative Arts Emmy Awards) --> Creative Arts Emmy Awards
List of Methodist churches > United States (Several, selected significant Methodist churches in the U.S. are:) --> Several, selected significant Methodist churches in the U.S. are:
List of senators of Doubs > Fourth Republic (Senators for Doubs under the French Fourth Republic were:) --> Senators for Doubs under the French Fourth Republic were:
List of members of the first Legislative Yuan > List of members > Supplementary members > Fujian (Fujian) --> Fujian
List of mayors of Traverse City, Michigan > City voter elections (2000–present) --> 2000–present
List of radio stations in the United Kingdom > Local and regional analogue and digital stations > Commercial radio > Northern Ireland (Northern Ireland) --> Northern Ireland
List of power stations in Ivory Coast > Hydroelectric (Partial list of hydroelectric power stations in Ivory Coast.) --> Partial list of hydroelectric power stations in Ivory Coast.
List of Hungarian monarchs > Grand Princes of Hungary (895–1000) > House of Árpád --> 895–1000
List of American films of 1999 > Box office (Highest-grossing films of 1999) --> Highest-grossing films of 1999
List of Kannada films of 2012 > Box office collection (The highest worldwide gross of 2012) --> The highest worldwide gross of 2012
List of Malayalam literary awards > Nalappadan Award (The literary prize was instituted in the name of writer Nalapat Narayana Menon .) --> The literary prize was instituted in the name of writer Nalapat Narayana Menon .
List of Internet top-level domains > ICANN-era generic top-level domains > Spanish (.es) --> .es
List of companies listed on the Athens Stock Exchange > Personal and household goods (Durable household goods) --> Durable household goods
List of Pakistan Tehreek-e-Insaf elected members (2013–2018) > Sindh Assembly (List of elected Members of the Sindh Assembly from Pakistan Tehreek-e-Insaf .) --> List of elected Members of the Sindh Assembly from Pakistan Tehreek-e-Insaf .
List of hospitals in British Columbia > Island Health (Island Health operates 12 hospitals on Vancouver Island .) --> Island Health operates 12 hospitals on Vancouver Island .
List of Nebraska state senators > District 19 (Today, District 19 consists of Madison County and the southern half of Pierce County.) --> Today, District 19 consists of Madison County and the southern half of Pierce County.
List of University Football Club players > University Football Club players (Key) --> Key
List of retired OTO Awards > Main categories > TV Sports – Host or Commentator (OTO Award TV Sports – Host or Commentator) --> OTO Award TV Sports – Host or Commentator
List of rulers of medieval Bosnia > Kings and queen (1377–1463) (All Bosnian kings added the honorific Stephen to their baptismal name upon accession.) --> All Bosnian kings added the honorific Stephen to their baptismal name upon accession.
List of Grand Prix motorcycle racing World Teams' Champions > By country (bold) --> bold
List of defunct airlines of Africa > Somalia (Defunct airlines of Somalia include:) --> Defunct airlines of Somalia include:
List of Nokia products > Past products and services > Mobile phones > 4-digit series (Main article: Nokia Communicator) --> Main article: Nokia Communicator
List of TVB series (2005) > First line series (These dramas aired in Hong Kong from 8:00 to 9:00 pm, Monday to Friday on TVB.) --> These dramas aired in Hong Kong from 8:00 to 9:00 pm, Monday to Friday on TVB.
List of causes of death by rate > By frequency > Developed vs. developing economies (Top causes of death, according to the World Health Organization report for the calendar year 2001:) --> Top causes of death, according to the World Health Organization report for the calendar year 2001:
List of vampire films > Carmilla films (There have been numerous films based on Carmilla , an 1872 Gothic novella by Irish author Joseph Sheridan Le Fanu and one of the early works of vampire fiction , predating Bram Stoker 's Dracula (1897) by 26 years. The story is narrated by a young woman preyed upon by a female vampire named Carmilla, later revealed to be Mircalla, Countess Karnstein (Carmilla is an anagram of Mircalla). The character is a prototypical example of the lesbian vampire, expressing romantic desires toward the protagonist.) --> Carmilla is an anagram of Mircalla
List of presidents of the Scottish Society of the History of Medicine > 1981-2000 (Table featuring presidents of the Scottish Society of the History of Medicine) --> Table featuring presidents of the Scottish Society of the History of Medicine
List of 2008 box office number-one films in Japan > Highest-grossing films (Highest-grossing films of 2008) --> Highest-grossing films of 2008
List of bodhisattvas > Classification > Five Great Bodhisattvas (Five Bodhisattvas of Great Power) --> Five Bodhisattvas of Great Power
List of image-sharing websites > Comparison of photo-sharing websites (Legend:) --> Legend:
List of Atlanta Thrashers players > Key (Goaltenders) --> Goaltenders
List of Marathi films of 1985 > 1985 Releases (A list of Marathi films released in 1985.) --> A list of Marathi films released in 1985.
List of DJ Awards winners and nominees > Winners and nominees > 2000 (The 3rd edition winners nominees and recipients were chosen from 11 categories.) --> The 3rd edition winners nominees and recipients were chosen from 11 categories.
List of senators of French West Africa > Ivory Coast (Senators for the Ivory Coast under the French Fourth Republic were:) --> Senators for the Ivory Coast under the French Fourth Republic were:
List of hospitals in Thailand > Public Hospitals > Bangkok Metropolitan Administration (All hospitals are operated by the Medical Services Department, Bangkok Metropolitan Administration .) --> All hospitals are operated by the Medical Services Department, Bangkok Metropolitan Administration .
List of New Avengers members > Time Runs Out (2015–2016) > All-New All-Different Marvel (2015–2016) (Avengers Idea Mechanics) --> Avengers Idea Mechanics
List of Hong Kong films of 2013 > Box office (Highest-grossing films released in 2013) --> Highest-grossing films released in 2013
List of World Tag Team Champions (WWE) > Title history > Names --> WWE
List of awards and nominations received by Im Yoon-ah > Other accolades > Listicles (Name of publisher, year listed, name of listicle , and placement) --> Name of publisher, year listed, name of listicle , and placement
List of members of the National Assembly of Zambia (1969–1973) > List of members > Non-elected members --> 1969–1973
List of members of the 89th session of the Iowa Senate > Leadership (Senate leadership as of January 11, 2021  .) --> Senate leadership as of January 11, 2021  .
List of earthquakes in 1934 > Notable events > January (January) --> January
List of senior rugby league clubs in New South Wales > National Rugby League (Main article: National Rugby League) --> Main article: National Rugby League
List of GMA Network original programming > Former original programming > Other (List of former other shows, showing the premiere date and finale date) --> List of former other shows, showing the premiere date and finale date
List of awards and nominations received by Jo Jung-suk > Awards and nominations > Listicles (Name of publisher, year listed, name of listicle , and placement) --> Name of publisher, year listed, name of listicle , and placement
List of UK Singles Downloads Chart number ones of the 2010s > Number-one singles > By record label (Seven record labels have spent 10 weeks or more at number one during the 2010s.) --> Seven record labels have spent 10 weeks or more at number one during the 2010s.
List of calendars > Variant month names (Regional or historical names for lunations or Julian/Gregorian months) --> Regional or historical names for lunations or Julian/Gregorian months
List of airports in Northern Cyprus > Airports (bold) --> bold
List of busiest airports by international passenger traffic > 2024 statistics (preliminary) --> preliminary
List of German flags > Standards > Imperial family standards (Further information: House of Hohenzollern) --> Further information: House of Hohenzollern
List of open-source video games > Open-source remakes with non-free data from the proprietary original (See also: List of game engine recreations) --> See also: List of game engine recreations
List of cities in Zhytomyr Oblast > List of cities (Cities in Zhytomyr Oblast) --> Cities in Zhytomyr Oblast
List of awards and nominations received by Naga Chaitanya > South Indian International Movie Awards (Chaitanya has won one South Indian International Movie Awards from four nominations.) --> Chaitanya has won one South Indian International Movie Awards from four nominations.
List of Chicago Cubs team records > Single Season Records > Pitching > Wins (Wins) --> Wins
List of municipalities in Mary Province > Lists > Cities (bolded) --> bolded
List of awards and nominations received by Ive > Other accolades > Listicles (Name of publisher, year listed, name of listicle , and placement) --> Name of publisher, year listed, name of listicle , and placement
List of Bavarian locomotives and railbuses > Locomotives of theBavarian Eastern Railway Company(Bayerische Ostbahn) (The initial use of names was soon given up again.) --> The initial use of names was soon given up again.
List of Los Angeles Kings players > Key (Goaltenders) --> Goaltenders
List of tallest buildings in Kansas City > Timeline of tallest buildings (These buildings once held the title of tallest building in Kansas City, Missouri.) --> These buildings once held the title of tallest building in Kansas City, Missouri.
List of awards and nominations received by Dexter > Emmy Awards > Creative Arts Emmy Awards (Creative Arts Emmy Awards) --> Creative Arts Emmy Awards
List of MNL48 members > Current Lineup (General Election Rankings) --> General Election Rankings
List of mayors of Bayside > Commissioners (1994–1997) --> 1994–1997
List of Latvian films > 2020s (2020s) --> 2020s
List of Kannada films of 2017 > Box office collection (Highest worldwide gross of 2017) --> Highest worldwide gross of 2017
List of National Basketball League (Australia) awards > Individual awards --> Australia
List of equipment of the Philippine Navy > Littoral warfare vessels > Aceroclass fast attack craft (Origin: Israel / Philippines) --> Origin: Israel / Philippines
List of Kansas City Royals minor league affiliates > Current affiliates (The Kansas City Royals farm system consists of seven minor league affiliates.) --> The Kansas City Royals farm system consists of seven minor league affiliates.
List of Florida Panthers players > Key (Goaltenders) --> Goaltenders
List of lacrosse teams in Canada > Intermediate B > BC Intermediate Lacrosse League (BCLA) --> BCLA
List of Odonata species of Sri Lanka > Dragonflies & Damselflies > Suborder:Zygoptera- Damselflies > Family:Platycnemididae- Threadtails (Family: Platycnemididae - Threadtails) --> Family: Platycnemididae - Threadtails
List of Saturday Night Live cast members > President of the United States impressionists (Portrayal of sitting Presidents of the United States) --> Portrayal of sitting Presidents of the United States
List of members of the 9th Bundestag > Summary (This summary includes changes in the numbers of the three caucuses ( CDU / CSU , SPD , FDP ):) -->  CDU / CSU , SPD , FDP
List of current first-class cricket teams > Bangladesh (National team: Bangladesh national cricket team) --> National team: Bangladesh national cricket team
List of Central European countries by development indexes > Education > Education performance (Positions in various subject groups) --> Positions in various subject groups
List of Utah Mammoth players > Key (Abbreviations) --> Abbreviations
List of 2011 box office number-one films in Spain > Highest-grossing films (Highest-grossing films of 2011) --> Highest-grossing films of 2011
List of 2020 box office number-one films in Spain > Highest-grossing films (Highest-grossing films of 2020) --> Highest-grossing films of 2020
List of schools in the Australian Capital Territory > Public schools > Secondary colleges (11–12) --> 11–12
List of colleges in Bangladesh > Public University Affiliate Colleges > Specialized Public (BSc. in Textile) Engineering Colleges --> BSc. in Textile
List of castles in Brittany > Côtes-d'Armor (Castles of which little or nothing remains include Château de Montafilan .) --> Castles of which little or nothing remains include Château de Montafilan .
List of defunct airlines of Asia > Syria (Defunct airlines of Syria include:) --> Defunct airlines of Syria include:
List of awards and nominations received by Penn & Teller: Bullshit! > Writers Guild of America Awards (List of Writers Guild of America Awards and nominations received by Penn & Teller: Bullshit!) --> List of Writers Guild of America Awards and nominations received by Penn & Teller: Bullshit!
List of mayors of South Perth > South Perth Road Board (1922–1956) --> 1922–1956
List of longhorn beetle species recorded in Britain > List of native species > Subfamily Spondylidinae (Subfamily Spondylidinae) --> Subfamily Spondylidinae
List of awards and nominations received by Karisma Kapoor > Bollywood Movie Awards (Kapoor has won three Bollywood Movie Awards out of eight nominations.) --> Kapoor has won three Bollywood Movie Awards out of eight nominations.
List of ambassadors of Sweden to Slovakia > List of representatives (See also: List of ambassadors of Sweden to Czechoslovakia) --> See also: List of ambassadors of Sweden to Czechoslovakia
List of Academy Award winners and nominees for Best International Feature Film > Multiple wins and nominations > Multiple wins (Six directors have won the award more than once.) --> Six directors have won the award more than once.
List of Padma Bhushan award recipients (2020–2029) > Overview (Award recipients by field) --> Award recipients by field
List of international television show franchises > Sitcoms > The Nanny (The Nanny) --> The Nanny
List of awards and nominations received by Smriti Irani > Indian Television Academy Awards (Main article: Indian Television Academy Awards) --> Main article: Indian Television Academy Awards
List of highest-grossing films > Highest-grossing films adjusted for inflation (Highest-grossing films as of 2024  adjusted for inflation) --> Highest-grossing films as of 2024  adjusted for inflation
List of American films of 2019 > Box office (Highest-grossing films of 2019) --> Highest-grossing films of 2019
List of airports in the Calgary area > Active airports (Airport names in italics are part of the National Airports System .) --> Airport names in italics are part of the National Airports System .
List of CR Flamengo players > Club captains (List of Flamengo club captains) --> List of Flamengo club captains
List of mayors of Vicenza > Republic of Italy (since 1946) > City Council election (1946–1995) (From 1946 to 1995, the Mayor of Vicenza was elected by the City's Council.) --> From 1946 to 1995, the Mayor of Vicenza was elected by the City's Council.
List of newspapers in Texas > Foreign-language newspapers (See also: List of Spanish-language newspapers published in the United States) --> See also: List of Spanish-language newspapers published in the United States
List of earthquakes in 1961 > Notable events > June (June) --> June
List of airports in Israel > Airports > Military airbases (All military airbases are owned by the Israeli Air Force .) --> All military airbases are owned by the Israeli Air Force .
List of Major League Baseball no-hitters > Regulation no-hitters > Key (Key) --> Key
List of senators of Loir-et-Cher > Fifth Republic (Senators for Loir-et-Cher under the French Fifth Republic :) --> Senators for Loir-et-Cher under the French Fifth Republic :
List of ambassadors of the United States to Germany > List of United States ambassadors to Germany > Heads of the U.S. embassy > Berlin (1921–1941) (Berlin (1921–1941)) --> 1921–1941
List of American films of 1985 > Box office (Highest-grossing films of 1985) --> Highest-grossing films of 1985
List of caves in Croatia > Deepest caves (Further information: List of deepest Dinaric caves) --> Further information: List of deepest Dinaric caves
List of Phineas and Ferb guest stars > Films (The following appeared as guest stars in Phineas and Ferb the Movie: Candace Against the Universe .) --> The following appeared as guest stars in Phineas and Ferb the Movie: Candace Against the Universe .
List of games by Epic Games > Video games > Published games (Games published as Epic Games Publishing) --> Games published as Epic Games Publishing
List of lighthouses in Peru > Lake Titicaca lights (There are six Peruvian lighthouses that aid navigation on the lake.) --> There are six Peruvian lighthouses that aid navigation on the lake.
List of commercial nuclear reactors > Turkey (Main article: Nuclear power in Turkey) --> Main article: Nuclear power in Turkey
List of Armenian monarchs > Ancient Armenia (521 BC – AD 428) > Orontid dynasty (401–200 BC) --> 401–200 BC

In [196]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

# extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/final_tables_test.jsonl"))
# validated_tables_file_name = await extractor.run_with_progress(random.sample(table_titles, 1000))

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/final_tables_test.jsonl"))
ttttt_cleaned_data = processor.process()

Filtering & Cleaning:   0%|          | 0/1770 [00:00<?, ?it/s]

════════════════════════════════════════════
📊 TABLE PROCESSING SUMMARY (Limit: 12)
════════════════════════════════════════════
Total tables scanned:      1770
Dropped (Bad Headers):     152
Dropped (Cell too long):   48
Dropped (Repeat Rows):     38
Short tables found:        810
Unique source pages:       312
Final sampled (1/page):    312
════════════════════════════════════════════

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                  ↓ EXAMPLE TABLES ↓
------------------------------------------------------------------------------------------------------------------------------------------------------

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
{'header_chain': '23rd Primetime Emmy Awards > Most major awards', 'caption': 'Programs with multiple major awards', 'additional_text': None}
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

                         Programs Category Network  Number of Awards
0      The Bold Ones: The Senator    Drama     NBC                 4
1       The Mary Tyler Moore Show   Comedy     CBS                 4
2               All in the Family   Comedy     CBS                 3
3                       The Price  Special     NBC                 3
4         The Andersonville Trial  Special     PBS                 2
5            The Flip Wilson Show  Variety     NBC                 2
6  Singer Presents Burt Bacharach  Variety     CBS                 2
7            Wide World of Sports   Sports     ABC                 2

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
{'header_chain': '2019 Melon Music Awards > Judging criteria', 'caption': None, 'additional_text': None}
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

               Division Online Voting Digital Sales Judge Score
0        Top 10 Artists           20%           80%           —
1          Main awards*           20%           60%         20%
2        Genre Awards**           30%           40%         30%
3  Popularity Awards***           60%           40%           —
4    Special Awards****             —             —        100%

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
{'header_chain': 'Tsinghua University > Academics > Rankings and reputation > Subjects rankings', 'caption': 'THE World University Rankings by Subject 2024', 'additional_text': None}
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

                Subject Global National
0     Arts & humanities     34        2
1  Business & economics      8        1
2     Clinical & health     14        1
3      Computer science     12        1
4             Education      7        1
5           Engineering     15        2
6                   Law     33        1
7         Life sciences    =12      1–2
8     Physical sciences     14        1
9       Social sciences     21        2

In [199]:
for s in ttttt_cleaned_data:
    if s['table_name']['header_chain'].lower().startswith("list of"):
        if s['table_name']['caption'] or s['table_name']['additional_text']:
            print(s['table_name'])
            # print("-"*100)

{'header_chain': 'List of mayors of Naples > Deputy Mayor', 'caption': None, 'additional_text': 'The Deputy Mayor is nominated and eventually dismissed by the Mayor.'}
{'header_chain': 'List of power stations in Angola > Hydroelectric', 'caption': None, 'additional_text': 'List of all hydroelectric power plants in Angola.'}
{'header_chain': 'List of Colorado Avalanche players > Key', 'caption': 'Abbreviations', 'additional_text': None}
{'header_chain': 'List of mayors of Clermont-Ferrand > Elected mayors', 'caption': None, 'additional_text': 'The mayors of Clermont-Ferrand from 1893 to present.'}
{'header_chain': 'List of Chicago Blackhawks players > Key', 'caption': 'Skaters', 'additional_text': None}
{'header_chain': "List of awards and nominations received by Jonny Greenwood > Critics' Choice Movie Awards", 'caption': None, 'additional_text': "The Critics' Choice Movie Awards are presented annually since 1995 by the Broadcast Film Critics Association for outstanding achievements in the cinema industry."}
{'header_chain': 'List of stadiums in England > Future stadiums', 'caption': None, 'additional_text': 'Stadiums which are currently in development, and are likely to open in the near future, include:'}
{'header_chain': 'List of companies listed on the Athens Stock Exchange > Personal and household goods', 'caption': 'Durable household goods', 'additional_text': None}
{'header_chain': 'List of 1987 box office number-one films in the United States > Highest-grossing films > In-Year Release', 'caption': 'Highest-grossing films of 1987 by In-year release', 'additional_text': None}
{'header_chain': 'List of American films of 2022 > Box office', 'caption': 'Highest-grossing films of 2022', 'additional_text': 'The highest-grossing American films released in 2022, by domestic box office gross revenue , are as follows:'}
{'header_chain': 'List of residences of presidents of the United States > Other official residences occupied by presidents > Official residences occupied while in other offices', 'caption': None, 'additional_text': 'This is a list of official residences occupied by individuals who later served as presidents with their families while they served in the office related to the residence.'}
{'header_chain': 'List of tunnels in Bulgaria > Road tunnels', 'caption': None, 'additional_text': 'It does not include tunnels under construction.'}
{'header_chain': "List of Olympic men's ice hockey players for Russia > Goaltenders", 'caption': 'Goaltenders', 'additional_text': None}
{'header_chain': 'List of members of the Folketing, 2007–2011 > Party and member changes after the November 2007 elections > Party changes', 'caption': '', 'additional_text': 'Below are all parliament members that have joined another party or become independent during the term.'}
{'header_chain': 'List of dismissals and resignations in the first Trump administration > In the aftermath of the 2021 Capitol attack', 'caption': None, 'additional_text': 'Five senior officials at the Federal Aviation Administration (FAA) resigned in protest.'}
{'header_chain': 'List of universities and colleges in Hungary > Universities > Other Hungarian-language universities', 'caption': 'Hungarian-language universities not in Hungary', 'additional_text': None}
{'header_chain': 'List of Essendon Football Club players > Essendon Football Club players', 'caption': 'Key', 'additional_text': None}
{'header_chain': 'List of 2013 box office number-one films in Mexico > Highest-grossing films', 'caption': 'Highest-grossing films of 2013', 'additional_text': None}
{'header_chain': 'List of museums in Finland > National museums', 'caption': None, 'additional_text': 'National central museums of Finland are the Finnish Museum of Natural History , the National Museum of Finland and the Finnish National Gallery which comprises three museums; Ateneum , Kiasma , and the Sinebrychoff Art Museum .'}
{'header_chain': 'List of programs broadcast by Disney XD > Former programming > Programming from Disney Channel > Live-action series', 'caption': '', 'additional_text': 'Live-action series'}
{'header_chain': 'List of 2021 box office number-one films in New Zealand > Highest-grossing films', 'caption': 'Highest-grossing films of 2021', 'additional_text': None}
{'header_chain': "List of awards and nominations received by Cameron Diaz > Audience awards > Nickelodeon Kid's Choice Awards", 'caption': None, 'additional_text': '2 wins of 10 nominations'}
{'header_chain': 'List of earthquakes in 2001 > By month > February', 'caption': 'February', 'additional_text': None}
{'header_chain': 'List of animated feature films of 2022 > Highest-grossing animated films', 'caption': None, 'additional_text': 'The following is a list of the 10 highest-grossing animated feature films first released in 2022.'}
{'header_chain': 'List of Russian architects > Alphabetical list > M', 'caption': None, 'additional_text': 'Contents : Top 0–9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z'}
{'header_chain': 'List of American films of 2019 > Box office', 'caption': 'Highest-grossing films of 2019', 'additional_text': 'The highest-grossing American films released in 2019, by domestic box office gross revenue , are as follows:'}
{'header_chain': 'List of Atlanta Braves team records > Table key', 'caption': 'Table key', 'additional_text': None}
{'header_chain': 'List of awards and nominations received by Casualty > Digital Spy Reader Awards', 'caption': None, 'additional_text': 'The Digital Spy Reader Awards are an annual digital award ceremony ran by Digital Spy , voted for by readers of the website.'}
{'header_chain': 'List of caves in Croatia > Deepest caves', 'caption': None, 'additional_text': 'Further information: List of deepest Dinaric caves'}
{'header_chain': 'List of newspapers in Chile > Print newspapers > Daily circulation > National circulation', 'caption': None, 'additional_text': 'National circulation'}
{'header_chain': 'List of awards and nominations received by Miguel > NAACP Image Awards', 'caption': '', 'additional_text': 'Soul Train Music Awards'}
{'header_chain': 'List of earthquakes in 2024 > By month > January', 'caption': 'January', 'additional_text': None}
{'header_chain': 'List of galaxies by surface brightness > Table', 'caption': '', 'additional_text': 'Combining this with the original formula we get: S = m + 2.5 log 10 \u2061 ( π a 2 b 2 ) {\\displaystyle S=m+2.5\\log _{10}(\\pi {\\frac {a}{2}}{\\frac {b}{2}})} , which simplifies to S = m + 2.5 log 10 \u2061 π a b 4 {\\displaystyle S=m+2.5\\log _{10}{\\frac {\\pi ab}{4}}} .'}
{'header_chain': 'List of mosques in Bangladesh > Mosques > Chittagong Division > Comilla District', 'caption': None, 'additional_text': 'Comilla District'}
{'header_chain': 'List of awards and nominations received by Urmila Matondkar > Major awards > Zee Cine Awards', 'caption': None, 'additional_text': 'Matondkar has received one award out of four nominations.'}
{'header_chain': 'List of members of the 14th Bundestag > Summary', 'caption': None, 'additional_text': 'This summary includes changes in the numbers of the five caucuses ( CDU / CSU , SPD , Greens , FDP , Party of Democratic Socialism ):'}

In [226]:
from knowledge_maze.create_dataset.create_questions.visualization import WikiTableCleaner

# ==========================================
# USAGE EXAMPLE
# ==========================================

# Run the processor
cleaner = WikiTableCleaner()
new_dataset = cleaner.process_batch([a for a in ttttt_cleaned_data if a['table_name']['header_chain'].lower().startswith("list of")])

# # Print results
# import json

# print(json.dumps(new_dataset, indent=2, ensure_ascii=False))

==========================================================================================
                              WIKI TABLE PROCESSING SUMMARY
==========================================================================================
Total Tables Processed:   95
Passed (Closed Sets):     87
Rejected:                 8
Success Rate:             91.6%
------------------------------------------------------------------------------------------
                                     EXTRACTED GROUPS
------------------------------------------------------------------------------------------
 1. List of schools in the Northern Territory | Cols: ['Name', 'Suburb', 'LGA'] | Rows: 7
 2. List of mayors of Naples                 | Cols: ['Mayor', 'Deputy', 'Term start', 'Term end', 'Party'] | Rows: 12
 3. List of airlines of Cambodia             | Cols: ['Airline', 'IATA', 'ICAO', 'Callsign'] | Rows: 4
 4. List of ambassadors of Russia to France  | Cols: ['Name', 'Title']         | Rows: 9
 5. List of airlines of the Philippines      | Cols: ['Airline', 'Hubs and focus cities'] | Rows: 12
 6. List of power stations in Angola         | Cols: ['Location', 'Station', 'River'] | Rows: 6
 7. List of United States television stations available in Canada | Cols: ['Lloydminster', 'CKSA-DT 2 Citytv CITL-DT 4 CTV'] | Rows: 5
 8. List of Colorado Avalanche players       | Cols: ['Nat', 'Nationality']    | Rows: 4
 9. List of mayors of Clermont-Ferrand       | Cols: ['Mayor', 'Party']        | Rows: 12
10. List of animated feature films of 1988   | Cols: ['Title', 'Studio']       | Rows: 4
11. List of Chicago Blackhawks players       | Cols: ['Position']              | Rows: 9
12. List of awards and nominations received by Jonny Greenwood | Cols: ['Category', 'Nominated work', 'Result'] | Rows: 6
13. List of ambassadors of China to Belarus  | Cols: ['Name (English)', 'Tenure begins'] | Rows: 9
14. List of diplomatic missions of Switzerland | Cols: ['Organization', 'Mission', 'Host city', 'Host country'] | Rows: 11
15. List of stadiums in England              | Cols: ['Location', 'Stadium', 'Sport', 'Occupant'] | Rows: 7
16. List of aircraft manufactured by China   | Cols: ['Designation', 'Manufacturer', 'Status', 'Remarks'] | Rows: 11
17. List of companies listed on the Athens Stock Exchange | Cols: ['Company']               | Rows: 10
18. List of 1987 box office number-one films in the United States | Cols: ['Title', 'Distributor']  | Rows: 10
19. List of American films of 2022           | Cols: ['Title', 'Distributor']  | Rows: 10
20. List of common physics notations         | Cols: ['Name', 'Symbol', 'Meaning'] | Rows: 8
==========================================================================================

In [210]:
new_dataset[0].keys()

dict_keys(['Table context', 'Wiki link', 'Table data'])

In [227]:
for s in new_dataset:
    if s['Table context']['header_chain'].lower().startswith("list of"):
        if s['Table context']['caption'] or s['Table context']['additional_text']:
            for k,v in s['Table context'].items():
                print(f"{k}: {v}")
            print("-"*100)

header_chain: List of mayors of Naples > Deputy Mayor
caption: None
additional_text: The Deputy Mayor is nominated and eventually dismissed by the Mayor.
possible_entity_cols: ['Mayor', 'Deputy', 'Term start', 'Term end', 'Party']
----------------------------------------------------------------------------------------------------
header_chain: List of power stations in Angola > Hydroelectric
caption: None
additional_text: List of all hydroelectric power plants in Angola.
possible_entity_cols: ['Location', 'Station', 'River']
----------------------------------------------------------------------------------------------------
header_chain: List of Colorado Avalanche players > Key
caption: Abbreviations
additional_text: None
possible_entity_cols: ['Nat', 'Nationality']
----------------------------------------------------------------------------------------------------
header_chain: List of mayors of Clermont-Ferrand > Elected mayors
caption: None
additional_text: The mayors of Clermont-Ferrand from 1893 to present.
possible_entity_cols: ['Mayor', 'Party']
----------------------------------------------------------------------------------------------------
header_chain: List of Chicago Blackhawks players > Key
caption: Skaters
additional_text: None
possible_entity_cols: ['Position']
----------------------------------------------------------------------------------------------------
header_chain: List of awards and nominations received by Jonny Greenwood > Critics' Choice Movie Awards
caption: None
additional_text: The Critics' Choice Movie Awards are presented annually since 1995 by the Broadcast Film Critics Association for outstanding achievements in the cinema industry.
possible_entity_cols: ['Category', 'Nominated work', 'Result']
----------------------------------------------------------------------------------------------------
header_chain: List of stadiums in England > Future stadiums
caption: None
additional_text: Stadiums which are currently in development, and are likely to open in the near future, include:
possible_entity_cols: ['Location', 'Stadium', 'Sport', 'Occupant']
----------------------------------------------------------------------------------------------------
header_chain: List of companies listed on the Athens Stock Exchange > Personal and household goods
caption: Durable household goods
additional_text: None
possible_entity_cols: ['Company']
----------------------------------------------------------------------------------------------------
header_chain: List of 1987 box office number-one films in the United States > Highest-grossing films > In-Year Release
caption: Highest-grossing films of 1987 by In-year release
additional_text: None
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of American films of 2022 > Box office
caption: Highest-grossing films of 2022
additional_text: The highest-grossing American films released in 2022, by domestic box office gross revenue , are as follows:
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of residences of presidents of the United States > Other official residences occupied by presidents > Official residences occupied while in other offices
caption: None
additional_text: This is a list of official residences occupied by individuals who later served as presidents with their families while they served in the office related to the residence.
possible_entity_cols: ['President', 'Residence', 'Related office']
----------------------------------------------------------------------------------------------------
header_chain: List of tunnels in Bulgaria > Road tunnels
caption: None
additional_text: It does not include tunnels under construction.
possible_entity_cols: ['Tunnel', 'Coordinates']
----------------------------------------------------------------------------------------------------
header_chain: List of Olympic men's ice hockey players for Russia > Goaltenders
caption: Goaltenders
additional_text: None
possible_entity_cols: ['Player']
----------------------------------------------------------------------------------------------------
header_chain: List of members of the Folketing, 2007–2011 > Party and member changes after the November 2007 elections > Party changes
caption:
additional_text: Below are all parliament members that have joined another party or become independent during the term.
possible_entity_cols: ['Name', 'Old party', 'Constituency', 'New party']
----------------------------------------------------------------------------------------------------
header_chain: List of dismissals and resignations in the first Trump administration > In the aftermath of the 2021 Capitol attack
caption: None
additional_text: Five senior officials at the Federal Aviation Administration (FAA) resigned in protest.
possible_entity_cols: ['Name', 'Office', 'Left office']
----------------------------------------------------------------------------------------------------
header_chain: List of universities and colleges in Hungary > Universities > Other Hungarian-language universities
caption: Hungarian-language universities not in Hungary
additional_text: None
possible_entity_cols: ['Name', 'City', 'Type', 'Country']
----------------------------------------------------------------------------------------------------
header_chain: List of Essendon Football Club players > Essendon Football Club players
caption: Key
additional_text: None
possible_entity_cols: ['Players are listed in order of debut']
----------------------------------------------------------------------------------------------------
header_chain: List of 2013 box office number-one films in Mexico > Highest-grossing films
caption: Highest-grossing films of 2013
additional_text: None
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of museums in Finland > National museums
caption: None
additional_text: National central museums of Finland are the Finnish Museum of Natural History , the National Museum of Finland and the Finnish National Gallery which comprises three museums; Ateneum , Kiasma , and the Sinebrychoff Art Museum .
possible_entity_cols: ['Name']
----------------------------------------------------------------------------------------------------
header_chain: List of programs broadcast by Disney XD > Former programming > Programming from Disney Channel > Live-action series
caption:
additional_text: Live-action series
possible_entity_cols: ['Title']
----------------------------------------------------------------------------------------------------
header_chain: List of 2021 box office number-one films in New Zealand > Highest-grossing films
caption: Highest-grossing films of 2021
additional_text: None
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of awards and nominations received by Cameron Diaz > Audience awards > Nickelodeon Kid's Choice Awards
caption: None
additional_text: 2 wins of 10 nominations
possible_entity_cols: ['Nominated Work', 'Category', 'Results']
----------------------------------------------------------------------------------------------------
header_chain: List of animated feature films of 2022 > Highest-grossing animated films
caption: None
additional_text: The following is a list of the 10 highest-grossing animated feature films first released in 2022.
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of Russian architects > Alphabetical list > M
caption: None
additional_text: Contents : Top 0–9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
possible_entity_cols: ['Person']
----------------------------------------------------------------------------------------------------
header_chain: List of American films of 2019 > Box office
caption: Highest-grossing films of 2019
additional_text: The highest-grossing American films released in 2019, by domestic box office gross revenue , are as follows:
possible_entity_cols: ['Title', 'Distributor']
----------------------------------------------------------------------------------------------------
header_chain: List of Atlanta Braves team records > Table key
caption: Table key
additional_text: None
possible_entity_cols: ['Run(s) batted in']
----------------------------------------------------------------------------------------------------
header_chain: List of awards and nominations received by Casualty > Digital Spy Reader Awards
caption: None
additional_text: The Digital Spy Reader Awards are an annual digital award ceremony ran by Digital Spy , voted for by readers of the website.
possible_entity_cols: ['Category', 'Nominee', 'Result']
----------------------------------------------------------------------------------------------------
header_chain: List of caves in Croatia > Deepest caves
caption: None
additional_text: Further information: List of deepest Dinaric caves
possible_entity_cols: ['Name', 'Depth']
----------------------------------------------------------------------------------------------------
header_chain: List of newspapers in Chile > Print newspapers > Daily circulation > National circulation
caption: None
additional_text: National circulation
possible_entity_cols: ['City', 'Newspaper', 'Founded', 'Publisher']
----------------------------------------------------------------------------------------------------
header_chain: List of awards and nominations received by Miguel > NAACP Image Awards
caption:
additional_text: Soul Train Music Awards
possible_entity_cols: ['Award', 'Nominee / work', 'Result']
----------------------------------------------------------------------------------------------------
header_chain: List of galaxies by surface brightness > Table
caption:
additional_text: Combining this with the original formula we get: S = m + 2.5 log 10 ⁡ ( π a 2 b 2 ) {\displaystyle S=m+2.5\log _{10}(\pi {\frac {a}{2}}{\frac {b}{2}})} , which simplifies to S = m + 2.5 log 10 ⁡ π a b 4 {\displaystyle S=m+2.5\log _{10}{\frac {\pi ab}{4}}} .
possible_entity_cols: ['Galaxy', 'Dimensions', 'Type']
----------------------------------------------------------------------------------------------------
header_chain: List of mosques in Bangladesh > Mosques > Chittagong Division > Comilla District
caption: None
additional_text: Comilla District
possible_entity_cols: ['Name', 'Location', 'Tradition']
----------------------------------------------------------------------------------------------------
header_chain: List of members of the 14th Bundestag > Summary
caption: None
additional_text: This summary includes changes in the numbers of the five caucuses ( CDU / CSU , SPD , Greens , FDP , Party of Democratic Socialism ):
possible_entity_cols: ['Reason of change']
----------------------------------------------------------------------------------------------------

In [243]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(new_dataset)
await group_constructor.get_groups()

🚀 Grouping 87 tables using Pre-Filtered Context...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/87 [00:00<?, ?it/s]

══════════════════════════════════════════════════════════════════════════════════════════
                                    📊 GROUPING REPORT
══════════════════════════════════════════════════════════════════════════════════════════
  ✅ Valid Groups Extracted: 77
  ❌ Invalid/Rejected:       10
══════════════════════════════════════════════════════════════════════════════════════════

✨ SAMPLE RESULTS:
  • Nominees for the Digital Spy Reader Awards related to Casualty (Col: Nominee)
  • Future stadiums in England (Col: Stadium)
  • Non-elected members of the National Assembly of Zambia (1969–1973) (Col: Member)
  • Highest-grossing animated feature films released in 2022 (Col: Title)
  • Members of the 4th Lok Sabha nominated to the Indian Parliament (Col: Member)

──────────────────────────────────────────────────────────────────────────────────────────
                                   🕵️ REJECTION SAMPLES
──────────────────────────────────────────────────────────────────────────────────────────
  [PATH]: List of awards and nominations received by Lacey Turner > All About SoapBubble Awards
  [WHY]:  The table contains a summary of awards and nominations, which does not represent a coherent group of entities. The rows do not contain specific instances of a class, but rather categories and results.
  [PATH]: List of United States television stations available in Canada > Further information
  [WHY]:  The table does not have a clear entity column as the headers contain mixed content and do not represent unique instances of a class. Additionally, there is no specific title or context provided to derive a coherent group name.
  [PATH]: List of members of the 14th Bundestag > Summary
  [WHY]:  The table summarizes changes in caucus numbers rather than listing specific entities. It does not meet the criteria for valid entities as it contains categorical summaries and metrics.

In [244]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(group_constructor.valid_tables)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/77 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/77 [00:00<?, ?it/s]

✅ Strategy Selection Complete.

═══════════════════════════════════════════════════════
📊 STRATEGY SELECTION SUMMARY
-------------------------------------------------------
✅ Groups Passed:     77
❌ Groups Discarded:  0
📈 Success Rate:      100.0%
-------------------------------------------------------
Strategy Distribution (Top 4 per table):
  - UNIQUE_DIVERSITY          : 62
  - COUNT_TOTAL               : 37
  - FREQUENCY_MODE            : 34
  - EXTREME_TEMPORAL          : 34
  - CATEGORICAL_FILTER_LOOKUP : 26
  - FILTER_COUNT_TEMPORAL     : 23
  - EXTREME_NUMERICAL         : 9
  - TOP_K_RANKING             : 8
  - AGGREGATION               : 5
  - FILTER_COUNT_NUMERICAL    : 3
  - COMPARATIVE_DIFFERENCE    : 1
-------------------------------------------------------
POSSIBLE STRATEGIES  | GROUP COUNT  | PERCENTAGE
-------------------------------------------------------
#1                   | 8            |      10.4%
#2                   | 16           |      20.8%
#3                   | 10           |      13.0%
#4                   | 43           |      55.8%
═══════════════════════════════════════════════════════

In [245]:
import random
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(selector.updated_data,
                              strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 77 tables...
--- Round 1: Processing 77 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/77 [00:00<?, ?it/s]

--- Round 2: Processing 2 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/2 [00:00<?, ?it/s]

═════════════════════════════════════════════════════════════════
                  📊 QUESTION GENERATION SUMMARY
═════════════════════════════════════════════════════════════════
Initial Tables:      77
Successfully Gen:    77
Exhausted Strats:    0
Success Rate:        100.0%
-----------------------------------------------------------------
STRATEGY                     | SUCCESS  | TRIED    | RATE
-----------------------------------------------------------------
UNIQUE_DIVERSITY             | 13       | 14       |  93%
COUNT_TOTAL                  | 12       | 12       | 100%
FILTER_COUNT_TEMPORAL        | 11       | 11       | 100%
CATEGORICAL_FILTER_LOOKUP    | 11       | 11       | 100%
EXTREME_TEMPORAL             | 11       | 11       | 100%
FREQUENCY_MODE               | 10       | 11       |  91%
AGGREGATION                  | 2        | 2        | 100%
EXTREME_NUMERICAL            | 2        | 2        | 100%
TOP_K_RANKING                | 2        | 2        | 100%
FILTER_COUNT_NUMERICAL       | 2        | 2        | 100%
COMPARATIVE_DIFFERENCE       | 1        | 1        | 100%
-----------------------------------------------------------------
Total                        | 77       | 79       |  97%
═════════════════════════════════════════════════════════════════

🔍 SAMPLES OF FAILED DATA VIEWS:
-----------------------------------------------------------------

[1] Table: Ambassadors of China to Belarus
    Original Data: https://en.wikipedia.org/wiki/List_of_ambassadors_of_China_to_Belarus
    Strategy Attempted: UNIQUE_DIVERSITY
    Rejection Reason:   The dataset does not contain a categorical column that allows for counting distinct values, as it only lists names without any additional roles or categories. Therefore, I cannot apply the UNIQUE_DIVERSITY strategy.
    Table Data:

  Name (English) Name (Chinese)
0    Wang Xingda            王行达
1      Zhao Xidi            赵希迪
2     Wu Xiaoqiu            吴筱秋
3      Yu Zhenqi            于振起
4     Wu Hongbin            吴虹滨
5    Lu Guicheng            鲁桂成
6   Gong Jianwei            宫建伟
7     Cui Qiming            崔启明
8   Xie Xiaoyong            谢小用

-----------------------------------------------------------------

[2] Table: Diplomatic missions of Thailand in the Americas
    Original Data: https://en.wikipedia.org/wiki/List_of_diplomatic_missions_of_Thailand
    Strategy Attempted: FREQUENCY_MODE
    Rejection Reason:   There is a tie for the most frequent value in the 'Mission' column, making it impossible to identify a single absolute mode.
    Table Data:

              Mission   Host country
0             Embassy      Argentina
1             Embassy         Brazil
2             Embassy         Canada
3   Consulate-General         Canada
4             Embassy          Chile
5             Embassy         Mexico
6             Embassy           Peru
7             Embassy  United States
8   Consulate-General  United States
9   Consulate-General  United States
10  Consulate-General  United States

-----------------------------------------------------------------

In [246]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(generator.valid_results, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/66 [00:00<?, ?it/s]

In [247]:
from knowledge_maze.create_dataset.create_questions.question_validator import ManualTagger

tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 2 samples already tagged in 'tagger_progress.json'.

Output()

In [290]:
from knowledge_maze.create_dataset.create_questions.visualization import GroupMaker
import numpy as np

# gm = GroupMaker(debug=True)
gm = GroupMaker()
res_stats = []
guess = []
aaaaaaa = False

list_of_cleaned_data = [a for a in ttttt_cleaned_data if a['table_name']['header_chain'].lower().startswith('list of')]

for sample in random.sample(list_of_cleaned_data, 60):
    ctx = sample['table_name']
    data = sample['rows']

    print(f"Context: {ctx['header_chain']}")
    # print(f"Data:")
    # for row in data[:3]:
    #     print(row)
    # display(pd.DataFrame(data))
    # print(f"Debug process:")
    ent_col = gm.identify_entity_column(ctx, data)
    if ent_col:
        res_stats.append(True)
    else:
        res_stats.append(False)
    print(f"Identified Entity Column: {ent_col}")
    for idx, c in enumerate(data[0].keys()):
        if ent_col == c:
            guess.append(idx)
            aaaaaaa = True
            break
    if not aaaaaaa:
        guess.append(100)
    else:
        aaaaaaa = False
    print("-"*100)

print(Counter(guess))
print(f"Summary: {100 * np.mean(res_stats):.1f}% of table are considered valid by this code.")

Context: List of newspapers in Chile > Print newspapers > Daily circulation > National circulation
Identified Entity Column: Newspaper
----------------------------------------------------------------------------------------------------
Context: List of 1987 box office number-one films in the United States > Highest-grossing films > In-Year Release
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Courtney Love > Film > Critics associations
Identified Entity Column: Association
----------------------------------------------------------------------------------------------------
Context: List of Atlanta Braves team records > Table key
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of residences of presidents of the United States > Other official residences occupied by presidents > Official residences occupied while in other offices
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of Olympic men's ice hockey players for Russia > Goaltenders
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Miguel > NAACP Image Awards
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of 2021 box office number-one films in New Zealand > Highest-grossing films
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of governors of Trujillo > Elected governors
Identified Entity Column: Governor
----------------------------------------------------------------------------------------------------
Context: List of Chicago Blackhawks players > Key
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of programs broadcast by Disney XD > Former programming > Programming from Disney Channel > Live-action series
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Cameron Diaz > Audience awards > Nickelodeon Kid's Choice Awards
Identified Entity Column: Nominated Work
----------------------------------------------------------------------------------------------------
Context: List of writers associated with Balliol College, Oxford > Authors > Biographers  including auto-biographers
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of schools in the Northern Territory > Private schools > Defunct private schools
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of diplomatic missions of Bosnia and Herzegovina > Missions to open
Identified Entity Column: Host country
----------------------------------------------------------------------------------------------------
Context: List of Ozzy Osbourne members > Other contributors > Guest contributors
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Mahershala Ali > Major associations > Screen Actors Guild Awards
Identified Entity Column: Nominated work
----------------------------------------------------------------------------------------------------
Context: List of ambassadors of Austria to Spain > Heads of Mission > Austro-Hungarian Ambassadors (1867 to 1918)
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of common physics notations > Other characters
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of American Whig–Cliosophic Society members > Academia
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of ambassadors of China to Belarus > List of representatives
Identified Entity Column: Name (English)
----------------------------------------------------------------------------------------------------
Context: List of museums in Finland > National museums
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of sports films > Team sport > Volleyball
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of airlines of Cambodia > Scheduled airlines
Identified Entity Column: Airline
----------------------------------------------------------------------------------------------------
Context: List of airlines of the Philippines > Charter airlines
Identified Entity Column: Airline
----------------------------------------------------------------------------------------------------
Context: List of caves in Croatia > Deepest caves
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of Misfits band members > Members > Touring
Identified Entity Column: Name (real name)
----------------------------------------------------------------------------------------------------
Context: List of monarchs of Vietnam > Second independent period (1428–1802) > Northern and Southern dynasty (1533–1592) > Tonkin – Trịnh lords (1545–1787)
Identified Entity Column: Given name
----------------------------------------------------------------------------------------------------
Context: List of animated feature films of 1988 > Highest-grossing animated films of the year
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of Tamil films of 1998 > Awards
Identified Entity Column: Category/Organization
----------------------------------------------------------------------------------------------------
Context: List of tunnels in Bulgaria > Road tunnels
Identified Entity Column: Tunnel
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Charmed > RATTY Awards
Identified Entity Column: Nominee(s)
----------------------------------------------------------------------------------------------------
Context: List of wars involving the Delhi Sultanate > Lodi Dynasty
Identified Entity Column: Name of conflict(time)
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Dianne Wiest > Major Associations > Golden Globe Awards
Identified Entity Column: Nominated work
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Jonny Greenwood > Critics' Choice Movie Awards
Identified Entity Column: Nominated work
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Anna Kendrick > Teen Choice Awards
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of mergers and acquisitions by Yahoo > Acquisitions (2021 - present)
Identified Entity Column: Company
----------------------------------------------------------------------------------------------------
Context: List of former Buddhists > Christianity
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of paintings by Ford Madox Brown > 1880s
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of galaxies by surface brightness > Table
Identified Entity Column: Galaxy
----------------------------------------------------------------------------------------------------
Context: List of Essendon Football Club players > Essendon Football Club players
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Casualty > Digital Spy Reader Awards
Identified Entity Column: Nominee
----------------------------------------------------------------------------------------------------
Context: List of classical guitarists > Baroque (17th and 18th centuries)
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Urmila Matondkar > Major awards > Zee Cine Awards
Identified Entity Column: Film
----------------------------------------------------------------------------------------------------
Context: List of American films of 2019 > Box office
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of mayors of Bordeaux > Mayors (1790–1796)
Identified Entity Column: Mayor
----------------------------------------------------------------------------------------------------
Context: List of earthquakes in 2024 > By month > January
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of mayors of Naples > Deputy Mayor
Identified Entity Column: Deputy
----------------------------------------------------------------------------------------------------
Context: List of mayors of Clermont-Ferrand > Elected mayors
Identified Entity Column: Mayor
----------------------------------------------------------------------------------------------------
Context: List of diplomatic missions of Thailand > Current missions > Americas
Identified Entity Column: Host country
----------------------------------------------------------------------------------------------------
Context: List of earthquakes in 1921 > Overall > By magnitude
Identified Entity Column: Location
----------------------------------------------------------------------------------------------------
Context: List of 2013 box office number-one films in Mexico > Highest-grossing films
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of United States television stations available in Canada > Further information
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of aircraft manufactured by China > Trainers
Identified Entity Column: None
----------------------------------------------------------------------------------------------------
Context: List of stadiums in England > Future stadiums
Identified Entity Column: Stadium
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Barry Levinson > Major awards > Golden Globe Awards
Identified Entity Column: Nominated work
----------------------------------------------------------------------------------------------------
Context: List of awards and nominations received by Charlie Kaufman > Miscellaneous awards
Identified Entity Column: Award
----------------------------------------------------------------------------------------------------
Context: List of dismissals and resignations in the first Trump administration > In the aftermath of the 2021 Capitol attack
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Context: List of American films of 2022 > Box office
Identified Entity Column: Title
----------------------------------------------------------------------------------------------------
Context: List of Judas Priest band members > Members > Former
Identified Entity Column: Name
----------------------------------------------------------------------------------------------------
Counter({0: 27, 1: 13, 100: 10, 2: 9, 3: 1})
Summary: 83.3% of table are considered valid by this code.