# Related Papers:
- https://aclanthology.org/2024.acl-short.2.pdf
- https://aclanthology.org/2024.emnlp-main.171.pdf
- https://arxiv.org/pdf/2408.09174v1
- https://aclanthology.org/2025.findings-emnlp.638.pdf
- https://aclanthology.org/2025.emnlp-main.363.pdf

In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
from dotenv.main import load_dotenv

load_dotenv()
REPO_PATH = os.getenv('REPO_PATH')

sys.path.append(REPO_PATH)

In [2]:
import json

def load_json(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)

def save_json(file_name, file):
    with open(os.path.join(REPO_PATH, "data_files", f"{file_name}.json"), "w", encoding="utf-8") as out_file:
        json.dump(file, out_file, indent=4)

def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]

# Data Creation:

## Havest Wikipedia pages with tables:

In [91]:
from knowledge_maze.create_dataset.create_questions.wikipedia_mining import WikiHarvester
# Initialize Wikipedia harvester
harvester = WikiHarvester()
# Run Phase 1 - Harvesting titles based on keywords
harvester.run_complete_harvest()
# Run Phase 2 - Filtering pages for tables
await harvester.filter_pages_async()

Harvesting Pages By Keywords:   0%|          | 0/233 [00:00<?, ?keyword/s]

TOTAL UNIQUE TITLES COLLECTED: 167913

Filtering Pages with Tables:   0%|          | 0/167913 [00:00<?, ?page/s]

TOTAL PAGES WITH TABLES COLLECTED: 62306

In [93]:
save_json("table_titles", harvester.valid_titles)

In [3]:
table_titles = load_json("C:/Users/Daniel/Desktop/KnowledgeMaze/data_files/table_titles.json")

## Parse and filter Wikipedia tables:

In [271]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
validated_tables_file_name = await extractor.run_with_progress(table_titles)
validated_tables = load_jsonl(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
cleaned_data = processor.process()

Pre-processing: cluster similar pages and discard similarities ---> 6426 pages discarded.

Extracting Tables:   0%|          | 0/55880 [00:00<?, ?Page/s]

Starting Extraction: 55880 titles | Async Limit: 20 | CPU Workers: 19
TOTAL PAGES WITH VALID TABLES: 32076 OUT OF 55880 (57.4%)

Filtering & Cleaning:   0%|          | 0/94101 [00:00<?, ?it/s]

════════════════════════════════════════════
📊 TABLE PROCESSING SUMMARY (Limit: 12)
════════════════════════════════════════════
Total tables scanned:      94101
Dropped (Bad Headers):     8435
Dropped (Cell too long):   2841
Dropped (Repeat Rows):     1783
Short tables found:        39837
Unique source pages:       16940
Final sampled (1/page):    16940
════════════════════════════════════════════

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                  ↓ EXAMPLE TABLES ↓
------------------------------------------------------------------------------------------------------------------------------------------------------

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Canada women's national soccer team > Individual records > Most appearances
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

    Rank              Player        Career  Caps  Goals
0      1  Christine Sinclair     2000–2023   331    190
1      2      Sophie Schmidt     2005–2023   226     20
2      3      Diana Matheson     2003–2021   206     19
3      4       Desiree Scott     2010–2025   188      0
4      5     Rhian Wilkinson     2003–2017   181      7
5      6   Kadeisha Buchanan  2013–present   154      6
6      7     Ashley Lawrence  2013–present   151      8
7      7      Jessie Fleming  2013–present   151     20
8      9     Brittany Baxter     2002–2014   132      5
9      9         Andrea Neil     1991–2007   132     24
10     9        Adriana Leon  2013-present   132     44

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Manchester City F.C. 3–2 Queens Park Rangers F.C. > Match > Statistics
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

           Statistic Manchester City Queens Park Rangers
0       Goals scored               3                   2
1         Possession           81.3%               18.7%
2    Shots on target              15                   3
3   Shots off target              10                   0
4      Blocked shots              19                   0
5       Corner kicks              19                   0
6              Fouls               4                   7
7            Tackles              15                  22
8           Offsides               1                   1
9       Yellow cards               2                   1
10         Red cards               1                   1

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Swinburne University of Technology > Notable people > Academics and staff
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Member,Executive team,Period
0,Pascale Quester,Vice-Chancellor,2020–present
1,Chris Pilgrim,Pro Vice-Chancellor (Academic),
2,Tara Magdalinski,Pro Vice-Chancellor (Education and Quality),
3,Sarah Maddison,Pro Vice-Chancellor (Academic Innovation and C...,
4,Bronwyn Fox,Deputy Vice-Chancellor (Research and Enterprise),
5,Beth Webster,Pro Vice-Chancellor (Research Policy and Impact),
6,Qing-Lon Han,Pro Vice-Chancellor (Research Quality),
7,Alan Kin-Tak Lau,Pro Vice-Chancellor (International Research De...,
8,Blair Kuys,Dean of the School of Design and Architecture,
9,Matthew Bailes,Director of the Data Science Research Institut...,
10,Karl Glazebrook,Laureate Fellow of the Centre for Astrophysics...,
11,Alan Duffy,Director of the Space Technology and Industry ...,

## Create Potential Entity Groups:

In [642]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(random.sample(cleaned_data, 100))
await group_constructor.get_groups()

🚀 Grouping 100 tables using Entity-Focus logic...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/100 [00:00<?, ?it/s]

════════════════════════════════════════════════════════════════════════════════
                               📊 GROUPING REPORT
════════════════════════════════════════════════════════════════════════════════
  ✅ Valid Groups:   86
  ❌ Invalid Tables: 14
════════════════════════════════════════════════════════════════════════════════

✨ SAMPLE VALID NAMES:
  → Companies owned by Bonheur
  → Rectors of Iberoamerican University of Science and Technology (Chile)
  → Pumped-storage hydroelectric power stations in California

────────────────────────────────────────────────────────────────────────────────
                     🕵️ REJECTION DEBUGGER (Random Sample)
────────────────────────────────────────────────────────────────────────────────

[TABLE]: Demographics of Nepal > Vital statistics > Demographic and Health Survey (Ideal family size by gender and age group)
[REASON]: The table contains demographic categories (age groups) rather than unique instances of entities. It does not represent a coherent group of entities as required.
[DATA]:   {'Age': '15–19', 'Women': 1.9, 'Men': 2.2}

[TABLE]: List of erotic video games > Legend
[REASON]: The table is a summary of platforms and their corresponding systems, which does not represent a coherent group of unique entities.
[DATA]:   {'PC-88': 'PC-98', 'PC-8800 series': 'PC-9800 series'}

[TABLE]: Cleveland > Demographics (Historical racial/ethnic composition)
[REASON]: The table contains categories of race/ethnicity, which are generic labels rather than unique instances of entities.
[DATA]:   {'Race/ethnicity': 'White (non-Hispanic)', '2020': '32.1%', '2010': '33.4%', '1990': '47.8%', '1970': '59.4%', '1940': '90.2%'}

════════════════════════════════════════════════════════════════════════════════

In [643]:
for sample in random.sample(group_constructor.valid_tables, 25):
    print(f"Group name: {sample['Group name']}")
    print(f"Wikipedia page: {sample['Wikipedia link']}")
    print(f"Entity column: {sample['Entity column']}")
    display(pd.DataFrame(sample['Table data']))
    print()
    print()

Group name: Football clubs in the 1929–30 Football League Third Division North season
Wikipedia page: https://en.wikipedia.org/wiki/1929–30_York_City_F.C._season#Match_details
Entity column: Club

,Pos,Club,Pld,W,D,L,F,A,GA,Pts
0,4th,Chesterfield,42,22,6,14,76,56,1.36,50
1,5th,Lincoln City,42,17,14,11,83,61,1.36,48
2,6th,York City,42,15,16,11,77,64,1.2,46
3,7th,South Shields,42,18,10,14,77,74,1.04,46
4,8th,Hartlepools United,42,17,11,14,81,74,1.09,45
5,Key,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...
6,Source,,,,,,,,,

Group name: Players transferred to Birmingham City F.C. in 2013–14 season
Wikipedia page: https://en.wikipedia.org/wiki/2013–14_Birmingham_City_F.C._season#Transfers
Entity column: Player

              Date           Player                            Club †   Fee
0      1 July 2013      Tom Adeyemi                  ( Norwich City )  Free
1      1 July 2013     Neal Eardley                     ( Blackpool )  Free
2      1 July 2013        Lee Novak             ( Huddersfield Town )  Free
3      1 July 2013  Darren Randolph                    ( Motherwell )  Free
4      1 July 2013   Andrew Shinnie  ( Inverness Caledonian Thistle )  Free
5      3 July 2013       Matt Green                ( Mansfield Town )  Free
6  31 October 2013    Dariusz Dudka                       ( Levante )  Free
7  14 January 2014     Brian Howard                    ( CSKA Sofia )  Free
8  30 January 2014     Aaron Martin                   ( Southampton )  Free

Group name: Lighthouses in Sabah, Malaysia
Wikipedia page: https://en.wikipedia.org/wiki/List_of_lighthouses_in_Malaysia#Sabah
Entity column: Lighthouse

,Lighthouse,Lat/Long,Constituency,State
0,Pulau Kalampunian Lighthouse,"7.0521671, 116.7457880",Kudat,Sabah
1,Pulau Mantanani Lighthouse,"6.7166787, 116.305755",Kudat,Sabah
2,Pulau Tiga Lighthouse,"5.7555724, 115.6343140",Papar,Sabah
3,Pulau Kuraman Lighthouse,"5.223852157, 115.1354535",Labuan,Wilayah Persekutuan
4,Pulau Papan Lighthouse,"5.2529477, 115.2679977",Labuan,Wilayah Persekutuan
5,Batu Tinagat Lighthouse,"4.2299475, 117.9805426",Tawau,Sabah
6,Pulau Berhala Lighthouse,"5.8699292, 118.1455287",Sandakan,Sabah
7,Tanjung Trang Lighthouse,"5.4235944, 119.2091190",Lahad Datu,Sabah

Group name: Airports in Bhutan
Wikipedia page: https://en.wikipedia.org/wiki/List_of_airports_in_Bhutan#Airports
Entity column: Airport name

,Location,ICAO,IATA,Airport name,Coordinates,Runway,Elev.,Constructed,Status
0,Gelephu,VQGP,GLU,Gelephu Airport,26°53′04″N 090°27′51″E ﻿ / ﻿ 26.88444°N 90.464...,11/29: 1500 m Asphalt,290 m,2008,Operational
1,Jakar,VQBT,BUT,Bathpalathang Airport,27°33′52″N 090°44′43″E ﻿ / ﻿ 27.56444°N 90.745...,14/32: 1200 m Asphalt,2473 m,2011,Operational
2,Paro,VQPR,PBH,Paro International Airport,27°24′12″N 089°25′29″E ﻿ / ﻿ 27.40333°N 89.424...,15/33: 1964 x 29 m Asphalt,2235 m,1968,Operational
3,Trashigang,VQTY,YON,Yongphulla Airport (Yonphula Airport),27°15′22″N 091°30′55″E ﻿ / ﻿ 27.25611°N 91.515...,12/30: 1266 x 37 m Asphalt,2743 m,2010,Operational

Group name: TV Series about the Basque conflict
Wikipedia page: https://en.wikipedia.org/wiki/List_of_films_about_the_Basque_conflict#TV_Series
Entity column: Main title (Alternative title)

,Year,Country,Main title (Alternative title),Original title (Original script),Director,Subject
0,2008,Spain,Future: 48 hours,Futuro: 48 horas,Manuel Estudillo,"Drama, Thriller."
1,2011,Spain,The murder of Carrero Blanco,El asesinato de Carrero Blanco,Miguel Bardem,History. Assassination of Luis Carrero Blanco
2,2011,Spain,The price of freedom,El precio de la libertad,Ana Murugarren,"Drama, Thriller. Mario Onaindia"
3,2016,Spain,Cain's father,El padre de Caín,Salvador Calvo,Drama.
4,2018,Spain,Alleged guilty,Presunto culpable,,Thriller.
5,2020,Spain,The invisible line,La línea invisible,Mariano Barroso,"Drama, History."
6,2020,Spain,Patria,,Félix Viscarret Óscar Pedraza,Drama.
7,2021,Spain,Parot,,Gustavo Ron Rafael Montesinos,"Crime, Mystery, Thriller."
8,2024,Spain,The Executioners,Verdugos,Daniel Guzmán Andrea Jaurrieta,"Thriller, Drama."
9,2025,Spain,The Border,La frontera,María Pulido Yolanda Centeno,"Action, Drama, Thriller."

Group name: Teams in the 1947–48 Stoke City F.C. season
Wikipedia page: https://en.wikipedia.org/wiki/1947–48_Stoke_City_F.C._season#Final_league_table
Entity column: Team v t e

   Pos         Team v t e  Pld   W   D   L  GF  GA    GAv  Pts
0   13  Charlton Athletic   42  17   6  19  57  66  0.864   40
1   14            Everton   42  17   6  19  52  66  0.788   40
2   15         Stoke City   42  14  10  18  41  55  0.745   38
3   16      Middlesbrough   42  14   9  19  71  73  0.973   37
4   17   Bolton Wanderers   42  16   5  21  46  58  0.793   37

Group name: Programs with multiple major awards at the 39th Primetime Emmy Awards
Wikipedia page: https://en.wikipedia.org/wiki/39th_Primetime_Emmy_Awards#Most_major_awards
Entity column: Program

            Program Category Network  Number of Awards
0           Promise  Special     CBS                 5
1          L.A. Law    Drama     NBC                 3
2  The Golden Girls   Comedy     NBC                 3
3       Family Ties   Comedy     NBC                 2

Group name: League One teams in the 2022–23 Exeter City F.C. season
Wikipedia page: https://en.wikipedia.org/wiki/2022–23_Exeter_City_F.C._season#Competitions
Entity column: Team v t e

   Pos       Team v t e  Pld   W   D   L  GF  GA    GD  Pts
0   11     Lincoln City   46  14  20  12  47  47     0   62
1   12  Shrewsbury Town   46  17   8  21  52  61   − 9   59
2   13   Fleetwood Town   46  14  16  16  53  51     2   58
3   14      Exeter City   46  15  11  20  64  68   − 4   56
4   15    Burton Albion   46  15  11  20  57  79  − 22   56
5   16  Cheltenham Town   46  14  12  20  45  61  − 16   54
6   17   Bristol Rovers   46  14  11  21  58  73  − 15   53

Group name: Matches in the 1988–89 Associate Members' Cup Southern Section First Round
Wikipedia page: https://en.wikipedia.org/wiki/1988–89_Associate_Members'_Cup#First_round
Entity column: Home team

         Date                Home team  Score         Away team
0  17 January                Brentford    2–0      Notts County
1  17 January             Chesterfield    4–2  Cambridge United
2  17 January        Colchester United    3–1     Leyton Orient
3  17 January         Northampton Town  2 – 1   Southend United
4  17 January           Torquay United    3–0        Gillingham
5  18 January                  Reading    2–3   Hereford United
6  24 January           Bristol Rovers    2–1      Cardiff City
7  24 January  Wolverhampton Wanderers    3–0      Bristol City

Group name: Lyricists with multiple Filmfare Awards for Best Lyricist
Wikipedia page: https://en.wikipedia.org/wiki/Filmfare_Award_for_Best_Lyricist#Superlatives
Entity column: Recipient

   Wins                                          Recipient
0    13                                             Gulzar
1     8                                       Javed Akhtar
2     4                Anand Bakshi , Amitabh Bhattacharya
3     3  Shakeel Badayuni , Shailendra , Sameer , Praso...
4     2  Hasrat Jaipuri , Verma Malik, Gulshan Kumar Me...

Group name: Coaching staff of the Gambia national football team
Wikipedia page: https://en.wikipedia.org/wiki/Gambia_national_football_team#Coaching_staff
Entity column: Name

             Position                                               Name
0          Head Coach                                   Johnny McKinstry
1   Assistant Coaches                           Alagie Sarr Abdou Jammeh
2   Goalkeeping Coach                                     Alhagie Marong
3       Fitness Coach                                     Mikael Igendia
4       Match Analyst                                       Milad Samadi
5             Doctors               Dr. Ousman Colley Dr. Alhagie Jawara
6    Physiotherapists  Ebrima Jallow Modou Jarra Alassan Fofanah Hass...
7    Team Coordinator                                     Ousman Drammeh
8  Technical Director                                         Sang Ndong

Group name: Deans of the Faculty of Information at the University of Toronto
Wikipedia page: https://en.wikipedia.org/wiki/University_of_Toronto_Faculty_of_Information#Academic_leadership
Entity column: Name

             Term                        Name
0  2023 – Current               Javed Mostafa
1     2016 – 2023                  Wendy Duff
2     2009 – 2015                 Seamus Ross
3     2003 – 2008        Brian Cantwell Smith
4     1995 – 2003               Lynne Howarth
5     1990 – 1995             Adele M. Fasick
6     1984 – 1990              Ann H. Schabas
7     1979 – 1984         Katherine H. Packer
8     1972 – 1978  Francess Georgina Halpenny
9            1972               R. Brian Land

Group name: Teams in the Relegation Zone of Division One (1977)
Wikipedia page: https://en.wikipedia.org/wiki/Coventry_City_2–2_Bristol_City_(1977)#Pre-match
Entity column: Team

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Relegation
0,17,West Ham United,42,11,14,17,46,65,− 19,36,
1,18,Sunderland,41,11,12,18,46,52,− 6,34,
2,19,Bristol City,41,11,12,18,36,46,− 10,34,
3,20,Coventry City,41,10,14,17,46,57,− 11,34,Relegation zone
4,21,Stoke City,42,10,14,18,28,51,− 23,34,Relegation zone
5,22,Tottenham Hotspur (R),42,12,9,21,48,72,− 24,33,Relegation zone

Group name: Racial and ethnic composition of Chula Vista, California
Wikipedia page: https://en.wikipedia.org/wiki/Chula_Vista,_California#Demographics
Entity column: Race / Ethnicity ( NH = Non-Hispanic )

,Race / Ethnicity ( NH = Non-Hispanic ),Pop 2000,Pop 2010,Pop 2020,% 2000,% 2010,% 2020
0,White alone (NH),55042,49641,43720,31.71%,20.35%,15.87%
1,Black or African American alone (NH),7517,9972,12703,4.33%,4.09%,4.61%
2,Native American or Alaska Native alone (NH),593,600,488,0.34%,0.25%,0.18%
3,Asian alone (NH),18410,33581,40841,10.61%,13.77%,14.83%
4,Native Hawaiian or Pacific Islander alone (NH),883,1105,1140,0.51%,0.45%,0.41%
5,Other race alone (NH),273,360,1175,0.16%,0.15%,0.43%
6,Mixed race or Multiracial (NH),4765,6591,10722,2.75%,2.70%,3.89%
7,Hispanic or Latino (any race),86073,142066,164698,49.59%,58.24%,59.78%

Group name: Governors of Congo Central (1962–1972)
Wikipedia page: https://en.wikipedia.org/wiki/List_of_governors_of_Kongo_Central#Congo_Central
Entity column: Officeholder

,Province,Start,End,Officeholder,Title
0,Congo Central,6 September 1962,3 January 1967,Vital Faustin Moanda (b. 1923),"President, from 1965 governor"
1,Congo Central,3 January 1967,30 August 1967,Denis Paluku (1936–2014),Governor
2,Congo Central,30 August 1967,9 August 1968,François Luakabwanga,Governor
3,Congo Central,9 August 1968,5 August 1969,Bruno Ndala,Governor
4,Congo Central,5 August 1969,23 December 1970,Anaclet Kaniki,Governor
5,Congo Central,23 December 1970,24 February 1972,Dieudonné Boji,Governor

Group name: Pumped-storage hydroelectric power stations in California
Wikipedia page: https://en.wikipedia.org/wiki/List_of_power_stations_in_California#Hydroelectric
Entity column: Name

,Name,Location,Coordinates,Capacity ( MW ),Owner,Year
0,Castaic,Los Angeles County,34°35′15″N 118°39′24″W ﻿ / ﻿ 34.58750°N 118.65...,1500,"CDWR , LADWP",1973
1,Helms,Fresno County,37°02′21″N 118°57′49″W ﻿ / ﻿ 37.03917°N 118.96...,1212,PG&E,1984
2,J.S. Eastwood,Fresno County,37°08′52″N 119°15′24″W ﻿ / ﻿ 37.14778°N 119.25...,200,SCE,1987
3,Lake Hodges,San Diego County,33°03′29″N 117°07′08″W ﻿ / ﻿ 33.05806°N 117.11...,42,SDCWA,2012
4,O'Neill,Merced County,37°05′55″N 121°02′52″W ﻿ / ﻿ 37.09861°N 121.04...,25,USBR,1967
5,Thermalito,Thermalito,39°30′55″N 121°37′45″W ﻿ / ﻿ 39.51528°N 121.62...,120,CDWR,1968
6,William R. Gianelli,Merced County,37°04′07″N 121°04′48″W ﻿ / ﻿ 37.06861°N 121.08...,424,"CDWR , USBR",1968

Group name: Members of the Provincial Assembly of Punjab (2013-2018)
Wikipedia page: https://en.wikipedia.org/wiki/Politics_of_Muzaffargarh#2013_General_Elections
Entity column: Member

,Constituency,Constituency name,Member,Political party
0,PP-251,PP-251 (Muzaffargarh-I),Malik Ahmad Yar Hunjra,Pakistan Muslim League (N)
1,PP-252,PP-252 (Muzaffargarh-II),Muhammad Zeeshan Gurmani,Pakistan Muslim League (N)
2,PP-253,PP-253 (Muzaffargarh-III),Ghulam Murtaza Raheem Khar,Pakistan Muslim League (N)
3,PP-254,PP-254 (Muzaffargarh-IV),Hammad Nawaz Khan,Pakistan Muslim League (N)
4,PP-255,PP-255 (Muzaffargarh-V),Mian Alamdar Abbas Qureshi,Pakistan Muslim League (N)
5,PP-256,PP-256 (Muzaffargarh-VI),Muhammad Imran Qureshi,Pakistan Muslim League (N)
6,PP-257,PP-257 (Muzaffargarh-VII),Malik Ahmad Karim Qaswar Langrial,Pakistan Muslim League (N)
7,PP-258,PP-258 (Muzaffargarh-VIII),Syed Haroon Ahmed Sultan Bokhari,Pakistan Muslim League (N)
8,PP-259,PP-259 (Muzaffargarh-IX),None,
9,PP-260,PP-260 (Muzaffargarh-X),Syed Muhammad Sibtain Raza,Pakistan Muslim League (N)
10,PP-261,PP-261 (Muzaffargarh-XI),Sardar Aamir Talal Khan Gopang,Pakistan Muslim League (N)

Group name: Awards won by Westbrook in 2022
Wikipedia page: https://en.wikipedia.org/wiki/Westbrook_(company)#Awards
Entity column: Nominee(s)

,Year,Award,Category,Nominee(s),Result
0,2022,Academy Awards,Best Picture,"Tim White, Trevor White, and Will Smith",Nominated
1,2022,Academy Awards,Best Actor,Will Smith,Won
2,2022,Academy Awards,Best Supporting Actress,Aunjanue Ellis,Nominated
3,2022,Academy Awards,Best Original Screenplay,Zach Baylin,Nominated
4,2022,Academy Awards,Best Film Editing,Pamela Martin,Nominated
5,2022,Academy Awards,Best Original Song,"Beyoncé and DIXSON (for "" Be Alive "")",Nominated
6,2023,NAACP Image Awards,Outstanding Actor in a Motion Picture,Will Smith,Won
7,2023,NAACP Image Awards,Outstanding Motion Picture,Emancipation,Nominated
8,2023,NAACP Image Awards,Outstanding Ensemble Cast in a Motion Picture,The cast of Emancipation,Nominated
9,2023,NAACP Image Awards,Outstanding Directing in a Motion Picture,Antoine Fuqua,Nominated
10,2023,NAACP Image Awards,Outstanding Costume Design (TV or Film),Francine Jamison-Tanchuck,Nominated

Group name: Programs of study at Lebanese International University
Wikipedia page: https://en.wikipedia.org/wiki/Lebanese_International_University#The_School_of_Business
Entity column: Undergraduate majors/Programs of study

,Undergraduate majors/Programs of study,Graduate majors/Programs of study
0,Accounting Information Systems,Master's of Business Administration
1,Economics,LIU-Worms Master's of Business Administration
2,Banking & Finance,
3,Hospitality Management,
4,Business Management,
5,Management Information Systems,
6,International Business Management,
7,LIU-Worms International Business Management,

Group name: SmartLynx Airlines fleet
Wikipedia page: https://en.wikipedia.org/wiki/SmartLynx_Airlines#Fleet
Entity column: Aircraft

,Aircraft,In service,Passengers,Notes
0,Airbus A320-200,26,180,11 operated by SmartLynx Airlines Ltd. 8 opera...
1,Airbus A321-200,8,220,5 operated by SmartLynx Airlines Ltd. 3 operat...
2,Airbus A321-200P2F,10,Cargo,1 operated by SmartLynx Airlines Ltd. 9 operat...
3,Airbus A330-300,1,436,Operated by SmartLynx Airlines Malta.
4,Boeing 737 MAX 8,12,189,Operated by SmartLynx Airlines Malta.

Group name: 2017 World TeamTennis teams standings
Wikipedia page: https://en.wikipedia.org/wiki/2017_World_TeamTennis_season#Standings
Entity column: Team

   Pos                    Team  MP  W   L    Pct  MB   GW   GL
0    1  Orange County Breakers  14  9   5  0.643   0  302  242
1    2      San Diego Aviators  14  9   5  0.643   0  275  266
2    3         New York Empire  14  7   7  0.500   2  279  290
3    4      Springfield Lasers  14  7   7  0.500   2  270  284
4    5   Philadelphia Freedoms  14  6   8  0.429   3  270  282
5    6      Washington Kastles  14  4  10  0.286   5  263  295

Group name: Hydroelectric power stations in Latvia
Wikipedia page: https://en.wikipedia.org/wiki/List_of_power_stations_in_Latvia#Renewable
Entity column: Station

,Station,Town,Coordinates,Capacity ( MW ),Completed,Notes
0,Pļaviņas Hydroelectric Power Station,Aizkraukle,56°34′56″N 25°14′14″E ﻿ / ﻿ 56.5822027°N 25.23...,883.5,1965,
1,Riga Hydroelectric Power Plant,Salaspils,56°51′05″N 24°16′19″E ﻿ / ﻿ 56.8513187°N 24.27...,402.0,1974,
2,Ķegums Hydroelectric Power Station,Ķegums,56°44′26″N 24°42′39″E ﻿ / ﻿ 56.7406744°N 24.71...,264.1,1940,
3,Aiviekste Hydroelectric Power Station,,,0.8,1925,First hydroelectric power station in Latvia

Group name: Companies owned by Bonheur
Wikipedia page: https://en.wikipedia.org/wiki/Bonheur_(company)#Investments
Entity column: Company

                    Company                  Sector Ownership %
0  Fred. Olsen Cruise Lines                  Cruise        100%
1         Fred. Olsen Ocean  Shipping/Offshore wind        100%
2    Fred. Olsen Renewables        Renewable energy        100%
3   Fred. Olsen Windcarrier  Shipping/Offshore wind        100%
4       Fred. Olsens gate 2             Real estate        100%
5             Koksa Eiendom             Real estate       12.6%
6            DN Media Group                   Media         54%
7     Stavenes Byggeselskap             Real estate        100%

Group name: Freight cab units of EMD locomotives
Wikipedia page: https://en.wikipedia.org/wiki/List_of_EMD_locomotives#Freight_cab_units
Entity column: Model designation

,Model designation,Build year,Total produced,AAR wheel arrangement,Prime mover,Power output
0,FT,1939–1945,"555 A units , 541 B units",B-B ( B-B+B-B with B unit),EMD 16-567 EMD 16-567A,"2,700 hp (with B unit)"
1,F2,1946,"74 A units , 30 B units",B-B,EMD 16-567B,"1,350 hp (1000 kW)"
2,F3,1946–1949,"1,111 A units , 696 B units",B-B,EMD 16-567B,"1,500 hp (1,100 kW)"
3,F7,1949–1953,"2,366 A units , 1,483 B units",B-B,EMD 16-567B,"1,500 hp (1,100 kW)"
4,FP7,1949–1953,"381 A units , no B units",B-B,EMD 16-567B,"1,500 hp (1,200 kW )"
5,F9,1953–1960,"99 A units , 156 B units",B-B,EMD 16-567C,"1,750 hp (1200 kW)"
6,FP9,1954–1959,"90 A units , no B units",B-B,EMD 567C,"1,750 hp (1,300 kW )"
7,FL9,1956–1960,"60 A units , no B units",B-A1A,EMD 567C or EMD 567 D1; plus 660 V DC (3rd rail),"567C: 1,750 hp (1,300 kW ); 567D1: 1,800 hp (1..."

Group name: 1998–99 Football League First Division clubs performance
Wikipedia page: https://en.wikipedia.org/wiki/1998–99_Birmingham_City_F.C._season#Football_League_First_Division
Entity column: Club

,Pos,Club,Pld,W,D,L,F,A,GD,Pts
0,2nd,Bradford City,46,26,9,11,82,47,35,87
1,3rd,Ipswich Town,46,26,8,12,69,32,37,86
2,4th,Birmingham City,46,23,12,11,66,37,29,81
3,5th,Watford,46,21,14,11,65,56,9,77
4,6th,Bolton Wanderers,46,20,16,10,78,59,19,76
5,Key,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...,Pos = League position; Pld = Matches played; W...
6,Source,,,,,,,,,

## Create FanOut-style Questions out of the Entity Groups:

### Rule-Based Strategy Candidate Selection:

In [644]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(group_constructor.valid_tables)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/86 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/86 [00:00<?, ?it/s]

✅ Strategy Selection Complete.

═══════════════════════════════════════════════════════
📊 STRATEGY SELECTION SUMMARY
-------------------------------------------------------
✅ Groups Passed:     82
❌ Groups Discarded:  4
📈 Success Rate:      95.3%
-------------------------------------------------------
Strategy Distribution (Top 4 per table):
  - UNIQUE_DIVERSITY          : 55
  - EXTREME_TEMPORAL          : 36
  - COUNT_TOTAL               : 34
  - FILTER_COUNT_TEMPORAL     : 28
  - FREQUENCY_MODE            : 21
  - AGGREGATION               : 19
  - COMPARATIVE_DIFFERENCE    : 18
  - TOP_K_RANKING             : 15
  - FILTER_COUNT_NUMERICAL    : 13
  - CATEGORICAL_FILTER_LOOKUP : 12
  - EXTREME_NUMERICAL         : 11
-------------------------------------------------------
POSSIBLE STRATEGIES  | GROUP COUNT  | PERCENTAGE
-------------------------------------------------------
#1                   | 9            |      11.0%
#2                   | 14           |      17.1%
#3                   | 11           |      13.4%
#4                   | 48           |      58.5%
═══════════════════════════════════════════════════════

In [597]:
selector.debug_strategy_samples("FREQUENCY_MODE")

Found 204 total tables with this strategy. Showing 5 random samples.

🔗 Source: https://en.wikipedia.org/wiki/List_of_Academy_Awards_ceremonies#Nominated_hosts

              Host                  Category
0      David Niven                Best Actor
1    Michael Caine                Best Actor
2   Walter Matthau                Best Actor
3       Paul Hogan  Best Original Screenplay
4     James Franco                Best Actor
5  Seth MacFarlane        Best Original Song

🔗 Source: https://en.wikipedia.org/wiki/List_of_gig_economy_companies#List_of_gig_economy_companies

                   Company        Based in
0                   Fiverr          Israel
1                Airtasker       Australia
2   Amazon Mechanical Turk   United States
3                   Toloka   United States
4        Figure Eight Inc.   United States
5           Freelancer.com       Australia
6                   Upwork   United States
7            PeoplePerHour  United Kingdom
8                   Toptal   United States
9             Hello Alfred   United States
10             InnoCentive   United States

🔗 Source: https://en.wikipedia.org/wiki/List_of_churches_in_the_Diocese_of_Carlisle#Archdeaconry_of_West_Cumberland

                         Churches   Founded
0               St Andrew, Aikton  Medieval
1               St Mary, Beaumont  Medieval
2      St Michael, Burgh by Sands  Medieval
3           St Giles, Great Orton  Medieval
4           St Peter, Kirkbampton  Medieval
5   St Michael, Bowness-on-Solway  Medieval
6          St Kentigern, Caldbeck   Ancient
7              St Mary, Sebergham  Medieval
8    St Kentigern, Castle Sowerby  Medieval
9              St Hilda, Westward      1560
10               St James, Welton      1874
11           Holy Trinity, Rosley      1840

🔗 Source: https://en.wikipedia.org/wiki/List_of_earthquakes_in_1970#Overall

                                            Location                  MMI
0                      Peru , offshore northern Peru        X ( Extreme )
1                            China , Yunnan Province        X ( Extreme )
2                          Turkey , Kutahya Province        X ( Extreme )
3                           Iran , Golestan Province      VIII ( Severe )
4                   Soviet Union , Dagestan , Russia  VII ( Very strong )
5                               Peru , Tumbes Region        X ( Extreme )
6                                    India , Gujarat                  ( )
7  Australia , Madang Province , Papua and New Gu...      VIII ( Severe )
8                                Philippines , Luzon      VIII ( Severe )
9                              Peru , Huanuco Region       IX ( Violent )

🔗 Source: https://en.wikipedia.org/wiki/List_of_American_films_of_2024#Box_office

                     Title   Distributor
0             Inside Out 2        Disney
1     Deadpool & Wolverine        Disney
2                   Wicked     Universal
3                  Moana 2        Disney
4          Despicable Me 4     Universal
5  Beetlejuice Beetlejuice  Warner Bros.
6           Dune: Part Two  Warner Bros.
7                 Twisters     Universal
8    Mufasa: The Lion King        Disney
9     Sonic the Hedgehog 3     Paramount

### Model-Based Question Generation:

In [645]:
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(selector.updated_data,
                              strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 82 tables...
--- Round 1: Processing 82 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/82 [00:00<?, ?it/s]

--- Round 2: Processing 3 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/3 [00:00<?, ?it/s]

--- Round 3: Processing 2 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/2 [00:00<?, ?it/s]

--- Round 4: Processing 1 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1 [00:00<?, ?it/s]

═════════════════════════════════════════════════════════════════
                  📊 QUESTION GENERATION SUMMARY
═════════════════════════════════════════════════════════════════
Initial Tables:      82
Successfully Gen:    82
Exhausted Strats:    0
Success Rate:        100.0%
-----------------------------------------------------------------
STRATEGY                     | SUCCESS  | TRIED    | RATE
-----------------------------------------------------------------
COUNT_TOTAL                  | 13       | 14       |  93%
UNIQUE_DIVERSITY             | 11       | 11       | 100%
EXTREME_TEMPORAL             | 10       | 12       |  83%
FILTER_COUNT_TEMPORAL        | 9        | 9        | 100%
FREQUENCY_MODE               | 9        | 9        | 100%
CATEGORICAL_FILTER_LOOKUP    | 9        | 9        | 100%
COMPARATIVE_DIFFERENCE       | 5        | 7        |  71%
AGGREGATION                  | 4        | 4        | 100%
EXTREME_NUMERICAL            | 4        | 5        |  80%
TOP_K_RANKING                | 4        | 4        | 100%
FILTER_COUNT_NUMERICAL       | 4        | 4        | 100%
-----------------------------------------------------------------
Total                        | 82       | 88       |  93%
═════════════════════════════════════════════════════════════════

🔍 SAMPLES OF FAILED DATA VIEWS:
-----------------------------------------------------------------

[1] Table: Leadership of the 89th session of the Iowa Senate
    Original Data: https://en.wikipedia.org/wiki/List_of_members_of_the_89th_session_of_the_Iowa_Senate#Leadership
    Strategy Attempted: EXTREME_NUMERICAL
    Rejection Reason:   There are no numerical columns present in the data to apply the extreme numerical strategy.
    Table Data:

           Name  District
0  Jake Chapman        10
1     Brad Zaun        20
2  Jack Whitver        19
3    Zach Wahls        37

-----------------------------------------------------------------

[2] Table: Matches in the 1988–89 Associate Members' Cup Southern Section First Round
    Original Data: https://en.wikipedia.org/wiki/1988–89_Associate_Members'_Cup#First_round
    Strategy Attempted: EXTREME_TEMPORAL
    Rejection Reason:   There is a tie for the earliest date (multiple matches on 17 January), preventing a single absolute answer.
    Table Data:

                 Home team        Date
0                Brentford  17 January
1             Chesterfield  17 January
2        Colchester United  17 January
3         Northampton Town  17 January
4           Torquay United  17 January
5                  Reading  18 January
6           Bristol Rovers  24 January
7  Wolverhampton Wanderers  24 January

-----------------------------------------------------------------

[3] Table: Chennai City FC Kit Manufacturers and Shirt Sponsors
    Original Data: https://en.wikipedia.org/wiki/Chennai_City_FC#Kit_manufacturers_and_shirt_sponsors
    Strategy Attempted: COUNT_TOTAL
    Rejection Reason:   The data does not provide a list of distinct entities (kit manufacturers and shirt sponsors), only periods are mentioned.
    Table Data:

      Period
0  2016—2017
1  2017—2018
2  2018—2019
3  2019—2021

-----------------------------------------------------------------

## Question Validation:

### Model-Based Question Validator (Gemini 2.5 Flash):

In [646]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(generator.valid_results, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/73 [00:00<?, ?it/s]

### Manual Validation:

In [647]:
tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 0 samples already tagged in 'tagger_progress.json'.

Output()

# Tests:

In [543]:
from difflib import SequenceMatcher
import pandas as pd
from IPython.display import display, HTML

def audit_categorical_system(samples, fuzzy_threshold=0.9):
    categorical_strategies = ['UNIQUE_DIVERSITY', 'FREQUENCY_MODE', 'CATEGORICAL_FILTER_LOOKUP']
    
    # Filter targets
    target_samples = [s for s in samples if s.get('Selected strategy') in categorical_strategies]
    total_samples = len(target_samples)
    
    if total_samples == 0:
        print("🔍 No samples found for the specified categorical strategies.")
        return

    problematic_sample_indices = []
    column_stats = {}
    fail_details = []

    # --- PROCESSING ---
    for idx, sample in enumerate(target_samples):
        table = sample.get('Relevant table data', [])
        if not table or not isinstance(table, list): continue
        
        strat = sample.get('Selected strategy')
        all_cols = list(table[0].keys())
        if len(all_cols) <= 1: continue
        
        # Skip the first column (Entity Column)
        data_cols = all_cols[1:] 
        sample_has_issue = False
        
        for col in data_cols:
            if col not in column_stats:
                column_stats[col] = {'systemic_fails': 0, 'any_issue_count': 0}
            
            raw_values = [str(row.get(col, "")).strip() for row in table if row.get(col)]
            unique_vals = sorted(list(set(raw_values)), key=len)
            if len(unique_vals) < 2: continue
            
            issue_vals = set()
            for i in range(len(unique_vals)):
                for j in range(i + 1, len(unique_vals)):
                    v1, v2 = unique_vals[i].lower(), unique_vals[j].lower()
                    if v1 in v2 or SequenceMatcher(None, v1, v2).ratio() >= fuzzy_threshold:
                        issue_vals.update([unique_vals[i], unique_vals[j]])

            if issue_vals:
                column_stats[col]['any_issue_count'] += 1
                sample_has_issue = True
                
                # Check for Systemic Fail
                if len(issue_vals) == len(unique_vals):
                    column_stats[col]['systemic_fails'] += 1
                    fail_details.append({
                        'sample': sample,
                        'bad_col': col,
                        'bad_values': unique_vals
                    })

        if sample_has_issue:
            problematic_sample_indices.append(idx)

    # --- 1. THE BIG PICTURE SUMMARY ---
    clean_count = total_samples - len(problematic_sample_indices)
    
    display(HTML(f"""
    <div style="border: 2px solid #2c3e50; border-radius: 10px; padding: 20px; font-family: sans-serif; background-color: #f8f9fa;">
        <h2 style="margin-top: 0; color: #2c3e50;">📊 CATEGORICAL AUDIT: TOTAL PICTURE</h2>
        <div style="display: flex; gap: 40px;">
            <div style="text-align: center;">
                <h1 style="color: #27ae60; margin: 0;">{clean_count}</h1>
                <p style="color: #666;">CLEAN SAMPLES</p>
            </div>
            <div style="text-align: center;">
                <h1 style="color: #e74c3c; margin: 0;">{len(problematic_sample_indices)}</h1>
                <p style="color: #666;">PROBLEMATIC SAMPLES</p>
            </div>
            <div style="text-align: center; border-left: 1px solid #ccc; padding-left: 40px;">
                <h1 style="color: #2980b9; margin: 0;">{(clean_count/total_samples)*100:.1f}%</h1>
                <p style="color: #666;">SUCCESS RATE</p>
            </div>
        </div>
    </div>
    """))

    # --- 2. DRILL DOWN (SYSTEMIC FAILS) ---
    if fail_details:
        display(HTML("<h3 style='margin-top: 30px; color: #c0392b;'>🚨 SYSTEMIC FAILURES DETECTED</h3>"))
        
        for fail in fail_details:
            s = fail['sample']
            df_full = pd.DataFrame(s['Relevant table data'])
            
            # Highlight the problematic column in the display
            html_output = f"""
            <div style="margin-bottom: 40px; border-left: 5px solid #e74c3c; padding-left: 15px;">
                <p style="margin: 0;"><b>Strategy:</b> <span style="color: #2980b9;">{s['Selected strategy']}</span></p>
                <p style="margin: 5px 0;"><b>Question:</b> <span style="font-size: 1.1em; color: #2c3e50;">{s['Question']}</span></p>
                <p style="margin: 0; font-size: 0.9em; color: #c0392b;"><b>Issue:</b> Every value in column <b>'{fail['bad_col']}'</b> is a near-duplicate.</p>
                <div style="margin-top: 10px;">
                    {df_full.to_html(index=False)}
                </div>
            </div>
            <hr style="border: 0; border-top: 1px solid #eee;">
            """
            display(HTML(html_output))
    else:
        print("✅ No systemic failures found in the categorical attributes.")

# Usage
# audit_categorical_system(generator.valid_results)

In [596]:
audit_categorical_system(generator.valid_results)

In [570]:
cou = 0
tot = 0
sam = 0
for s in [a for a in generator.valid_results if a['Selected strategy'] == "TOP_K_RANKING"]:
    if "three" in s['Question'].lower():
       tot += 1
    sam += 1
print(f"Top 3: {tot/sam}")

Top 3: 1.0

In [557]:
cou = 0
tot = 0
sam = 0
for s in [a for a in generator.valid_results if a['Selected strategy'] == "AGGREGATION"]:
    if "total" in s['Question'].lower():
       tot += 1
    if "average" in s['Question'].lower():
       cou += 1
    sam += 1
print(f"Sum: {tot/sam}, Avg: {cou/sam}")

Sum: 0.9148936170212766, Avg: 0.0851063829787234

In [595]:
import pandas as pd
import re
from IPython.display import display, HTML

def audit_numeric_in_categorical(samples):
    categorical_strategies = ['UNIQUE_DIVERSITY', 'FREQUENCY_MODE', 'CATEGORICAL_FILTER_LOOKUP']
    target_samples = [s for s in samples if s.get('Selected strategy') in categorical_strategies]
    total_samples = len(target_samples)
    
    if total_samples == 0:
        print("🔍 No samples found for categorical strategies.")
        return

    problem_details = []
    problematic_sample_indices = set()

    # Regex to find: Integers, Decimals, and Ranges (e.g., 10-20, 10 to 20, 10/20)
    # This also handles currency symbols and commas
    num_pattern = re.compile(r'^[\$€£%]*\d+([.,]\d+)?([\s\-\/]+(to[\s\-]+)?\d+([.,]\d+)?[\$€£%]*)?$')

    for idx, sample in enumerate(target_samples):
        table = sample.get('Relevant table data', [])
        if not table or not isinstance(table, list): continue
        
        all_cols = list(table[0].keys())
        if len(all_cols) <= 1: continue
        
        data_cols = all_cols[1:]
        
        for col in data_cols:
            values = [str(row.get(col, "")).strip() for row in table if row.get(col)]
            if not values: continue
            
            # Find values that match numeric or range patterns
            numeric_values = [v for v in values if num_pattern.match(v.replace(',', ''))]

            # NEW THRESHOLD: 25% (1/4 of the column)
            if len(numeric_values) >= len(values) / 4:
                problematic_sample_indices.add(idx)
                problem_details.append({
                    'sample': sample,
                    'col': col,
                    'found_nums': list(set(numeric_values))
                })
                break 

    # --- 1. THE BIG PICTURE SUMMARY ---
    clean_count = total_samples - len(problematic_sample_indices)
    
    display(HTML(f"""
    <div style="border: 2px solid #8e44ad; border-radius: 10px; padding: 20px; font-family: sans-serif; background-color: #f4f0f7;">
        <h2 style="margin-top: 0; color: #8e44ad;">🔢 NUMERIC & RANGE AUDIT (Threshold: 25%)</h2>
        <div style="display: flex; gap: 40px;">
            <div style="text-align: center;">
                <h1 style="color: #27ae60; margin: 0;">{clean_count}</h1>
                <p style="color: #666;">CATEGORICAL PURITY</p>
            </div>
            <div style="text-align: center;">
                <h1 style="color: #e74c3c; margin: 0;">{len(problematic_sample_indices)}</h1>
                <p style="color: #666;">NUMERIC/RANGE LEAKS</p>
            </div>
            <div style="text-align: center; border-left: 1px solid #ccc; padding-left: 40px;">
                <h1 style="color: #8e44ad; margin: 0;">{(clean_count/total_samples)*100:.1f}%</h1>
                <p style="color: #666;">OVERALL QUALITY</p>
            </div>
        </div>
    </div>
    """))

    # --- 2. EXAMPLES (QUESTION + FULL TABLE) ---
    if problem_details:
        display(HTML("<h3 style='margin-top: 30px; color: #e67e22;'>⚠️ LEAKAGE EXAMPLES (Including Ranges)</h3>"))
        for p in problem_details:
            s = p['sample']
            df_full = pd.DataFrame(s['Relevant table data'])
            
            html_output = f"""
            <div style="margin-bottom: 40px; border-left: 5px solid #e67e22; padding-left: 15px;">
                <p style="margin: 0;"><b>Strategy:</b> {s['Selected strategy']}</p>
                <p style="margin: 5px 0;"><b>Question:</b> <span style="font-size: 1.1em; color: #2c3e50; font-weight: bold;">{s['Question']}</span></p>
                <p style="margin: 0; color: #d35400;"><b>Issue:</b> Column <b>'{p['col']}'</b> leaked numeric values or ranges: <code style="background: #fff; padding: 2px 5px;">{p['found_nums']}</code></p>
                <div style="margin-top: 10px;">
                    {df_full.to_html(index=False)}
                </div>
            </div>
            <hr style="border: 0; border-top: 1px solid #eee;">
            """
            display(HTML(html_output))
    else:
        print("✅ No numeric or range leakage detected in categorical columns!")

In [594]:
audit_numeric_in_categorical(generator.valid_results)