# Related Papers:
- https://aclanthology.org/2024.acl-short.2.pdf
- https://aclanthology.org/2024.emnlp-main.171.pdf
- https://arxiv.org/pdf/2408.09174v1
- https://aclanthology.org/2025.findings-emnlp.638.pdf
- https://aclanthology.org/2025.emnlp-main.363.pdf

In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
import random
from dotenv.main import load_dotenv

load_dotenv()
REPO_PATH = os.getenv('REPO_PATH')

sys.path.append(REPO_PATH)

In [2]:
import json
import numpy as np
import pandas as pd
from collections import Counter

In [3]:
def load_json(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)

def save_json(file_name, file):
    with open(os.path.join(REPO_PATH, "data_files", f"{file_name}.json"), "w", encoding="utf-8") as out_file:
        json.dump(file, out_file, indent=4)

def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]

def save_jsonl(file_name, records):
    path = os.path.join(REPO_PATH, "data_files", f"{file_name}.jsonl")
    with open(path, "w", encoding="utf-8") as out_file:
        for record in records:
            out_file.write(json.dumps(record, ensure_ascii=False) + "\n")

# Data Creation:

## Harvest Wikipedia pages with tables:

In [91]:
from knowledge_maze.create_dataset.create_questions.wikipedia_mining import WikiHarvester
# Initialize Wikipedia harvester
harvester = WikiHarvester()
# Run Phase 1 - Harvesting titles based on keywords
harvester.run_complete_harvest()
# Run Phase 2 - Filtering pages for tables
await harvester.filter_pages_async()

Harvesting Pages By Keywords:   0%|          | 0/233 [00:00<?, ?keyword/s]

TOTAL UNIQUE TITLES COLLECTED: 167913

Filtering Pages with Tables:   0%|          | 0/167913 [00:00<?, ?page/s]

TOTAL PAGES WITH TABLES COLLECTED: 62306

In [93]:
save_json("table_titles", harvester.valid_titles)

In [174]:
table_titles = load_json("C:/Users/Daniel/Desktop/KnowledgeMaze/data_files/table_titles.json")

## Parse and filter Wikipedia tables:

In [271]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
validated_tables_file_name = await extractor.run_with_progress(table_titles)
validated_tables = load_jsonl(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/final_tables.jsonl"))
cleaned_data = processor.process()

Pre-processing: cluster similar pages and discard similarities ---> 6426 pages discarded.

Extracting Tables:   0%|          | 0/55880 [00:00<?, ?Page/s]

Starting Extraction: 55880 titles | Async Limit: 20 | CPU Workers: 19
TOTAL PAGES WITH VALID TABLES: 32076 OUT OF 55880 (57.4%)

Filtering & Cleaning:   0%|          | 0/94101 [00:00<?, ?it/s]

════════════════════════════════════════════
📊 TABLE PROCESSING SUMMARY (Limit: 12)
════════════════════════════════════════════
Total tables scanned:      94101
Dropped (Bad Headers):     8435
Dropped (Cell too long):   2841
Dropped (Repeat Rows):     1783
Short tables found:        39837
Unique source pages:       16940
Final sampled (1/page):    16940
════════════════════════════════════════════

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                  ↓ EXAMPLE TABLES ↓
------------------------------------------------------------------------------------------------------------------------------------------------------

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Canada women's national soccer team > Individual records > Most appearances
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

    Rank              Player        Career  Caps  Goals
0      1  Christine Sinclair     2000–2023   331    190
1      2      Sophie Schmidt     2005–2023   226     20
2      3      Diana Matheson     2003–2021   206     19
3      4       Desiree Scott     2010–2025   188      0
4      5     Rhian Wilkinson     2003–2017   181      7
5      6   Kadeisha Buchanan  2013–present   154      6
6      7     Ashley Lawrence  2013–present   151      8
7      7      Jessie Fleming  2013–present   151     20
8      9     Brittany Baxter     2002–2014   132      5
9      9         Andrea Neil     1991–2007   132     24
10     9        Adriana Leon  2013-present   132     44

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Manchester City F.C. 3–2 Queens Park Rangers F.C. > Match > Statistics
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

           Statistic Manchester City Queens Park Rangers
0       Goals scored               3                   2
1         Possession           81.3%               18.7%
2    Shots on target              15                   3
3   Shots off target              10                   0
4      Blocked shots              19                   0
5       Corner kicks              19                   0
6              Fouls               4                   7
7            Tackles              15                  22
8           Offsides               1                   1
9       Yellow cards               2                   1
10         Red cards               1                   1

══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Swinburne University of Technology > Notable people > Academics and staff
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

,Member,Executive team,Period
0,Pascale Quester,Vice-Chancellor,2020–present
1,Chris Pilgrim,Pro Vice-Chancellor (Academic),
2,Tara Magdalinski,Pro Vice-Chancellor (Education and Quality),
3,Sarah Maddison,Pro Vice-Chancellor (Academic Innovation and C...,
4,Bronwyn Fox,Deputy Vice-Chancellor (Research and Enterprise),
5,Beth Webster,Pro Vice-Chancellor (Research Policy and Impact),
6,Qing-Lon Han,Pro Vice-Chancellor (Research Quality),
7,Alan Kin-Tak Lau,Pro Vice-Chancellor (International Research De...,
8,Blair Kuys,Dean of the School of Design and Architecture,
9,Matthew Bailes,Director of the Data Science Research Institut...,
10,Karl Glazebrook,Laureate Fellow of the Centre for Astrophysics...,
11,Alan Duffy,Director of the Space Technology and Industry ...,

## Create Potential Entity Groups:

In [296]:
list_of_cleaned_data = [a for a in cleaned_data if a['table_name'].lower().startswith('list of')]
len(list_of_cleaned_data)

5690

In [297]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(random.sample(list_of_cleaned_data, 1000))
await group_constructor.get_groups()

🚀 Grouping 1000 tables using Entity-Focus logic...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1000 [00:00<?, ?it/s]

════════════════════════════════════════════════════════════════════════════════
                               📊 GROUPING REPORT
════════════════════════════════════════════════════════════════════════════════
  ✅ Valid Groups:   933
  ❌ Invalid Tables: 67
════════════════════════════════════════════════════════════════════════════════

✨ SAMPLE VALID NAMES:
  → Towns on the Isle of Wight
  → Senior Staff Officers of the Indian Air Force
  → Railway stations in India starting with O

────────────────────────────────────────────────────────────────────────────────
                     🕵️ REJECTION DEBUGGER (Random Sample)
────────────────────────────────────────────────────────────────────────────────

[TABLE]: List of founders of religious traditions > Bibliography
[REASON]: The table contains categories of religious traditions rather than unique instances of entities. It does not meet the criteria for a coherent group of entities.
[DATA]:   {'Abrahamic': 'African', 'Baháʼí Christianity Islam Judaism Rastafari': 'Berber Egyptian Kongo Kushite'}

[TABLE]: List of Canadian Football League records (team) > Streaks
[REASON]: The table contains numerical records categorized by regions (West, East, North, South) rather than unique instances of entities. It does not meet the criteria for a coherent group of entities.
[DATA]:   {'West': 33, 'East': 0, 'North': 1, 'South': 0}

[TABLE]: List of NCHC All-Tournament Teams > All-Tournament Teams > All-Tournament Team players by school
[REASON]: The table contains generic categories (schools) and counts of winners, which does not represent unique instances of a class. It is a summary of counts rather than a coherent group of entities.
[DATA]:   {'School': 'St. Cloud State', 'Winners': 17}

════════════════════════════════════════════════════════════════════════════════

In [310]:
stst = []
for sample in random.sample(group_constructor.valid_tables, 100):
    try:
        stst.append(list(sample['Table data'][0].keys()).index(sample['Entity column']))
        print(sample['Group name'])
        print(sample['Entity column'])
        for row in sample['Table data'][:3]:
            print(row)
        print("=" * 100)
        # display(pd.DataFrame(sample['Table data']))
    except:
        pass
        stst.append('Failed')
# print(Counter(stst))

Grammy Awards received by Carly Simon
Award
{'Year': 1974, 'Work': 'No Secrets', 'Award': 'Best Engineered Recording', 'Recipient': 'Robin Geoffrey Cable and Bill Schnee', 'Result': 'Nominated'}
{'Year': 1976, 'Work': 'Playing Possum', 'Award': 'Best Album Package', 'Recipient': 'Gene Christensen A', 'Result': 'Nominated'}
{'Year': 1978, 'Work': '" Nobody Does It Better "', 'Award': 'Song of the Year', 'Recipient': 'Marvin Hamlisch and Carole Bayer Sager', 'Result': 'Nominated'}
====================================================================================================
Massacres in the Ottoman Empire before 1914
Name
{'Name': 'Massacres during the Greek War of Independence', 'Date': '1821–1829', 'Location': 'Ottoman Empire', 'Deaths': 'Unknown', 'Responsible Party': 'Ottoman government and Greek rebels', 'Victims': 'Greeks , Turks, Albanians and Jews', 'Notes': 'Massacres were committed by both sides during the conflict.'}
{'Name': 'Massacres of Badr Khan', 'Date': '1843-1846', 'Location': 'Hakkari', 'Deaths': '4,000-7,000', 'Responsible Party': 'Kurdish Emirs of Bhutan, Badr Khan and Nurullah', 'Victims': 'Assyrians', 'Notes': 'Many who were not killed were sold into slavery. 1826 Janissaries massacred by government (link to Auspicious Incident).'}
{'Name': 'Asheetha Revolt', 'Date': 1843, 'Location': 'Hakkari', 'Deaths': 10000, 'Responsible Party': 'Tyari Assyrians', 'Victims': 'Kurds', 'Notes': 'Assyrians of Lower Tyari revolted against the oppressive rule of the Kurdish Mir of Berwari,  and killed 10,000 Kurds of Bedir Khan.'}
====================================================================================================
Settlements in Palau by population
Settlement
{'Settlement': 'Koror', 'State': 'Koror', 'Population (2020)': 9524}
{'Settlement': 'Meyuns', 'State': 'Koror', 'Population (2020)': 1631}
{'Settlement': 'Ngetkib', 'State': 'Airai', 'Population (2020)': 630}
====================================================================================================
Argentine cheeses
Name
{'Name': 'Cremoso cheese', 'Description': "A fresh cheese elaborated with cow's milk , with or without the addition of cream. It has its origin in Argentina , and derives from Italian cheeses with similar characteristics as Crescenza ."}
{'Name': 'Criollo', 'Description': ''}
{'Name': 'Goya', 'Description': ''}
====================================================================================================
Closed diplomatic missions in Cameroon
Mission
{'Host city': 'Yaoundé', 'Sending country': 'Greece', 'Mission': 'Embassy', 'Year closed': 2009}
{'Host city': 'Yaoundé', 'Sending country': 'Netherlands', 'Mission': 'Embassy', 'Year closed': 2011}
{'Host city': 'Yaoundé', 'Sending country': 'North Korea', 'Mission': 'Embassy', 'Year closed': 1995}
====================================================================================================
Football clubs in North Macedonia
Club
{'Club': 'Arsimi', 'City / Town': 'Čegrane'}
{'Club': 'Bashkimi', 'City / Town': 'Kumanovo'}
{'Club': 'Brera Strumica', 'City / Town': 'Strumica'}
====================================================================================================
Largest airlines in North America by available seat miles (ASMs)
Airline
{'Rank': 1, 'Airline': 'United Airlines', 'Country': 'United States', '2024': 311, '2023': 291, '2022': 248, '2021': 179, '2020': 123, '2019': 285}
{'Rank': 2, 'Airline': 'American Airlines', 'Country': 'United States', '2024': 293, '2023': 278, '2022': 260, '2021': 215, '2020': 143, '2019': 285}
{'Rank': 3, 'Airline': 'Delta Air Lines', 'Country': 'United States', '2024': 288, '2023': 272, '2022': 233, '2021': 194, '2020': 134, '2019': 275}
====================================================================================================
Later CD-i games
Title
{'Title': 'The New Grolier Electronic Encyclopedia', 'Developer': 'Digimail', 'Publisher': 'World Of Games', 'Release date': 2024, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'Required'}
{'Title': "Origami: Doll's House", 'Developer': 'Eaglevision Interactive productions b.v.', 'Publisher': 'World Of Games', 'Release date': 2024, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'No'}
{'Title': 'Klik', 'Developer': 'Editions Renyi Inc and Sidac s.p.a', 'Publisher': 'World Of Games', 'Release date': 2023, 'U.S. release': 'Yes', 'EU release': 'No', 'Multi-player support': 'No', 'Digital Video Card status': 'No'}
====================================================================================================
Largest companies in the Philippines (2024)
Name
{'Rank': 1, 'Forbes 2000 rank': 806, 'Name': 'SM Investments', 'Headquarters': 'Pasay', 'Revenue (billions US$)': 10.3, 'Profit (billions US$)': 1.4, 'Assets (billions US$)': 28.4, 'Value (billions US$)': 18.6, 'Industry': 'Conglomerate'}
{'Rank': 2, 'Forbes 2000 rank': 880, 'Name': 'Banco de Oro', 'Headquarters': 'Mandaluyong', 'Revenue (billions US$)': 6.1, 'Profit (billions US$)': 1.3, 'Assets (billions US$)': 81.4, 'Value (billions US$)': 12.7, 'Industry': 'Banking'}
{'Rank': 3, 'Forbes 2000 rank': 1137, 'Name': 'Top Frontier Investment Holdings', 'Headquarters': 'Mandaluyong', 'Revenue (billions US$)': 26.0, 'Profit (billions US$)': 0.0, 'Assets (billions US$)': 47.1, 'Value (billions US$)': 0.6, 'Industry': 'Conglomerate'}
====================================================================================================
Members of the Legion of Super-Heroes who joined after the 'Five Year Gap'
Character
{'Character': 'Kono', 'Real name': "Brita An'nan", 'Home world': 'Sklar', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #2 (December 1989); joined in Legion of Super-Heroes vol. 4, #12 (October 1990).', 'Powers': 'Mass-shifting powers allow her to turn herself and others immaterial or super-dense.'}
{'Character': 'Neon', 'Real name': 'Celeste McCauley (a.k.a. Celeste Rockfish)', 'Home world': 'Earth', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #6 (April 1990).', 'Powers': 'Imbued with ancient Green Lantern energy.'}
{'Character': 'Reflex', 'Real name': "Devlin O'Ryan", 'Home world': 'Xanthu', 'Membership notes': 'First appeared in Legion of Super-Heroes vol. 4, #6 (April 1990); joined in Legion of Super-Heroes vol. 4, #40 (February 1993).', 'Powers': 'Can reflect physical and energy attacks back to their source.'}
====================================================================================================
Lakes of Latvia by depth
Name
{'Name': 'Drīdzis', 'Depth': '66.2 m (217 ft)'}
{'Name': 'Garais ezers', 'Depth': '56.0 m (183.7 ft)'}
{'Name': 'Lielais Gusena ezers', 'Depth': '56.0 m (183.7 ft)'}
====================================================================================================
Toonami block programs
Title
{'Title': 'FLCL', 'Premiere date': 'August 5, 2003', 'Finale date(s)': 'October 15, 2023'}
{'Title': 'Space Dandy', 'Premiere date': 'January 4, 2014', 'Finale date(s)': 'September 28, 2014'}
{'Title': 'Samurai Jack', 'Premiere date': 'March 11, 2017', 'Finale date(s)': 'May 20, 2017'}
====================================================================================================
Dubbed Malayalam films of 2001
Title
{'Title': 'City Hospital', 'Director': 'Moorthi', 'Screenplay': '', 'Cast': ''}
{'Title': 'Sukhamo Sukham', 'Director': 'KR Joshi', 'Screenplay': '', 'Cast': ''}
{'Title': 'Dheena', 'Director': 'AR Murukadas', 'Screenplay': 'AR Murukadas', 'Cast': 'Ajith Kumar, Suresh Gopi, Laila'}
====================================================================================================
Akademi Yuva Puraskar winners for Odia
Author
{'Year': 2011, 'Author': 'Gayatribala Panda', 'Book': 'Gaan', 'Category': 'Poetry'}
{'Year': 2012, 'Author': 'Srushthishree Naik', 'Book': 'Bhirna Upabana', 'Category': 'Short Stories'}
{'Year': 2013, 'Author': 'Kshetrabasi Naik', 'Book': 'Dadan', 'Category': 'Short Stories'}
====================================================================================================
Banned films in South Africa
Title
{'Date': 1910, 'Title': 'The Johnson-Jeffries Fight', 'Notes': 'Banned because the footage depicted the black boxer Jack Johnson defeating the white boxer James J. Jeffries , which had already inspired race riots in the American South.'}
{'Date': 1964, 'Title': 'Zulu', 'Notes': 'Banned under the apartheid regime from screening to black South Africans, because it depicts a Zulu uprising in the 19th century. Whites were allowed to see it in their own segregated cinemas.'}
{'Date': '1971–1984', 'Title': 'A Clockwork Orange', 'Notes': 'Banned under the apartheid regime for 13 years, then released with one cut and only made available to people over the age of 21.'}
====================================================================================================
Colleges and universities in the University of Missouri System
School
{'School': 'University of Missouri', 'Location(s)': 'Columbia', 'Control': 'Public', 'Type': 'Doctoral/very high activity research university', 'Enrollment (fall 2023)': 31543, 'Founded': 1839}
{'School': 'University of Missouri–Kansas City', 'Location(s)': 'Kansas City', 'Control': 'Public', 'Type': 'Doctoral/high activity research university', 'Enrollment (fall 2023)': 14732, 'Founded': 1933}
{'School': 'Missouri University of Science and Technology', 'Location(s)': 'Rolla', 'Control': 'Public', 'Type': 'Doctoral/high activity research university', 'Enrollment (fall 2023)': 7154, 'Founded': 1870}
====================================================================================================
Top ten grossing Philippine films of 2012
Film
{'Rank': 1.0, 'Film': 'Sisterakas', 'Production outfit': 'Star Cinema , Viva Films', 'Domestic gross 1': '₱ 393,439,711'}
{'Rank': 2.0, 'Film': 'The Mistress', 'Production outfit': 'Star Cinema', 'Domestic gross 1': '₱ 262,790,300'}
{'Rank': 3.0, 'Film': "This Guy's in Love with U Mare!", 'Production outfit': 'Star Cinema , Viva Films', 'Domestic gross 1': '₱ 249,105,182'}
====================================================================================================
Ten largest lakes in Jyväskylä
name
{'rank': 1, 'name': 'Päijänne', 'area (km 2 )': 1082.89}
{'rank': 2, 'name': 'Leppävesi', 'area (km 2 )': 63.593}
{'rank': 3, 'name': 'Muuratjärvi', 'area (km 2 )': 31.54}
====================================================================================================
Screen Actors Guild Awards received by Glenn Close
Nominated work
{'Year': 1995, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'Serving in Silence: The Margarethe Cammermeyer Story', 'Result': 'Nominated'}
{'Year': 1997, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'In the Gloaming', 'Result': 'Nominated'}
{'Year': 2004, 'Category': 'Outstanding Female Actor in a Miniseries or TV Movie', 'Nominated work': 'The Lion in Winter', 'Result': 'Won'}
====================================================================================================
Battles with most Romanian military fatalities
Battle or siege
{'Battle or siege': 'Siege of Odessa', 'Conflict': 'World War II', 'Date': 'August 8 to October 16, 1941', 'Estimated number killed': '17,729 killed', 'Opposing force': 'Soviet Union'}
{'Battle or siege': 'Battle of Mărășești', 'Conflict': 'World War I', 'Date': 'August 6 to September 3, 1917', 'Estimated number killed': '5,125 killed', 'Opposing force': 'Germany Austria-Hungary'}
{'Battle or siege': 'Battle of Mirăslău', 'Conflict': 'Long Turkish War', 'Date': 'September 18, 1600', 'Estimated number killed': 'Over 5,000 killed', 'Opposing force': 'Holy Roman Empire'}
====================================================================================================
Dungeons & Dragons video games in other settings
Title
{'Title': 'Dungeons & Dragons Computer Fantasy Game', 'Setting': 'Generic', 'Genre': 'Action', 'Platform(s)': 'Handheld LCD', 'Developer': 'Mattel', 'Release': 1981, 'Engine': ''}
{'Title': 'Advanced Dungeons & Dragons: Cloudy Mountain', 'Setting': 'Generic', 'Genre': 'Action-adventure', 'Platform(s)': 'Intellivision', 'Developer': 'Mattel', 'Release': 1982, 'Engine': ''}
{'Title': 'Advanced Dungeons & Dragons: Treasure of Tarmin', 'Setting': 'Generic', 'Genre': 'Action-adventure', 'Platform(s)': 'Intellivision', 'Developer': 'Tom Loughry', 'Release': 1982, 'Engine': ''}
====================================================================================================
Highest-grossing films in Japan in 2007
Title
{'Rank': 1, 'Title': "Pirates of the Caribbean: At World's End", 'Gross': '¥10.90 billion ( $92.57 million )'}
{'Rank': 2, 'Title': 'Harry Potter and the Order of the Phoenix', 'Gross': '¥9.40 billion ( $79.83 million )'}
{'Rank': 3, 'Title': 'Hero', 'Gross': '¥8.15 billion ( $69.21 million )'}
====================================================================================================
Former Omaha landmarks
Name
{'Name': 'Clarinda & Page Apartments', 'Location': '1027 Farnam Street, 305-11 Turner Boulevard', 'Built': 1909, 'Destroyed': 2014, 'Notes': 'Demolished by the Mutual of Omaha , now an empty lot.'}
{'Name': 'Monmouth Park School', 'Location': '4508 North 33rd Street', 'Built': 1903, 'Destroyed': 1995, 'Notes': 'Declared a health and safety hazard and razed.'}
{'Name': 'Guy C. Barton House', 'Location': '3522 Farnam St', 'Built': 1899, 'Destroyed': 1982, 'Notes': 'Destroyed in a fire'}
====================================================================================================
Ambassadors of Tajikistan to China
ambassador
{'diplomatic agreement/designated/ Diplomatic accreditation': 'January 4, 1992', 'ambassador': '', 'Russian language': '', 'Observations': 'China and Tajikistan established diplomatic relations in 1992. The Republic of Tajikistan opened its diplomatic mission in Beijing in March 1992', 'Prime Minister of Tajikistan': 'Akbar Mirzoyev', "Premier of the People's Republic of China": 'Li Peng', 'Term end': ''}
{'diplomatic agreement/designated/ Diplomatic accreditation': 'June 20, 1997', 'ambassador': 'Jamshed Karimov', 'Russian language': 'ru:Каримов, Джамшед Хилолович', 'Observations': '', 'Prime Minister of Tajikistan': 'Yahyo Azimov', "Premier of the People's Republic of China": 'Li Peng', 'Term end': ''}
{'diplomatic agreement/designated/ Diplomatic accreditation': 2002, 'ambassador': 'Bahodur Abdulloev', 'Russian language': '', 'Observations': '(*1948 in Bokhtar District ) A major general of state security.', 'Prime Minister of Tajikistan': 'Oqil Oqilov', "Premier of the People's Republic of China": 'Zhu Rongji', 'Term end': 'December 28, 2005'}
====================================================================================================
Exoplanets discovered by star type
Planet
{'Star type': 'First pulsar planet discovered', 'Planet': 'PSR B1257+12 B PSR B1257+12 C', 'Star': 'PSR B1257+12', 'Year': 1992, 'Notes': ''}
{'Star type': 'First known planet orbiting a white dwarf', 'Planet': 'PSR B1620-26 b', 'Star': 'PSR B1620-26', 'Year': 1993, 'Notes': 'Orbits a pulsar and a white dwarf. Discovery confirmed in 2003. GD 66 b was announced in 2007, but has not been confirmed.'}
{'Star type': 'First known extrasolar planet orbiting a main sequence star (Sun-like)', 'Planet': '51 Pegasi b', 'Star': '51 Pegasi', 'Year': 1995, 'Notes': 'First hot Jupiter .'}
====================================================================================================
Kings of Greece from the House of Schleswig-Holstein-Sonderburg-Glücksburg
Name Reign
{'Name Reign': 'George I ( Γεώργιος Αʹ ) 30 March 1863 – 18 March 1913', 'Duration of reign': '49 years, 353 days', 'Birth Date, location, parents': '24 December 1845 Copenhagen , Denmark Son of Christian IX of Denmark and Louise of Hesse-Kassel', 'Marriage(s) Issue': 'Olga Constantinovna of Russia 27 October 1867 8 children', 'Death': '18 March 1913 Thessaloniki , Ottoman Empire  Aged 67', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Third cousin once removed through Christian Karl Reinhard of Leiningen-Dagsburg-Falkenburg and then elected King of the Greeks.'}
{'Name Reign': 'Constantine I ( Κωνσταντῖνος Αʹ ) 18 March 1913 – 11 June 1917', 'Duration of reign': '4 years, 85 days', 'Birth Date, location, parents': '2 August 1868 Athens , Kingdom of Greece Son of George I of Greece and Olga Constantinovna of Russia', 'Marriage(s) Issue': 'Sophia of Prussia 27 October 1889 6 children', 'Death': '11 January 1923 Palermo , Kingdom of Italy Aged 54', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Son of George I'}
{'Name Reign': 'Alexander ( Ἀλέξανδρος ) 11 June 1917 – 25 October 1920', 'Duration of reign': '3 years, 136 days', 'Birth Date, location, parents': '1 August 1893 Athens , Kingdom of Greece Son of Constantine I of Greece and Sophia of Prussia', 'Marriage(s) Issue': 'Aspasia Manos 17 November 1919 1 child', 'Death': '25 October 1920 Athens , Kingdom of Greece Aged 27', 'Title Succession right': 'King of the Hellenes ( Βασιλεὺς τῶν Ἑλλήνων ) Son of Constantine I'}
====================================================================================================
Faculty members of the College of Arts and Science at New York University
Saul Bellow
{'Saul Bellow': 'Harold Bloom', 'Writer': 'Literary critic', 'Professor': 'Berg Professor of English', '1976 Nobel Prize in Literature': '1985 MacArthur Fellow'}
{'Saul Bellow': 'Faye D. Ginsburg', 'Writer': 'Scholar', 'Professor': 'Professor of Anthropology', '1976 Nobel Prize in Literature': '1994 MacArthur Fellow'}
{'Saul Bellow': 'Galway Kinnell', 'Writer': 'Poet', 'Professor': 'Professor', '1976 Nobel Prize in Literature': '1982 Pulitzer Prize for Poetry'}
====================================================================================================
Marathi films released in 1942
Film
{'Year': 1942, 'Film': 'Pahili Mangalagaur', 'Director': 'R.S. Junnarkar', 'Cast': 'Vishnupant Jog, Lata Mangeshkar , Shahu Modak ,Snehprabha Pradhan', 'Production': 'Prabhat Films', 'Notes': 'This film is primarily remembered for being the acting debut of legend Lata Mangeshkar'}
{'Year': 1942, 'Film': 'Kiti Hasaal', 'Director': 'Vasant Joglekar', 'Cast': '', 'Production': '', 'Notes': ''}
{'Year': 1942, 'Film': 'Pahila Palna', 'Director': 'Vishram Bedekar', 'Cast': 'Shanta Hublikar , Indu Natu, Baburao Pendharkar', 'Production': '', 'Notes': ''}
====================================================================================================
Obscura band touring members
Name
{'Name': 'Ernst "Azmo" Wurdak', 'Years active': 2004, 'Instruments': 'bass', 'Details': "Following the departure of Martin Ketzer, Wurdak filled in for the band's show at Walpurgis Metal Days IV."}
{'Name': 'Matthias "Seraph" Landes', 'Years active': 2007, 'Instruments': 'drums', 'Details': 'Landes filled in for Jonas Baumgartl, who was unavailable, for a European tour in September 2007.'}
{'Name': 'Jacob Schmidt', 'Years active': '2009 2011', 'Instruments': 'bass', 'Details': 'Schmidt filled in for regular bassist Jeroen Paul Thesseling at shows in October 2009 and early 2011.'}
====================================================================================================
Highest-grossing American films of 1987
Title
{'Rank': 1, 'Title': 'Three Men and a Baby', 'Distributor': 'Buena Vista', 'Domestic gross': '$167,780,960'}
{'Rank': 2, 'Title': 'Fatal Attraction', 'Distributor': 'Paramount', 'Domestic gross': '$156,645,693'}
{'Rank': 3, 'Title': 'Beverly Hills Cop II', 'Distributor': 'Paramount', 'Domestic gross': '$153,665,036'}
====================================================================================================
Members of the Folketing (1990–1994)

In [663]:
for sample in random.sample(group_constructor.valid_tables, 25):
    print(f"Group name: {sample['Group name']}")
    print(f"Wikipedia page: {sample['Wikipedia link']}")
    print(f"Entity column: {sample['Entity column']}")
    display(pd.DataFrame(sample['Table data']))
    print()
    print()

Group name: Artists with multiple nominations and awards at the Brit Awards 2006
Wikipedia page: https://en.wikipedia.org/wiki/Brit_Awards_2006#Multiple_nominations_and_awards
Entity column: Artist

  Awards         Artist
0      3  Kaiser Chiefs
1  2 (3)       Coldplay
2  2 (3)      Green Day
3  2 (3)    James Blunt

Group name: Awards and nominations received by Sam Smith at the iHeartRadio Music Awards
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Sam_Smith#iHeartRadio_Music_Awards
Entity column: Nominee / work

,Year,Nominee / work,Award,Result
0,2015,Sam Smith,Artist of the Year,Nominated
1,2015,Sam Smith,Best New Artist,Won
2,2015,"""Stay with Me""",Song of the Year,Nominated
3,2015,"""Stay with Me""",Best Lyrics,Nominated
4,2016,Sam Smith,Male Artist of the Year,Nominated
5,2016,In the Lonely Hour,Album of the Year,Nominated
6,2016,"""Writing's on the Wall""",Best Song from a Movie,Nominated
7,2016,""" Hotline Bling """,Best Cover Song,Nominated
8,2020,"""Dancing With A Stranger"" (with Normani)",Best Collaboration,Nominated
9,2020,"""Dancing With A Stranger"" (with Normani)",Best Music Video,Nominated
10,2021,"""Fix You""",Best Cover Song,Nominated

Group name: 1965 Tennessee Volunteers football schedule
Wikipedia page: https://en.wikipedia.org/wiki/1965_Tennessee_Volunteers_football_team#Schedule
Entity column: Opponent

,Date,Opponent,Rank,Site,TV,Result,Attendance,Source
0,September 18,Army *,,"Neyland Stadium Knoxville, TN",,W 21–0,48500,
1,September 25,Auburn,,"Neyland Stadium Knoxville, TN ( rivalry )",,T 13–13,43614,
2,October 9,South Carolina,,"Neyland Stadium Knoxville, TN (rivalry )",,W 24–3,38519,
3,October 16,at Alabama,,"Legion Field Birmingham, AL ( Third Saturday i...",,T 7–7,65680,
4,October 23,Houston *,,"Neyland Stadium Knoxville, TN",,W 17–8,34504,
5,November 6,No. 7 Georgia Tech *,,Neyland Stadium ( rivalry ),,W 21–7,52174,
6,November 13,vs. Ole Miss,No. 8,"Memphis Memorial Stadium Memphis, TN ( rivalry )",NBC,L 13–14,40181,
7,November 20,at Kentucky,,"McLean Stadium Lexington, KY ( rivalry )",,W 19–3,38000,
8,November 27,Vanderbilt,No. 9,"Neyland Stadium Knoxville, TN ( rivalry )",,W 21–3,36248,
9,December 4,No. 5 UCLA *,No. 7,"Memphis Memorial Stadium Memphis, TN",,W 37–34,44495,
10,December 18,vs. Tulsa,No. 7,"Rice Stadium Houston, TX ( Bluebonnet Bowl )",NBC,W 27–6,40000,

Group name: Villains from the Young Bond series by Charlie Higson
Wikipedia page: https://en.wikipedia.org/wiki/List_of_James_Bond_villains#Novel_villains_by_author
Entity column: Villain

,Novel,Villain,Objective,Outcome,Fate
0,SilverFin,Lord Randolph Hellebore,Achieve world domination with an army of human...,Bond and George Hellebore wreck his laboratory...,Eaten alive by eels alongside his mutated brot...
1,Blood Fever,Count Ugo Carnifex,Steal paintings and sculptures from around the...,His associate Zoltan floods his palace for his...,Dies in the chaos of the flooding fortress whe...
2,Double or Die,"Irina Sedova ""Babushka""",Create an innovative decoding machine for the ...,Bond destroys the machine.,"Spared by Bond. Returns in By Royal Command , ..."
3,Hurricane Gold,Mrs. Glass,Sell important American documents to the Japan...,Succeeds.,Imprisoned on Huracán's island.
4,Hurricane Gold,El Huracán,Punish all guests on his island who break his ...,Bond beats his obstacle course and escapes.,Spared by Bond.
5,By Royal Command,Dr. Perseus Friend,Assist the Nazi cause by making a plan to murd...,"Bond saves the king, destroys Friend's operati...",Shot in the face by Colonel Sedova.
6,By Royal Command,"Irina Sedova ""Babushka""",Find and kill Friend after King George is dead.,"Bond saves the king, destroys Friend's operati...","Shot by Bond, but survives because of her bull..."
7,""" A Hard Man to Kill "" (short story)",Emil Lefebrve,Help General Caiboche escape.,Succeeds.,
8,""" A Hard Man to Kill "" (short story)",Caiboche,Escape from custody.,Succeeds.,Survives.

Group name: Adelaide Strikers Captains
Wikipedia page: https://en.wikipedia.org/wiki/List_of_Adelaide_Strikers_players#Captains
Entity column: Name

              Name             Span  Mat  Won  Lost  Tied  NR  Win %
0  Michael Klinger          2011/12    7    2     5     0   0  28.57
1      Johan Botha  2012/13–2014/15   23   12     9     0   2  57.14
2   Phillip Hughes          2013/14    2    0     2     0   0   0.00
3       Brad Hodge  2015/16–2016/17   17   10     7     0   0  58.82
4      Travis Head  2017/18–2022/23   28   17    11     0   0  60.71
5     Colin Ingram  2017/18–2018/19   14    5     9     0   0  35.71
6       Alex Carey  2019/20–2020/21   16    7     8     0   1  46.66
7     Peter Siddle  2020/21–2022/23   27   12    15     0   0  44.44
8       Matt Short         2022/23-   20   12     8     0   0  60.00
9        Alex Ross          2024/25    3    2     1     0   0  66.67

Group name: Hosts of the European Men's and Women's Team Badminton Championships
Wikipedia page: https://en.wikipedia.org/wiki/European_Men's_and_Women's_Team_Badminton_Championships#Hosts
Entity column: Host city

    Year                Host city
0   2006    Thessalonica , Greece
1   2008     Almere , Netherlands
2   2010          Warsaw , Poland
3   2012  Amsterdam , Netherlands
4   2014      Basel , Switzerland
5   2016           Kazan , Russia
6   2018            Kazan, Russia
7   2020          Liévin , France
8   2022          Lahti , Finland
9   2024            Łódź , Poland
10  2026        Istanbul , Turkey

Group name: Major employers in Ohio
Wikipedia page: https://en.wikipedia.org/wiki/Economy_of_Ohio#Major_employers
Entity column: Employer

,Rank,Employer,Number of Ohio employees,Headquarters location,Sector
0,1,Cleveland Clinic Foundation,56986,Cleveland,Health
1,2,Kroger,44077,Cincinnati,Retail: Food Stores
2,3,Ohio State University and Medical Center,35656,Columbus,Education and Health
3,4,Wright Patterson Air Force Base,28000,Dayton,Government: Air Force base
4,5,University Hospitals Health System,30891,Cleveland,Health
5,6,Mercy Health Partners,30510,Cincinnati,Health
6,7,OhioHealth,30488,Columbus,Health
7,8,ProMedica,18712,Toledo,Health
8,9,Cincinnati Children's Hospital Medical Center,17204,Cincinnati,Health
9,10,Kettering Health,14413,Dayton,Health

Group name: Senators appointed during the 31st Parliament of Canada
Wikipedia page: https://en.wikipedia.org/wiki/List_of_senators_in_the_31st_Parliament_of_Canada#List_of_senators
Entity column: Name

,Name,Party,Province (Division),Date appointed,Appointed by,Left office,Reason
0,Robert de Cotret,Progressive Conservative,Ontario,"June 5, 1979",Clark,"January 14, 1980",Resignation
1,Richard Donahoe,Progressive Conservative,Nova Scotia,"September 13, 1979",Clark,"September 27, 1984",Retirement
2,Lowell Murray,Progressive Conservative,Ontario,"September 13, 1979",Clark,"September 26, 2011",Retirement
3,James Balfour,Progressive Conservative,Saskatchewan,"September 13, 1979",Clark,"December 12, 1999",Death
4,Arthur Tremblay,Progressive Conservative,Quebec,"September 27, 1979",Clark,"June 18, 1992",Retirement
5,Guy Charbonneau,Progressive Conservative,Quebec,"September 27, 1979",Clark,"June 21, 1997",Retirement
6,Martha Bielish,Progressive Conservative,Alberta,"September 27, 1979",Clark,"September 26, 1990",Resignation
7,Nathan Nurgitz,Progressive Conservative,Manitoba,"October 3, 1979",Clark,"February 9, 1993",Resignation
8,Heath MacQuarrie,Progressive Conservative,Prince Edward Island,"October 3, 1979",Clark,"September 18, 1994",Retirement
9,C. William Doody,Progressive Conservative,Newfoundland and Labrador,"October 3, 1979",Clark,"December 27, 2005",Death
10,Cyril Sherwood,Progressive Conservative,New Brunswick,"October 3, 1979",Clark,"July 1, 1990",Retirement

Group name: Honorary degrees received by A. P. J. Abdul Kalam
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_honours_received_by_A._P._J._Abdul_Kalam#Scholastic
Entity column: Degree

,Year,Degree,University,Country
0,2007,Doctor of Science and Technology,Carnegie Mellon University,United States
1,2007,Doctor of Science,University of Wolverhampton,United Kingdom
2,2008,Doctor of Science,Aligarh Muslim University,India
3,2008,Doctor of Science,Universiti Sains Malaysia,Malaysia
4,2008,Doctor of Engineering,Nanyang Technological University,Singapore
5,2009,Honorary Doctorate,Oakland University,United States
6,2010,Doctor of Engineering,University of Waterloo,Canada
7,2012,Doctor of Law,Simon Fraser University,Canada
8,2014,Doctor of Science,University of Edinburgh,United Kingdom

Group name: Teams in the 1987–88 Football League Second Division
Wikipedia page: https://en.wikipedia.org/wiki/1987–88_Birmingham_City_F.C._season#Football_League_Second_Division
Entity column: Team

    Pos                  Team  Pld   W   D   L  GF  GA    GD  Pts
0  17th       AFC Bournemouth   44  13  10  21  56  68  − 12   49
1  18th       Shrewsbury Town   44  11  16  17  42  54  − 12   49
2  19th       Birmingham City   44  11  15  18  41  66  − 25   48
3  20th  West Bromwich Albion   44  12  11  21  50  69  − 19   47
4  21st      Sheffield United   44  13   7  24  45  74  − 29   46

Group name: Teams in the 1997–98 Norwich City F.C. season
Wikipedia page: https://en.wikipedia.org/wiki/1997–98_Norwich_City_F.C._season#Final_league_table
Entity column: Team v t e

   Pos         Team v t e  Pld   W   D   L  GF  GA    GD  Pts
0   13      Bradford City   46  14  15  17  46  59  − 13   57
1   14    Tranmere Rovers   46  14  14  18  54  57   − 3   56
2   15       Norwich City   46  14  13  19  52  69  − 17   55
3   16  Huddersfield Town   46  14  11  21  50  72  − 22   53
4   17               Bury   46  11  19  16  42  58  − 16   52

Group name: UEFA Team of the Year Managers
Wikipedia page: https://en.wikipedia.org/wiki/UEFA_Team_of_the_Year#Most_appearances
Entity column: Manager

           Manager  Appearances
0    José Mourinho            4
1    Alex Ferguson            2
2  Gérard Houllier            1
3      Şenol Güneş            1
4   Frank Rijkaard            1
5    Pep Guardiola            1

Group name: Germany women's national youth football teams head coaches
Wikipedia page: https://en.wikipedia.org/wiki/Germany_women's_national_youth_football_teams#Head_coaches
Entity column: Team

          Team        Head coach
0     Under-23            Vacant
1  Under-19/20     Kathrin Peter
2     Under-17  Friederike Kromp
3     Under-16    Sabine Loderer
4     Under-15  Bettina Wiegmann

Group name: MTV Video Music Awards received by Garbage
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Garbage#List_of_awards
Entity column: Recipient/Work

,Year,Category,Recipient/Work,Result,Winner
0,1996,Breakthrough Video,""" Queer """,Nominated,"The Smashing Pumpkins "" Tonight, Tonight """
1,1996,Best New Artist in a Video,""" Stupid Girl """,Nominated,"Alanis Morissette "" Ironic """
2,1998,Best Group Video,""" Push It """,Nominated,"Backstreet Boys "" Everybody (Backstreet's Back) """
3,1998,Best Alternative Video,""" Push It """,Nominated,"Green Day "" Good Riddance (Time of Your Life) """
4,1998,Breakthrough Video,""" Push It """,Nominated,"The Prodigy "" Smack My Bitch Up """
5,1998,Best Direction,""" Push It """,Nominated,"Madonna "" Ray of Light """
6,1998,Best Editing,""" Push It """,Nominated,"Madonna "" Ray of Light """
7,1998,Best Art Direction,""" Push It """,Nominated,"Björk "" Bachelorette """
8,1998,Best Cinematography,""" Push It """,Nominated,"Fiona Apple "" Criminal """
9,1998,Best Special Effects,""" Push It """,Nominated,"Madonna "" Frozen """
10,1999,Best Special Effects,""" Special """,Won,"Garbage ""Special"""

Group name: Release history of the album 'We Walked in Song'
Wikipedia page: https://en.wikipedia.org/wiki/We_Walked_in_Song#Release_history
Entity column: Region

,Region,Date,Label,Format,Catalog
0,Japan,"March 8, 2007",P-Vine,CD,PCD-23875
1,North America,"March 13, 2007",Badman Recording Co.,CD,BRCD-939
2,Korea,"March 13, 2007",Pastel Music,CD,PMCD-303
3,Taiwan,"March 19, 2007",Avant Garden,"CD, Vinyl",AG1068
4,North America,"March 20, 2007",Badman Recording Co.,Vinyl,BRLP-939
5,Europe,"August 18, 2007",Fargo,CD/Deluxe Edition,FA0096

Group name: Current members of the Anaheim City Council
Wikipedia page: https://en.wikipedia.org/wiki/Anaheim_City_Council#Current_members
Entity column: Councilmember

,District,Councilmember,Party (officially nonpartisan),Entered office,Next election
0,Mayor,Ashleigh Aitken,Democratic,2022,2026
1,1,Ryan Balius,Independent,2024,2028
2,2,Carlos A. Leon,Democratic,2022,2026
3,3,Natalie Rubalcava,Democratic,2022,2026
4,4,Norma Campos Kurtz,Democratic,2023,2028
5,5,Kristen M. Maahs,Democratic,2024,2028
6,6,Natalie Meeks,Republican,2022,2026

Group name: 2019 Ngoma Awards Theatre Winners
Wikipedia page: https://en.wikipedia.org/wiki/Ngoma_Awards#2019_winners
Entity column: Winner

,Award,Winner,Also Nominated
0,Most Outstanding Stage Theatre Actress,Maureen Banda as Mwansa in The Throne,Barbara Mumpanga as Zoe in The Baby ; Karen Nd...
1,Most Outstanding Stage Theatre Production,Banjo – Green Buffaloes,The Baby – Nkhwazi; The Chosen One – Napsa
2,Most Outstanding Comedian,Abel Chungu Musuka,Cheelo Mwanachingwala; Emmanuel Munsaka
3,Most Outstanding Community Theatre Production,Kakhonyonyo – Jere Ensemble Arts Acre,Children of the Dead – Mwazanji Dance Theatre;...
4,Most Outstanding Stage Theatre Director,Bizwell Mudenda for Banjo – Green Buffaloes,Hamalala Hamalala for The Chosen One – Napsa; ...
5,Most Outstanding Male Community Theatre Artist,Jacob Wachata – Chamwaza Performing Arts (Solw...,Daniel Ngoma – Tusole Theatre (Livingstone); S...
6,Most Outstanding Female Community Theatre Artist,Onolina Zulu – Twiza Mobile Theatre (Chipata),Grace Mudenda – Mwazanji Community Dance Theat...

Group name: Academy Awards received by Tony Kushner
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Tony_Kushner#Major_associations
Entity column: Nominated work

   Year                  Category Nominated work     Result
0  2005   Best Adapted Screenplay         Munich  Nominated
1  2012   Best Adapted Screenplay        Lincoln  Nominated
2  2022              Best Picture  The Fabelmans  Nominated
3  2022  Best Original Screenplay  The Fabelmans  Nominated

Group name: Men's teams in the 1927 International Cross Country Championships
Wikipedia page: https://en.wikipedia.org/wiki/1927_International_Cross_Country_Championships#Team_Results
Entity column: Team

   Rank   Country                                               Team  Points
0     1    France  Seghir Beddari Henri Gallet Henri Lahitte Roge...      49
1     2   England  Lewis Payne Walter Beavers Ernie Harper Austin...      61
2     3  Scotland  Frank Stevenson Robert Miller Dunky Wright Joh...     112
3     4     Wales  Ernie Thomas E.R. Leyshon Danny Phillips Ted H...     120
4     5   Ireland  Pat Coyle Tommy Keating George Magan Patrick G...     145

Group name: Champions of the Low Countries Cup
Wikipedia page: https://en.wikipedia.org/wiki/Low_Countries_Cup#Champions
Entity column: Winner

   Year               Winner           Runner-up            3rd place
0  2006       Amstel Tijgers    Tilburg Trappers    Heerenveen Flyers
1  2005   Amsterdam Bulldogs   Heerenveen Flyers  Smoke Eaters Geleen
2  2004    Heerenveen Flyers  Amsterdam Bulldogs     Tilburg Trappers
3  1999  Smoke Eaters Geleen       HYC Herentals                 none
4  1998  Smoke Eaters Geleen           Den Bosch           IHC Leuven
5  1997        HYC Herentals           Den Bosch       Griffoens Geel
6  1996      Phantoms Deurne       HYC Herentals        HYS The Hague

Group name: MTV Movie & TV Awards received by John Travolta
Wikipedia page: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_John_Travolta#Other_associations
Entity column: Nominated work

,Year,Nominated work,Category,Result
0,1995,Pulp Fiction,Best Male Performance,Nominated
1,1995,Pulp Fiction,Best On-Screen Duo (shared with Samuel L. Jack...,Nominated
2,1995,Pulp Fiction,Best Dance Sequence (shared with Uma Thurman ),Won
3,1996,Broken Arrow,Best Villain,Nominated
4,1996,Broken Arrow,Best Fight (shared with Christian Slater ),Nominated
5,1997,Phenomenon,Best Male Performance,Nominated
6,1997,Phenomenon,Best Kiss (shared with Kyra Sedgwick ),Nominated
7,1998,Face/Off,Best Male Performance,Nominated
8,1998,Face/Off,Best Villain (shared with Nicolas Cage ),Nominated
9,1998,Face/Off,Best On-Screen Duo (shared with Nicolas Cage ),Won

Group name: Diplomatic missions of Syria in Africa
Wikipedia page: https://en.wikipedia.org/wiki/List_of_diplomatic_missions_of_Syria#Current_missions
Entity column: Host country

,Host country,Host city,Mission,Concurrent accreditation
0,Algeria,Algiers,Embassy,
1,Egypt,Cairo,Embassy,International Organizations : Arab League
2,Libya,Tripoli,Embassy,
3,Mauritania,Nouakchott,Embassy,
4,Nigeria,Abuja,Embassy,
5,Senegal,Dakar,Embassy,
6,South Africa,Pretoria,Embassy,Countries : Mauritius
7,Sudan,Khartoum,Embassy,Countries : Kenya
8,Tanzania,Dar es Salaam,Embassy,International Organizations : United Nations U...
9,Tunisia,Tunis,Embassy,

Group name: Racial and ethnic composition of Bay County, Florida
Wikipedia page: https://en.wikipedia.org/wiki/Bay_County,_Florida#Demographics
Entity column: Race / Ethnicity ( NH = Non-Hispanic )

,Race / Ethnicity ( NH = Non-Hispanic ),Pop 2000,Pop 2010,Pop 2020,% 2000,% 2010,% 2020
0,White (NH),122708,133790,128348,82.79%,79.24%,73.25%
1,Black or African American (NH),15526,17844,17549,10.48%,10.57%,10.02%
2,Native American or Alaska Native (NH),1096,1033,795,0.74%,0.61%,0.45%
3,Asian (NH),2534,3298,4068,1.71%,1.95%,2.32%
4,Native Hawaiian or Pacific Islander alone (NH),111,140,194,0.07%,0.08%,0.11%
5,Other race alone (NH),164,223,720,0.11%,0.13%,0.41%
6,Mixed race or Multiracial (NH),2487,4417,9696,1.68%,2.62%,5.53%
7,Hispanic or Latino,3591,8107,13846,2.42%,4.80%,7.90%

Group name: Guns N' Roses touring members
Wikipedia page: https://en.wikipedia.org/wiki/List_of_Guns_N'_Roses_members#Members
Entity column: Name

,Name,Years active,Instruments,Details
0,Fred Coury,1987–1988,drums,Coury substituted for Steven Adler between lat...
1,"Kid ""Haggis"" Chaos (Stephen Harris)",1988,bass,Harris replaced Duff McKagan for a show on May...
2,Don Henley,1989,drums backing vocals,Henley replaced Steven Adler for the 1989 Amer...
3,Teddy Andreadis,1991–1993,keyboards percussion harmonica backing vocals,Additional members of the Use Your Illusion To...
4,Roberta Freeman,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
5,Tracey Amos,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
6,Diane Jones,1991–1993,backing vocals tambourine,Additional members of the Use Your Illusion To...
7,Cece Worrall,1991–1993,saxophones,Additional members of the Use Your Illusion To...
8,Lisa Maxwell,1991–1993,saxophones,Additional members of the Use Your Illusion To...
9,Anne King,1991–1993,trumpet,Additional members of the Use Your Illusion To...

Group name: Racial and ethnic composition of Rapids City, Illinois
Wikipedia page: https://en.wikipedia.org/wiki/Rapids_City,_Illinois#Demographics
Entity column: Race / Ethnicity ( NH = Non-Hispanic )

,Race / Ethnicity ( NH = Non-Hispanic ),Pop 2000,Pop 2010,Pop 2020,% 2000,% 2010,% 2020
0,White alone (NH),924,922,889,96.96%,96.14%,92.22%
1,Black or African American alone (NH),0,2,8,0.00%,0.21%,0.83%
2,Native American or Alaska Native alone (NH),0,1,1,0.00%,0.10%,0.10%
3,Asian alone (NH),1,3,1,0.10%,0.31%,0.10%
4,Native Hawaiian or Pacific Islander alone (NH),1,0,0,0.10%,0.00%,0.00%
5,Other race alone (NH),1,0,1,0.10%,0.00%,0.10%
6,Mixed race or Multiracial (NH),6,10,27,0.63%,1.04%,2.80%
7,Hispanic or Latino (any race),20,21,37,2.10%,2.19%,3.84%

## Create FanOut-style Questions out of the Entity Groups:

### Rule-Based Strategy Candidate Selection:

In [311]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(group_constructor.valid_tables)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/933 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/933 [00:00<?, ?it/s]

✅ Strategy Selection Complete.

═══════════════════════════════════════════════════════
📊 STRATEGY SELECTION SUMMARY
-------------------------------------------------------
✅ Groups Passed:     897
❌ Groups Discarded:  36
📈 Success Rate:      96.1%
-------------------------------------------------------
Strategy Distribution (Top 4 per table):
  - UNIQUE_DIVERSITY          : 657
  - COUNT_TOTAL               : 473
  - EXTREME_TEMPORAL          : 472
  - FILTER_COUNT_TEMPORAL     : 354
  - FREQUENCY_MODE            : 266
  - CATEGORICAL_FILTER_LOOKUP : 235
  - EXTREME_NUMERICAL         : 91
  - AGGREGATION               : 84
  - TOP_K_RANKING             : 83
  - COMPARATIVE_DIFFERENCE    : 57
  - FILTER_COUNT_NUMERICAL    : 34
-------------------------------------------------------
POSSIBLE STRATEGIES  | GROUP COUNT  | PERCENTAGE
-------------------------------------------------------
#1                   | 79           |       8.8%
#2                   | 182          |      20.3%
#3                   | 181          |      20.2%
#4                   | 455          |      50.7%
═══════════════════════════════════════════════════════

In [316]:
selector.debug_strategy_samples("FREQUENCY_MODE")

Found 266 total tables with this strategy. Showing 5 random samples.

🔗 Source: https://en.wikipedia.org/wiki/List_of_motor_vehicle_awards#People

,Award,Sponsor
0,Automotive Executive of the Year Award,DNV GL - Business Assurance
1,Automotive Hall of Fame,MotorCities National Heritage Area
2,Car Designer of the Century,Global Automotive Elections Foundation
3,Car Engineer of the Century,Global Automotive Elections Foundation
4,Car Entrepreneur of the Century,Global Automotive Elections Foundation
5,Louis Schwitzer Award,Society of Automotive Engineers
6,Time Magazine Quality Dealer Award,"Time , Ally Financial"

🔗 Source: https://en.wikipedia.org/wiki/List_of_new_members_of_the_109th_United_States_Congress#Senate

              Senator                                   Prior background
0     Ken Salazar (D)                       Attorney General of Colorado
1    Mel Martinez (R)  U.S. Secretary of Housing and Urban Developmen...
2  Johnny Isakson (R)  U.S. House of Representatives  Georgia Senate ...
3    Barack Obama (D)                                    Illinois Senate
4    David Vitter (R)  U.S. House of Representatives  Louisiana House...
5    Richard Burr (R)                      U.S. House of Representatives
6      Tom Coburn (R)                      U.S. House of Representatives
7      Jim DeMint (R)                      U.S. House of Representatives
8      John Thune (R)                      U.S. House of Representatives

🔗 Source: https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Benedict_Cumberbatch#Major_awards

         Nominated work                                         Category
0  August: Osage County             Outstanding Cast in a Motion Picture
1      12 Years a Slave             Outstanding Cast in a Motion Picture
2    The Imitation Game             Outstanding Cast in a Motion Picture
3    The Imitation Game         Outstanding Male Actor in a Leading Role
4              Sherlock  Outstanding Male Actor in a Miniseries or Movie
5              Sherlock  Outstanding Male Actor in a Miniseries or Movie
6  The Power of the Dog         Outstanding Male Actor in a Leading Role

🔗 Source: https://en.wikipedia.org/wiki/List_of_power_stations_in_Idaho#Renewable_power_stations

                           Name           Primary fuel
0   Bannock County Landfill Gas           Landfill gas
1  Cargill Dry Creek Biofactory                 Biogas
2      Clearwater Paper Biomass        Wood/wood waste
3   Fighting Creek Landfill Gas           Landfill gas
4          Hidden Hollow Energy           Landfill gas
5             Milner Butte LFGE           Landfill gas
6                 Plummer Cogen        Wood/wood waste
7              Rock Creek Dairy                 Biogas
8             Simplot Don Plant  Industrial waste heat
9               Tamarack Energy        Wood/wood waste

🔗 Source: https://en.wikipedia.org/wiki/List_of_Dungeons_&_Dragons_video_games#List_of_games

                                             Title      Setting
0         Dungeons & Dragons Computer Fantasy Game      Generic
1     Advanced Dungeons & Dragons: Cloudy Mountain      Generic
2  Advanced Dungeons & Dragons: Treasure of Tarmin      Generic
3               Spelljammer: Pirates of Realmspace  Spelljammer
4                                       Stronghold      Generic
5                      Al-Qadim: The Genie's Curse     Al-Qadim
6                                           Slayer      Generic
7                                        DeathKeep      Generic
8                Birthright: The Gorgon's Alliance   Birthright
9                       Dungeons & Dragons Tactics      Generic

### Model-Based Question Generation:

In [312]:
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(random.sample(selector.updated_data, 100),
                              strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 100 tables...
--- Round 1: Processing 100 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/100 [00:00<?, ?it/s]

--- Round 2: Processing 1 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1 [00:00<?, ?it/s]

═════════════════════════════════════════════════════════════════
                  📊 QUESTION GENERATION SUMMARY
═════════════════════════════════════════════════════════════════
Initial Tables:      100
Successfully Gen:    100
Exhausted Strats:    0
Success Rate:        100.0%
-----------------------------------------------------------------
STRATEGY                     | SUCCESS  | TRIED    | RATE
-----------------------------------------------------------------
COUNT_TOTAL                  | 16       | 16       | 100%
UNIQUE_DIVERSITY             | 15       | 15       | 100%
EXTREME_TEMPORAL             | 14       | 14       | 100%
FILTER_COUNT_TEMPORAL        | 13       | 13       | 100%
FREQUENCY_MODE               | 13       | 14       |  93%
CATEGORICAL_FILTER_LOOKUP    | 13       | 13       | 100%
AGGREGATION                  | 4        | 4        | 100%
EXTREME_NUMERICAL            | 3        | 3        | 100%
TOP_K_RANKING                | 3        | 3        | 100%
COMPARATIVE_DIFFERENCE       | 3        | 3        | 100%
FILTER_COUNT_NUMERICAL       | 3        | 3        | 100%
-----------------------------------------------------------------
Total                        | 100      | 101      |  99%
═════════════════════════════════════════════════════════════════

🔍 SAMPLES OF FAILED DATA VIEWS:
-----------------------------------------------------------------

[1] Table: Automotive award recipients
    Original Data: https://en.wikipedia.org/wiki/List_of_motor_vehicle_awards#People
    Strategy Attempted: FREQUENCY_MODE
    Rejection Reason:   There is no single most frequent award as all awards are unique in the dataset.
    Table Data:

,Award,Sponsor
0,Automotive Executive of the Year Award,DNV GL - Business Assurance
1,Automotive Hall of Fame,MotorCities National Heritage Area
2,Car Designer of the Century,Global Automotive Elections Foundation
3,Car Engineer of the Century,Global Automotive Elections Foundation
4,Car Entrepreneur of the Century,Global Automotive Elections Foundation
5,Louis Schwitzer Award,Society of Automotive Engineers
6,Time Magazine Quality Dealer Award,"Time , Ally Financial"

-----------------------------------------------------------------

## Question Validation:

### Model-Based Question Validator (Gemini 2.5 Flash):

In [313]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(generator.valid_results, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/91 [00:00<?, ?it/s]

### Manual Validation:

In [318]:
tagger = ManualTagger(validator.approved_data, load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
tagger.display() # Render the output area

📦 Progress Loaded: 14 samples already tagged in 'tagger_progress.json'.

Output()

# Tests:

## 1. Harvest Wikipedia pages with tables:

1. **The Discovery Phase (The Wide Net)**
   - Input: 22 Subject Groups (e.g., Infrastructure, Sports).
   - Action: We hit the Wikipedia API with two distinct patterns:
     - Prefix Mining: Grabbing every page starting with "Entity in/of..."
     - Search Mining: Finding every page with "List of [Entity]" in the title.
     - Goal: Maximum recall. We want to find everything that might be a list.
2. **The Validation Phase (The Filter)**
   - Action: We open every page found in Phase 1 (asynchronously for speed).
   - Logic: We look for the "DNA" of a table: the {| or wikitable tags.
   - Outcome: We discard the "stub" articles or prose-only pages that don't actually contain structured data.
3. **The Clustering Phase (The De-duplicator)**
   - Problem: Wikipedia often has "List of 2023 Films" and "List of films of 2023." These are duplicates.
   - Action: Using TF-IDF to cluster similar page titles.
   - If two titles are >80% similar, we draw a line (edge) between them.
   - Pick a representative from each cluster to continue.

In [12]:
from knowledge_maze.create_dataset.create_questions.wikipedia_mining import WikiMiner

miner = WikiMiner()
await miner.extract()

Mining Pages:   0%|          | 0/320 [00:00<?, ?entity/s]

Filtering Pages with Tables:   0%|          | 0/89666 [00:00<?, ?page/s]

Computing Similarities for 43937 Titles:   0%|          | 0/43937 [00:00<?, ?titles/s]

Picking Representatives from 39391 Clusters:   0%|          | 0/39391 [00:00<?, ?cluster/s]

## 2. Parse and filter valid Wikipedia tables:

1. **Geometric Fix** - Rebuilds the "hidden grid" of the table. It maps merged cells (rowspans) to their correct spots so the data doesn't shift.
2. **Context Grab** - Captures the Section Path (e.g., Earthquakes > 1954) and the Intro Sentence above the table to explain what the data means.
3. **Trash Filter** - Deletes "Legend" tables, empty tables, and tiny snippets. If it's less than 4 rows or 50% empty, it’s gone.
4. **Variety Control** - "Detects ""Clones"" (like 12 identical monthly tables). It keeps a maximum of 4 different tables per page to ensure the dataset isn't boring.

In [93]:
save_json("valid_titles", miner.valid_titles)

In [4]:
valid_titles = load_json(os.path.join(REPO_PATH, "data_files/valid_titles.json"))

In [5]:
from knowledge_maze.create_dataset.create_questions.table_processing import AsyncWikiExtractor, TablePostProcessor

extractor = AsyncWikiExtractor(output_file=os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
validated_tables_file_name = await extractor.run_with_progress(valid_titles) # (miner.valid_titles)

processor = TablePostProcessor(os.path.join(REPO_PATH, "data_files/candidate_tables.jsonl"))
cleaned_data = processor.process()

Extracting Tables:   0%|          | 0/39391 [00:00<?, ?Page/s]

Starting Extraction: 39391 titles | Async Limit: 5 | CPU Workers: 7

Filtering & Cleaning:   0%|          | 0/64646 [00:00<?, ?it/s]

In [6]:
processor.display_sample()

,Formation name,Created,Ceased to exist,Locations served,Notes
0,1st Division,18 June 1809,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
1,2nd Division,18 June 1809,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
2,3rd Division,18 June 1809,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
3,4th Division,18 June 1809,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
4,5th Division,6 October 1810,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
5,6th Division,6 October 1810,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
6,7th Division,5 March 1811,April 1814,"Portugal, Spain, France","At the conclusion of the Peninsular War, in 18..."
7,Light Division,22 February 1810,1814?,,
8,1st Cavalry Division,19 June 1811,21 April 1813,Spain,Served with main field army. Broken up into in...
9,2nd Cavalry Division,19 June 1811,21 April 1813,Spain,Served with Hill's Corps. Broken up into indiv...

## 3. Create Potential Entity Groups:

A table is considered a valid **entity group** if it satisfies the following conditions:

- **Entity Column:** The table must contain a column where each cell is a unique instance of the same entity type (e.g., person, film, city, team).
- **Subject Over Data:** The group name must describe **what the rows are**, not attributes or statistics about them.
- **Entity–Name Alignment:** The group name must accurately match the type of entities in the entity column.
- **No Repeated Labels:** The entity column cannot contain generic labels or repeated categories (e.g., "Height", "Weight").
- **No Summary Tables:** Tables that summarize metrics (e.g., "Total Population", "Revenue") rather than listing entities are invalid.
- **Clear Grouping Rule:** The group must explain why these entities appear together (e.g., *Top 10 films by revenue*, *Citrus fruits*).
- **Closed and Coherent Set:** The rows cannot be a random subset of a larger category unless a clear filter exists (e.g., ranking, time constraint).
- **Member Consistency:** All entities must logically belong to the group definition.
- **Specific Category:** The group must use precise and objective definitions; vague terms like "famous" or "important" are not allowed.
- **Natural Category:** The grouping must reflect a meaningful category that humans would reasonably recognize.
- **Context Usage:** Headers, captions, and nearby text may be used to refine the group definition when informative.
- **Conservative Validation:** If the grouping logic is unclear or ambiguous, the table should be rejected.

In [9]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import TableGroupConstructor

group_constructor = TableGroupConstructor(random.sample(cleaned_data, 1000))
await group_constructor.get_groups()

🚀 Processing 1000 tables...

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1000 [00:00<?, ?it/s]

In [18]:
group_constructor.display_debug_samples()

### Validate a small subset using Gemini 3.1 pro:

### RULES FOR VALIDITY

1. **FATEFULNESS:** Members must logically match the Group Name. Reject if the description is misleading, overly broad, or contains unrelated concepts.
2. **CLOSED_SET:** The group must be coherent and complete. Reject random subsets (e.g., "6 random cities in France"). 
   *Exception:* Specific filters (e.g., "Top 10", "Oldest 5", "Members in 2024") are valid.
3. **SPECIFICALITY:** The group must have a narrow, clear concept. Reject vague names like "Famous movies" or "Important countries."
4. **NATURALNESS:** The category must be one that humans would reasonably group together. Reject arbitrary rules (e.g., "Cities starting with Q that have 3 vowels").
5. **CORRECT_ENTITY:** The Entity Column must contain the primary entities, not metadata (Rank, Year, ID) or attributes.

In [11]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidator

group_val = GroupValidator(random.sample(group_constructor.valid_tables, 200))
await group_val.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/200 [00:00<?, ?it/s]

## 4. Select Preferred Question Strategies for each Entity Group:

In [57]:
from knowledge_maze.create_dataset.create_questions.question_generation import StrategySelector

selector = StrategySelector(group_constructor.valid_tables)
selector.get_strategies()

Sanitizing tables:   0%|          | 0/700 [00:00<?, ?it/s]

Slicing strategy views:   0%|          | 0/700 [00:00<?, ?it/s]

In [55]:
selector.debug_strategy_samples("CATEGORICAL_FILTER_LOOKUP")

## 5. Create Complex Reasoning Questions w.r.t. Entity Groups & Selected Strategies:

In [133]:
from knowledge_maze.create_dataset.create_questions.question_generation import TableSanitizer, StrategySelector, QuestionGenerator

generator = QuestionGenerator(random.sample(selector.updated_data, 300), strategy_definitions=load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await generator.generate_questions()

🚀 Starting Question Generation for 300 tables...
--- Round 1: Processing 300 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/300 [00:00<?, ?it/s]

--- Round 2: Processing 11 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/11 [00:00<?, ?it/s]

--- Round 3: Processing 3 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/3 [00:00<?, ?it/s]

--- Round 4: Processing 1 tables ---

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/1 [00:00<?, ?it/s]

In [145]:
from knowledge_maze.create_dataset.create_questions.question_generation import QuestionFilter

val = QuestionFilter(generator.valid_results)
val.run_pipeline()

Starting post-processing with 299 samples...

## 6. Filter Out Bad Samples Using a Validator Model:

In [146]:
from knowledge_maze.create_dataset.create_questions.question_validator import QuestionValidator
validator = QuestionValidator(random.sample(val.approved_data, 50), load_json(os.path.join(REPO_PATH, "knowledge_maze/create_dataset/create_questions/question_strategies.json")))
await validator.validate()

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/50 [00:00<?, ?it/s]

## 7. Data Statistics:

1. model based accuracy
2. human based accuracy
3. subject distribution
4. number of evidences distribution
5. strategy distribution (2-layered pie chart)

## API Stuff:

In [199]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidatorTest

group_val = GroupValidatorTest(random.sample(group_constructor.valid_tables, 4))
await group_val.validate()

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev[True] / sum(rev.values()):.1f}%")
rev

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/4 [00:00<?, ?it/s]

ChatCompletion(id='gen-1773190353-q2hzZ6AWwTuuDHm1Vo26', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='True', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None, reasoning='**Evaluating Group Cohesion**\n\nI\'m currently focused on the coherence of the group "Wind power stations in Iran." Initial assessments suggest a common theme, but I need to ascertain if the group is specific enough to be meaningful. I\'m investigating if the shared location and function constitute a naturally occurring group, or if further refinement is necessary. The group size seems manageable for now.\n\n\n**Defining Group Membership**\n\nI\'ve confirmed each entity\'s presence within the specified geographic and functional criteria. The group\'s coherence is demonstrable, with all members adhering to the definition of "wind power stations in Iran." The entity column\'s members are valid, and the group definition provides a clear rationale for their inclusion. Further, I see the group isn\'t an arbitrary subset, it reflects a real-world category. The size is manageable and suitable. I\'m ready to answer.\n\n\n', reasoning_details=[{'type': 'reasoning.text', 'text': '**Evaluating Group Cohesion**\n\nI\'m currently focused on the coherence of the group "Wind power stations in Iran." Initial assessments suggest a common theme, but I need to ascertain if the group is specific enough to be meaningful. I\'m investigating if the shared location and function constitute a naturally occurring group, or if further refinement is necessary. The group size seems manageable for now.\n\n\n**Defining Group Membership**\n\nI\'ve confirmed each entity\'s presence within the specified geographic and functional criteria. The group\'s coherence is demonstrable, with all members adhering to the definition of "wind power stations in Iran." The entity column\'s members are valid, and the group definition provides a clear rationale for their inclusion. Further, I see the group isn\'t an arbitrary subset, it reflects a real-world category. The size is manageable and suitable. I\'m ready to answer.\n\n\n', 'format': 'google-gemini-v1', 'index': 0}, {'type': 'reasoning.encrypted', 'data': 'CnIBjz1rXyW+K0EOLK5LF8wW9kyMwkF38RlJtWb9PxraQ/bur0VKmM2QAKMVAftTX8lYY6g6gJqG+W68AA4zTYlBPJFv6GQ6GRRHDOYhUPaaC1iOqJvcXtMwMMRCVbUAjE3ZAb3Y8Fj8cU91Dl/IvXiTd1kKYwGPPWtfRNBMoFZ2jlQxEY4uJv6FkNkSfT2viBaOGUNGRuUq9kpvEQUK/nYDCZS8gomny5YUb2w+/nIWTURHm2DDQDJFcYAPzW6IcfuehzHT3LbcefTXP5tt+O6fO8JtK59sVgqLAQGPPWtfEuRie8Lr65IBJYTT08m2ztanpq4JcknLiQtKoe1WUpvFvZPDxgLOjPwC3thuskYFUP/Hi+y0318731IUEetlYafGjlKzFmy2wSFcVsFkuEjKhcvFlIza+si/Q0mrjcG7IdV/zd5Lq7espFRxwk6KsmcXwAMTGy6PGSi7SqA398XScfNALdYKiwEBjz1rX3wp0MlXhxOkAsrV3aSVrM9eEUPfYiLFYYvNPYZjChl2L+V3OUfET1MbpmCexZV0A8KRscLQk/8N78Epmih5vsBFa8C2WVedn6lXS03agzvIAiBN8bc0k1CkCmyFsDSBOHyedN9bJeWf3Bt3/geZCdBEVh9pezQOdpqlzBQkkoEe30ib8Hv1CsQBAY89a18aFiwDzgnQtkCD/BzleaH4wXVsQUm5liduO9zdZlioihY4P7uSjJKK8hiGNB32VCD2YymsB7BzBSPiUvwSTJL7TwA207jjFgcHocNVzN9yUGVJwVPAJpRCDYs+Ve6FJM+o7z88clfCVw66bz/F9DNT7vBeioyjfOGDzKC2Sy6DpJ8wyV55zjsZcT4o3HgRnQzac2SQRr6mgrrAFYd0yqzwGpK1mxF7ZRaUAPdWWjeYdG8cjCMkVkPE+7mDf7HWPgq0AQGPPWtfxougKnAttG4cTKL1V9pWQIbU5wQQ/Ts+gHN8Y03sermrwuvY7KBOOQ87YqIwq2ouTZ9lSlzQUXyscIpHXJuvgXsFIevtnR2alTugq5ecyI0GQOApXLNarLr78c5/cTTEueaDzuONGNLdI0y8atUbdKrcXECFpFsEB6vUwwKTg1Y/f6K3cmu8NGEa2fpeHpY6169QOmldx1RgeRUoE/sEyZWqXLtB168xsrJBT8QWJwrBAgGPPWtfoUmtA1uspY+gzX0IQGPVRV7pJl29X/eM3fjcEu+Obl/R8uMqWI844Do1mdiluyDwccDwx4zPIddCgUHVzvJJVEOKdKCpevbwOEUaILp4pINx7Jpd5NJVXlNiGPaDtrG0m5H/xaCUnYUacGbIHR2F0Z5DITS3kV4TyavVCPi50hdm6jsgwFAMERpNrlewmyLJPF8bFGX4AFmL6CmUN5dxibmIwgp9p8Nq2k9upg0NZApdV5O4CJMT+ttUSXBb90UwH2HYM9/6IKfHxffFGpniYmzcZgszLw1YghGrt0ld8+pHGdLbM9Ppa9AsjHY6XpQ+RPHNOSnRmY4sxdoA1eBkQby6AEoVLrGGDYwiVaIH/rP0ClW+9eZ+bIMPbrGGmEIRXFADjzRV85eI6Grmm7GHWzjx6vCv0meSQwy2DgqbAgGPPWtfSGbrl3Q+0M0X9/6yJrimJxNfQw33oQdEGEgxtdPaXSd5UHnMoFWoaMX+k7xiKsmPI5bgAmqOM9pOFNADV/doLVhuOUnAzlpzW5qkSwDSTwZT4qW+caot9DAFhhqvEdIAIDBWqyOp7FQaSCWmLWKSS/8NmWHAYvu22w2nUs4xRPb1W4TRg/gdUZdAwDksRq9HoRiq1vdRs/A4lP5uxVkaE9/K4bbFSGOQcoHq2VPQYAYe38EePXrp6LGq/TIBH2Z3yDQ3o/A3EFR37+hUSqmc6VSDMQ74fEdpPVyWqIgxuMvtdSBUyejQOCyJFHdGjE5/1+MEEqfGCEjx4CzaIUfKlth0SEB2dJGpXVsBoHJKXwop3uFjx24KUwGPPWtfmS8X/EQvpc8ts5YGS5RLICaUusIL5yrXP6o6fphZD/VdLrUnauFH78FEpCkh2ILOu640qW5Tfk+/fmkv347Iu8GN4+R4vcRppEc+9grO', 'format': 'google-gemini-v1', 'index': 1}]), native_finish_reason='STOP')], created=1773190353, model='google/gemini-3.1-pro-preview-20260219', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=340, prompt_tokens=153, total_tokens=493, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=339, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.004386, is_byok=False, cost_details={'upstream_inference_cost': 0.004386, 'upstream_inference_prompt_cost': 0.000306, 'upstream_inference_completions_cost': 0.00408}), provider='Google')
Unexpected Error: 'ChatCompletionMessage' object has no attribute 'parsed'
ChatCompletion(id='gen-1773190353-UsULX3UXGLhbdde5zvkU', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='True', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None, reasoning='**Analyzing Group Cohesion**\n\nI\'m currently focused on the coherence of the group. Initial assessment indicates a specific, rather focused, group. Its members seem to be naturally connected by their shared role. Now, I\'m verifying the naturalness of the group, which could be dependent on the duration of their tenure and other factors.\n\n\n**Validating the Membership**\n\nI\'m now cross-referencing the example members against the official list. It appears there may have been a typo ("Xiaoshen" instead of "Xiaosheng"), but otherwise the list seems accurate. Now, I\'ll analyze the listed period of service.\n\n\n**Confirming the Attributes**\n\nThe "Ambassador" designation appears accurate, given the role\'s function as a de facto embassy. The group definition is precise and the listed members align with the official roster, once the single typo is corrected.\n\n\n', reasoning_details=[{'type': 'reasoning.text', 'text': '**Analyzing Group Cohesion**\n\nI\'m currently focused on the coherence of the group. Initial assessment indicates a specific, rather focused, group. Its members seem to be naturally connected by their shared role. Now, I\'m verifying the naturalness of the group, which could be dependent on the duration of their tenure and other factors.\n\n\n**Validating the Membership**\n\nI\'m now cross-referencing the example members against the official list. It appears there may have been a typo ("Xiaoshen" instead of "Xiaosheng"), but otherwise the list seems accurate. Now, I\'ll analyze the listed period of service.\n\n\n**Confirming the Attributes**\n\nThe "Ambassador" designation appears accurate, given the role\'s function as a de facto embassy. The group definition is precise and the listed members align with the official roster, once the single typo is corrected.\n\n\n', 'format': 'google-gemini-v1', 'index': 0}, {'type': 'reasoning.encrypted', 'data': 'CncBjz1rXwa+BQyDsHLtOoDPzzkUay5z4FAxYV87cc9tE8T/8dNQXvIs3uFd7bMeiaEHwPf0u+cUTsh2HyP/KCsvDpg1Fqu07xcukflCY1TFV//LgPtFBii5NNUVgY4+qxuvZx7VAL1S2PLNms+mFE9BcPzu0DJBAgptAY89a1/NnHOFgKbl9MaxuPhPM8TQH0H71XRJZ4haWbteftNh7Nzsm0ZyAU5e+1JjO/kph9Y9a/KXd6c+uzqVzMjdRZsiUzh0/HQQ5GbYfpt8Fc6rOrmJVNfd0wBG6mGPtuhZ2s877Sy44f/JTwq1AQGPPWtfEQag4Z6XARBDcpwlSIlSEvNQKMwQgDpShSSnm5oCDwIpDgvwTdvEp9OfEcZihzSXQRbf3tv2kwCOMCwIPHblsu/qGNY5yDaBAnqeizSillLs/mCuiZc1fvHaKJkifutpmpkKBo+VPkj3lg/rh5BJFqiIFSbNjKhB6HooxfkvFHYB2D7GCbi5zm5GISty+o+d6myMrpSrkFgIvFEzOgVe5cRwc1gjhqtFdpz67fP2TBMKewGPPWtf9cG9aAmWNaPaeq52Ph5sv/a+Avv5Fc6XEQ0fZLrtQrlN+VWzBIFheOirQH/UEs9Y4/2JzsUvvYAD1m6dqunoZp461grlJ3aW6zZ59nYze9euGJtHWU+Zaw711Rnfv8MV9Vblb7WgHpL+iowsBb681ojF3NkTeArkAQGPPWtfOCcnoSu/CIzswPbUW2E2G/Phd9yrON4GN26BWP3CWIPiLTfG2fZVJ6Qzj9R0mfaYesCykI1U3T+ATAABcbeFl2etcCb5mJ7SnJ0Bckujx1v8qtKTvLVVc7myoZIMM6vVwCzEsZJ9PWfG+z7qEOmCVXTLBZzs6hDMMe7SopOBV90Yf4Fr4OJbQ7bDo18V/gtun2y5h6TU+pMQQv+gcEJs71RUP4C0bcHcG1gI9ugTr6kOhLe8fI88yLhKqwnXbKlRjwlAIIOj3whs+JKAsZ06uu68YJ/JpcuJefTofz8HLQqFAgGPPWtfkcqs+MouFUMGNd170021kRp8/8vcmJm1tLxi+oILNV1eGbHJGyGIweR20ZbwHAVgykgwUjm93cUHanqZG/0COuRJZ4nh4SBg3fNwYVpwllA5nFDGaXTcCkpFgCEkJC5bsCYcBZgapPZv99fHsd18oK27+ubO7swSGTbqu+//fqd+DYT4HJuJfRc3ZFpfe0z2LaxLhS8Ma5FjrtKtsq657IUmQiqSUCJfiwiO17QM72ZCgduLT9LQaVrgOfxQGrTYqBzJLow4umDSRHCSWMq8wMGXybR7z/DiVLxWZFrznuFpAv4fyYsuGhvBKgXQweu/WT/OqVrbkf2W6v+p0lOX7ArBAQGPPWtfJFdJu6BuoaGSuxLteuzkXP5kMGRMpGyyXegggRroKxovmBlP2GajbD5iHwx+GrNOwLuTxi8z8Qxjp6MezMAuxGetb6drF4sySoiTPQz4zzQGwesq+E/HMQ07OvTkm4eQR9HjUQjbr62Ly7DYgVDmKmAr16pGbm58Y8AR+wiA+76m2hHq0c4eFT31kfrIelRdeD2BOqzTxqdBgfVW3+f5FqQn+MChH5d06vGM8aHa9PmR45rUk7oLEOrxXI0KkwEBjz1rX5Hoz5xSmeXXS/Fp8DcsavPNOtJ6qMX0YA0NhJ2/oZcS7ysm+T+kubZPREMHPtSbcTy/eku/+LfJDN1rZV/F0uBfrwy3NnHpRziH2p5YZwcIA6PEUtdqmYMOOPOTVLA1xDuWdOb7vpiu86ZTeYBAO2N0OTZlA+K99epKJx3aDCnhglJdB4z7n3QpNs5H6xcKvwEBjz1rX/SpnjYeHKVii0hjIrvnMd0iW0MjJuf6btVHTcL19O8uWDmifq9nPx4kz+D6DDeOvN4P3emjKaEu+xD/d4rfe3IuuKtED0Xwjc3cDque+V42gQ4l4VjLGZ+dj5gi0Jqsh4TQARJoGl7cqb6iSnq/815Jj1Ds10TPKuqQ2P27SizneAGY77r2+HrUw/wfkeSrkCVVYh2/vw8T8Xkp5RM2jhXSJ6XiYUz6NJ1TmeOrJ4b4lT4UWQjzBG/b4wqVAQGPPWtfXDJbe7PKrcBBK4qMmoPt7A+ImLdq15+oRu0rWJ+vH5+8S3VTmgVV5VggP4mGe/4ZxCf8ghbOOi2BFoWCVDIS3BtGIleIiFOGZj+13XgaJZvo8YB8gXt/PqeyAITktEVCQ14baNvQU19TPBsZaYHxQA3hjLnPjci8H/UHtqNEFgCair1Npt0ViiG/VxBq4rPOCs4BAY89a19RhSOHzUA7zDgpY/Z0USUl5z8x3Vp2naGbjB6obhXYeYAOkYgs3Ma03nAGrgGAfIlZUTVj8ZbJ/70nhOfteYp6cp1yRTfTn+zHiJ5ycuee+VeEp1soVs+PqMASYmXaheQHhq8cpJjNM334ePzAlOWCXmp7oKO3ThNMQRqlqAc7wo/Vyl7UBfnWZsGlvuMlsErUKM1ns14Y1AXQ651oKHzb3IEp07mEpQ/AwbR24adDGKe2ea4bYSDHWOCXrGMWWPs94JQP1NTDqlgKwQIBjz1rX4hef+c1HCsE6XZTOuWPkrOvvUowo1wACiR4WC8Y4Dx8em6MBIF0O3yP5PKMkw277/mEDvPtjcl1dlXV90kpVE+HmAU3ARyqeipoC1lemmrePQjs82nLSggKqPy5oDkdTgy9sKnFOBfQLuA3StcuoSI0MyMYzYyqyYTDby9Ab15LX67ilvlHMsmxdrsmqRfYSnlI85ximYo3YqRB22VTmhNxgPKLtdHw+jAeCtG5xQJ8Lf0Zh2QMgoVVIZnJb/Zft5tkcaZ+VjRKhrFbqQG0K2BILuZ3MEaSsFkhHhdPxiKyWARgV3cYCnejT3LI7YR/v6RfaU5/B/v4GpzVQAAMikTpA89f22y79oFbhLR3jSX0cu9Hm95ZpS0NeqKzp+Ead+MA19ODaCUGDhyNQeA1HjsyPzuB+FSqp3owNqoKmAIBjz1rXyTLZuiVjx3PfRxyu3OcTcNJn5XWZHoWh1td8bw+7muGfBkaZnx1z+ApDBNlj01LOixSLrwX9v0RtJxQFJDnHTe3ljfZVMCUNolNYblvhzfhOEgA1C4QreV8BCx7l5Loa0+AL4K9SGw6lgxcbgPUHw8LNY22slyzYxEOXvm9WVJ+emgLbfTZdu7dDiFiNsqABDeFiFAocj4v/iKXPmco4P9Vq5jX4E3e5E7BSZhpI0zyGoGqUuV+tImEQHNY6YSmLPIsRH4JEbEeGsTEz+UTKwjQjh6zwXXlEPxyYu0OsqvsSkjsrIaRD80qPjG+5uONhB9gutiVBAIOGVO74XiI6P1i2Ckqkx4NKMY53q4IoMNG4kQzCpECAY89a1+LRh37Dt5JK5+AEGRd8EUwY/GZkDMz1FVRt0KeRsjl32uEicPDukFuON+YHcLVZ/BAKIbjjOR2l6yO9ZHIpaRspjldgYeoSRJtvV281VFhGv2rqGOCcniuZENEdst0M900Gl6wjJPWUTw/RTSgz9NI11aaqBT9vOYm4TDLLMkENadQQgk+CKPzMPhnz70D4ft9nOV/PQOSKJ0tt3tDJF5fgXsPJmQZgPP/WX6/1FPiTmNOgd88c8zlViM4jUiH9j99WqQggupRAgCDxJ2bOZ5Swn3I73x9linnDeiGD+7s6lUbpna7xbEE/Mk5sqX4iPA7ef7pLymse6KmiQ9jzq8UB5EdhoNZ4X310mAF', 'format': 'google-gemini-v1', 'index': 1}]), native_finish_reason='STOP')], created=1773190353, model='google/gemini-3.1-pro-preview-20260219', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=714, prompt_tokens=145, total_tokens=859, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=713, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.008858, is_byok=False, cost_details={'upstream_inference_cost': 0.008858, 'upstream_inference_prompt_cost': 0.00029, 'upstream_inference_completions_cost': 0.008568}), provider='Google')
Unexpected Error: 'ChatCompletionMessage' object has no attribute 'parsed'

Counter({None: 4})

In [184]:
for s in [sample for sample in group_val.output_data if not sample['verdict']]:
    print(s['Group name'])
    print(s['Entity column'])
    print(s['Wiki url'])
    print("-"*100)

Members of Task Force ✱/Suicide Squad Dark
Character
https://en.wikipedia.org/wiki/List_of_Suicide_Squad_members#Task_Force_%E2%9C%B1/Suicide_Squad_Dark
----------------------------------------------------------------------------------------------------
Top 5 mainland Chinese albums by annual sales percentage on the Billboard China V Chart in 2016
Album
https://en.wikipedia.org/wiki/List_of_Billboard_China_V_Chart_top_10_albums_of_2016#Mainland_%28Domestic%29_albums
----------------------------------------------------------------------------------------------------
Taiwanese films released in 2001
Title
https://en.wikipedia.org/wiki/List_of_Taiwanese_films_of_the_2000s#2001
----------------------------------------------------------------------------------------------------

In [187]:
from knowledge_maze.create_dataset.create_questions.grouping_entities import GroupValidator

group_val = GroupValidator([sample for sample in group_val.output_data if sample['verdict']])
await group_val.validate()

rev = Counter([sample['verdict'] for sample in group_val.output_data])
print(f"{100 * rev['ACCEPT'] / sum(rev.values()):.1f}%")
rev

Usage cost: 0.0000$ (Estimated: 0.00$):   0%|          | 0/17 [00:00<?, ?it/s]

Input tokens: 642
Output tokens: 188
Input tokens: 577
Output tokens: 271
Input tokens: 578
Output tokens: 207
Input tokens: 519
Output tokens: 255
Input tokens: 629
Output tokens: 236
Input tokens: 622
Output tokens: 251
Input tokens: 533
Output tokens: 369
Input tokens: 624
Output tokens: 406
Input tokens: 616
Output tokens: 430
Input tokens: 606
Output tokens: 548
Input tokens: 630
Output tokens: 182
Input tokens: 596
Output tokens: 217
Input tokens: 607
Output tokens: 155
Input tokens: 571
Output tokens: 238
Input tokens: 544
Output tokens: 219
Input tokens: 580
Output tokens: 892
Input tokens: 581
Output tokens: 181
94.1%

Counter({'ACCEPT': 16, 'CLOSED_SET': 1})